NMDSdevopsServiceAdm/SopraSteria-SFC

- server/utils/fileLockS3.js
> Added logging to file lock

- server/utils/fileLockS3.js
> Removed s3 calls

- server/utils/fileLockS3.js
> Added false to lock

- src/app/core/services/report.service.ts
> Upped report check to 5 seconds

- server/utils/fileLockS3.js
> strip out all references to aws and other libraries

- server/utils/fileLockS3.js
> remove database logic

- server/data/parentWDFReport.js
> Correcting SQL for wdf report

- server/models/classes/worker.js
> Updated logic for weekly hours average

- server/utils/fileLockS3.js
> Revert changes to filelocks3

- manifest.test.yml
> Upped staging to 4gb of memory

- server/models/classes/establishment.js
> Removed lines that removed the sharing permissions

- package-lock.json
- package.json
- server/config/config.js
- server/data/bulkUploadLock.js
- server/routes/establishments/bulkUpload.js
- src/app/core/model/bulk-upload.model.ts
- src/app/core/services/bulk-upload.service.ts
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2524
> Revert "Added new S3 locking to bulk upload"

- server/data/parentWDFReport.js
> WDF report : fixing sql

- migrations/20201007134732-trainingReportIndex.js
> Added indexs to columns used by the training report

- server/models/postcodes.js
> Added sanitisation to the postcode before looking it up

- server/models/classes/establishment.js
- src/app/features/workplace/data-sharing/data-sharing.component.ts
> Fix so local authorities are correctly reset

- migrations/20201007134732-trainingReportIndex.js
- migrations/20201008152741-bulkUploadIndexes.js
> Added indexes to common BU functions

- server/data/parentWDFReport.js
> Only perm temp have sickdays

- manifest.benchmarks.yml
- manifest.bluegreen.yml
- manifest.dev.yml
- manifest.preprod.yml
- manifest.prod.yml
- manifest.test.yml
- package.json
> Updated node to latest LTS

- migrations/20201013113128-workerNurseSpecialisms.js
- package-lock.json
- server/models/BulkImport/BUDI/index.js
- server/models/BulkImport/csv/workers.js
- server/models/classes/worker.js
- server/models/classes/worker/properties/nurseSpecialismsProperty.js
- server/models/classes/worker/workerProperties.js
- server/models/worker.js
- server/models/workerNurseSpecialisms.js
- server/test/unit/mockdata/workers.js
- server/test/unit/models/Bulkimport/csv/workers.spec.js
- src/app/core/model/nurse-specialism.model.ts
- src/app/core/model/worker.model.ts
- src/app/features/workers/nursing-category/nursing-category.component.html
- src/app/features/workers/nursing-category/nursing-category.component.ts
- src/app/features/workers/nursing-specialism/nursing-specialism.component.html
- src/app/features/workers/nursing-specialism/nursing-specialism.component.spec.ts
- src/app/features/workers/nursing-specialism/nursing-specialism.component.ts
- src/app/shared/components/staff-record-summary/employment/employment.component.html
> Nurse specialisms multi answer

- server/models/BulkImport/BUDI/index.js
- server/models/BulkImport/csv/workers.js
> Changed codes to be correct way round

- migrations/20201007134732-trainingReportIndex.js
> Removed problematic migration

- migrations/20201013113128-workerNurseSpecialisms.js
> Updated nurse specialisms migration

- server/models/classes/worker.js
- server/models/classes/worker/properties/nurseSpecialismsProperty.js
- server/test/unit/models/classes/worker.spec.js
- src/app/features/workers/nursing-category/nursing-category.component.html
- src/app/features/workers/nursing-category/nursing-category.component.ts
- src/app/shared/components/staff-record-summary/employment/employment.component.html
- src/app/shared/pipes/nursing-categories-text.pipe.ts
- src/app/shared/shared.module.ts
> Nurse specialisms content and consequential update fixes

- src/app/features/workers/nursing-specialism/nursing-specialism.component.ts
> Fix options not appearing

- package.json
> Removed postinstall

- .circleci/config.yml
- migrations/20201027094527-updateBenchmarks_add_barchart_columns.js
- server/models/benchmarks.js
> Adding new columns to Benchmarks table

- src/app/features/workers/nursing-specialism/nursing-specialism.component.html
- src/app/shared/components/staff-record-summary/employment/employment.component.html
- src/app/shared/pipes/nursing-specialisms-text.pipe.ts
- src/app/shared/shared.module.ts
> Bug fix showing 'change' when shouldn't

- CQCLocationAPICall/aws/secrets.js
> Updated vars for the db user and pass on CQC

- package.json
> Added typescript to deps

- package-lock.json
- package.json
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2623
> Revert "Bump pg from 8.2.1 to 8.4.2"

- migrations/20201105142147-benchmarkMetric.js
- src/app/shared/components/benchmark-metric/barchart/barchart.component.spec.ts
> Added script to add comparison tables and group details

- server/models/benchmarks.js
- server/models/dataImports.js
- server/routes/establishments/benchmarks/index.js
- server/test/unit/routes/establishments/benchmarks.spec.js
- src/app/core/model/benchmarks.model.ts
- src/app/core/utils/benchmarks-util.ts
- src/app/shared/components/benchmark-metric/barchart/barchart-options-builder.ts
- src/app/shared/components/benchmark-metric/barchart/barchart.component.spec.ts
- src/app/shared/components/benchmark-metric/barchart/barchart.component.ts
- src/app/shared/components/benchmark-tile/benchmark-tile.component.html
- src/app/shared/components/benchmark-tile/benchmark-tile.component.ts
- src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html
- src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts
- src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
- src/app/shared/components/benchmarks-tab/metric/metric.component.html
- src/app/shared/components/benchmarks-tab/metric/metric.component.ts
> Added read about comparison group

- server/models/dataImports.js
> Bug fix when no data import record

- package-lock.json
- package.json
- server/models/index.js
> Updated pg to 8.5.0 and changed clear to destoryAllNow

- package-lock.json
- package.json
- server/models/index.js
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2661
> Revert "Updated pg to 8.5.0 and changed clear to destoryAllNow"

- server/models/benchmarksTurnover.js
- server/models/establishment.js
- server/routes/establishments/benchmarks/benchmarksService.js
- server/routes/establishments/benchmarks/index.js
- server/routes/establishments/benchmarks/rankings/index.js
- server/test/unit/routes/establishments/benchmarks.spec.js
- server/test/unit/routes/establishments/benchmarks/rankings.spec.js
- server/test/unit/utils/benchmarksUtils.spec.js
- server/utils/benchmarksUtils.js
- src/app/core/model/benchmarks.model.ts
- src/app/shared/components/benchmark-metric/barchart/barchart-options-builder.ts
- src/app/shared/components/benchmark-metric/ranking-content/ranking-content.component.html
- src/app/shared/components/benchmark-metric/ranking-content/ranking-content.component.ts
- src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
- src/app/shared/components/benchmarks-tab/metric/metric.component.html
- src/app/shared/components/benchmarks-tab/metric/metric.component.spec.ts
- src/app/shared/components/benchmarks-tab/metric/metric.component.ts
- [] No, they are not required for this change
> Turnover ranking

- server/routes/reports/localAuthorityReport/user.js
- server/routes/reports/trainingReport/training.js
- server/routes/reports/wdf/parent.js
**Work done**
- Removed `debuglog` - it was never used due to an empty function
- Fixed linting issues
> Fix: Remove unused debuglog

- server/models/benchmarks.js
- server/models/benchmarksQualifications.js
- server/models/establishment.js
- server/models/services.js
- server/models/worker.js
- server/routes/establishments/benchmarks/benchmarksService.js
- server/routes/establishments/benchmarks/index.js
- server/routes/establishments/benchmarks/rankings/index.js
- server/test/unit/routes/establishments/benchmarks.spec.js
- server/test/unit/routes/establishments/benchmarks/rankings.spec.js
> Added qualifications logic

- server/models/benchmarksSickness.js
- server/routes/establishments/benchmarks/benchmarksService.js
- server/routes/establishments/benchmarks/index.js
- server/routes/establishments/benchmarks/rankings/index.js
- server/test/unit/routes/establishments/benchmarks/rankings.spec.js
- src/app/shared/components/benchmark-metric/ranking-content/ranking-content.component.html
> Added sickness ranking logic

- server/routes/accounts/user.js
**Work done**
- Updated copy for the error message shown when the limit has been reached for a specific role
> Fix: Update error message for permission limits

- server/models/benchmarks.js
- server/models/cssr.js
- server/routes/establishments/benchmarks/benchmarksService.js
- server/routes/establishments/benchmarks/index.js
- server/test/unit/routes/establishments/benchmarks.spec.js
> Fixed postcode bug on benchmarks

- src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.html
- src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.spec.ts
> Added last updated date to benchmark tab

- src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.spec.ts
> Removed fdescribe

- server/routes/establishments/benchmarks/benchmarksService.js
- server/test/unit/routes/establishments/benchmarks.spec.js
> Fixed bug with benchmark pay values

- migrations/20201201145802-satisfactionSurvey.js
- server.js
- server/config/config.js
- server/config/localhost.yaml
- server/config/test.yaml
- server/models/establishment.js
- server/models/login.js
- server/models/satisfactionSurvey.js
- server/models/userAudit.js
- server/routes/logout.js
- server/routes/satisfactionSurvey.js
- server/test/unit/routes/logout.spec.js
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/core/components/header/header.component.logout.spec.ts
- src/app/core/services/auth.service.ts
- src/app/core/test-utils/MockAuthService.ts
- src/app/core/test-utils/TestRootComponent.ts
- src/app/features/satisfaction-survey/satisfaction-survey.component.html
- src/app/features/satisfaction-survey/satisfaction-survey.component.spec.ts
- src/app/features/satisfaction-survey/satisfaction-survey.component.ts
- src/app/shared/components/error-summary/error-summary.component.ts
> Satisfaction survey

- src/app/shared/components/benchmark-tile/benchmark-tile.component.scss
> Added shadow to the tiles on benchmarks

- src/app/core/components/header/header.component.logout.spec.ts
- src/app/core/components/header/header.component.ts
- src/app/core/services/auth.service.ts
> User a different function for when the user trys to sign out

- src/app/features/workplace/view-workplace/view-workplace.component.html
- src/app/features/workplace/workplace.module.ts
> Fixed Benchmarks tab on workplace info

- server/models/BulkImport/csv/establishments.js
> Check for empty postcode before querying database

- src/app/core/components/header/header.component.logout.spec.ts
- src/app/core/components/header/header.component.ts
- src/app/features/satisfaction-survey/satisfaction-survey.component.html
- src/app/features/satisfaction-survey/satisfaction-survey.component.ts
> Staging fixes for satisfaction survey

- src/app/features/dashboard/home-tab/home-tab.component.ts
> Updated to send event rather than use the pageview

- src/app/core/services/pdf.service.ts
- src/app/features/pdf/footer/pdf-footer.component.html
- src/app/features/pdf/footer/pdf-footer.component.ts
- src/app/shared/components/benchmarks-tab/metric/metric.component.html
**Work done**
- Fixed spacing on footer to be closer to the benchmarks PDF
- Added pages (Page 1 of 2 etc) to the footer
- Fixed wording for # of pages / download size
> Fix: Add pages / Metric PDF footer spacing / fix copy on download link

- src/app/shared/components/benchmark-metric/barchart/barchart-options-builder.ts
> Added more margin so numbers don't get cut off on barchart

- src/app/app.module.ts
- src/app/core/guards/development/development.guard.ts
- src/app/development-routing.module.ts
- src/app/features/bulk-upload/bulk-upload.module.ts
- src/app/features/bulk-upload/v2/bulk-upload-page/bulk-upload-page.component.html
- src/app/features/bulk-upload/v2/bulk-upload-page/bulk-upload-page.component.ts
- src/app/features/bulk-upload/v2/bulk-upload-routing.module.ts
- src/app/features/bulk-upload/v2/bulk-upload.module.ts
- src/environments/environment.ts
> Created hidden route for new bulk upload work

- src/app/app.module.ts
- src/app/core/guards/development/development.guard.ts
- src/app/core/services/establishment.service.ts
> Don't throw in dev mode when no establishment

- src/app/app.module.ts
- src/app/core/guards/development/development.guard.ts
> Revert isDevMode causes a bug

- migrations/20201211124706-satisfactionSurveyPerUser.js
- server/models/satisfactionSurvey.js
- server/models/userAudit.js
- server/routes/logout.js
- server/routes/satisfactionSurvey.js
- src/app/core/components/header/header.component.logout.spec.ts
- src/app/core/services/auth.service.ts
- src/app/core/test-utils/MockUserService.ts
- src/app/features/satisfaction-survey/satisfaction-survey.component.spec.ts
- src/app/features/satisfaction-survey/satisfaction-survey.component.ts
> Bug for satisfaction survey not showing

- src/app/core/utils/file-util.ts
- src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.html
- src/app/features/bulk-upload-v2/bulk-upload-sidebar/bulk-upload-sidebar.component.html
- src/app/features/bulk-upload-v2/bulk-upload-sidebar/bulk-upload-sidebar.component.ts
- src/app/features/bulk-upload-v2/bulk-upload.module.ts
> adding sidebar component

- package-lock.json
- package.json
- src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.html
- src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.ts
- src/app/features/bulk-upload-v2/bulk-upload.module.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.html
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.scss
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.html
- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.scss
- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.spec.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.ts
- src/app/features/bulk-upload/bulk-upload.module.ts
> Drag and drop component

- server/routes/establishments/linkToParent.js
> Revert link to parent code

- src/app/features/public/contact-us/contact-us.component.html
> Added Christmas message to the contact us page

- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.html
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> Changed notification and button text

- src/app/features/public/contact-us/contact-us.component.html
> Remove Christmas message

- loaderio-63e80cd3c669177f22e9ec997ea2594d.txt
- server.js
> Added loader.io verification file

- server/routes/approvals/becomeAParent.js
- server/routes/approvals/index.js
- server/routes/ownershipRequest/index.js
- server/routes/parentSubLinking/index.js
- server/routes/reports/localAuthorityReport/index.js
- server/routes/reports/trainingReport/index.js
- server/routes/reports/wdf/index.js
> Added permissions to the remaining endpoints

- server/routes/accounts/user.js
- server/routes/establishments/approve.js
- server/routes/establishments/benchmarks/index.js
- server/routes/establishments/benchmarks/rankings/index.js
- server/routes/establishments/bulkUpload/index.js
- server/routes/establishments/capacity.js
- server/routes/establishments/dataPermissions.js
- server/routes/establishments/employerType.js
- server/routes/establishments/fluJab.js
- server/routes/establishments/index.js
- server/routes/establishments/jobs.js
- server/routes/establishments/la.js
- server/routes/establishments/linkToParent.js
- server/routes/establishments/localIdentifier.js
- server/routes/establishments/localIdentifiers.js
- server/routes/establishments/locationdetails.js
- server/routes/establishments/mainService.js
- server/routes/establishments/mandatoryTraining/index.js
- server/routes/establishments/name.js
- server/routes/establishments/ownershipChange.js
- server/routes/establishments/qualification/index.js
- server/routes/establishments/reject.js
- server/routes/establishments/serviceUsers.js
- server/routes/establishments/services.js
- server/routes/establishments/shareData.js
- server/routes/establishments/staff.js
- server/routes/establishments/training/index.js
- server/routes/establishments/workers.js
> Added permission check to user endpoints

- server/routes/establishments/approve.js
- server/routes/establishments/benchmarks/index.js
- server/routes/establishments/benchmarks/rankings/index.js
- server/routes/establishments/bulkUpload/index.js
- server/routes/establishments/capacity.js
- server/routes/establishments/dataPermissions.js
- server/routes/establishments/employerType.js
- server/routes/establishments/fluJab.js
- server/routes/establishments/index.js
- server/routes/establishments/jobs.js
- server/routes/establishments/la.js
- server/routes/establishments/linkToParent.js
- server/routes/establishments/localIdentifier.js
- server/routes/establishments/localIdentifiers.js
- server/routes/establishments/locationdetails.js
- server/routes/establishments/mainService.js
- server/routes/establishments/mandatoryTraining/index.js
- server/routes/establishments/name.js
- server/routes/establishments/ownershipChange.js
- server/routes/establishments/qualification/index.js
- server/routes/establishments/reject.js
- server/routes/establishments/serviceUsers.js
- server/routes/establishments/services.js
- server/routes/establishments/shareData.js
- server/routes/establishments/staff.js
- server/routes/establishments/training/index.js
- server/routes/establishments/workers.js
> Fix: Establishment permission checks

- server/utils/security/isAuthenticated.js
- src/app/core/components/header/header.component.ts
- src/app/core/guards/role/role.guard.ts
- src/app/core/model/auth.model.ts
- src/app/core/services/auth.service.ts
- src/app/features/reports/pages/reports/reports.component.html
- src/app/features/reports/pages/reports/reports.component.ts
> Swapped role check from endpoint to endpoint and token, and added a reqiest on roleCheck guard

- server/routes/accounts/user.js
> Added a role check if trying to upgrade own role and Read only

- src/app/features/bulk-upload-v2/bulk-upload.module.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.html
- src/app/features/bulk-upload-v2/file_error_message/file-error-message.component.html
- src/app/features/bulk-upload-v2/file_error_message/file-error-message.component.spec.ts
- src/app/features/bulk-upload-v2/file_error_message/file-error-message.component.ts
> Bu/error messages: Adding in message to show errors and warnings for bulk upload

- server/routes/approvals/index.js
> Fix issue with permissions on becomeAParent endpoint

- server/routes/reports/wdf/index.js
> Changed endpoint permission

- server/utils/security/hasPermission.js
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2855
> Revert "Fix: Skip permission check until bugs have been tested"

- server/models/approvals.js
> Fixed parent issue

- package-lock.json
- package.json
> Fix: Downgrade cheerio to live

- src/app/features/dashboard/home-tab/home-tab.component.ts
> Added isAdmin to datalayer

- server/utils/security/isAuthenticated.js
> Added establishmentId to isAuthorized call

- server/routes/parentSubLinking/index.js
- server/routes/reports/wdf/index.js
> Bug: Fixed permission issues

- server/routes/establishments/ownershipChange.js
- server/routes/parentSubLinking/index.js
- server/routes/reports/wdf/index.js
> Bug: Permission issue fix on Ownership change

- server/utils/wdfEligibilityDate.js
> Changed WDF date to January

- server/utils/wdfEligibilityDate.js
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2913
> Revert "Changed WDF date to January"

- src/app/features/dashboard/dashboard.component.ts
> Fixed logout error

- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.html
- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.spec.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-upload/drag-and-drop-files-upload.component.ts
> Bu/none csv file upload: adding error message if you try to upload none csv

- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
**Issue**
When v2 of BU is first loaded, the initial state shows "Complete the upload" and then updates to say "Validate files".
The reason for this is that there are 2 subscriptions set up - one to get the uploaded files and another to get the status of the BU.
When the component is first rendered, `uploadedFiles` is set to null and `validationComplete` is set to `false`
However, because the subscriptions are ran in parallel, `validationComplete` was being set to `true` before it knew if there are even any files.
**Work done**
- Use `combineLatest` to get access to both `uploadedFiles` and `state` in the `subscribe` callback
> Fix: Loading state for BU V2

- src/app/features/add-mandatory-training/add-mandatory-training.component.html
**Issue**
The template was erroring with `Cannot read property 'mandatoryTrainingCount' of undefined`
**Work done**
- Check there is mandatory training before checking the count
> Fix if statement when no mandatory training is set

- server/routes/establishments/bulkUpload/uploadFiles.js
- server/test/unit/routes/establishments/bulkUpload/uploadFiles.spec.js
- src/app/core/model/bulk-upload.model.ts
- src/app/core/test-utils/MockBulkUploadService.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.html
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.spec.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> Bu/invalid bu file: adds error message for unrecognised CSV file

- src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.html
**Issue**
We have a details component for displaying a summary but the BU v2 had an additional class to remove the margin which was not needed.
**Work done**
- Use the `<app-details>` component for consistency
> Fix: BU v2 Summary

- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.spec.ts
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
- Add line to clear error message after pressing delete
- Update test
> BU fix delete button

- src/app/shared/components/trianing-link-panel/training-link-panel.component.spec.ts
- src/app/shared/components/trianing-link-panel/trianing-link-panel.component.component.ts
> Fixed a bug where it would 403 after visiting another workplace

- src/app/features/dashboard/home-tab/home-tab.component.html
- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/dashboard/home-tab/home-tab.component.ts
- src/app/shared/components/total-staff/total-staff.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
- src/assets/scss/components/_summary-list.scss
> Added banners when you have more staff records than total staff

- src/app/shared/components/tabs/tabs.component.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
> Fixed tab selection when on sub

- CQCLocationAPICall/.gitignore
- CQCLocationAPICall/importPostcodeData.js
- CQCLocationAPICall/models/pcodedata.js
- CQCLocationAPICall/package.json
> Postcode import

- src/app/features/bulk-upload-v2/bulk-upload-references/bulk-upload-references.directive.ts
- src/app/features/bulk-upload-v2/bulk-upload-references/staff-references/staff-references-page.component.spec.ts
- src/app/features/bulk-upload-v2/bulk-upload-references/workplace-references/workplace-references-page.component.spec.ts
> Added check if from control dirty

- server/models/BulkImport/csv/establishments.js
> Added validation rule for regtype 0 but cqc main service

- migrations/20210216141604-create-email-campaign.js
- migrations/20210218162736-create-email-campaign-history.js
- server/models/emailcampaign.js
- server/models/emailcampaignhistory.js
- server/routes/admin/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js
- server/routes/admin/email-campaigns/inactive-workplaces/index.js
- server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js
**Work done**
- Added migrations and models for `EmailCampaign` and `EmailCampaignHistory`
- Updated `createCampaign` endpoint to create records in the DB
> Feat: Keep Workplaces Active - Database work to create a new campaign

- src/app/shared/components/total-staff-panel/total-staff-panel.component.html
- src/app/shared/components/total-staff-panel/total-staff-panel.component.spec.ts
- src/app/shared/components/total-staff-panel/total-staff-panel.component.ts
- src/assets/scss/partials/_lists.scss
> Staff Mismatch Grey Banner Changes

- migrations/20210216141604-create-email-campaign.js
- migrations/20210218162736-create-email-campaign-history.js
- server/models/emailcampaign.js
- server/models/emailcampaignhistory.js
- server/routes/admin/email-campaigns/inactive-workplaces/index.js
- server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js
- Update `getHistory` endpoint to get email campaign history from database
- Update test to mock database call
> Update getHistory endpoint

- src/app/shared/components/workplace-summary/workplace-summary.component.ts
> Changed location of staff records to get staff record count

- server/routes/establishments/bulkUpload/download.js
- src/app/core/breadcrumb/journey.bulk-upload.ts
- src/app/features/bulk-upload-v2/about-bulk-upload/about-bulk-upload.component.html
- src/app/features/bulk-upload-v2/bulk-upload-routing.module.ts
- src/app/features/bulk-upload-v2/bulk-upload-sidebar/bulk-upload-download-current-data/bulk-upload-download-current-data.component.html
- src/app/features/bulk-upload-v2/bulk-upload-start-page/bulk-upload-start-page.component.html
- src/app/features/bulk-upload-v2/codes-and-guidance/codes-and-guidance.component.html
- src/app/features/bulk-upload-v2/drag-and-drop-files-list/drag-and-drop-files-list.component.html
> Bug/bulk upload v2- bug fixes

- src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.html
> fixing typo

- server/routes/establishments/bulkUpload/validate/validateWorkerCsv.js
> Fixed: Bulk upload not adding new workers on new workplace

- src/app/features/dashboard/home-tab/staff-mismatch-banner/staff-mismatch-banner.component.html
> Fixed typo on mismatch banner

- server/routes/accounts/user.js
- src/app/shared/components/trianing-link-panel/trianing-link-panel.component.component.ts
> Fixed download report and permissions when adding user

- src/app/features/workers/move-worker-dialog/move-worker-dialog.component.ts
> Add check for isParent and send admin to dashboard

- server/routes/accounts/user.js
- src/app/shared/components/trianing-link-panel/trianing-link-panel.component.component.ts
> Fixed download report and permissions when adding user in Staging

- src/app/features/workers/move-worker-dialog/move-worker-dialog.component.ts
> Fix move worker dialog

- .circleci/config.yml
- package.json
- src/app/app-routing.module.ts
> Fixed production build in preprod

- .circleci/config.yml
- package.json
- server/routes/accounts/user.js
- src/app/app-routing.module.ts
- src/app/features/workers/move-worker-dialog/move-worker-dialog.component.ts
- src/app/shared/components/trianing-link-panel/trianing-link-panel.component.component.ts
> Live: Fix  move worker and preprod build fix

- src/app/app-routing.module.ts
> Put BU Live in Production

- server/routes/admin/email-campaigns/inactive-workplaces/sendEmail.js
- server/test/unit/routes/admin/email-campaigns/inactive-workplaces/sendEmail.spec.js
**Work done**
- Send `FULL_NAME` param to Send in Blue to use in the templates
> Feat: Send full name to Send in Blue

- src/app/core/guards/bulk-upload/bulk-upload-missing.guard.ts
- src/app/core/guards/bulk-upload/bulk-upload-start.guard.ts
- src/app/features/bulk-upload-v2/admin-skip.service.ts
- src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.ts
- src/app/features/bulk-upload-v2/bulk-upload-references/missing-workplace-references/missing-workplace-references-page.component.ts
> Adding in logic for admin skip

- server/models/cache/singletons/permissions.js
> Added fix for 403 when admin deleting workplaces

- server/routes/login.js
> Made sure that the object not been there wont affect logins

- server/aws/secrets.js
- server/config/config.js
**Work done**
- Updated Send in Blue API key to use AWS Secrets Manager
> Feat: Get Send in Blue API key from AWS Secrets Manager

- server/models/classes/user.js
- server/routes/accounts/user.js
> Add getter for display status

- .circleci/config.yml
- package-lock.json
- package.json
- server.js
- server/models/classes/user.js
- server/routes/accounts/user.js
- server/routes/login.js
- server/routes/registration.js
- server/utils/middleware/sqreen.mock.js
- server/utils/security/isAuthenticated.js
- src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.spec.ts
- src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
- src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts
- src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
Added sqreen integration (#3087) 
Made sure that the object not been there wont affect logins (#3104) 
Add getter for display status (#3110) 
Fixed getting the benchmarks before getting the correct permissions - caused random admin logouts (#3109)
> Live: Pending user status fix and added sqreen

- server/models/cache/singletons/permissions.js
> Fixed permissions issue on parent WDF report

- server/routes/reports/trainingReport/index.js
> Fixed bug with training report for read only users

- server/services/email-campaigns/inactive-workplaces/nextEmail.js
> Refactor getTemplate function in nextEmail.js

- migrations/20210304155254-otherServices.js
- package-lock.json
- package.json
- server/models/BulkImport/csv/establishments.js
- server/models/classes/establishment.js
- server/models/classes/establishment/properties/servicesProperty.js
- server/models/email-campaigns/inactive-workplaces/getInactiveWorkplaces.js
- server/models/establishment.js
- server/routes/ownershipRequest/index.js
- server/routes/ownershipRequest/updateOwnership.js
- server/services/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js
- server/services/email-campaigns/inactive-workplaces/nextEmail.js
- server/test/factories/establishment/csv.js
- server/test/factories/models.js
- server/test/unit/models/Bulkimport/csv/establishments.spec.js
- server/test/unit/models/classes/establishment/properties/servicesProperty.spec.js
- server/test/unit/routes/ownershipRequest/updateOwnership.spec.js
- server/test/unit/services/email-campaigns/inactive-workplaces/nextEmail.spec.js
- server/test/unit/utils/correctCapacities.spec.js
- server/utils/correctCapacities.js
- server/utils/correctServices.js
- src/app/core/model/establishment.model.ts
- src/app/core/test-utils/MockEstablishmentService.ts
- src/app/features/workplace/other-services/other-services.component.html
- src/app/features/workplace/other-services/other-services.component.spec.ts
- src/app/features/workplace/other-services/other-services.component.ts
- src/app/shared/components/submit-button/submit-button.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.html
Feat/other services no. Explictly asking the user if they have any other services yes/no/null (#3149)
fix(trim-nmdsid): Use TRIM to remove whitespace from either side of nmdsid (#3150)
Fix: 24 months plus inactive (#3152) 
Fix/other services issues (#3165) 
Bug/data permission not set correctly (#3163)
> Live: Other services No and data permissions issue

- server.js
> Added security headers to protect both back end and front end templates

- server/models/index.js
> Updated closing connections to be new sequelize-pool

- server/models/index.js
> Removed drain and just destroy all connections

- src/app/features/workers/training-qualifications-record/training/training.component.html
- src/app/shared/components/staff-summary/staff-summary.component.html
- src/app/shared/components/tabs/tabs.component.html
- src/app/shared/components/total-staff-panel/total-staff-panel.component.html
- src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html
- src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.spec.ts
- src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.html
- src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.spec.ts
- src/app/shared/components/training-info-panel/training-info-panel.component.html
- src/assets/scss/components/_inset-text.scss
- Change colour of orange banner to increase contrast
- Update `alt` text on flags so they are only used where they don't already have a description
- Change `sortBy` labels to be unique
> Fix: Accessibility Audit

- package-lock.json
- package.json
- src/app/features/search/registration/registration.component.spec.ts
> Fixed bug with 404 on training report

- server.js
> Added Security headers to staging

- server/models/classes/user.js
> Fixed out of date $not to Op.not

- server/models/BulkImport/csv/establishments.js
> Update to allow longer location ID's

- server/models/establishment.js
> Fixed bug where find one didn't have where clause

- server/models/classes/user.js
> Fixed bug where is no primary user in payload, would default to false

- src/app/features/dashboard/home-tab/home-tab.component.html
- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/dashboard/home-tab/home-tab.component.ts
> Bugfix/staffmismatchbanner: Only edit users can see mismatch banner

- server/models/classes/wdfCalculator.js
- server/routes/reports/wdf/parent.js
- server/utils/wdfEligibilityDate.js
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#3251
> Revert "Bugfix/wdf parent"

- server/models/user.js
> Fix: Registration survey

- server/reports/inactive-workplaces/subsidiaries.js
- server/reports/inactive-workplaces/workplaces.js
**Issue**
The last updated columns were including the time which is not required
**Work done**
- Applied formatting to the last updated columns to only include the date
> Hotfix: Remove time from last updated columns in KWA report

- src/app/features/login/login.component.ts
**Work done**
- Remove test local storage item that was used for testing local storage was working
> Fix: Remove test local storage item

- migrations/20210414105909-addCryptColWorker.js
> creating new columns for encryption

- server/models/satisfactionSurvey.js
- server/routes/reports/satisfactionSurveyReport/report.js
- server/test/unit/routes/reports/satisfactionSurveyReport/report.spec.js
> Update handling for empty user and establishment data

- src/app/features/public/contact-us/contact-us.component.html
**Issue**
The opening hours PR (#3274) was merged into `test` but there's an issue with the satisfaction survey so hot fixing the commit from test into live 
**Work done**
- Cherry picked #3274 into live
> Hotfix: Change support hours (#3274)

- migrations/20210414105909-addCryptColWorker.js
- server/models/registrationSurvey.js
- server/models/satisfactionSurvey.js
- server/routes/reports/index.js
- server/routes/reports/registrationSurveyReport/index.js
- server/routes/reports/registrationSurveyReport/report.js
- server/routes/reports/satisfactionSurveyReport/index.js
- server/routes/reports/satisfactionSurveyReport/report.js
- server/test/unit/routes/reports/registrationSurveyReport/report.spec.js
- server/test/unit/routes/reports/satisfactionSurveyReport/report.spec.js
- src/app/core/services/report.service.ts
- src/app/features/public/contact-us/contact-us.component.html
- src/app/features/reports/pages/reports/reports.component.html
- src/app/features/reports/pages/reports/reports.component.spec.ts
- src/app/features/reports/pages/reports/reports.component.ts
- src/app/features/search/registrations/registrations.component.html
- src/app/features/search/registrations/registrations.component.spec.ts
- src/app/features/search/registrations/registrations.component.ts
- Changed hours on Contact us page
- Added a 'Download registration survey report' button on reports page for admins
- Added functionality to download report 
> Registration survey report and contact hours change

- src/app/app-routing.module.ts
- src/app/core/breadcrumb/breadcrumb.model.ts
- src/app/core/breadcrumb/journey.wdf.ts
- src/app/core/services/breadcrumb.service.ts
- src/app/core/test-utils/MockReportService.ts
- src/app/features/wdf/wdf-overview/wdf-overview.component.html
- src/app/features/wdf/wdf-overview/wdf-overview.component.spec.ts
- src/app/features/wdf/wdf-overview/wdf-overview.component.ts
- src/app/features/wdf/wdf-routing.module.ts
- src/app/features/wdf/wdf.module.ts
- Create new WDF overview page for happy path
- Use `reportService` to get WDF dates
> Feat: WDF Overview

- server/models/classes/user/properties/emailProperty.js
- server/test/unit/models/classes/user/property/emailProperty.spec.js
- src/app/core/constants/constants.ts
> Fixed bug where it wouldn't accept an email with longer than 4 tld

- src/app/features/wdf/wdf-overview/wdf-overview.component.html
- src/app/features/wdf/wdf-overview/wdf-overview.component.spec.ts
- src/app/features/wdf/wdf-overview/wdf-overview.component.ts
- Update overview page for when user is not eligible for WDF
> Feat: WDF Overview - unhappy path

- src/app/core/breadcrumb/journey.wdf.ts
- src/app/features/wdf/wdf-data/wdf-data.component.html
- src/app/features/wdf/wdf-data/wdf-data.component.spec.ts
- src/app/features/wdf/wdf-data/wdf-data.component.ts
- src/app/features/wdf/wdf-overview/wdf-overview.component.html
- src/app/features/wdf/wdf-overview/wdf-overview.component.spec.ts
- src/app/features/wdf/wdf-routing.module.ts
- src/app/features/wdf/wdf.module.ts
- src/app/shared/components/summary-record-value/summary-record-value.component.html
- src/app/shared/components/tabs/tab.component.ts
- src/app/shared/components/tabs/tabs.component.html
- src/assets/scss/components/_tabs.scss
- Create new page for WDF data
- Add green tick to tabs component
- Hard-coded page for happy path (meeting WDF requirements)
> Feat: WDF data - workplace

- server/models/worker.js
- server/test/unit/utils/db/openpgp/decrypt.spec.js
- server/test/unit/utils/db/openpgp/encrypt.spec.js
> swapping tests and fixing column

- server/models/classes/worker/properties/dateOfBirthProperty.js
> Making sure dateofbirth is a string not an object

- server/data/parentWDFReport.js
- server/routes/reports/wdf/parent.js
> Adding decryption to wdf parent report

- server/test/factories/models.js
- src/app/core/model/establishment.model.ts
- src/app/shared/components/staff-summary/staff-summary.component.html
- src/app/shared/components/staff-summary/staff-summary.component.spec.ts
- src/app/shared/components/staff-summary/staff-summary.component.ts
- Add `WDF requirements (meeting)` and `WDF requirements (not meeting)` to sort by options
> Feat: WDF data - Staff summary

- package-lock.json
- package.json
- server/routes/postcodes.js
- server/test/unit/routes/postcodes.spec.js
- src/app/features/wdf/wdf-data/wdf-data.component.html
- src/app/features/wdf/wdf-overview/wdf-overview.component.html
- src/app/features/workplace-find-and-select/select-workplace-address/select-workplace-address.ts
- src/assets/scss/components/_tabs.scss
> Test > Live: move tab icons down, fix bug for format of addresses

- server/models/establishment.js
- server/routes/establishments/worker.js
- server/test/unit/routes/establishments/worker.spec.js
> Updated worker endpoint to be more efficient

- package-lock.json
- package.json
- server/models/establishment.js
- server/routes/establishments/worker.js
- server/routes/postcodes.js
- server/test/unit/routes/establishments/worker.spec.js
- server/test/unit/routes/postcodes.spec.js
- src/app/core/breadcrumb/journey.wdf.ts
- src/app/features/wdf/wdf-data/wdf-data.component.html
- src/app/features/wdf/wdf-overview/wdf-overview.component.html
- src/app/features/wdf/wdf-routing.module.ts
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.html
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.spec.ts
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.ts
- src/app/features/wdf/wdf.module.ts
- src/app/features/workplace-find-and-select/select-workplace-address/select-workplace-address.ts
- src/app/shared/components/staff-record-summary/staff-record-summary.component.ts
- src/assets/scss/components/_tabs.scss
> Live: Dependancy updates, worker endpoint update and WDF staff records happy path

- server/routes/establishments/worker.js
- server/test/unit/routes/establishments/worker.spec.js
> Updated worker total endpoint to use worker model call

- server/routes/establishments/worker.js
- server/test/unit/routes/establishments/worker.spec.js
- src/app/core/model/wdf.model.ts
- src/app/features/wdf/wdf-data/wdf-data.component.html
- src/app/features/wdf/wdf-data/wdf-data.component.spec.ts
- src/app/features/wdf/wdf-data/wdf-data.component.ts
- src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.html
- src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.ts
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.html
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.spec.ts
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.ts
- src/app/features/wdf/wdf-status-message/wdf-status-message.component.html
- src/app/features/wdf/wdf-status-message/wdf-status-message.component.ts
- src/app/features/wdf/wdf.module.ts
> Live: Updated worker total endpoint and WDF staff Summary

- migrations/20210430135104-workerEndpointIndexes.js
- server/models/establishment.js
> Worker endpoint fixes

- server/models/establishment.js
- server/models/worker.js
- server/routes/establishments/worker.js
- server/test/unit/routes/establishments/worker.spec.js
> Fixed query speed issue on worker endpoint

- src/app/core/services/auth.service.ts
- src/app/core/test-utils/MockAuthService.ts
- src/app/features/bulk-upload/bulk-upload-missing/bulk-upload-missing-page.component.spec.ts
- src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.spec.ts
- src/app/features/bulk-upload/bulk-upload-references/staff-references/staff-references-page.component.spec.ts
- src/app/features/bulk-upload/bulk-upload-references/workplace-references/workplace-references-page.component.spec.ts
- src/app/features/bulk-upload/bulk-upload-start-page/bulk-upload-start-page.component.spec.ts
- src/app/features/bulk-upload/error-page/error-page.component.spec.ts
- src/app/features/public/contact-us-or-leave-feedback/contact-us-or-leave-feedback.component.spec.ts
- src/app/features/public/feedback/feedback.component.spec.ts
- src/app/features/public/thank-you/thank-you.component.spec.ts
- src/app/features/reports/pages/reports/reports.component.spec.ts
- src/app/features/search/cqc-status-change/cqc-status-change.component.spec.ts
- src/app/features/search/cqc-status-changes/cqc-status-changes.component.spec.ts
- src/app/features/search/parent-request/parent-request.component.spec.ts
- src/app/features/search/parent-requests/parent-requests.component.spec.ts
- src/app/features/search/search.component.spec.ts
- src/app/features/wdf/wdf-data/wdf-data.component.spec.ts
- src/app/features/wdf/wdf-overview/wdf-overview.component.spec.ts
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.spec.ts
- src/app/shared/components/benchmarks-tab/metric/metric.component.spec.ts
- src/app/shared/components/benchmarks-tab/rankings/rankings.component.spec.ts
- src/app/shared/services/feature-flags.service.ts
> Changing Feature Flag Polling to On login

- .circleci/config.yml
> Switched order of parameters of plugin install

- src/app/features/dashboard/home-tab/home-tab.component.html
- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
> Stopped mismatch banner showing when workerCount = 0

- src/app/shared/services/feature-flags.service.ts
> removing logging

- src/app/features/wdf/wdf-data/wdf-data.component.html
- src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.html
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.spec.ts
- src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.html
- src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.spec.ts
- src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
- src/app/shared/shared.module.ts
- Create new staff mismatch component for WDF
- Add feature flags to display new staff mismatch message
- Change wording on WDF requirements state component for snagging list
> Feat: WDF Workplace - Meeting with changes

- src/app/features/wdf/wdf-staff-record/wdf-pagination/wdf-pagination.component.html
- src/app/features/wdf/wdf-staff-record/wdf-pagination/wdf-pagination.component.spec.ts
- src/app/features/wdf/wdf-staff-record/wdf-pagination/wdf-pagination.component.ts
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.html
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.spec.ts
- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.ts
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.html
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.spec.ts
- src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.ts
- src/app/features/wdf/wdf.module.ts
- src/assets/scss/components/_buttons.scss
> Feat/wdf staff record navi - WDF staff record navigation

- server/data/parentWDFReport.js
- server/models/worker.js
- server/routes/reports/wdf/parent.js
> Disabled encryption

- policy.sfcpreprod.json
- policy.sfcprod.json
> Changed cooldown to 60 seconds

- .circleci/config.yml
> Removed autoscale from production

- server/routes/cqcStatusCheck/index.js
- server/test/unit/routes/cqcStatusCheck/index.spec.js
- server/test/unit/utils/CQCDataAPI.spec.js
- src/app/core/services/establishment.service.ts
- src/app/features/dashboard/dashboard.component.ts
- src/app/features/workplace/view-workplace/view-workplace.component.ts
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#3385
> Revert "Feat/check postcode and service against cqc2"

- src/app/features/wdf/wdf-overview/wdf-overview.component.html
- src/app/features/wdf/wdf-overview/wdf-overview.component.spec.ts
- src/app/features/wdf/wdf-overview/wdf-overview.component.ts
- Added logic to display different WDF overview page for parents when both eligible and not eligible
> Feat: WDF parent overview

- src/app/features/dashboard/dashboard.component.html
- src/app/features/dashboard/dashboard.component.spec.ts
- src/app/features/dashboard/dashboard.component.ts
- src/app/features/dashboard/home-tab/home-tab.component.html
- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/dashboard/home-tab/home-tab.component.ts
- src/app/features/dashboard/home-tab/staff-mismatch-banner/staff-mismatch-banner.component.html
- src/app/features/dashboard/home-tab/staff-mismatch-banner/staff-mismatch-banner.component.spec.ts
- src/app/features/dashboard/home-tab/staff-mismatch-banner/staff-mismatch-banner.component.ts
- src/app/features/workplace/view-workplace/view-workplace.component.html
- src/app/features/workplace/view-workplace/view-workplace.component.spec.ts
- src/app/features/workplace/view-workplace/view-workplace.component.ts
- src/app/shared/components/staff-records-tab/staff-records-tab.component.html
- src/app/shared/components/staff-records-tab/staff-records-tab.component.ts
- src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html
- src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.ts
- src/app/shared/components/training-link-panel/training-link-panel.component.spec.ts
- src/app/shared/components/training-link-panel/training-link-panel.component.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
- src/app/shared/components/workplace-tab/workplace-tab.component.html
- src/app/shared/components/workplace-tab/workplace-tab.component.ts
> Cleaned up the dashboard to only query the worker endpoint once

- src/app/features/wdf/wdf-staff-record/wdf-pagination/wdf-pagination.component.spec.ts
> possible fix for tests

- .circleci/config.yml
> Tech debt/ff config cat - Adding Feature Flag check to circleCI

- src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.spec.ts
> Fix for WDF test

- src/app/features/add-mandatory-training/add-mandatory-training.component.ts
> Fixed 403 on Mandatory training

- server/models/BulkImport/csv/workers.js
- server/models/establishment.js
- server/models/worker.js
- server/routes/establishments/bulkUpload/download.js
- server/test/integration/utils/worker.js
- server/test/unit/models/Bulkimport/csv/workers.spec.js
- server/test/unit/routes/establishments/bulkUpload/download.spec.js
> Changed the way the worker file is downloaded to use database rather than restoring workers

- server/models/BulkImport/csv/training.js
- server/models/establishment.js
- server/routes/establishments/bulkUpload/download.js
- server/test/integration/utils/training.js
- server/test/unit/mockdata/training.js
- server/test/unit/models/Bulkimport/csv/training.spec.js
- server/test/unit/routes/establishments/bulkUpload.spec.js
- server/test/unit/routes/establishments/bulkUpload/download.spec.js
> Changed the way the training file is downloaded to use database rather than restoring training

- server/routes/cqcStatusCheck/index.js
- server/test/unit/routes/cqcStatusCheck/index.spec.js
- server/test/unit/utils/CQCDataAPI.spec.js
- server/utils/CQCDataAPI.js
> CQC Main Service Check

- src/app/features/wdf/wdf-workplaces-summary-table/wdf-workplaces-summary-table.component.html
- src/app/features/wdf/wdf-workplaces-summary-table/wdf-workplaces-summary-table.component.spec.ts
- src/app/features/wdf/wdf-workplaces-summary-table/wdf-workplaces-summary-table.component.ts
> Feat/wdf permissions - removing link to workplaces where the user doesn't have permissions

- server/models/BulkImport/csv/establishments.js
- server/test/unit/models/Bulkimport/csv/establishments.spec.js
> Fixing error when a service contains a zero

- server/config/config.js
> Changed LA dates

- server/routes/cqcStatusCheck/index.js
- server/test/unit/routes/cqcStatusCheck/index.spec.js
> Added a new cqc service for care home without nursing

- server/models/BulkImport/csv/establishments.js
- server/models/classes/establishment.js
- server/test/unit/models/Bulkimport/csv/establishments.spec.js
> Bugfix for capacity in bulk upload

- src/app/core/breadcrumb/journey.wdf.ts
> Tech debt: WDF tabs

- server/models/cssr.js
> Fixed CSSR lookup issue where district not found

- migrations/20210607093353-WdfEligibilityColumn.js
> Fix: WDF bug migration

- migrations/20210607093353-WdfEligibilityColumn.js
- server/models/classes/worker.js
- server/models/worker.js
- server/routes/establishments/worker.js
- server/test/unit/models/classes/worker.spec.js
- server/test/unit/routes/establishments/worker.spec.js
- src/app/features/wdf/wdf-data/wdf-data.component.spec.ts
- src/app/features/wdf/wdf-data/wdf-data.component.ts
- src/app/features/workers/social-care-qualification/social-care-qualification.component.html
- src/app/shared/components/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html
> Live: WDF bug fixes, staff record label changes

- .circleci/config.yml
- angular.json
- package.json
- src/environments/environment.preprod.ts
> Added preprod build

- src/app/features/dashboard/home-tab/home-tab.component.html
- Remove mandatory training link from home tab
> fix(removeMandatoryTrainingLinkFromHomeTab): Remove mandatory training link from home tab

- src/environments/environment.preprod.ts
> Added cmsUri to preprod

- server/models/BulkImport/csv/workers.js
- server/test/unit/models/Bulkimport/csv/workers.spec.js
> Bugfix for BU encoding special characters

- server/models/BulkImport/csv/workers.js
- server/test/factories/models.js
- server/test/unit/models/Bulkimport/csv/workers.spec.js
- src/app/features/wdf/wdf-data/wdf-data.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
- src/environments/environment.preprod.ts
> Live: CMS URI fix, BU Encoding issue and WDF update

- src/environments/environment.preprod.ts
- src/environments/environment.prod.ts
> Updated CMS URL

- src/app/features/registration/about-us/about-us.component.html
- src/app/features/registration/about-us/about-us.component.spec.ts
- src/app/features/registration/about-us/about-us.component.ts
- src/app/features/registration/registration-routing.module.ts
- src/app/features/registration/registration.module.ts
- Added a new about us component using the same about us content from the CMS
> Created new about us component for a public about us page

- src/app/shared/components/training-link-panel/training-link-panel.component.ts
Quick fix to stop the error that ForEach cant run because object doesnt exist yet. 
> fix to stop the forEach of unknown object error

- .circleci/config.yml
> Fix/circle ciff: making feature flag check not mandatory 

- src/app/core/services/articles.service.ts
- Added published filter to the articles list so it wont show draft or archived articles
> Added a filter to only show published articles

- src/app/core/breadcrumb/journey.pages-articles.ts
- src/app/features/dashboard/home-tab/home-tab.component.html
- src/app/features/pages/pages-routing.module.ts
- src/app/features/registration/create-account/create-account.component.html
- src/app/features/registration/create-account/create-account.component.spec.ts
- src/app/features/registration/registration-routing.module.ts
> Updated the about us pages URL to `about-ascwds`

- server/models/classes/worker.js
- still requires weeklyhours for WDF if ZeroHoursContracted is Don't Know
> adding the DontKnow option for wdf

- server/models/classes/worker.js
- Not answering ZeroHourContract is treated like a No or I Don't Know
> Feat/wdf zero hours - ZeroHourContract Null value

- src/app/features/bulk-upload/codes-and-guidance/codes-and-guidance.component.html
- Change BU reference filenames
> Change BU reference filenames

- server/models/classes/establishment.js
- Added isParent to the db call rather than using the sub count
> WDF Parent Fix

- src/app/core/guards/register/register.guard.ts
- src/app/core/model/location.model.ts
- src/app/core/services/registration.service.ts
- src/app/core/test-utils/MockRegistrationService.ts
- src/app/features/add-workplace/add-workplace-routing.module.ts
- src/app/features/add-workplace/select-workplace/select-workplace.component.spec.ts
- src/app/features/add-workplace/select-workplace/select-workplace.component.ts
- src/app/features/bulk-upload/codes-and-guidance/codes-and-guidance.component.html
- src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.ts
- src/app/features/create-account/workplace/is-this-your-workplace/is-this-your-workplace.component.html
- src/app/features/create-account/workplace/is-this-your-workplace/is-this-your-workplace.component.spec.ts
- src/app/features/create-account/workplace/is-this-your-workplace/is-this-your-workplace.component.ts
- src/app/features/dashboard/dashboard.component.ts
- src/app/features/registration/registration-routing.module.ts
- src/app/features/registration/registration.module.ts
- src/app/features/registration/select-workplace/select-workplace.component.html
- src/app/features/registration/select-workplace/select-workplace.component.spec.ts
- src/app/features/registration/select-workplace/select-workplace.component.ts
- src/app/features/workplace-find-and-select/select-workplace/select-workplace.component.html
- src/app/features/workplace-find-and-select/select-workplace/select-workplace.directive.ts
- src/app/features/workplace/select-workplace/select-workplace.component.ts
> Live: Changed filenames to preprod

- server/models/classes/establishment.js
- src/app/features/add-workplace/add-workplace-routing.module.ts
- src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.ts
- src/app/features/create-account/workplace/name-of-workplace/name-of-workplace.component.html
- src/app/features/create-account/workplace/name-of-workplace/name-of-workplace.component.spec.ts
- src/app/features/create-account/workplace/name-of-workplace/name-of-workplace.component.ts
- src/app/features/create-account/workplace/new-regulated-by-cqc/new-regulated-by-cqc.component.ts
- src/app/features/registration/registration-routing.module.ts
- src/app/features/registration/registration.module.ts
>  Live: WDF Fix 

- src/app/core/services/registration.service.ts
- src/app/core/utils/sanitize-postcode-util.ts
- src/app/features/add-workplace/add-workplace-routing.module.ts
- src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.spec.ts
- src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.ts
- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.html
- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.spec.ts
- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.ts
- src/app/features/registration/registration-routing.module.ts
- src/app/features/registration/registration.module.ts
- Create new workplace not found page
- Create sanitize postcode util for front end
- Set back links in `findYourWorkplace` component depending on if you've come from the workplace not found page
> Feat: Create Account - workplace not found

- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.ts
- Added line to set back link for new workplace not found page which was missed off
> Fix: Set back link

- src/app/shared/directives/user/create-username.directive.ts
> Removed console log

- src/app/features/account-management/change-user-security/change-user-security.component.ts
- src/app/features/activate-user-account/security-question/security-question.component.ts
- src/app/features/create-account/user/create-security-question/create-security-question.component.html
- src/app/features/create-account/user/create-security-question/create-security-question.component.spec.ts
- src/app/features/create-account/user/create-security-question/create-security-question.component.ts
- src/app/features/create-account/user/username-password/username-password.component.spec.ts
- src/app/features/create-account/user/username-password/username-password.component.ts
- src/app/features/registration/confirm-account-details/confirm-account-details.component.ts
- src/app/features/registration/registration-routing.module.ts
- src/app/features/registration/registration.module.ts
- src/app/shared/directives/user/security-question.directive.ts
- Changed validation messages
- Added new text
- Added tests
> Added and updated create security question

- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.spec.ts
- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.ts
- Remove full stop from error message
> Remove full stop from error message

- src/app/features/registration/registration-routing.module.ts
- Remove duplicate UsernamePasswordComponent import from registration routing
> Remove duplicate UsernamePasswordComponent import from registration routing

- src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.ts
- Fixed another error message with a full stop
> Fix error message that has a full stop

- src/app/features/registration/registration-routing.module.ts
> Fixed security question guard

- src/app/core/test-utils/MockWorkplaceService.ts
- src/app/features/add-workplace/select-workplace/select-workplace.component.spec.ts
- src/app/features/add-workplace/select-workplace/select-workplace.component.ts
- Change add-workplace flow to use workplaceService and create mock workplaceService
> hotfix(selectWorkplacePostcodeBug)

- src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.component.html
- Update heading size from `xl` to `l`
> Update heading size

- src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- Add `updateOn: 'submit'` to form fields to stop error messages disappearing when you type
> Add update on submit to form for every field

- src/app/features/create-account/user/your-details/your-details.component.spec.ts
- src/app/shared/directives/user/account-details.directive.ts
- updated error messages for an empty name and job title input
- updated relevant tests
- [ x] Yes
> your-details error messages updated

- src/app/app-routing.module.ts
- Changed URL due to Gov PaaS `/admin`
> Changed admin URL to `sfcadmin`

- src/app/features/create-account/user/create-security-question/create-security-question.component.html
- Changed text from You will to you'll
> Changed text to you'll

- server/models/BulkImport/csv/establishments.js
- Changed the BU validation to the sanitise postcode function
> Changed postcode validation

- src/app/features/admin/admin.routing.module.ts
- src/app/features/admin/local-authorities-return/local-authorities-return.component.html
- src/app/features/admin/local-authorities-return/local-authorities-return.component.spec.ts
- src/app/features/admin/local-authorities-return/local-authorities-return.component.ts
- Added content to la page
- Got dates for the new endpoint
> Added content to the local authority returns pages

- src/app/app.component.html
- src/app/app.component.ts
- src/assets/scss/components/_grid.scss
- Added new class depending on the current route you are on
- Added isAdmin flag to existing code to follow route changes
> Added wider class to new admin screens

- src/app/core/utils/format-util.spec.ts
- src/app/core/utils/format-util.ts
- src/app/features/admin/local-authorities-return/set-dates/set-dates.component.spec.ts
- src/app/features/admin/local-authorities-return/set-dates/set-dates.component.ts
- src/app/shared/validators/date.validator.ts
- Fixed validation failure when selecting a date after end date
- Moved formatters to util
> Fixed validation and moved formatters to util

- src/app/core/breadcrumb/journey.admin.ts
- src/app/core/model/admin/local-authorities-return.model.ts
- src/app/features/admin/admin.module.ts
- src/app/features/admin/admin.routing.module.ts
- src/app/features/admin/local-authorities-return/monitor/monitor.component.html
- src/app/features/admin/local-authorities-return/monitor/monitor.component.spec.ts
- src/app/features/admin/local-authorities-return/monitor/monitor.component.ts
- Created new adminn. `/monitor` route
- Added new component for monitor page
- Added non functional accordian code 
> Added monitor page

- .circleci/config.yml
- angular.json
- package.json
- src/environments/environment.benchmarks.ts
- Benchmarks should use the production FF not dev
> Updated benchmarks to use the production FF

- src/app/shared/directives/create-workplace/select-workplace-address.directive.ts
- enter-workplace-address endpoint has been replaced with workplace-name-address, so changed old flow link in select-workplace-address to new endpoint
> fix(changeOldEnterWorkplaceAddressLink)

- src/app/features/create-account/user/confirm-account-details/confirm-account-details.component.html
- src/app/features/create-account/workplace/confirm-details/confirm-details.component.html
> Fix: Confirm details page

- server/models/localAuthorities.js
- server/routes/admin/local-authority-return/monitor/index.js
- server/test/unit/routes/admin/local-authority-returns/monitor/index.spec.js
- src/app/core/services/admin/local-authorities-return/local-authorities-return.service.spec.ts
- src/app/core/services/admin/local-authorities-return/local-authorities-return.service.ts
- src/app/features/admin/local-authorities-return/monitor/monitor.component.html
- src/app/features/admin/local-authorities-return/monitor/monitor.component.spec.ts
- src/app/features/admin/local-authorities-return/monitor/monitor.component.ts
- src/app/features/admin/local-authorities-return/monitor/reset-dialog/reset-dialog.component.html
- src/app/features/admin/local-authorities-return/monitor/reset-dialog/reset-dialog.component.spec.ts
- src/app/features/admin/local-authorities-return/monitor/reset-dialog/reset-dialog.component.ts
> Reset LA's

- migrations/20210810155647-adminLAReportFunction.js
- server/routes/reports/localAuthorityReport/admin.js
- server/routes/reports/localAuthorityReport/user.js
- server/test/unit/routes/reports/localAuthorityReport/admin.spec.js
- Updated admin function to use the new table
- Added the functionality to the admin report
- Changed the way dates work on the reports to use the date in the database
> LA Reports

- src/app/features/registration-survey/why-create-account/why-create-account.component.ts
- Added new option to why did you create an account on registration survey
> Added new option to why did you create an account on registration survey

- server/models/BulkImport/csv/workers.js
- server/test/unit/models/Bulkimport/csv/workers.spec.js
- Added a No option to other job roles
- Added a fix to allow bulk upload to accept other job roles
> Added fix rather than defaulting to 0 and added no option

- server/routes/registration.js
- Address line 3 wasn't being stored in the database on registration so it has now been added to the registration endpoint
> Add address line 3 to registration endpoint

- server/routes/registration.js
- src/app/core/services/workplace-interface.service.ts
- src/app/features/add-workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.spec.ts
- src/app/features/add-workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.ts
- src/app/features/add-workplace/find-workplace-address/find-workplace-address.component.spec.ts
- src/app/features/add-workplace/new-workplace-not-found/new-workplace-not-found.component.spec.ts
- src/app/features/add-workplace/workplace-added-thank-you/workplace-added-thank-you.component.spec.ts
- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/features/create-account/workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.spec.ts
- src/app/features/create-account/workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.ts
- src/app/features/create-account/workplace/find-workplace-address/find-workplace-address.component.spec.ts
- src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.spec.ts
- src/app/features/create-account/workplace/thank-you/thank-you.component.spec.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/shared/directives/create-workplace/could-not-find-workplace-address/could-not-find-workplace-address.directive.ts
- src/app/shared/directives/create-workplace/find-workplace-address/find-workplace-address.ts
- src/app/shared/directives/create-workplace/new-workplace-not-found/new-workplace-not-found.directive.ts
- Fix for pre filling responses in create account
- Saving address line 3 in database
> Test > Live: Fix for pre filling responses in create account, saving address line 3

- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.spec.ts
- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.spec.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- Fix pre filling workplace name address
- Fix disappearing back buttons
- [] Yes
> Test > Live: Fix pre filling workplace name address (#3895)

- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.spec.ts
- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.spec.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
> Test > Live: Fix pre filling form on workplace name address

- migrations/20210818130914-addNewQualification.js
- server/models/BulkImport/BUDI/index.js
- Add Health and Social Care degree to database
- Update bulk upload validation to accept new qualification
> Feat: Add new qualification

- server/models/BulkImport/csv/establishments.js
- Changed the regex to allow more characters in a provider id
> Updated the length allowed in a provider ID

- migrations/20210831095955-updateFluVaccination.js
- server/models/worker.js
- src/app/features/workers/flu-jab/flu-jab.component.html
- src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html
- Update front end to 2021
- Add migration to rename current flu jab columns to be last year and create new columns for current flu jab status
> Feat: Flu vaccination

- server/models/userAudit.js
- add delete to the type enum on the user audit model
> add delete to userAudit model type enum

- server/models/userAudit.js
- added delete to userAudit model type enum
> add delete to userAudit model type enum (#3942)

- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.spec.ts
- src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.spec.ts
- src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/features/workplace/workplace-name-address/workplace-name-address.component.ts
- src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- Add `fixture.whenStable()` to tests to fix issue where tests were running before awaited function had finished eg. with feature flag function
- Move common code into directive
> Tech Debt: Refactor workplace name address

- server/routes/establishments/bulkUpload/complete.js
- server/routes/establishments/bulkUpload/download.js
- server/routes/establishments/bulkUpload/errorReport.js
- server/routes/establishments/bulkUpload/lock.js
- server/routes/establishments/bulkUpload/report.js
- server/routes/establishments/bulkUpload/signedUrl.js
- server/routes/establishments/bulkUpload/uploadFiles.js
- server/routes/establishments/bulkUpload/uploaded.js
- server/routes/establishments/bulkUpload/validate/index.js
- server/routes/establishments/bulkUpload/validate/validatePut.js
- Created a new `completeLock` function that can be ran separately
- Validation works in a separate worker to keep the main thread free
> Changed validation to be a seperate worker not on the main thread

- src/app/app-routing.module.ts
- src/app/core/resolvers/workers.resolver.ts
- src/app/core/services/training.service.ts
- src/app/core/test-utils/MockTrainingService.ts
- src/app/core/test-utils/MockWorkerService.ts
- src/app/features/add-multiple-training/add-multiple-training-routing.module.ts
- src/app/features/add-multiple-training/add-multiple-training.module.ts
- src/app/features/add-multiple-training/select-staff/select-staff.component.html
- src/app/features/add-multiple-training/select-staff/select-staff.component.spec.ts
- src/app/features/add-multiple-training/select-staff/select-staff.component.ts
- src/app/features/workplace/workplace-routing.module.ts
- src/app/shared/components/error-summary/error-summary.component.ts
- Created `add-multiple-training` folder and set up routing and modules
- Added `selectedStaff` array to training service to store which staff have been selected
- Created `select-staff` component
- Added check for `formArray.errors` in `error-summary` component 
> Feat: Multi update - select staff

- server/config/preproduction.yaml
- server/config/production.yaml
- server/routes/establishments/bulkUpload/validate/validatePut.js
- src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html
- src/app/shared/components/staff-record-summary/employment/employment.component.html
- src/app/shared/components/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html
- src/app/shared/components/staff-record-summary/staff-record-summary.component.ts
- src/app/shared/components/wdf-field-confirmation/wdf-field-confirmation.component.spec.ts
- src/app/shared/components/wdf-field-confirmation/wdf-field-confirmation.component.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
- Merge live branch into test
- Fix merge conflict in registrations index file
> Merge live into test branch

- src/app/features/admin/registration-requests/registration-request/registration-request.component.spec.ts
- src/app/features/admin/registration-requests/registration-request/registration-request.component.ts
- fix the error messages when clicking checkbox when already in progress
- amended the tests
> fix errors when clicking checkbox

- src/app/features/admin/registration-requests/registration-request/registration-request.component.spec.ts
- src/app/features/admin/registration-requests/registration-request/registration-request.component.ts
- create a fix for the error messages on clicking checkbox on registration page, if already in progress
> Live: merge test into live

- migrations/20210922082458-longTermAbsence.js
- server.js
- server/models/classes/worker/properties/longTermAbsenceProperty.js
- server/models/classes/worker/workerProperties.js
- server/models/worker.js
- server/routes/longTermAbsence.js
- server/test/unit/routes/longTermAbsence.spec.js
- src/app/core/model/worker.model.ts
- src/app/core/resolvers/long-term-absence.resolver.ts
- src/app/core/services/worker.service.ts
- src/app/core/test-utils/MockWorkerService.ts
- src/app/features/workers/long-term-absence/long-term-absence.component.html
- src/app/features/workers/long-term-absence/long-term-absence.component.spec.ts
- src/app/features/workers/long-term-absence/long-term-absence.component.ts
- src/app/features/workers/workers-routing.module.ts
- src/app/features/workers/workers.module.ts
- Add `LongTermAbsence` column to worker table in database
- Add `longTermAbsence` to worker endpoint
- Create `long-term-absence` component
- Create `longTermAbsence` endpoint to get enum values from the database
> Feat: Long-term absence

- src/app/features/public/terms-conditions/terms-conditions.component.html
-Add a paragraph to the Terms and Condition.
> Tand c paragraph

- server/models/BulkImport/csv/workers.js
- Change type to correct function
> Changed error to correct code

- .gitignore
- src/app/features/workers/staff-record/staff-record.component.html
- src/app/features/workers/staff-record/staff-record.component.spec.ts
- src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.html
- src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.spec.ts
-Add styles to the long term absence page
> Add styles to the long term absence page

- package.json
- Upped memory on build command to 8gb
> Upped memory on build command to 8gb

- server/routes/registration.js
- src/app/features/forgot-your-password/confirmation/confirmation.component.html
- src/app/features/forgot-your-password/forgot-your-password.component.ts
- Removed the resetUUID from the back end
- Removed the if to show it on the front end
> Removed the reset uuid from the password reset request

- .gitignore
- server/routes/reports/registrationSurveyReport/report.js
- add conditional check for establishment returned from db call
> add conditional check in print row for the establishment

- src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html
- src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts
- src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.html
- src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.ts
- Remove error messages for qualifications with achievable from/until dates
- Update error messages for validation
> Feat: Remove quals validation

- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
> Fixed tests what kept failing

- server.js
> Removed calls to test only files

- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.html
- src/app/features/workers/new-training-qualifications-record/new-training/new-training.component.html
- src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.html
- src/app/shared/components/training-info-panel/training-info-panel.component.html
- src/app/shared/components/training-info-panel/training-info-panel.component.scss
- Fix spacing issues with Training and Qualifications pages
> Fix: Training And Quals Snagging List

- server/models/establishment.js
- Added required false to workersAndTraining to prevent error being thrown when no staff records on workplace
> Fix: workersAndTraining Bug

- server/test/unit/utils/trainingAndQualificationsUtils.spec.js
- server/utils/trainingAndQualificationsUtils.js
- Added test for number rather than parseInt
> Changed check to only convert to number if only numbers and not a string on quals and workers

- src/app/features/dashboard/home-tab/home-tab.component.html
- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
- Add link to `Other links` section for first login wizard
> Feat: First login wizard link

- src/app/features/first-login-wizard/first-login-wizard.component.html
- Update styling on first login wizard 
> Fix: First login wizard - styling

- src/app/features/first-login-wizard/first-login-wizard.component.html
- src/app/features/first-login-wizard/first-login-wizard.component.scss
- Added max-width to image in the wizard
> Added a max width to the image to stop the image overflowing out of the wizard box

- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/workplace/data-sharing/data-sharing.component.spec.ts
- src/app/shared/components/workplace-tab/workplace-tab.component.spec.ts
- Added routes to spec files which had tests intermittently failing due to navigation away from component with no routes provided
- Added detectChanges to Become a parent test in home tab spec file to fix it(hopefully) 
> Fix: Flaky tests

- src/app/features/registration-survey/why-create-account/why-create-account.component.ts
- Add benefit bundle to registration survey
> Add Benefit bundle to registration survey

- server/models/establishment.js
- server/routes/reports/trainingAndQualifications/trainingTab.js
- server/test/unit/mockdata/trainingAndQualifications.js
- server/test/unit/utils/trainingAndQualificationsUtils.spec.js
- server/utils/trainingAndQualificationsUtils.js
- src/app/core/services/trainingStatus.service.ts
- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.spec.ts
- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.ts
- src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.html
- src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.spec.ts
- src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.ts
- src/app/features/workers/training-qualifications-record/training/training.component.ts
- src/app/features/workers/workers-routing.module.ts
- src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html
- src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.spec.ts
- src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.ts
- Add `ExpiresSoonAlertDate` to `workersAndTraining` and `getEstablishmentTrainingRecords` db calls
- Add `expiresSoonAlertDate` to necessary functions in `trainingAndQualificationsUtils` to calculate correct status in training reports
- Update `trainingStatus` service to use `expiresSoonAlertDate$` variable in `getTrainingStatus` function
- Delete unused function from `trainingStatus` service
- Set `expiresSoonAlertDate$` in new and old training and quals record components and categories component
- Update status messages for training and quals categories component
> Feat: Update expires soon dates

- server/routes/admin/cqc-status-change/index.js
- Delete unused variables from LGTM 
> Fix: Remove unused variables

- server/models/establishment.js
- server/routes/admin/registrations/getRegistrationNotes.js
- server/routes/admin/registrations/getSingleRegistration.js
- Check archived is true or false when getting registrations
> Bug: rejected registrations list

- src/app/features/bulk-upload/help-area/bulk-upload-help-main-page.component.html
- alter the title block for the Bulk Upload Help Main Page
> change title block on bulk upload help main page component

- src/app/features/bulk-upload/help-area/bulk-upload-help-main-page.component.html
- fix typo on bulk upload help main page
> fix typo on bulk upload help main page

- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.html
- Fix the `Long Term Absent` tag 
> Fix the Long Term Ansent Tag

- src/app/features/bulk-upload/bulk-upload-troubleshooting-page/bulk-upload-troubleshooting-page.component.html
- Fixed Margins for related content
> Fixed related content margin to be consistent with other pages

- src/app/features/bulk-upload/bulk-upload-sidebar/bulk-upload-related-content/bulk-upload-related-content.component.html
- src/app/features/bulk-upload/help-area/bulk-upload-flowchart/bulk-upload-flowchart.component.html
- src/app/features/bulk-upload/help-area/bulk-upload-flowchart/bulk-upload-flowchart.component.spec.ts
- edit flowchart download link
- add margin to data changes related content link
> updated download flowchart link

- src/app/shared/components/training-link-panel/training-link-panel.component.ts
> Removed changingExpiryDateLinkFlag Feature Flag from code

- src/app/features/bulk-upload/bulk-upload-routing.module.ts
> add resolver to about bulk upload routing

- src/app/core/components/header/header.component.html
- src/app/core/components/header/header.component.spec.ts
> Changed back to admin link to go to new admin pages

- src/app/core/test-utils/MockAuthService.ts
- src/app/features/login/login.component.html
- src/app/features/login/login.component.spec.ts
- src/app/features/login/login.component.ts
- Redirected to admin if role is admin
- Added tests
> Added redirect to sfcadmin on login for admins

- src/app/core/breadcrumb/journey.workplaces.ts
- src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts
- src/app/features/workers/add-edit-training/add-edit-training.component.ts
- Changed all paths to /training
> Fixed URL's to go to new training page at /training

- src/app/features/bulk-upload/help-area/bulk-upload-help-main-page.component.spec.ts
- src/app/features/bulk-upload/help-area/bulk-upload-top-tip-page/bulk-upload-top-tip-page.component.spec.ts
- Fixes to flaky tests by passing the correct URL's
> Fix for flaky tests

- server/models/BulkImport/csv/crossValidate.js
- server/test/unit/models/Bulkimport/csv/crossValidate.spec.js
- Fixed status not been found if workplace not found
- Added test for if it to check if it's not true OR false
> Fixed issue where if status is not found it would try access it and fail

- lambdas/bulkUpload/serverless.yml
- Changed supported version in yml file
> Updated serverless framework supported version

- .circleci/config.yml
- lambdas/bulkUpload/serverless.yml
- Changed framework version to 2c 
- installed latest 2.72 release
> Dropped serverles to version 2

- .circleci/config.yml
> Fixed Typo

- src/app/features/bulk-upload/bulk-upload-sidebar/bulk-upload-related-content/bulk-upload-related-content.component.ts
- Removed the null check for data changes flag
> removed the null check for data changes flag

- server/utils/security/isAuthenticated.js
- Fixed database call to get the correct permissions
> Fixed database call for parent check

- src/app/features/workers/new-training-qualifications-record/missing-mandatory-training/missing-mandatory-training.component.html
- src/app/features/workers/new-training-qualifications-record/missing-mandatory-training/missing-mandatory-training.component.spec.ts
- src/app/features/workers/new-training-qualifications-record/missing-mandatory-training/missing-mandatory-training.component.ts
- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.html
- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.spec.ts
- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.ts
- src/app/features/workers/workers.module.ts
- Added new mandatory training messages
- Removed tests that were no longer relevant
- Added tests for new training messages
> Added new mandatory training messages

- src/app/features/workplace/workplace-routing.module.ts
- change required permission for accessing add-mandatory-training
> change permission required to access the add-mandatory-training route

- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record-summary/new-training-and-qualifications-record-summary.component.scss
> Bug: Added default font size for training summary box

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/core/breadcrumb/journey.benefits-bundle.ts
- src/app/features/benefits-bundle/benefits-bundle.component.html
- src/app/features/benefits-bundle/benefits-bundle.component.spec.ts
- src/app/features/benefits-bundle/benefits-bundle.component.ts
- src/app/features/benefits-bundle/benefits-elearning/benefits-elearning.component.html
- src/app/features/benefits-bundle/benefits-elearning/benefits-elearning.component.ts
- src/app/features/benefits-bundle/benefits-elearning/benefits-elearning.spec.ts
Co-authored-by: M Daley <mdaley-madetech@users.noreply.github.com>
Added dynamic content for eLearning benefits bundle.
> Added new eLearning modules component

- src/app/features/workers/staff-details/staff-details.component.ts
- Fixes bug introduced by [adding a cancel button ticket](https://trello.com/c/ILEZMgO3/767-add-a-staff-record-cancel-link).
- Refactored logic for cancel navigation.
> bug/addStaffBtn "Fixes incorrect rendering of text when adding staff"

- src/app/features/workers/other-qualifications-level/other-qualifications-level.component.spec.ts
- src/app/features/workers/other-qualifications/other-qualifications.component.spec.ts
- Fixes tests due to conflicts in merges.
> Fixes other qualification tests

- server/test/unit/utils/security/permissions.spec.js
- server/utils/security/permissions.js
- src/app/app-routing.module.ts
- src/app/core/guards/permissions/check-permissions/check-permissions.guard.spec.ts
- src/app/core/guards/permissions/has-permissions/has-permissions.guard.spec.ts
- src/app/core/model/permissions.model.ts
- src/app/features/bulk-upload/bulk-upload-routing.module.ts
- src/app/features/workplace/workplace-routing.module.ts
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#4644
> Revert "Revert "Feat/remove role guard""

- server/models/establishment.js
- server/test/unit/security/isAuthenticated.spec.js
- server/utils/security/isAuthenticated.js
- Added tests around authorisedEstablishmentPermissionCheck
- Refactored authorisedEstablishmentPermissionCheck into smaller functions
> Tech debt/isAuthenticatedFlow

- server/test/unit/security/isAuthenticated.spec.js
- server/utils/bulkUploadUtils.js
- server/utils/security/isAuthenticated.js
- Fix for broken parent/child authentication 
> Fix/isAuthDefect - Updates check for parent/child

- src/app/features/workers/staff-record/staff-record.component.spec.ts
- src/app/features/workers/staff-record/staff-record.component.ts
- Fix navigation to workplace if establishment is a parent
> FIX - Confirm staff record navigation

- server/config/development.yaml
- server/config/preproduction.yaml
- server/config/production.yaml
> Remove the indentation in Yaml file for disbursement

- migrations/20220302121750-loginTableAddIndexForRegistrationId.js
- create migration for adding an index to the login table, to speed up getInactiveWorkplace function call
> correctly implement migration down function for login index migration

- server.js
- server/config/config.js
- Added report URI to config
- Added report URI to Expect CT
> Added report URI

- .circleci/config.yml
- Repurposes benchmarks branch to mimic deployed application.
> Circle CI deployment updates

- server/models/establishment.js
- server/routes/establishments/worker.js
- server/test/unit/routes/establishments/worker.spec.js
- Alter query to accept a limit and offset
- Change query to order results
- Update response with count for pagination
> Server changes for pagination for workers

- server/routes/cqcStatusCheck/index.js
- server/test/unit/routes/cqcStatusCheck/index.spec.js
- Added new service type under Community healthcare services
> Added new service type under Community healthcare services

- manifest.benchmarks.yml
- manifest.bluegreen.yml
- manifest.dev.yml
- manifest.preprod.yml
- manifest.prod.yml
- manifest.test.yml
- package-lock.json
- package.json
- Updated manifests to have the latest buildpack all the time
- Updated engine to node 16 (without a minor or patch version, this will use latest node 16 version)
- Removed unused manifests
> Updated to node 16

- src/app/features/workers/main-job-start-date/main-job-start-date.component.spec.ts
- src/app/features/workers/main-job-start-date/main-job-start-date.component.ts
- src/app/features/workers/mandatory-details/mandatory-details.component.ts
- Adds state navigation when adding staff details so that journey flow can be correct
> Fix - Staff record journey navigation

- src/app/app-routing.module.ts
- src/app/core/resolvers/workers.resolver.spec.ts
- src/app/core/resolvers/workers.resolver.ts
- src/app/features/add-multiple-training/add-multiple-training-routing.module.ts
- src/app/features/add-multiple-training/select-staff/select-staff.component.spec.ts
- src/app/features/add-multiple-training/select-staff/select-staff.component.ts
- Updated workers resolver to check if it is being called for pagination to determine how many workers to get
> fix(updateAddMultipleTraining) 

- server/routes/admin/registrations/addRegistrationNote.js
- remove default scope for archived establishments for adding registration notes
> Bug - Registration notes on rejected establishments

- src/app/core/components/header/header.component.html
- Removed class if link not active on header
> Added underlines on all links in header except active links

- server/models/establishment.js
- server/test/unit/routes/admin/registrations/getRegistrations.spec.js
- server/utils/registrationsUtils.js
- src/app/features/admin/registration-requests/pending-registration-requests/pending-registration-requests.component.html
- src/app/features/admin/registration-requests/pending-registration-requests/pending-registration-requests.component.spec.ts
- Updated the clock format for pending registrations created timestamp
- Added regulated column to registration table
> Admin update - Registrations

- src/app/core/components/header/header.component.html
- src/app/core/components/header/header.component.logout.spec.ts
- src/app/core/components/header/header.component.ts
- Add fix to prevent refreshing admin page everytime
> add fix to prevent refreshing admin page everytime

- src/app/core/components/header/header.component.html
- src/app/core/components/header/header.component.logout.spec.ts
- src/app/core/components/header/header.component.ts
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#4828
> Revert "add fix to prevent refreshing admin page everytime"

- src/app/shared/components/summary-list/summary-list.component.html
- src/app/shared/directives/create-workplace/confirm-workplace-details/confirm-workplace-details.directive.ts
- src/assets/scss/modules/_utils.scss
- Replaces `<br/>` with newline and CSS styling 
> fix - removes setting of innerHTML

- server/utils/middleware/rateLimiting.js
> Add  windowMs for rate limitimg

- server/utils/middleware/rateLimiting.js
> changed the rate limiter

- server/utils/middleware/rateLimiting.js
> change rateLimiting to 200

- server/utils/middleware/rateLimiting.js
> Add fix for rate limiter

- server/utils/middleware/rateLimiting.js
> change dbLimiter

- server/models/establishment.js
> Sort workplace in alphabetic order

- server/models/email-campaigns/inactive-workplaces/getInactiveWorkplacesForDeletion.js
- server/reports/inactive-workplaces/deleteInactiveWorkplace.js
- server/services/email-campaigns/inactive-workplaces/setInactiveWorkplacesForDeletion.js
- server/test/unit/reports/inactive-workplaces/deleteInactiveWorkplace.spec.js
> Add additional fields for inactive workplaces report

- .circleci/config.yml
- Changed workflows to deploy serverless after blue green deployment
- Moved serverless deployment to a different location in circleci config.yml
> Tech debt/move lambda in circle workflow

- src/app/features/workplace/services-capacity/services-capacity.component.html
- Changed services capacity title (size and text) and message
> feat: workplaceDetailsCapacityOfServicesTextChanges

- src/app/features/benefits-bundle/benefits-bundle.component.html
- src/app/features/benefits-bundle/benefits-bundle.component.spec.ts
- src/app/features/benefits-bundle/benefits-bundle.component.ts
Removed unnecessary accordion sections and amended voucher code. Also removed tests that are no longer needed.
> Removed unnecessary accordion fields and amended voucher code text

- src/app/features/registration-survey/why-create-account/why-create-account.component.ts
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#4939
> Revert "Feat/registration survey amendment"

- src/app/features/workplace/start/start.component.spec.ts
- src/app/features/workplace/start/start.component.ts
- src/app/shared/components/workplace-tab/workplace-tab.component.html
Added back link to workplace details start page
> Added back link to workplace details start page

- src/app/features/workplace/other-services/other-services.component.html
- src/app/features/workplace/other-services/other-services.component.spec.ts
- src/app/features/workplace/other-services/other-services.component.ts
- Updated other services header text and error message text
> Feat/workplace Details Do You Provide Any Other Services Text Change

- src/app/features/dashboard/home-tab/home-tab.component.spec.ts
> Add fix for failing test

- server/test/factories/establishment/csv.js
> remove obsolete SHARELA field from test factory

- src/app/features/workplace/other-services/other-services.component.ts
- src/app/features/workplace/start/start.component.html
- src/app/features/workplace/start/start.component.spec.ts
- Change the navigation
- Edit the Workplace flow  info 
> Change the navigation and change the info about workplace

- src/app/features/admin/admin-users/admin-account-view/admin-account-view.component.spec.ts
> add dialog service to the admin-account-view component

- src/app/features/admin/admin-users/admin-account-view/admin-account-view.component.spec.ts
> comment out failing admin-account-view component tests

- src/app/features/workplace/services-capacity/services-capacity.component.html
- src/app/features/workplace/services-capacity/services-capacity.component.spec.ts
- src/app/features/workplace/services-capacity/services-capacity.component.ts
Added progress bar to services-capacity.
> Added progress bar to services-capacity component

- server/models/classes/user.js
- server/utils/security/isAuthenticated.js
> remove updates to audit tables from the db transaction

- src/app/features/workplace/number-of-interviews/number-of-interviews.component.html
- src/app/features/workplace/number-of-interviews/number-of-interviews.component.spec.ts
- src/app/features/workplace/number-of-interviews/number-of-interviews.component.ts
- src/app/features/workplace/starters/starters.component.html
- Implemented progress bar on the page
- updated page spacing
- updated header text content
> Feat/Implemented Progress Bar Staff Recruitment Interviews

- src/app/features/workplace/accept-previous-care-certificate/accept-previous-care-certificate.component.html
- src/app/features/workplace/accept-previous-care-certificate/accept-previous-care-certificate.component.spec.ts
- src/app/features/workplace/accept-previous-care-certificate/accept-previous-care-certificate.component.ts
-  Implemented progress bar
-  made small navigation refactor
> Feat/Implement Progress Bar Staff Recruitment Care Certificate

- migrations/20220718113815-workerAuditTableAddIndexForUsername.js
> fix existing index check in migration

- migrations/20220718113815-workerAuditTableAddIndexForUsername.js
> modify worker audit migration

- migrations/20220718113815-workerAuditTableAddIndexForUsername.js
> alter migration to set name of index

- migrations/20220718113815-workerAuditTableAddIndexForUsername.js
- server/routes/accounts/user.js
- src/app/features/admin/admin-users/admin-account-view/admin-account-view.component.spec.ts
- src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.spec.ts
> change migration

- server/routes/establishments/bulkUpload/s3.js
- server/routes/establishments/bulkUpload/uploaded.js
- src/app/core/services/bulk-upload.service.ts
- src/app/features/bulk-upload/last-bulk-upload/last-bulk-upload.component.html
- src/app/features/bulk-upload/last-bulk-upload/last-bulk-upload.component.ts
- Changed how type of file is working in last-bulk-upload 
> Bug/admin Download Most Recent Upload

- src/app/features/workplace/start/start.component.html
- Added bullet points and changed bullet point spacing
> Feat/workplace Start Page Amendments

- src/app/features/workplace/staff-benefit-cash-loyalty/staff-benefit-cash-loyalty.component.ts
> changed the message for validation

- lambdas/bulkUpload/validateWorker/index.js
- server/models/classes/establishment.js
- Fixed null violation in recruitmentJourneyExistingUserBanner
> fix/staff Recruitment Banner Not Null Violation

- src/app/features/login/login.component.ts
- src/app/features/workplace/type-of-employer/type-of-employer.component.spec.ts
- src/app/features/workplace/type-of-employer/type-of-employer.component.ts
-changed navigation route to first login wizard
> type of employer now navigates to first login wizard

- src/app/features/dashboard/dashboard-header/dashboard-header.component.html
- src/app/shared/components/progress-bar/progress-bar.component.html
-  Fixed formatting issue on header, component and progress bar
> Fix/staff Recruitment Snagging List V2

- migrations/20220819091447-removeEnumApprenticeshipAndReplaceit.js
> change the migration and removed the transaction

- server/models/BulkImport/csv/workplaceCSVValidator.js
- server/models/classes/establishment.js
- src/app/features/bulk-upload/drag-and-drop-files-list/drag-and-drop-files-list.component.spec.ts
- src/app/features/bulk-upload/drag-and-drop-files-list/drag-and-drop-files-list.component.ts
> set banner flags in the backend on bulk upload

- src/app/features/add-workplace/find-workplace-address/find-workplace-address.component.spec.ts
- src/app/features/create-account/workplace/find-workplace-address/find-workplace-address.component.spec.ts
- src/app/shared/directives/create-workplace/find-workplace-address/find-workplace-address.component.html
- src/app/shared/directives/create-workplace/find-workplace-address/find-workplace-address.directive.ts
- add progress bar to find workplace address component
> add progress bars to find-workplace-address component

- src/app/features/create-account/workplace/thank-you/thank-you.component.html
- src/app/features/create-account/workplace/thank-you/thank-you.component.spec.ts
- Add new reveal for the contact us and changed the style 
> change the style for the registration thank you page and fix the tests

- src/app/features/benefits-bundle/benefit-tailored-seminars/benefit-tailored-seminars.component.html
- src/app/features/benefits-bundle/benefits-bundle.component.html
> Add the requested changes for the benefit bundle

- src/app/features/add-workplace/workplace-added-thank-you/workplace-added-thank-you.component.html
- src/app/features/add-workplace/workplace-added-thank-you/workplace-added-thank-you.component.spec.ts
- change the confirmation panel 
- add reveal for contact us
> Add the design changes for the add workplace

- migrations/20220908102458-updateServices.js
- Added migration for updating services
> add services data migration

- src/app/features/add-workplace/add-workplace-routing.module.ts
- src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.spec.ts
- src/app/features/add-workplace/select-main-service/select-main-service.component.spec.ts
- src/app/features/add-workplace/select-main-service/select-main-service.component.ts
- src/app/features/create-account/workplace/confirm-workplace-details/confirm-workplace-details.component.spec.ts
- src/app/features/create-account/workplace/select-main-service/select-main-service.component.spec.ts
- src/app/features/create-account/workplace/select-main-service/select-main-service.component.ts
- src/app/features/registration/registration-routing.module.ts
- src/app/shared/directives/create-workplace/confirm-workplace-details/confirm-workplace-details.directive.ts
- src/app/shared/directives/create-workplace/select-main-service/select-main-service.component.html
- src/app/shared/directives/create-workplace/select-main-service/select-main-service.directive.ts
- Fixed bug where error handling was incorrect in main service select
- Fixed bug where wrong buttons would show on main service
> Feat/ Registration Flow Pre Merge Fixes

- src/app/features/dashboard/home-tab/home-tab.component.ts
- Changed employerTypeValue check to include .toLowerCase as employerType was returned with varying capitalisation during service usage
> Fix/Progress Report Download Link Disappearing

- server/models/classes/user/properties/emailProperty.js
- src/app/core/constants/constants.ts
> change email regex to allow apostrophe in first part of email

- migrations/20220920144617-servicesAmendments.js
- src/app/features/workplace/other-services/other-services.component.html
-Added new migration to update services
-Amended other services text
> amended text on other services page, updated service in db

- src/app/features/create-account/workplace/confirm-details/confirm-details.component.html
- src/app/features/create-account/workplace/confirm-details/confirm-details.component.spec.ts
- src/app/features/create-account/workplace/type-of-employer/type-of-employer.component.spec.ts
- src/app/features/create-account/workplace/type-of-employer/type-of-employer.component.ts
- Fixed a typo on conformation pages
- Changed type of employer header so it will no longer display the workplaceName on create-account
> Feat/snagging List Create Account V2 

- src/app/core/services/wizard.service.ts
> Add fix for login wizard

- src/app/core/test-utils/MockWorkerService.ts
- src/app/features/workers/question/question.component.ts
- src/app/features/workers/staff-details/staff-details.component.html
- src/app/features/workers/staff-details/staff-details.component.spec.ts
- src/app/features/workers/staff-details/staff-details.component.ts
- src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html
- src/app/shared/components/staff-record-summary/staff-record-summary.component.ts
- src/app/shared/components/staff-summary/staff-summary.component.ts
- Added progress bar to create-staff-record
- Fixed navigation for pages leaving or navigating to create-staff-record and staff-details
> feat(createStaffRecordAmendments): Re-wrote page navigtion

- src/app/features/workers/year-arrived-uk/year-arrived-uk.component.html
- src/app/features/workers/year-arrived-uk/year-arrived-uk.component.spec.ts
- src/app/features/workers/year-arrived-uk/year-arrived-uk.component.ts
- Added progress bars
- Fixed page routing
- Year can now enter text in year input and validation only allowing numbers has been added
> Feat/arrived In UK amendments

- src/app/features/workplace/starters/starters.component.html
> change the text from vacancies to starters

- src/app/features/workers/date-of-birth/date-of-birth.component.spec.ts
- src/app/features/workers/date-of-birth/date-of-birth.component.ts
- src/app/features/workers/nationality/nationality.component.spec.ts
- src/app/features/workers/nationality/nationality.component.ts
- src/app/features/workers/question/question.component.ts
- Add tests for backlinks on date-of-birth and nationality page
- Alter question component so back links work
- Change Nationality component so returns to the correct page when hitting backlink outside of flow
> add backlink tests for date-of-birth and nationality components

- src/app/features/workplace/starters/starters.component.html
- Change the Total vacancies text
> fix the total starters text

- server/routes/establishments/bulkUpload/download.js
> alter logs in mapping function

- server/routes/establishments/bulkUpload/download.js
> remove await from before calling trainingCsv function

- server/routes/establishments/bulkUpload/download.js
> add additional logging

- server/routes/establishments/bulkUpload/download.js
> add logging

- server.js
- server/routes/establishments/bulkUpload/download.js
- src/app/features/admin/admin-users/admin-account-view/admin-account-view.component.spec.ts
> add await to trainingCsv function

- server/routes/establishments/bulkUpload/download.js
- server/routes/establishments/bulkUpload/download/trainingCSV.js
> add more logging

- server/routes/establishments/bulkUpload/download/trainingCSV.js
> add logging for decodingURI

- server/models/BulkImport/csv/workplaceCSVValidator.js
- server/models/classes/establishment.js
- server/routes/establishments/bulkUpload/validate/validateEstablishmentCsv.js
> add logging to BU validation

- src/app/core/services/establishment.service.spec.ts
- src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.spec.ts
- src/app/features/admin/admin-users/admin-account-view/admin-account-view.component.spec.ts
> Spike circle ci flaky test/fix flaky tests

- karma.conf.js
- package-lock.json
- package.json
- src/app/core/utils/workplace-util.ts
- src/app/features/admin/admin-users/admin-account-view/admin-account-view.component.spec.ts
- src/app/features/workers/adult-social-care-started/adult-social-care-started.component.spec.ts
- src/app/features/workers/days-of-sickness/days-of-sickness.component.spec.ts
- src/app/features/workplace/staff-recruitment/staff-recruitment-start.component.spec.ts
- src/app/shared/components/workplace-tab/workplace-tab.component.spec.ts
- Fixed the tests failing locally.
- Add reporter package to find the failing tests on circle ci 
> Spike circle ci flaky test/fix local tests

- server/models/classes/establishment.js
- server/models/classes/worker.js
- server/routes/establishments/bulkUpload/validate/validateBulkUploadFiles.js
- server/routes/establishments/bulkUpload/validate/validateEstablishmentCsv.js
- server/routes/establishments/bulkUpload/validate/validatePut.js
- server/routes/establishments/bulkUpload/validate/workers/validateWorkerCsv.js
- server/routes/establishments/bulkUpload/validate/workers/validateWorkers.js
> add logs to backend

- server/models/BulkImport/csv/workplaceCSVValidator.js
- server/models/classes/worker.js
- server/routes/establishments/bulkUpload/complete.js
- server/routes/establishments/bulkUpload/s3.js
- server/routes/establishments/bulkUpload/validate/validateBulkUploadFiles.js
- server/routes/establishments/bulkUpload/validate/validatePut.js
- server/routes/establishments/bulkUpload/validate/workers/validateWorkerCsv.js
- server/routes/establishments/bulkUpload/validate/workers/validateWorkers.js
> add logs to complete function due to bug

- server/routes/establishments/bulkUpload/complete.js
- server/routes/establishments/bulkUpload/s3.js
- remove logs added for debugging
> remove console.logs in complete.js and s3.js

- src/app/features/activate-user-account/create-username/create-username.component.ts
- src/app/features/activate-user-account/security-question/security-question.component.ts
- src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.spec.ts
- src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.ts
- src/app/features/add-workplace/select-main-service/select-main-service.component.spec.ts
- src/app/features/add-workplace/select-main-service/select-main-service.component.ts
- src/app/features/add-workplace/start/start.component.spec.ts
- src/app/features/add-workplace/start/start.component.ts
- src/app/features/create-account/user/create-security-question/create-security-question.component.ts
- src/app/features/create-account/user/username-password/username-password.component.ts
- src/app/features/create-account/user/your-details/your-details.component.ts
- src/app/features/create-account/workplace/confirm-workplace-details/confirm-workplace-details.component.ts
- src/app/features/registration/change-your-details/change-your-details.component.ts
- src/app/features/workplace/select-main-service/select-main-service.component.ts
- src/app/shared/components/new-back-link/new-back-link.component.html
- src/app/shared/components/new-back-link/new-back-link.component.spec.ts
- src/app/shared/directives/create-workplace/confirm-workplace-details/confirm-workplace-details.directive.ts
- src/app/shared/directives/create-workplace/select-main-service/select-main-service.directive.ts
- src/app/shared/directives/create-workplace/select-workplace/select-workplace.component.html
- src/app/shared/directives/user/account-details.directive.ts
- src/app/shared/directives/user/create-username.directive.ts
- src/app/shared/directives/user/security-question.directive.ts
- make fixes to components using new back link 
- Change back link to show just back
> make fixes to pages using new back links

- src/app/core/components/error/cannot-create-account/cannot-create-account.component.spec.ts
- src/app/core/components/error/cannot-create-account/cannot-create-account.component.ts
- add new back links to cannot create account page
> add new back links to the cannot create account page

- server/config/config.js
- server/config/preproduction.yaml
- server/config/production.yaml
- server/config/test.yaml
> config changes for certificates bucket

- server/routes/establishments/certificates.js
> debugging s3 getObject errors

- server/routes/establishments/certificates.js
> additional logging for s3 upload

- server/routes/establishments/certificates.js
> more logging around s3

- server/routes/establishments/certificates.js
> yet more logging around s3 functionality

- server/routes/establishments/certificates.js
> added ACL back in

- server/routes/establishments/certificates.js
> even more logging

- server/config/config.js
- server/routes/establishments/certificates.js
> change get object

- server/routes/establishments/certificates.js
> make the s3 object awaitable

- server/routes/establishments/certificates.js
- src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.ts
> get certificate route

- server.js
- src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.ts
> get cetificate route

- server/routes/establishments/certificates.js
> Add logs to get the params

- server/routes/establishments/certificates.js
- src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.ts
> remove ACL

- src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.html
> Updated file path

- src/app/core/breadcrumb/journey.public.ts
- Changed breadcrumb text on certificates page
> Certificates breadcrumb fix

- server/routes/establishments/certificates.js
-Removed fileExists check to allow overwriting of existing files
> Removed fileExists check to allow overwriting of existing files

- server/models/user.js
- server/routes/admin/search/users/index.js
- src/app/core/services/admin/search/search.service.ts
- src/app/features/admin/search/search-for-user/search-for-user.component.ts
> add logging for debugging

- server/models/user.js
- server/routes/admin/search/users/index.js
- src/app/core/services/admin/search/search.service.ts
- src/app/features/admin/search/search-for-user/search-for-user.component.ts
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#5498
> Revert "add logging for debugging"

- server/config/sequelize.js
> change the way sequelize gets db credentials for test environment

- src/app/features/workplace/change-expires-soon-alerts/change-expires-soon-alerts.component.html
-Altered styling on manage expiry alerts page to more closely align with design
> fixed spacing on paragraphs

- migrations/20230113093014-trainingCategoryAmendments.js
- src/app/features/add-mandatory-training/add-mandatory-training.component.html
-  Minor adjustments to existing training categories and default text for dropdown
> Training Category Amendments

- src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.spec.ts
- src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.ts
- src/app/shared/directives/add-edit-training/add-edit-training.directive.ts
- change the routing for redirecting after deletion
> change the route for delete and fixes the failing tests

- src/app/shared/components/workplace-summary/workplace-summary.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
- Re-order list of other services
> Changed list ordering for other services

- src/app/core/resolvers/workers.resolver.ts
> bug in workers resolver fixed

- src/app/features/workplace/create-user-account/create-user-account.component.ts
-removed breadcrumbs, added back link
> removed breadcrumb from add user page, added back link instead

- src/app/features/workplace/services-capacity/services-capacity.component.spec.ts
- src/app/features/workplace/services-capacity/services-capacity.component.ts
- Updated validation messaging to be more specific to service types
> updated error messaging

- src/app/features/add-multiple-training/confirm-multiple-training/confirm-multiple-training.component.html
- src/app/features/add-multiple-training/confirm-multiple-training/confirm-multiple-training.component.ts
- ui change to confirm multiple training page
> change the grey heading size on the confirm multiple training page

- src/app/shared/components/wdf-field-confirmation/wdf-field-confirmation.component.ts
> change the  setreturn to true to see if this solve the issue

- server/models/classes/wdfCalculator.js
- src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html
- src/app/shared/components/staff-record-summary/employment/employment.component.html
- src/app/shared/components/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html
- src/app/shared/components/wdf-field-confirmation/wdf-field-confirmation.component.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.html
> Add fix for wdf redirection

- src/app/shared/directives/add-edit-training/add-edit-training.directive.ts
> add fix for expiry date validation

- src/app/core/services/benchmarks.service.ts
-  Add fix for Benchmark read-only users 
> fix the benchmark signing out for benchmark edit users

- server/routes/admin/search/users/index.js
- src/app/features/dashboard/dashboard.component.html
- Removed workplace condition from benchmark tab
> remove workplace condition on benchmarks tab

- src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html
- src/app/features/workers/add-edit-qualification/add-edit-qualification.component.spec.ts
- src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts
> fix qualifications page

- server/models/classes/mandatoryTraining.js
- src/app/core/model/establishment.model.ts
- src/app/core/services/establishment.service.ts
- src/app/core/test-utils/MockEstablishmentService.ts
- src/app/features/add-mandatory-training/add-mandatory-training.component.spec.ts
- src/app/features/add-mandatory-training/add-mandatory-training.component.ts
> change update mandatory training so the training category can be updated

- src/app/features/new-dashboard/dashboard-header/dashboard-header.component.html
> remove border on add staff record button

- server/models/benchmarks.js
- server/models/establishment.js
> alter get benchmarks data call to use the main service reporting id

- .gitignore
- server/models/establishment.js
> fix search not working correctly on training call

- src/app/features/workers/new-training-qualifications-record/new-training/new-training.component.html
> correct spelling mistake on table heading

- src/app/core/utils/workplace-util.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.html
- src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts
- src/app/shared/components/workplace-summary/workplace-summary.component.ts
> fix bug on wdf page that removed employer type when confirming field

- src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.ts
- fix problem with new wdf workplace summary component due to changes to format type of employer util
> fix employer type formatting error in wdf workplace summary component

- src/app/core/services/pdf.service.ts
- src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.html
- Remove the new header from appearing in the pdf download for the new benchmark page
> Set benchmark header no not display in pdf

- src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.spec.ts
- src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.ts
- Added training and quals message 3 to summary box
- Resolved minor navigation bug
> Added message 3 to summary panel

- src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.html
- src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.spec.ts
- src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.ts
-Added message 4 for training and quals summary on home page
> added summary message 4 for training and quals

- src/app/features/new-dashboard/home-tab/home-tab.component.html
- src/app/features/new-dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/new-dashboard/home-tab/home-tab.component.ts
- src/mockdata/establishment.js
- https://trello.com/c/lnqeYeSU/1234-home-page-non-regulated-link-for-benchmarks
- Updated text on benchmark card
> updated text on benchmark link

- src/app/features/new-dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/new-dashboard/home-tab/home-tab.component.ts
-Casing change for workplace town name
> formatted casing on town name

- .vscode/launch.json
- Change launch.json file to activate debugging
> fix the lauch.json file to enable debugging

- src/app/features/new-dashboard/staff-tab/staff-basic-record/staff-basic-record.component.html
> change column name for staff basic records

- src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.html
> change the tumbanil year which was hardcoded

- server/models/cssr.js
- server/routes/establishments/benchmarks/index.js
- server/test/unit/routes/establishments/benchmarks.spec.js
- Changed query to return different column
> changed cssr query to return la area

- server/routes/establishments/benchmarks/benchmarksService.js
- server/routes/establishments/benchmarks/rankings/index.js
- change call for getting benchmarks to use cssr id
> fix getting benchmarks metrics

- angular.json
- index.prod.html
- index.test.html
- lighthouserc.json
- service_unavailable/index.html
- src/app/features/new-dashboard/home-tab/home-tab.component.spec.ts
- src/app/features/new-dashboard/home-tab/home-tab.component.ts
- Add Configuration for Google Analytics 4 
> Add the configuration for Google Analalytics 4

- src/app/features/registration-survey/how-did-you-hear-about/how-did-you-hear-about.component.spec.ts
- src/app/features/registration-survey/how-did-you-hear-about/how-did-you-hear-about.component.ts
- Add two additional options to registration survey
> Add additional options to registration survey

- src/app/features/new-dashboard/dashboard/dashboard.component.html
- src/app/features/new-dashboard/dashboard/dashboard.component.spec.ts
- src/app/features/new-dashboard/dashboard/dashboard.component.ts
- src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.spec.ts
- Add a check to only show the new data area to establishments with services of 1,2 and 8.
> bug-fix/Do main service check before rendering benchmarks tab

- server/models/api/services.js
- server/models/classes/establishment.js
- server/test/unit/models/classes/establishment/properties/servicesProperty.spec.js
- src/app/core/model/establishment.model.ts
- src/app/features/new-dashboard/dashboard/dashboard.component.ts
- Add `reportingID` to the service model to allow it to be use in the frontend in data area check
> Bug fix/use main service reporting id for data area check

- src/app/features/new-dashboard/data-area-tab/data-area-tab.component.html
- Fix to add the new downloads title to the data area page
> Add downloads link text to data are page

- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.html
> text change for comparison group

- src/app/core/model/benchmarks.model.ts
- src/app/core/test-utils/MockBenchmarkService.ts
- src/app/shared/components/benchmarks-select-view-panel/benchmarks-select-view-panel.component.html
- src/app/shared/components/benchmarks-select-view-panel/benchmarks-select-view-panel.component.spec.ts
- src/app/shared/components/benchmarks-select-view-panel/benchmarks-select-view-panel.component.ts
- src/app/shared/components/benchmarks-tab/rankings/rankings.component.spec.ts
- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.html
- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.spec.ts
- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.ts
- src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruiment-and-retention.component.ts
- src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruitment-and-retention.component.html
- src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruitment-and-retention.component.spec.ts
- src/app/shared/components/data-area-tab/data-area-tab.component.html
- src/app/shared/components/data-area-tab/data-area-tab.component.spec.ts
- src/app/shared/components/data-area-tab/data-area-tab.component.ts
- src/app/shared/components/data-area-tab/data-area-tab.module.ts
- src/app/shared/components/data-area-tab/download-pdf/download-pdf.component.html
- src/app/shared/components/data-area-tab/download-pdf/download-pdf.component.spec.ts
- src/app/shared/components/data-area-tab/download-pdf/download-pdf.component.ts
- src/assets/scss/modules/_utils.scss
- refactor data area pay
- create date area recruitment and retention
- update tests
> Feat/benchmarks r and r table#1249

- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.html
- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.spec.ts
- src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.ts
- src/app/shared/components/data-area-tab/data-area-tab.module.ts
- src/app/shared/components/data-area-tab/data-area-table-row/data-area-table-row.component.html
- src/app/shared/components/data-area-tab/data-area-table-row/data-area-table-row.component.ts
https://trello.com/c/m6wlpP66/1253-data-area-pay-missing-job-role-data-at-workplace
Created new table row component for comparison table
> created new component for comparison table rows

- server/routes/reports/registrationSurveyReport/report.js
- Add sort to registration survey report so responses show in correct submitted date order
> Add sort on registration survey report

- index.html
- index.prod.html
- index.test.html
- update google analytics codes
> fix google analytics codes

- server/models/benchmarksEstablishmentsAndWorkers.js
- server/models/benchmarksEstablishmentsAndWorkersGoodOutstanding.js
- server/models/cssr.js
- server/models/postcodes.js
- server/routes/establishments/benchmarks/benchmarksService.js
- server/utils/getAddressAPI.js
> add logs to find address api call issue

- migrations/20230710115502-addJobRoles.js
> chnge the page margin

- src/app/shared/components/data-area-tab/data-area-tab.component.html
- src/app/shared/components/data-area-tab/data-area-tab.component.ts
- Remove pdf link from data area for [ticket](https://trello.com/c/Sy9UxqSj/1305-download-pdf-link)
> Remove pdf link from data area

- src/app/features/benefits-bundle/benefits-bundle.component.html
- [Ticket](https://trello.com/c/8QbfgcW5/1315-change-text-in-benefits-bundle)
- Update voucher code on benefits bundle page
> Update voucher code in benefits bundle

- src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart-options-builder.ts
- Update font size and colour for bar chart axis title
> Update font size and colour for bar chart axis title

- src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.html
- Update misspelt word in wdf card 
- Update sentence in bulk upload card
> Fix misspelt word and update text on parent home tab

- src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.html
- src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.spec.ts
- Update the card link for ASC-WDS, on parent home tab
> Update card link on parent home tab

- backend/Dockerfile
- migration_scripts.sh
- server.js
- server/config/config.js
The following commits have been moved over from the [SFC-Migration-Test](https://github.com/NMDSdevopsServiceAdm/SFC-Migration-Test) repo
- [WIP: Frontend Backend Split](https://github.com/NMDSdevopsServiceAdm/SFC-Migration-Test/commit/7c0bd4ff81cb7dbfe4581415bced86e32de4af7d)
- [add corsOptions to the server.js](https://github.com/NMDSdevopsServiceAdm/SFC-Migration-Test/commit/31f1369f15f15c681ee8baab73a96ab871763554)
- [Update dockerfile to specify architecture when building](https://github.com/NMDSdevopsServiceAdm/SFC-Migration-Test/commit/87453b62c9901625b26f8aec2288a1ebb9b9398f)
- [Update server.js to setup CORS for the backend routes](https://github.com/NMDSdevopsServiceAdm/SFC-Migration-Test/commit/e8aec4d6fddcd65188f536206dc27c6ff977162f)
- [Add env overide for get address api …
> Frontend Backend split capability for AWS migration

- package-lock.json
- package.json
- This shoud fix the CORS package thats not being found as part of this [CircleCI run](https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/runs/15705215037)
> Fix cors package

- server/routes/establishments/benchmarks/index.js
- src/app/app-routing.module.ts
- src/app/core/breadcrumb/journey.workplaces.ts
- src/app/features/dashboard/dashboard.component.html
- src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking-options-builder.ts
- src/app/shared/components/data-area-tab/data-area-tab.component.ts
- src/app/shared/components/staff-records-tab/staff-records-tab.component.html
- src/app/shared/components/training-link-panel/training-link-panel.component.html
- src/app/shared/components/workplace-tab/workplace-tab.component.html
- merge bug fix from pre-prod (live branch) into staging (test branch)
> Merge live into test

- package-lock.json
- src/app/features/registration/create-account/create-account.component.html
- Updated main text for the "create an account" page.
> Updated main text for create an account page

- .gitignore
- terraform/environment/non-prod/main.tf
- terraform/modules/backend/main.tf
- terraform/modules/backend/varibles.tf
- terraform/modules/networking/internet_gateway.tf
- terraform/modules/networking/nat_gateway.tf
- terraform/modules/networking/outputs.tf
- terraform/modules/networking/security_group.tf
- terraform/modules/networking/varibles.tf
- terraform/modules/networking/vpc.tf
- Create new VPC with public and private subnets along with supporting infrastructure.
- Add S3 backend for Terrform
- Fix RDS password generation to meet password requirements
- add .gitignore for terraform
- Create outputs for private subnets and security groups to be consumed by the backend
- Deploy RDS & Elasticache to the new VPC
- Expose Elasticache endpoint programatically via replication group so it can be consumed by parameter store
> Create new VPC with public and private subnets

- .gitignore
- buildspec/build.yml
- buildspec/deploy-backend.yml
- buildspec/deploy-frontend.yml
- buildspec/test-backend.yml
- buildspec/test-frontend.yml
- buildspec/test-performance.yml
- karma.conf.js
- lighthouserc.json
- migration_scripts.sh
- Build pipeline to build and test application code
- Update migration script to include karma, nyc & lighthouse
- Update karma and lighthouse config file for Codebuild (backwards compatible with circleci)
- Add extra entries to gitignore
> Create pipeline to build and test our post migration application code

- buildspec/build.yml
- buildspec/deploy-backend.yml
- buildspec/deploy-frontend.yml
- buildspec/deploy-staging.yml
- Update existing build specs
- Create deploy staging buildspec
> Update existing buildspec file  and create deploy-staging buildspec

- buildspec/deploy-staging.yml
- Add capability to assume a role and start app runner deployment
> Add capability to assume a role and start app runner deployment

- migrations/20231121095049-fix-postcode-thoroughfare-column.js
- Added new migration to resolve issue creating new column in postcodes table
> created new migration to resolve column creation issues

- src/app/features/workplace/workplace-routing.module.ts
- Quick routing fix to resolve navigation on new benchmarks
> resolved issue accessing about the data page

- src/app/features/workplace/view-workplace/view-workplace.component.html
- added ability to view new benchmarks on subs when logged in as parent
> view new benchmarks on subs when logged in as parent

- server/models/cssr.js
- server/routes/reports/localAuthorityReport/user.js
- server/test/unit/routes/reports/localAuthorityReport/user.spec.js
- Temp turn off faulty test
- Fix pluralisation issue
- Fix if
> Fix pluralisation and faulty if, ignore faulty test

- server/models/BulkImport/csv/workplaceCSVValidator.js
- server/test/unit/models/Bulkimport/csv/workplaceCSVValidator.spec.js
> revert workplaceCSVvalidator status

- server/models/classes/establishment/establishmentExceptions.js
- Added err to exception response for testing
> add fields to exception

- server/routes/reports/deleteReport/report.js
- Re-added establishmentsData map so we're not passing a null reference.
> added map for postcodes to get cssrs for deletion report

- server/models/classes/training.js
- Added logging to BU training
> added log to BU

- src/app/shared/components/benchmarks-select-comparison-group/benchmarks-select-comparison-group.component.html
> Fix typo benchmarks select comparision group

- server/models/classes/establishment.js
- server/models/cssr.js
- server/models/pcodedata.js
- server/test/unit/routes/pcodedata.spec.js
> add debugging and return empty arrays

- service_unavailable/assets/service_unavailable.css
- service_unavailable/index.html
- Add correct path to the links and alt tags
-  Increased font size 
- Adjusted wordings in the page 
>  Change Service unavailable page text and font size

- server/models/pcodedata.js
> Readd lost merge

- backend/server/config/test.yaml
- Set SSL to False for testing purposes
> Change SSL to false in config for testing purposes

- frontend/src/environments/environment.preprod.ts
- frontend/src/environments/environment.prod.ts
- frontend/src/environments/environment.test.ts
- frontend/src/environments/environment.ts
- Add app runner endpoints to the application
> Add app runner endpoints

- frontend/src/environments/environment.preprod.ts
- frontend/src/environments/environment.prod.ts
- frontend/src/environments/environment.test.ts
- frontend/src/environments/environment.ts
- Remove app runner endpoints so /api can be served on the same domain
> Let Cloudfront handle /api

- backend/server/config/benchmarks.yaml
- backend/server/config/preproduction.yaml
- backend/server/config/production.yaml
- Change Sequalize configuration to avoid keychain issues
> Change Sequalize configuration to avoid keychain issues

- backend/server/models/classes/worker.js
- Reverted the transaction changes for BU
> revert the transaction changes for bulkupload

- backend/server/config/benchmarks.yaml
- Set the secrets to false for benchmark
> set the secrets to false for benchmark

- buildspec/deploy/deploy-benchmark.yml
- Add command so frontend assets get deployed to benchmarks
> Add pipeline command so frontend assets get deployed to benchmarks

- README.md
- frontend/karma.conf.js
> test main branch

- backend/server/services/email-campaigns/isWhitelisted.js
- Disable whitelist when parameter = off
> Disable send in blue whitelist when parameter = off

- buildspec/build/test-frontend.yml
- Allow frontend-tests to stop pipeline on failure
> Allow frontend-tests to stop pipeline on failure

- .github/workflows/codeql.yml
- Set codeql to run off PR's against main
> Set codeql to run off PR's against main

- frontend/src/app/core/services/bulk-upload/bulk-upload-top-tips.service.spec.ts
- frontend/src/app/features/admin/external-link/external-link.component.html
- frontend/src/app/features/admin/external-link/external-link.component.spec.ts
- frontend/src/environments/environment.preprod.ts
- frontend/src/environments/environment.prod.ts
- frontend/src/environments/environment.test.ts
- frontend/src/environments/environment.ts
- Migrated the CMS from Self Hosted GovPaaS to Directus Cloud
> Migrate CMS to Directus Cloud

- frontend/src/app/features/benefits-bundle/benefits-bundle.component.html
- frontend/src/app/features/benefits-bundle/benefits-bundle.component.spec.ts
- Change the text for the Benefit bundle
> Change the text for benefit bundle

- frontend/src/app/features/benefits-bundle/benefits-bundle.component.html
- frontend/src/app/features/benefits-bundle/benefits-bundle.component.spec.ts
- Change the link for benefit bundle
> Change the link for benefit bundle

- frontend/src/app/core/breadcrumb/journey.public.ts
- frontend/src/app/core/components/footer/footer.component.html
- Added about asc-wds route to the breadcrumb journey
- Added about asc-wds link to the footer component 
> Add changes to the footer links

- frontend/src/app/core/breadcrumb/journey.public.ts
- frontend/src/app/core/components/footer/footer.component.html
- This reverts commit reverse the changes made to add changes to the footer in PR  #6099
> Revert add changes to the footer 

- frontend/src/app/core/services/establishment.service.ts
- Removed console.log which break the sign out page flow. 
> Remove console.log

- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.html
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- frontend/src/app/features/subsidiary/subsidiary.module.ts
- Added content to staff records page
- added page to subsidiary module
> added staff records page content for subs

- frontend/src/app/core/breadcrumb/journey.subsidiary.ts
- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.html
- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.ts
- frontend/src/app/core/services/breadcrumb.service.ts
- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- frontend/src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.html
- frontend/src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.ts
- fixed benchmark about the data link
- added about the data link routing to the subsidiary 
> Fix benchmark about data link

- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.html
- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.ts
- Added input to display `Add a staff record button`
- Added updated date input to show the updated date in the staff records banner
> Add missing button in banner

- frontend/src/app/core/services/breadcrumb.service.ts
- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts
- frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
- frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.ts
- frontend/src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.ts
- Show banner on the main tabs 
> Show banner only on the main tabs

- frontend/src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.ts
- Removed subsidiary link from the about the data link component
> Remove subsidiary to the workplace routing in about the data link component

- frontend/src/app/shared/services/subsidiary-router-service.spec.ts
- frontend/src/app/shared/services/subsidiary-router-service.ts
-Added condition to exit sub view on account management page
> added satisfaction-survey to exit sub view list

- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.ts
- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts
- frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
- frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.ts
- frontend/src/app/shared/components/summary-section/summary-section.component.ts
- frontend/src/app/shared/services/parent-subsidiary-view.service.ts
- Fixed rendering banner in summary section links in home tab
- Fixed broken back to parent link
> Make summary section links in home tab to render correct banner

- frontend/src/app/shared/services/subsidiary-router-service.spec.ts
- frontend/src/app/shared/services/subsidiary-router-service.ts
- Fixed 'return to admin' link when viewing subs
> fixed return to admin link on subs

- frontend/src/app/app-routing.module.ts
- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- frontend/src/app/features/subsidiary/subsidiary.module.ts
- Added `userResolver` to `subsidiary.module`
> added user resolver to subsidiary module

- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts
- frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
> Allow banner to be showen in the pages

- frontend/src/app/core/services/breadcrumb.service.ts
- frontend/src/app/core/services/establishment.service.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
- frontend/src/app/features/workplace/edit-workplace/edit-workplace.component.ts
- frontend/src/app/features/workplace/start/start.component.ts
- frontend/src/app/shared/services/parent-subsidiary-view.service.ts
- frontend/src/app/shared/services/subsidiary-router-service.ts
> Remove console logging

- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.html
- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.ts
- frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
- frontend/src/app/shared/components/new-dashboard-header/dashboard-header.component.ts
- frontend/src/app/shared/services/parent-subsidiary-view.service.ts
- Show multiple training records button
- add-multiple-training component added to subsidiary routing
> Show add training button

- frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.ts
- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts
- frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
- frontend/src/app/features/subsidiary/workplace-users/view-subsidiary-workplace-users.component.ts
- frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.ts
- frontend/src/app/shared/services/parent-subsidiary-view.service.ts
- Added observer server to get last updated date
- Subscribe the service in subsidiary component 
- Added the last updated value in tab component
> Add observer service to get last updated date for each tab component

- backend/server/routes/admin/registrations/getRegistrations.js
- backend/server/test/unit/routes/admin/registrations/getRegistrations.spec.js
- Add check to return null when there is no parent id
> Add check to return null when there is no parent id

- frontend/src/app/features/new-dashboard/dashboard/dashboard.component.html
- Add the canSeeNewDataArea flag for stand alone
> Add the canSeeNewDataArea flag for stand alone

- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-pay/data-area-useful-link-pay.component.html
- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-pay/data-area-useful-link-pay.component.spec.ts
- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-recuitment/data-area-useful-link-recruitment.component.html
- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-recuitment/data-area-useful-link-recruitment.component.spec.ts
- Made useful-links-pay, useful-links-recruitment not render if no data
> Hotfix- Handle null return data from CMS

- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.html
- Removed test message from subsidiary training and qualifications
> Remove no workers message from subs t&q

- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-pay/data-area-useful-link-pay.component.html
- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-pay/data-area-useful-link-pay.component.spec.ts
- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-recuitment/data-area-useful-link-recruitment.component.html
- frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-recuitment/data-area-useful-link-recruitment.component.spec.ts
- Merging CMS fix which went into the main branch into the test branch 
> Merge cms fix from main into test

- frontend/src/app/features/new-dashboard/link-to-parent/link-to-parent.component.html
- frontend/src/app/features/new-dashboard/link-to-parent/link-to-parent.component.scss
- Change Cancel link in link-to-parent to use govuk-button-group and fix height
> Change Cancel link in link-to-parent to use govuk-button-group and fix height

- frontend/src/app/shared/components/new-tabs/new-tabs.component.html
- frontend/src/app/shared/components/new-tabs/new-tabs.component.scss
- frontend/src/app/shared/components/new-tabs/new-tabs.component.ts
- frontend/src/assets/scss/components/_tabs.scss
- Added variable css extensions for new-tabs component when in parentViewingSubsidiary mode.
> Fix spacing on subsidiary new tabs

- frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.html
- frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.spec.ts
- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.spec.ts
> Add unit tests

- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.html
- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.spec.ts
- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts
- frontend/src/app/shared/components/data-area-tab/data-area-tab.component.html
- frontend/src/app/shared/components/data-area-tab/data-area-tab.component.spec.ts
- frontend/src/app/shared/components/data-area-tab/data-area-tab.component.ts
- Refactored `viewSubsidiaryBenchmarksComponent` to reduce duplicate code
> Parent sub benchmarks refactor

- frontend/src/app/app-routing.module.ts
- frontend/src/app/app.module.ts
- frontend/src/app/features/benefits-bundle/benefits-bundle-routing.module.ts
- frontend/src/app/features/benefits-bundle/benefits-bundle.module.ts
- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- Added benefits bundle path to the subsidiary routing
> Add benefits bundle path to the subsidiary routing

- frontend/src/app/app.module.ts
- frontend/src/app/features/new-dashboard/training-tab/training-link-panel/training-link-panel.component.ts
- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- frontend/src/app/shared/shared.module.ts
- Fixed broken Add a mandatory training category in sub and standalone view.
> Fix broken mandatory category 

- backend/migrations/20240416091645-addNewJobRoles.js
- Added db migration for new job roles
> added new job roles migration

- backend/reference/jobRoles.js
- Added mappings to BU for new job roles
> added mappings to BU for new job roles

- frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.html
- frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.spec.ts
- frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
- Update url for view your benchmarks button in about the data page for benchmarks v1
> Update url on view your benchmarks button

- backend/server/config/config.js
- backend/server/test/unit/utils/CQCDataAPI.spec.js
- backend/server/utils/CQCDataAPI.js
- Updated CQC API call to use new endpoint and add subscription key as header
> Update CQC API endpoint

- backend/package-lock.json
- backend/package.json
- backend/server.js
- backend/server/config/config.js
- backend/server/models/establishment.js
- backend/server/routes/nhsBsaApi.js
- backend/server/routes/nhsBsaApi/index.js
- backend/server/routes/nhsBsaApi/workplaceData.js
- backend/server/test/unit/routes/nhsBsaApi/workplaceData.spec.js
- backend/server/utils/middleware/isNHSBSAAuthenticated.js
- backend/server/utils/middleware/rateLimitingNHSBSAAPI.js
- backend/server/utils/security/NHSBSAgenerateJWT.js
- Add two routes for NHSBSA API (one for authentication and another for data retrieval )
- Add sequelize query to retrieve data from database
- Add function to retrieve WDF eligibility for each workplace
- Add authentication with jwt token
- Add ratelimiting
> NHSBSA-API changes

- frontend/src/app/features/new-dashboard/link-to-parent/link-to-parent.component.html
- Updated spacing for Send link request and cancel buttons on link to parent page
> Updated spacing for Send link request and cancel buttons on link to parent page

- backend/package-lock.json
- backend/package.json
- backend/server.js
- backend/server/config/config.js
- backend/server/models/establishment.js
- backend/server/routes/nhsBsaApi/index.js
- backend/server/routes/nhsBsaApi/workplaceData.js
- backend/server/test/unit/routes/nhsBsaApi/workplaceData.spec.js
- backend/server/test/unit/utils/CQCDataAPI.spec.js
- backend/server/utils/CQCDataAPI.js
- backend/server/utils/middleware/isNHSBSAAuthenticated.js
- backend/server/utils/middleware/rateLimitingNHSBSAAPI.js
- backend/server/utils/security/NHSBSAgenerateJWT.js
- Merge the work in the main branch into the test branch
> Merge main into test

- frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.html
- fixed spacing in the about the data page in old benchmarks page
> Fix spacing

- frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts
- frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts
- frontend/src/app/features/subsidiary/workplace-users/view-subsidiary-workplace-users.component.ts
- frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.ts
- Manually set tabs for each sub-page so that the pages and tabs look consistent when the browser back button has been clicked.
> Set tabs in each sub pages

- backend/migrations/20240424143655-renameTrainingCategories.js
- Added new migration for renaming training categories
> added migration for renaming training categories

- backend/migrations/20240419083154-addTrainingCategories.js
- backend/migrations/20240424143655-renameTrainingCategories.js
- backend/reference/trainingCategory.js
- Removed Assisting and moving people from new training categories as an existing category is being renamed to it
- Fixed capitalisation and spelling mistakes
> Remove Assisting and moving people from new training categories as an existing category is being renamed to it

- frontend/src/app/features/new-dashboard/become-a-parent/become-a-parent.component.spec.ts
- frontend/src/app/features/new-dashboard/become-a-parent/become-a-parent.component.ts
- frontend/src/app/features/new-dashboard/home-tab/home-tab.component.spec.ts
- frontend/src/app/features/new-dashboard/link-to-parent/link-to-parent.component.spec.ts
- frontend/src/app/features/new-dashboard/link-to-parent/link-to-parent.component.ts
- frontend/src/app/features/new-dashboard/remove-link-to-parent/remove-link-to-parent.component.spec.ts
- frontend/src/app/features/new-dashboard/remove-link-to-parent/remove-link-to-parent.component.ts
- frontend/src/app/features/workplace/change-data-owner/change-data-owner.component.spec.ts
- frontend/src/app/features/workplace/change-data-owner/change-data-owner.component.ts
- frontend/src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.spec.ts
- frontend/src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.ts
- frontend/src/app/shared/directives/new-home-tab/new-home-tab.directive.ts
- Added alert service to link to parent notification messages
> Fix alert banners in home page 

- Makefile
- backend/bin/run-db-migrations.js
- backend/migrations/20240415084724-simplifySequencingForTrainingCategories.js
- backend/migrations/20240419083154-addTrainingCategories.js
- backend/migrations/20240424143655-renameTrainingCategories.js
- backend/migrations/20240501131241-fixTrainingCategoryName.js
- backend/package.json
- backend/reference/trainingCategory.js
- backend/server/config/sequelize.js
- backend/server/models/cache/singletons/trainingCategories.js
- backend/server/routes/workerTrainingCategories.js
Merge latest changes in main into test branch
> Merge main into test branch

- frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.html
- Added data protection header to old About the data page
> Added data protection header to old About the data page

- frontend/src/app/core/breadcrumb/journey.subsidiary.ts
- frontend/src/app/features/workplace/user-account-edit-permissions/user-account-edit-permissions.component.spec.ts
- frontend/src/app/features/workplace/user-account-edit-permissions/user-account-edit-permissions.component.ts
- frontend/src/app/features/workplace/user-account-view/user-account-view.component.spec.ts
- frontend/src/app/features/workplace/user-account-view/user-account-view.component.ts
- Set subsidiary breadcrumbs on user pages when in sub view
> Set subsidiary breadcrumbs on user pages when in sub view

- backend/migrations/20240416091645-addNewJobRoles.js
- backend/reference/jobRoles.js
- backend/server.js
- backend/server/routes/nhsBsaApi/apiDocs.js
- backend/server/routes/nhsBsaApi/docs/wds-api.yaml
- backend/server/test/unit/routes/cqcStatusCheck/index.spec.js
- backend/server/test/unit/routes/nhsBsaApi/apiDocs.spec.js
> Merge main branch into test

- frontend/src/app/shared/components/new-tabs/new-tabs.component.spec.ts
- frontend/src/app/shared/components/new-tabs/new-tabs.component.ts
- Updated new-tabs component to use variable for isParentViewingSub to correct spacing of tabs in sub view
- Added tests which check correct classes are being set in different views
> Correct spacing of tabs in sub view

- frontend/src/app/features/new-dashboard/workplace-tab/workplace-tab.component.html
- frontend/src/app/features/new-dashboard/workplace-tab/workplace-tab.component.ts
- frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.html
- frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.ts
- frontend/src/app/shared/components/new-workplace-summary/workplace-summary.component.spec.ts
- frontend/src/app/shared/components/new-workplace-summary/workplace-summary.component.ts
- Pass in navigateToTab function to workplace tab components to handle difference between tab navigation in parent and sub view
> Pass in navigateToTab function to workplace tab components to handle difference between tab navigation in parent and sub view

- backend/server/routes/nhsBsaApi/workplaceData.js
- backend/server/test/unit/routes/nhsBsaApi/workplaceData.spec.js
> Merge main branch into test branch

- frontend/src/app/features/workers/employed-from-outside-uk/employed-from-outside-uk.component.html
- frontend/src/app/features/workers/employed-from-outside-uk/employed-from-outside-uk.component.spec.ts
- frontend/src/app/features/workers/employed-from-outside-uk/employed-from-outside-uk.component.ts
- Reworded reveal
- Removed unnecessary code
> removed unnecessary code, reworded reveal

- backend/server/routes/nhsBsaApi/workplaceData.js
- backend/server/test/unit/routes/nhsBsaApi/workplaceData.spec.js
> Merge main into international recruitment

- frontend/src/app/features/new-dashboard/training-tab/training-link-panel/training-link-panel.component.html
- frontend/src/app/features/new-dashboard/training-tab/training-link-panel/training-link-panel.component.spec.ts
- frontend/src/app/features/new-dashboard/training-tab/training-link-panel/training-link-panel.component.ts
- Added link to download the parent training report to the new training panel
> Add parent training report to new version of training panel

- frontend/src/app/features/benefits-bundle/benefits-bundle.component.html
- Updated discount code for bookshop in benefits bundle
> Update discount code for bookshop in benefits bundle

- backend/migrations/20240711142204-addTrainingGroupsEnum.js
- backend/migrations/20240711151423-setTrainingGroupCategories.js
- backend/server/models/workerTrainingCategories.js
- Added enum for training category groups
- Added new `TrainingCategoryGroup` column to `TrainingCategories` table
- Populated new column in `TrainingCategories`
> added and populated new trainingCategoryGroup column

- backend/server/routes/establishments/bulkUpload/validate/workers/validateWorkerUnderNationalInsuranceMaximum.js
- backend/server/test/unit/routes/establishments/bulkUpload/validate/workers/validateWorkerUnderNationalInsuranceMaximum.spec.js
- Update number being checked as national insurance maximum hours from 65 to 75 to be aligned with individual worker validation in bulk upload
> Update hours number for worker over ni maximum check

- frontend/src/app/shared/components/accordions/radio-button-accordion/radio-button-accordion.component.html
- frontend/src/app/shared/components/accordions/radio-button-accordion/radio-button-accordion.component.ts
- Update value passed by radio button accordion to also pass the category label as it was only passing the id 
> Update radio btn accordion to also pass label

- backend/server/routes/jobs.js
- frontend/src/app/core/model/job.model.ts
- frontend/src/app/features/wdf/wdf-data-change/wdf-routing.module.ts
- frontend/src/app/features/workers/main-job-role/main-job-role.component.html
- frontend/src/app/features/workers/main-job-role/main-job-role.component.spec.ts
- frontend/src/app/features/workers/main-job-role/main-job-role.component.ts
- frontend/src/app/features/workers/workers-routing.module.ts
- frontend/src/app/features/workers/workers.module.ts
For [Editing main job role](https://trello.com/c/wGZAeFaM/1467-jobs-roles-editing-main-job-role)
- Create new page for main job role which will only pre-fill the main job, if already saved on the worker andsave the updated job
> 1467 jobs roles editing main job role

- frontend/src/app/features/benefits-bundle/benefit-accordion/benefit-accordion.component.html
- frontend/src/app/features/benefits-bundle/benefits-bundle.component.html
- frontend/src/app/features/benefits-bundle/benefits-bundle.component.spec.ts
- frontend/src/app/shared/components/accordions/radio-button-accordion/grouped-radio-button-accordion/grouped-radio-button-accordion.component.html
- frontend/src/app/shared/components/accordions/radio-button-accordion/grouped-radio-button-accordion/grouped-radio-button-accordion.component.spec.ts
- frontend/src/app/shared/components/accordions/radio-button-accordion/grouped-radio-button-accordion/grouped-radio-button-accordion.component.ts
- frontend/src/app/shared/components/accordions/radio-button-accordion/radio-button-accordion.component.spec.ts
- Resolved issues with Show/Hide and Show/Hide all buttons on accordions
> Fixed issues with show/hide all text

- frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-qualifications/new-qualifications.component.html
- frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-qualifications/new-qualifications.spec.ts
- Removed notes column from quals table on training page
> removed notes column from quals table

- .github/dependabot.yml
- Change target branch and limit in dependabot.yml
- Also add group for patch updates
> Change target branch and limit in dependabot.yml

- backend/migrations/20240926141934-renameManagerJobRole.js
> added missing migration

- backend/migrations/20240909153100-fixQualificationStatsViewForAnalysisFiles.js
- backend/migrations/20240909153600-fixWorkerTrainingStatsViewForAnalysisFiles.js
- Added migrations to include archived workers in qualification and training stats views
> Add migrations to include archived workers in qualification and training stats views

- frontend/src/app/features/registration-survey/why-create-account/why-create-account.component.ts
- Updated WDF option in registration survey to be generic funding option
> Update WDF option in registration survey to be generic funding option

- frontend/src/app/shared/components/certifications-table/certifications-table.component.html
- frontend/src/app/shared/components/certifications-table/certifications-table.component.spec.ts
- frontend/src/app/shared/components/certifications-table/certifications-table.component.ts
- Update certificates table to show date on files to upload
> Display today's date on certificate files to be uploaded

- backend/server/models/classes/qualification.js
- backend/server/test/unit/models/classes/qualification.spec.js
- Fixed an issue where qualification model tests weren't running due to an unexpected import
- Fixed a failing test that was previously hidden by the above issue
> fixed qualifications models tests not running

- frontend/src/app/shared/validators/custom-form-validators.ts
- Changed priority order for cert upload  error messages
> swapped the priority of the error messages for cert uploads

- frontend/src/app/features/wdf/wdf-data-change/wdf-staff-summary/wdf-staff-summary.component.html
- Removed standalone condition on no staff record message
> removed unnecessary condition on no staff message

- frontend/src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.html
- frontend/src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.spec.ts
- frontend/src/app/shared/components/new-workplace-summary/workplace-summary.component.html
- frontend/src/app/shared/components/new-workplace-summary/workplace-summary.component.spec.ts
- frontend/src/app/shared/components/workplace-summary/workplace-summary.component.html
- frontend/src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts
- Update wording for starters and leavers on workplace summary and wdf workplace summary 
> Change starters and leavers wording on workplace summary

- frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- frontend/src/app/features/workplace/select-leaver-job-roles/select-leaver-job-roles.component.spec.ts
- frontend/src/app/features/workplace/select-leaver-job-roles/select-leaver-job-roles.component.ts
- frontend/src/app/features/workplace/select-vacancy-job-roles/select-vacancy-job-roles.component.ts
- frontend/src/app/features/workplace/vacancies-and-turnover/select-job-roles.directive.ts
- frontend/src/app/features/workplace/vacancies-and-turnover/select-job-roles.html
- frontend/src/app/features/workplace/workplace-routing.module.ts
- frontend/src/app/features/workplace/workplace.module.ts
- Created second page for leavers - '_Select leaver job roles_'
> Feat: Leavers 2nd page - 'Select leaver job roles'

- frontend/src/app/app.module.ts
- frontend/src/app/features/new-dashboard/delete-workplace/delete-workplace.component.ts
- frontend/src/app/features/workplace/select-leaver-job-roles/select-leaver-job-roles.component.spec.ts
- frontend/src/app/features/workplace/select-starter-job-roles/select-starter-job-roles.component.ts
- frontend/src/app/features/workplace/select-starter-job-roles/select-starter-job-roles.spec.ts
- frontend/src/app/features/workplace/select-vacancy-job-roles/select-vacancy-job-roles.component.spec.ts
- frontend/src/app/features/workplace/vacancies-and-turnover/select-job-roles.directive.ts
- frontend/src/app/features/workplace/vacancies-and-turnover/select-job-roles.html
- frontend/src/app/features/workplace/workplace-routing.module.ts
- Added new page for starters job roles
> Add new starters page

- backend/server/utils/limitFindUserAccountUtils.js
- Change the Redis client config for new code, passing in redis.url as a string
> try fix redis client config for find user account attempts

- frontend/src/app/core/test-utils/MockEstablishmentService.ts
- frontend/src/app/shared/components/navigate-to-workplace-dropdown/navigate-to-workplace-dropdown.component.spec.ts
> Test skipped dropdown tests in pipeline

- frontend/src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.scss
- Added padding to the right side of the column to ensure that text wraps at the correct point
> added padding to first column

- frontend/src/app/app.component.spec.ts
- frontend/src/app/app.component.ts
- Removed help button from admin page
> removed help button from admin pages

- frontend/cypress/e2e/standAloneEstablishment/EditUser/helpPages.spec.cy.js
- Added basic e2e tests for the help section
> Create e2e tests for navigating to different pages in help section

- frontend/src/app/app.component.spec.ts
- frontend/src/app/app.component.ts
- Updated checks for rendering help button to hide when viewing help section in sub view
> Fix: Stop help button rendering in sub view

- frontend/src/app/features/help/helpful-downloads/helpful-downloads.component.html
- Fixed alignment on downloads tab in help section
> fixed alignment on helpful downloads page

- frontend/src/app/features/help/q-and-a-page/q-and-a-page.component.html
- Fixed positioning of navbar line on individual Q&A page
> Fix positioning of navbar line on individual Q&A page

- frontend/src/app/features/funding/wdf-overview/wdf-overview.component.html
- frontend/src/app/features/funding/wdf-overview/wdf-overview.component.spec.ts
- Updated wording on funding requirements link to match when meeting and not meeting
> Fix: Update funding link wording

- frontend/src/app/features/benefits-bundle/benefits-bundle.component.html
- Updated bookshop code in benefits bundle
> Fix: Update bookshop code in benefits bundle

- frontend/src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.html
- frontend/src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.spec.ts
- Corrected 'No, change it' links for SLV in funding workplace summary
> Correct 'No, change it' links for SLV in funding workplace summary

- frontend/src/app/features/dashboard/home-tab/home-tab.component.html
- frontend/src/app/features/new-dashboard/home-tab/home-tab.component.html
- frontend/src/app/shared/components/other-links/other-links.component.html
- Removed NEW from ASC-WDS certificate link on home pages
> Remove NEW from ASC-WDS certificate link on home pages

- frontend/src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.spec.ts
- frontend/src/app/features/dashboard/asc-wds-certificate/asc-wds-certificate.component.ts
- Fix a bug at `AscWdsCertificateComponent` about date comparison. Add unit tests around the issue
> Fix/1691 download ASC-WDS certificates page not using the correct year

- backend/server.js
- backend/server/aws/sns.js
- backend/server/models/classes/training.js
- backend/server/models/classes/worker.js
- backend/server/routes/accounts/user.js
- backend/server/routes/admin/recalcWdf/index.js
- backend/server/routes/admin/search/users/index.js
- backend/server/services/establishment/establishment.js
- backend/server/test/integration/routes/establishments/worker.spec.js
- backend/server/test/integration/utils/changeHistory.js
- backend/server/test/unit/models/Bulkimport/csv/workplaceCSVValidator.spec.js
- backend/server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js
- backend/server/test/unit/routes/establishments/childWorkplaces.spec.js
- backend/server/utils/timerLog.js
- Remove console logs from backend which are not needed/log out data 
> Remove console logs from backend which are not needed

- backend/migrations/20250725112009-addDHAWorkerColumns.js
- backend/migrations/20250725112107-addDHAColumnToJobRolesTable.js
- backend/migrations/20250725112125-updateWhichJobRolesCanDoDHA.js
- backend/server/models/classes/worker.js
- backend/server/models/classes/worker/properties/carryOutDelegatedHealthcareActivitiesProperty.js
- backend/server/models/classes/worker/properties/mainJobProperty.js
- backend/server/models/classes/worker/workerProperties.js
- backend/server/models/hooks/workerHooks.js
- backend/server/models/job.js
- backend/server/models/worker.js
- backend/server/test/unit/models/classes/worker/properties/carryOutDelegatedHealthcareActivitiesProperty.spec.js
- backend/server/test/unit/models/hooks/workerHooks.spec.js
- frontend/src/app/core/model/job.model.ts
- frontend/src/app/core/model/worker.model.ts
- frontend/src/app/core/test-utils/MockWorkerService.ts
- frontend/src/app/core/utils/worker-util.ts
- frontend/src/app/features/funding/funding-routing.module.ts
- frontend/src/app/features/workers/adult-social-care-started/adult-social-care-started.component.spec.ts
- frontend/src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts
- frontend/src/app/features/workers/carry-out-delegated-healthcare-activities/carry-out-delegated-healthcare-activities.component.html
- frontend/src/app/features/workers/carry-out-delegated-healthcare-activities/carry-out-delegated-healthcare-activities.component.spec.ts
- frontend/src/app/features/workers/carry-out-delegated-healthcare-activities/carry-out-delegated-healthcare-activities.component.ts
- frontend/src/app/features/workers/workers-routing.module.ts
- frontend/src/app/features/workers/workers.module.ts
- Add migrations for the new columns related to worker delegated healthcare activities question, and a new property to worker class
- Add a new worker question `CarryOutDelegatedHealthcareActivitiesComponent` to frontend. Also update the logic to determine next route in previous question `AdultSocialCareStartedComponent`
- Add a sequelize hook to worker model, which clears the answer of worker DHA question when a worker change to a job role that can't do DHA
> Feat/1756 DHA staff record flow question

- backend/migrations/20250620140922-insertNewAwardQualifications.js
- backend/reference/qualifications.js
- Add qualification level 5 in the qualifications table
- Add the level 5 qualification into the BU reference
> Add qualification level 5 in the qualifications table

- frontend/src/app/shared/components/staff-summary/staff-summary.component.html
- Changed staff name column to Name or ID number for staff records tab and funding staff records tab
> Feat: Change staff name column to Name or ID number
