.gitignore, CQCLocationAPICall/handler.js, package.json, server.js, server/config/config.json, server/data/locations.json, server/models/index.js, server/models/pcodedata.js, server/routes/locations.js, server/routes/postcodes.js
Moving Postcode API to Develop branch for Denny to access.
=> Merging Backendwork - Postcode API

server/routes/postcodes.js
Sanitises string and check it matches regex before searching now. Error handling to be implemented.
=> Update postcodes.js to sanitise and verify postcode string 

server/routes/services.js
Also removing the unnecessary console.log and the unnecessary async on createServicesJSON
=> 4 denny services

README.md, resources/api-namespace.json, resources/establishment_api.schema.json, resources/establishment_types.schema.json, server/models/index.js, server/routes/postcodes.js, server/routes/registration.js, server/utils/concatenateAddress.js, server/utils/postcodeSanitizer.js
This pull request includes:
1. Allow local override of database connections from environment variables - to allow working against a local database instance.
2. Correcting the fixed connection settings for registration DB client.
3. Bug fix: ordering postcode results
4. Bug fix: concatenating address fields (to remove null/undefined)
5. Bug fix: to handle short postcodes on lookup
6. Refactoring the registration queries to simplify structure by using async/await and exception handling, allowing the introduction of transaction handling to cope with failures
I have embedded (and commented out) explicit forced errors to test for the different combinations of reasons for failure  in the response sent back to the UI (Establishment, User and Login).  I have uncommented and proven each …
=> Erroneous registration data

server/routes/services.js
Hi Nasir
A quick (but speedy) review and deploy if you could. It's for Denny and the defects he's currently working on.
Thanks
=> Filtering services by category by cqc/not cqc registered

resources/establishment_api.schema.json, server.js, server/models/establishment.js, server/routes/establishments/employerType.js, server/routes/establishments/index.js, server/routes/tmpLogin.js, server/utils/security/isAuthenticated.js
As discussed on the phone Nasir, this is the employer type endpoint; derives from a common estasblishment route.
It is expected that Denny will make a start on the UI stories tomorrow. I'd like to have a couple of the APIs ready for him in Dev to play with.
Thanks.
=> Establishment api

server/models/api/shareData.js, server/models/establishment.js, server/routes/establishments/index.js, server/routes/establishments/shareData.js
This is a much simpler endpoint; just updating a set of boolean flags. The update logic allow for a simple toggle on/off and a reset of options.
=> Added share data API endpoint

server/routes/registration.js
Hi Nasir
This calms down some dreadful looking noise on the UI when it is continuously looking up against username in registration.
Please review, approve and merge (and delete branch when done).
=> Username lookup

resources/db/jobs.sql, resources/establishment_types.schema.json, server.js, server/models/api/jobs.js, server/models/establishment.js, server/models/establishmentJobs.js, server/models/establishmentLocalAuthority.js, server/models/job.js, server/models/localAuthority.js, server/routes/establishments/index.js, server/routes/establishments/jobs.js, server/routes/establishments/staff.js, server/routes/jobs.js
Hey Nasir
Hope you landed safely and you're already having fun.
This Pull Request (on to `develop` not `master` - I doubled checked) is a quadruple whammy:
* Staff (total number of)
* Vacancies
* Starters
* Leavers
The last three all essentially do the same thing (the UI is broken apart to make it easier for the user to comprehend). So I've combined them all into a single API endpoint.
Please merge these when you can. Our new guy Adam will be working on the frontend UIs for the above, and will create a branch from `develop` on Monday 24th Dec 2018..
Thanks
=> Staff, Vacancies, Starters and Leavers API endpoint

server.js, server/models/feedback.js, server/models/pcodedata.js, server/routes/establishments/la.js, server/routes/feedback.js
Hey Nasir
Hans is at work today, so I've used this morning to finish of my APIs. It also means I'm totally available to help you with the login but also pair up with Adam on the UIs.
This PR includes the new feedback API.
It also includes a minor update to "Local Authorities Share" to return the primary Authority which is then shown on the UI.
=> Feedback and minor update to "Local Authorities Share"

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/services/establishment.service.ts, src/app/features/confirm-leavers/confirm-leavers.component.html, src/app/features/confirm-leavers/confirm-leavers.component.spec.ts, src/app/features/confirm-leavers/confirm-leavers.component.ts, src/app/features/confirm-starters/confirm-starters.component.html, src/app/features/confirm-starters/confirm-starters.component.ts, src/app/features/leavers/leavers.component.html, src/app/features/leavers/leavers.component.scss, src/app/features/leavers/leavers.component.ts, src/app/features/staff/staff.component.html, src/app/features/staff/staff.component.spec.ts, src/app/features/staff/staff.component.ts
Merging latest from `leavers-confirm` to merged branch `establishment_ui`.
=> Leavers confirm

src/app/core/services/establishment.service.ts, src/app/features/staff/staff.component.html, src/app/features/staff/staff.component.scss, src/app/features/staff/staff.component.ts
Wanting to merge back down to keep the common branch in good shape.
=> Functional 'staff' component, although needs some further work on error messaging for validation

src/app/app.module.ts
=> fix conflicts after merge

.travis.yml, manifest.yml, server/config/config.json
Hi Warren, 
Kindly review; few UAT related changes needed in config files. 
Thanks
Nasir
=> uat related config changes

src/app/features/contactUs/contactUs.component.html, src/app/features/feedback/feedback.component.html, src/app/features/feedback/feedback.component.scss, src/app/features/feedback/feedback.component.ts, src/app/features/homepage/homepage.component.html, src/app/features/leavers/leavers.component.scss, src/app/features/registration-complete/registration-complete.component.html, src/app/features/shareOptions/shareOptions.component.html, src/app/features/starters/starters.component.scss, src/app/features/user-details/user-details.component.ts, src/app/features/vacancies/vacancies.component.scss
Mainly feedback form and validation, but also include telephone number validation (user details), a few typos on contact form, welcome page, share options et al.
Thanks
=> Ui feedback form

src/app/shared/terms-conditions/terms-conditions.component.html
And this is the quickest of all PRs, just some rewording for the infamous T&Cs.
=> Quick re-wording on the T&C text

src/app/features/homepage/homepage.component.html, src/app/features/registration-complete/registration-complete.component.html
=> Minor text fixes needed for deploy to test

src/app/core/messages/messages.component.scss, src/app/core/services/auth-service.ts, src/app/features/leavers/leavers.component.html, src/app/features/leavers/leavers.component.ts, src/app/features/login/login.component.html, src/app/features/login/login.component.ts, src/app/features/select-other-services/select-other-services-list/select-other-services-list.component.html, src/app/features/select-other-services/select-other-services.component.html, src/app/features/select-other-services/select-other-services.component.ts, src/app/features/starters/starters.component.html, src/app/features/starters/starters.component.ts, src/app/features/type-of-employer/type-of-employer.component.html, src/app/features/vacancies/vacancies.component.html, src/app/features/vacancies/vacancies.component.ts, src/assets/scss/forms.scss
https://trello.com/c/d5msXNix/336-log-in-issues
+ fixed some validator error displays in couple of screens vacancies, type-of-employer, starters, select-other-services, login, leavers
=> 336-log-in-issues: implemented + fixed some validator error displays

src/app/core/header/header.component.html
Fixed typo Ann mentioned -> https://skills-for-care.slack.com/archives/GF10X3Y9G/p1547558596037500.
=> logout_typo_fix: fixed wrong title on "Sign in" link.

resources/establishment_types.schema.json, server/models/classes/worker/properties/dateOfBirthProperty.js, server/models/classes/worker/properties/nationalInsuranceProperty.js, server/models/classes/worker/properties/postcodeProperty.js, server/models/classes/worker/workerProperties.js, server/models/worker.js
Three additional extended properties to Worker:
1. NI (National Insurance) Number
2. DOB (Date of Birth)
3. Postcode
=> Worker - NI Number, DOB and Postcode

.travis.yml, index_staging.html, index_uat.html, manifest.dev.yml
Hi Warren, 
Another for review and below is the summary
- Three GA tracking for dev, test and uat
- Initially i tried to put into custom js file as we discussed but there is script tag in the tracking code didnt trigger if i put this in external js file <script async src="https://www.googletagmanager.com/gtag/js?id=UA-132324399-1"></script>
- Denny also had a look but didnt find workable solution.
- Alternatively, There is custom js code where you can call the js file via js code rather via script tag above but that didnt work with our angular like this below
// var s = document.createElement('script');
// s.type = 'text/javascript';
// s.async = true;
// s.src = 'https://www.googletagmanager.com/gtag/js?id=UA-132324399-1';
// var x = document.getElementsByTagName('script')[0];
// …
=> 107-google analytics integration

server/models/classes/worker/properties/dateOfBirthProperty.js, server/models/worker.js
Hi Nasir
Apologies, but another PR to fix some annoying spelling mistakes I found while automating the integration tests.
=> Correcting spelling mistakes in date of birth

resources/establishment_types.schema.json, server/models/classes/worker/properties/disabilityProperty.js, server/models/classes/worker/properties/genderProperty.js, server/models/classes/worker/workerProperties.js, server/models/worker.js
Extended properies for gender and disability.
This observes the latest UI screen for gender which has descope the 'other' drop down.
=> Added gender and disablility extended properties

resources/establishment_types.schema.json, server.js, server/models/classes/worker.js, server/models/classes/worker/properties/ethnicityProperty.js, server/models/classes/worker/workerProperties.js, server/models/country.js, server/models/ethnicity.js, server/models/nationality.js, server/models/qualification.js, server/models/recruitedFrom.js, server/models/worker.js, server/routes/country.js, server/routes/ethnicity.js, server/routes/nationalities.js, server/routes/qualifications.js, server/routes/recruitedFrom.js, server/utils/middleware/refCache.js
This one PR includes five stories within the Worker Epic; all five stories requiring an additional reference lookup along with a property on the Worker:
1. Ethnicity - https://trello.com/c/8XIckTL9
2. Nationality - https://trello.com/c/eBXpK76c
3. Country of Birth - https://trello.com/c/W7XnNxhH
4. Recruited From - https://trello.com/c/a01Sa1vO
5. Highest Qualification - https://trello.com/c/ACAfFG8D
All five stories are being done under one branch `worker_reference` to aid efficiency in their implementation - as their approach is the same.
This PR includes five additional reference APIs (one for each above) in addition to the Ethnicity property on Worker.
All code has been documented in the API Usage document. All evidence has been collected and reported in Worker Test Evidence and on …
=> Worker Epic - Ethnicity, Nationality, Country of Birth, recruited from and qualification API backend

src/app/features/homepage/homepage.component.html, src/app/features/homepage/homepage.component.ts, src/assets/scss/buttons.scss
https://trello.com/c/9G7MRtXR/285-create-a-button-on-welcome-page-to-add-a-worker
=> 285-create-a-button-on-welcome-page-to-add-a-worker-front: done

server/models/classes/worker/properties/countryProperty.js, server/models/classes/worker/properties/dateOfBirthProperty.js, server/models/classes/worker/properties/ethnicityProperty.js, server/models/classes/worker/properties/nationalityProperty.js, server/models/classes/worker/properties/qualificationProperty.js, server/models/classes/worker/properties/recruitedFromProperty.js, server/models/classes/worker/workerProperties.js
Introduces Nationality property to Worker.
Introduces Country of Birth property to Worker.
Introduces Recruited From property to Worker.
Introduces Qualifications (highest) property to Worker.
Includes some corrections to copy 'n' paste trivia with Ethnicity, observed whilst refining Nationalities and Country of Birth.
=> Worker Nationality, Country Of Birth, Recruited From and Qualification (highest) properties (and DOB cross check validation update)

server/models/classes/properties/changePrototype.js, server/models/classes/worker/properties/annualHourlyPayProperty.js, server/models/classes/worker/properties/daysSickProperty.js, server/models/classes/worker/properties/weeklyHoursAverageProperty.js, server/models/classes/worker/properties/weeklyHoursContractedProperty.js
1. For handling when a property has changed if it has never been set, and for saving property values only when the property has changed.
2. Correcting the JSON response on Days Sick.
3. Correcting the JSON reponse and incorrect isEqual logic on Weekly Average & Contracted Hours.
=> Wortker Property Corrections following updated automated integration test

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/ethnicity.model.ts, src/app/core/model/worker.model.ts, src/app/core/services/ethnicity.service.ts, src/app/core/services/worker.service.ts, src/app/features/workers/ethnicity/ethnicity.component.html, src/app/features/workers/ethnicity/ethnicity.component.ts, src/app/features/workers/nationality/nationality.component.html, src/app/features/workers/nationality/nationality.component.spec.ts, src/app/features/workers/nationality/nationality.component.ts, src/assets/scss/forms.scss
=> 63 ethnicity front

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/ethnicity.model.ts, src/app/core/model/worker.model.ts, src/app/core/services/ethnicity.service.ts, src/app/core/services/recruitment.service.ts, src/app/core/services/worker.service.ts, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.html, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.spec.ts, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/ethnicity/ethnicity.component.html, src/app/features/workers/ethnicity/ethnicity.component.ts, src/app/features/workers/nationality/nationality.component.html, src/app/features/workers/nationality/nationality.component.spec.ts, src/app/features/workers/nationality/nationality.component.ts, src/app/features/workers/recruited-from/recruited-from.component.html, src/app/features/workers/recruited-from/recruited-from.component.spec.ts, src/app/features/workers/recruited-from/recruited-from.component.ts, src/assets/scss/forms.scss, src/assets/scss/type.scss
=> 68 recruited from front

src/app/features/workers/date-of-birth/date-of-birth.component.ts
Date of birth between now-100 and now-14 all inclusive.
=> Date of Birth - validation change

src/app/core/messages/messages.component.html, src/app/core/messages/messages.component.ts, src/app/core/services/message.service.ts
Message Service supports storing only one message of every type at a time. We need it to handle multiple messages of the same type.
=> message-service: support for multiple messages of the same type at once.

src/app/core/messages/messages.component.html, src/app/core/messages/messages.component.ts, src/app/core/services/message.service.ts, src/app/features/workers/create-staff-record/create-staff-record.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.ts
https://trello.com/c/dmKEApAr after UAT.
=> Create Staff Record: Fixed validation and error display

src/app/core/messages/messages.component.html, src/app/core/messages/messages.component.ts, src/app/core/services/message.service.ts, src/app/features/workers/other-job-roles/other-job-roles.component.html, src/app/features/workers/other-job-roles/other-job-roles.component.ts
=> Other job role front

src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/core/services/country.service.ts, src/app/features/workers/country-of-birth/country-of-birth.component.html, src/app/features/workers/country-of-birth/country-of-birth.component.ts
=> Country of birth front

src/app/app.component.ts, src/app/core/services/auth-service.ts
Below I have fixed the issue regarding local storage but also added the same functionality to clear local storage on logout.
=> Bugfix 216 reset localstorage

src/app/core/model/worker.model.ts, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.html, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.ts
=> Year Arrived UK frontend

manifest.dev.yml, manifest.test.yml, manifest.yml
I have cheery pick this commit from Develop branch which is basically specify nodejs version due to build failure
=> Merge From 1.3 to Test specify nodejs buildpack in manifest file

src/app/features/enter-workplace-address/enter-workplace-address.component.html
=> Update enter-workplace-address validation

package.json, server/routes/feedback.js, server/routes/registration.js, server/utils/slack/slack-logger.js
Hi Nasir
This is against Trello card (https://trello.com/c/PTIz2Ghs), which during stand up this morning (Friday 7th Feb), Pete agreed the work needed to be prioritised.
He wants to demo this on Monday to Jackie while he's in Leeds.
Hence this PR to `develop`. I shall also raise a separate PR against test, because Pete is looking to get it into UAT as soon as. The low impact of the changes makes it possible to merge straight into test.
But note - you'll need two environment variables to each environment. I've sent you an updated set of release notes. I can walk you through.
Thanks
=> Slack to develop

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/services/worker-guard.service.ts, src/app/core/services/worker.service.ts, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/british-citizenship/british-citizenship.component.ts, src/app/features/workers/country-of-birth/country-of-birth.component.ts, src/app/features/workers/create-staff-record/create-staff-record.component.ts, src/app/features/workers/date-of-birth/date-of-birth.component.ts, src/app/features/workers/days-of-sickness/days-of-sickness.component.ts, src/app/features/workers/disability/disability.component.ts, src/app/features/workers/edit-worker/edit-worker.component.html, src/app/features/workers/edit-worker/edit-worker.component.ts, src/app/features/workers/ethnicity/ethnicity.component.ts, src/app/features/workers/gender/gender.component.ts, src/app/features/workers/home-postcode/home-postcode.component.ts, src/app/features/workers/main-job-start-date/main-job-start-date.component.ts, src/app/features/workers/mental-health/mental-health.component.ts, src/app/features/workers/national-insurance-number/national-insurance-number.component.ts, src/app/features/workers/nationality/nationality.component.ts, src/app/features/workers/other-job-roles/other-job-roles.component.ts, src/app/features/workers/recruited-from/recruited-from.component.ts, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.ts
Some of these files are going to have big changes because I've tidied up the imports, fixed TS linting errors and moved the OnInit and OnDestroy methods to the top of the class.
The main change is that the workerId is set and stored in the service once a worker has been created. The Editing pages are then wrapped by another Component which unsets the workerId when it's destroyed.
=> 204 Remover Worker UID from URL

src/app/app.component.ts
Added an subscription to the Router events which will return the page position to the top on successful NavigationEnd event
=> 183: Scroll to top on navigate

server/routes/registration.js
Hi Nasir
Following the merge to develop yesterday of the refactored registration, the slack notification code went a little amiss.
I've corrected it on this branch and I've tested locally. Any chance of a speedy PR review and approve.
No need to merge. I'll do all that and test the deployment at the same time.
=> Slack merge error

package.json, server/routes/feedback.js, server/routes/registration.js, server/utils/slack/slack-logger.js
Hi Nasir
This PR is in anticipation of Jackie accepting the Slack notifications as deployed into dev for immediate deployment to staging then UAT.
Do not review and approve until we have authorisation from Pete and Ann.
=> introducing slack notifications direct to test/UAT, and adding slack notify to registrations and feedback

src/app/features/workers/adult-social-care-started/adult-social-care-started.component.html, src/app/features/workers/british-citizenship/british-citizenship.component.html, src/app/features/workers/date-of-birth/date-of-birth.component.html, src/app/features/workers/days-of-sickness/days-of-sickness.component.html, src/app/features/workers/disability/disability.component.html, src/app/features/workers/ethnicity/ethnicity.component.html, src/app/features/workers/gender/gender.component.html, src/app/features/workers/home-postcode/home-postcode.component.html, src/app/features/workers/national-insurance-number/national-insurance-number.component.html, src/app/features/workers/nationality/nationality.component.html, src/app/features/workers/other-job-roles/other-job-roles.component.html, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.html
Missed the workerId being used in the template files for the Back button.
=> 204: Removing workerId from Back button URL

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/average-weekly-hours/average-weekly-hours.component.html, src/app/features/workers/average-weekly-hours/average-weekly-hours.component.spec.ts, src/app/features/workers/average-weekly-hours/average-weekly-hours.component.ts
Adding the Average Weekly Hours Card.
@wozzer72 There's API calls on line 34 and 75 of `src/app/features/workers/average-weekly-hours/average-weekly-hours.component.ts`.
=> 261: Average Weekly Hours Card

CQCLocationAPICall/handler.js, CQCLocationAPICall/local.js, CQCLocationAPICall/models/location.js
Hi Nasir
This is a small change to the lambda function that fetches the locations. I've reintroduced the `populateAllLocations` function previously commented out and I've introduced predicate logic in to the main handler function to choose which of `REFRESH` or `BULK_UPLOAD` to perform.
I've added a condition to `getIndividualLocations` function which checks the presence of `deregistrationDate` and if not present (not archived) copies the location data.
The `location` table structure has changed since this lambda function was first written; so I've had to update the sequelize model.
And the `local.js` I've introduced to run the handler locally; no need to deploy the lambda and run in the cloud.
=> Non archived locations

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/average-contracted-hours/average-contracted-hours.component.html, src/app/features/workers/average-contracted-hours/average-contracted-hours.component.spec.ts, src/app/features/workers/average-contracted-hours/average-contracted-hours.component.ts
Adding the Average Contracted Hours Card.
@wozzer72 There's API calls on line 34 and 75 of `src/app/features/workers/average-contracted-hours/average-contracted-hours.component.ts`.
=> 262: Average Contracted Hours Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/blank-card.component.ts, src/app/features/workers/salary/salary.component.html, src/app/features/workers/salary/salary.component.spec.ts, src/app/features/workers/salary/salary.component.ts
Adding Salary Card, asking the question "Are they paid hourly or annually?"
Validation has only been implemented to a basic functionality.
@wozzer72 you can see the API PUT call in the `saveHandler()` method.
=> 263: Salary Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/care-certificate/care-certificate.component.html, src/app/features/workers/care-certificate/care-certificate.component.spec.ts, src/app/features/workers/care-certificate/care-certificate.component.ts
@wozzer72 same here, API calls made on lines 34 and 70 in `src/app/features/workers/care-certificate/care-certificate.component.ts`
=> 269: Care Certificate Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/apprenticeship-training/apprenticeship-training.component.html, src/app/features/workers/apprenticeship-training/apprenticeship-training.component.spec.ts, src/app/features/workers/apprenticeship-training/apprenticeship-training.component.ts
@wozzer72 Lines 34 and 70 in src/app/features/workers/apprenticeship-training/apprenticeship-training.component.ts
=> 264: Apprenticeship Training Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/social-care-qualification/social-care-qualification.component.html, src/app/features/workers/social-care-qualification/social-care-qualification.component.spec.ts, src/app/features/workers/social-care-qualification/social-care-qualification.component.ts
@wozzer72 Lines 34 and 74 on `src/app/features/workers/social-care-qualification/social-care-qualification.component.ts`
=> 265: Social Care Qualification Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/other-qualifications/other-qualifications.component.html, src/app/features/workers/other-qualifications/other-qualifications.component.spec.ts, src/app/features/workers/other-qualifications/other-qualifications.component.ts
@wozzer72 34 and 84 in `src/app/features/workers/other-qualifications/other-qualifications.component.ts`
=> 267: Adding Other Qualifications Card

.prettierrc.yml, src/app/core/header/header.component.ts, src/app/core/services/auth-service.ts, src/app/core/services/establishment.service.ts, src/app/features/shareOptions/shareOptions.component.ts
Fix for issue where establishment ID was not getting cleared on sign out and page reload... also on sign out was bugging on welcome page and not routing to /login.
Also added prettier config code to route.
=> Fix localstorage clear issue

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/qualification.model.ts, src/app/core/model/worker.model.ts, src/app/core/services/qualification.service.ts, src/app/features/workers/other-qualifications/other-qualifications.component.html, src/app/features/workers/other-qualifications/other-qualifications.component.ts, src/app/features/workers/salary/salary.component.ts, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.html, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.spec.ts, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.ts, src/app/features/workers/social-care-qualification/social-care-qualification.component.ts
Adding Qualification Service.
@wozzer72 API calls on lines 37, 43 and 81 in `src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.ts`
=> 266: Social Care Qualification Level Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.spec.ts, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.ts, src/app/features/workers/other-qualifications/other-qualifications.component.ts, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.html, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.ts
@wozzer72 lines 37, 43 and 83 in `src/app/features/workers/other-qualifications-level/other-qualifications-level.component.ts`
=> 268: Other Qualifications Level Card

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/features/homepage/homepage.component.ts, src/app/features/workers/create-staff-record-start-screen/create-staff-record-start-screen.component.html, src/app/features/workers/create-staff-record-start-screen/create-staff-record-start-screen.component.spec.ts, src/app/features/workers/create-staff-record-start-screen/create-staff-record-start-screen.component.ts, src/assets/scss/type.scss
Adding the Staff Record start screen.
Updated the link on the welcome screen to point to start screen.
Adding styling for bulleted links.
=> 169: Staff Record Start Screen

.travis.yml
Hello, very think PR for change of slack notification to sfc channel.
trello card here https://trello.com/c/7yv1W5cT
thanks
=> changing slack notification to SFC channel

server/models/location.js, server/models/pcodedata.js, server/routes/establishments/la.js, server/routes/la.js, server/routes/registration.js
HI Nasir
A slightly bigger change than had we done it last week. I introduced three embedded queries to accommodate a complex join across multiple tables which was a bugger to represent in sequelize associations.
Can you review and approve. I'll merge.
=> Accommodating chaneg of schema name for pcodedata and location only

src/app/core/guards/worker/worker-guard.service.ts, src/app/core/services/worker-guard.service.ts, src/app/features/homepage/homepage.component.html, src/app/features/workers/workers-routing.module.ts
- Removing Worker Subscription from Worker Guard
- Moving the Worker Guard to the `core/guards` folder
- Renaming the service by removing the prefixed underscore to follow Angular Style Guide rules https://angular.io/guide/styleguide#style-03-04
=> Fixing Worker Guard

src/app/features/homepage/homepage.component.ts, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/apprenticeship-training/apprenticeship-training.component.ts, src/app/features/workers/average-weekly-hours/average-weekly-hours.component.ts, src/app/features/workers/british-citizenship/british-citizenship.component.ts, src/app/features/workers/care-certificate/care-certificate.component.ts, src/app/features/workers/contract-with-zero-hours/contract-with-zero-hours.component.ts, src/app/features/workers/country-of-birth/country-of-birth.component.ts, src/app/features/workers/create-staff-record/create-staff-record.component.ts, src/app/features/workers/date-of-birth/date-of-birth.component.ts, src/app/features/workers/days-of-sickness/days-of-sickness.component.ts, src/app/features/workers/disability/disability.component.ts, src/app/features/workers/edit-worker/edit-worker.component.ts, src/app/features/workers/ethnicity/ethnicity.component.ts, src/app/features/workers/gender/gender.component.ts, src/app/features/workers/home-postcode/home-postcode.component.ts, src/app/features/workers/main-job-start-date/main-job-start-date.component.ts, src/app/features/workers/mental-health/mental-health.component.ts, src/app/features/workers/national-insurance-number/national-insurance-number.component.ts, src/app/features/workers/nationality/nationality.component.ts, src/app/features/workers/other-job-roles/other-job-roles.component.ts, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.ts, src/app/features/workers/other-qualifications/other-qualifications.component.ts, src/app/features/workers/recruited-from/recruited-from.component.ts, src/app/features/workers/salary/salary.component.ts, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.ts, src/app/features/workers/social-care-qualification/social-care-qualification.component.ts, src/app/features/workers/weekly-contracted-hours/weekly-contracted-hours.component.ts, src/app/features/workers/worker-summary/worker-summary.component.ts, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.ts
- Updated the imports to use the `@core` path alias
- Added binding to saveHandler method
- Fixed Edit Workers button on Homepage to set the Worker ID in the service
=> 336: Fixing Save and Exit callback on Workers Questions

src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/contract-with-zero-hours/contract-with-zero-hours.component.html, src/app/features/workers/contract-with-zero-hours/contract-with-zero-hours.component.ts
Reverting 146
Related Comment https://trello.com/c/84drk6zs/7-days-sickness-in-last-12-months-152#comment-5c6d6b1bfe11428a677f963d
=> Revert 146

src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/days-of-sickness/days-of-sickness.component.ts, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.ts
- Updating copy for year error message on Adult Social Care Started and Year Arrived UK Questions.
- Removing redundant year error message on Days of Sickness
=> 142: Year Error message

src/app/features/workers/main-job-start-date/main-job-start-date.component.ts
=> 340: Fixing duplicate Worker creation

server/routes/accounts/user.js, server/routes/login.js
Hi Nasir
Although the associated trello card for this work is not yet in scope (https://trello.com/c/57qCi7Dv), I've included the necessary changes to handle failed logins, in addition to adding the necessary auditing events.
This extends upon the password reset (which resets the InvalidAttempt counter).
It's much more efficient if I simply tag these changes on here, rather than having to come back later and revisit them.
=> Password failed lock

src/app/features/workers/create-staff-record/create-staff-record.component.ts, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.ts, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.ts, src/app/features/workers/worker-summary/worker-summary.component.html, src/app/features/workers/worker-summary/worker-summary.component.scss, src/app/features/workers/worker-summary/worker-summary.component.ts
Cleaning up the CSS and data displayed on the Workers Summary
=> Workers Summary Cleanup

src/app/features/workers/worker-save-success/worker-save-success.component.html, src/app/features/workers/worker-save-success/worker-save-success.component.scss, src/app/features/workers/worker-save-success/worker-save-success.component.ts, src/app/features/workers/worker-summary/worker-summary.component.html, src/app/features/workers/worker-summary/worker-summary.component.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workers/workers.module.ts, src/app/shared/components/panel/panel.component.html, src/app/shared/components/panel/panel.component.scss, src/app/shared/components/panel/panel.component.spec.ts, src/app/shared/components/panel/panel.component.ts, src/app/shared/shared.module.ts
Also added a shared Panel Component
=> 54: Worker Save Success

package.json, server/sendEmail.js
A placeholder PR. DO NOT ACTION ANYONE.
=> Aws ses test - command line demo

package.json, src/app/features/dashboard/dashboard.component.html, src/app/features/workers/worker-save-success/worker-save-success.component.html, src/app/features/workers/worker-save-success/worker-save-success.component.ts, src/app/features/workers/worker.resolver.ts, src/app/shared/components/tabs/tab.component.ts, src/app/shared/components/tabs/tabs.component.ts
This will make sure that tabs can be navigated to via the URL using the # fragment.
=> Bugfix: Updating tabs to have default active state from URL

src/app/app.module.ts, src/app/core/model/worker.model.ts, src/app/core/services/worker.service.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.spec.ts, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.ts, src/app/features/workers/create-staff-record/create-staff-record.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.scss, src/app/features/workers/create-staff-record/create-staff-record.component.ts, src/app/shared/components/error-summary/error-summary.component.html, src/app/shared/components/error-summary/error-summary.component.scss, src/app/shared/components/error-summary/error-summary.component.spec.ts, src/app/shared/components/error-summary/error-summary.component.ts, src/app/shared/components/error-summary/error.component.ts, src/app/shared/components/status/status.component.html, src/app/shared/components/status/status.component.scss, src/app/shared/components/status/status.component.spec.ts, src/app/shared/components/status/status.component.ts, src/app/shared/shared.module.ts, src/assets/scss/buttons.scss, src/assets/scss/forms.scss, src/assets/scss/variables.scss
Users can now create skeleton records.
Added a Status Component similar to https://home-office-digital-patterns.herokuapp.com/components/status
Added Error Summary Component https://design-system.service.gov.uk/components/error-summary/
Added blue button style
=> 151: Staff Skeleton Records

src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/contract-with-zero-hours/contract-with-zero-hours.component.html, src/app/features/workers/contract-with-zero-hours/contract-with-zero-hours.component.ts, src/app/features/workers/create-staff-record/create-staff-record.component.ts, src/app/features/workers/days-of-sickness/days-of-sickness.component.ts
This has been brought back in by duplicate tickets 216 and 232.
=> Days of Sickness can only be answered if Contract Type is Permanent or Temporary

resources/establishment_types.schema.json, server/models/establishment.js, server/routes/establishments/employerType.js, src/app/features/type-of-employer/type-of-employer.component.ts
trello card: https://trello.com/c/MtKBV9EP
Both backend and frontend changes here; frontend because it is little more than updating an array of options.
Trello card includes screenshot of new frontend UI, and Insomnia manual tests, and confirmation of successful Establishment integration tests, after being updated to assert on the new additional Local Authority entities.
Thanks
=> Two additional entities to the employer type; both backend and frontend changes.

src/app/core/model/worker.model.ts, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.ts, src/app/features/workers/worker-summary/worker-summary.component.ts
Save and Complete on Summary screen now updates the `completed` property for a Worker.
This then effects the display of links on the Staff Records Tab on the Dashboard, and the display of total number of incomplete workers.
=> 333: Workers Completed Property

server/models/classes/worker/properties/countryProperty.js, server/models/classes/worker/properties/nationalityProperty.js
Hi Nasir
On Ann's priority list of Cohort 2 defects, two of the defects include backend:
* https://trello.com/c/CqgkWzya - Nationality "other" is optional
* https://trello.com/c/UqLUIYhD - Country of Birth "other" is optional
Before they can be fixed in the frontend, the backend must be fixed.
As properties, these are localised, and as equivalent properties, they are also the "same" changes.
Note - no database changes required because the database already supports nullable "other".
=> Optional nationality country of birth

src/app/features/workers/days-of-sickness/days-of-sickness.component.ts, src/app/features/workers/worker-summary/worker-summary.component.html
I have also updated the other ternary operator statements to check if the value is not `null` to avoid this on other question answers.
=> 339: Properly Displaying 0 Days Sickness in Question and Summary Page

src/app/features/workers/create-staff-record/create-staff-record.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.ts
343: Fixing issue where it was not calculating amount of staff records added
343: Adding Validation for staff records to be required
=> 343: Create Skeleton Records Validation errors

src/app/features/reset-password/edit/edit.component.html, src/app/features/reset-password/edit/edit.component.ts
Fixed - replacing reset password button text
Fixed - adding '.body' back into reference link.
=> Bugfix issues with reset button and username

server/models/classes/worker.js, server/models/worker.js, server/routes/establishments/worker.js
Hi Nasir
Having spent weeks adding and updating Workers, they now want to be able to delete a Worker. https://trello.com/c/ZPK4AF4o
The changes are relatively simple. Not actually deleting; just archiving with audit.
Grateful if you could review and approve for Monday, so Charlie can then look to complete on the Worker epic.
Complementary DB PR sent to Shakir: https://github.com/NMDSdevopsServiceAdm/NMDSDB-SFC/pull/35
=> Implementing delete (archive) worker.

server/routes/login.js, server/routes/registration.js
https://trello.com/c/CSGha5w5
manual tests using various complex passwords on registration, password reset and change password each followed by successful login.
=> Special Characters in Password

src/app/features/dashboard/dashboard.component.html, src/app/shared/components/inset-text/inset-text.component.html, src/app/shared/components/inset-text/inset-text.component.scss, src/app/shared/components/inset-text/inset-text.component.spec.ts, src/app/shared/components/inset-text/inset-text.component.ts, src/app/shared/shared.module.ts, src/assets/scss/variables.scss
Added Inset Text Component
Updated Home Tab on Dashboard
=> 183: Dashboard Home Tab

src/app/features/workers/days-of-sickness/days-of-sickness.component.html
The Validation for min - max is already in place on the Component
=> Removing Directives from Days of Sickness Input

server.js, server/models/classes/worker.js, server/models/worker.js, server/models/workerReasons.js, server/routes/establishments/worker.js, server/routes/workerReason.js
Hi Nasir
https://trello.com/c/6bctXaoy
A simple PR review, which will help Charlie deliver some critical changes to the Worker Delete screens (and Worker is a necessary for UAT deployment next week.
Thanks
=> Api delete staff reason

server/models/classes/worker.js, server/routes/establishments/worker.js
Hi Nasir
This is a quick review and approval required to restore POST worker following yesterday's deployment of Delete Worker Reason.
=> Delete reason failure

src/app/core/services/auth-guard.service.ts, src/app/core/services/auth-interceptor.ts, src/app/core/services/auth-service.ts, src/app/core/services/country.service.ts, src/app/core/services/establishment.service.ts, src/app/core/services/ethnicity.service.ts, src/app/core/services/feedback.service.ts, src/app/core/services/http-error-handler.service.ts, src/app/core/services/job.service.ts, src/app/core/services/localAuthority.service.ts, src/app/core/services/location.service.ts, src/app/core/services/message.service.ts, src/app/core/services/nationality.service.ts, src/app/core/services/password-reset.service.ts, src/app/core/services/qualification.service.ts, src/app/core/services/recruitment.service.ts, src/app/core/services/registration.service.ts
This PR includes only style changes (and the removal of 1 commented piece of code) that is produced via running Prettier `prettier --config .prettierrc.yml --write "./src/app/core/services/*.ts"` and then saving the files after running TypeScript Hero to remove unused imports
=> Running Prettier on Core Services

.travis.yml, manifest.bluegreen.yml
Hello Warren, 
I have made following changes as per trello ticket https://trello.com/c/K7GMK0K4
- I have removed the auto deployment from Master branch as I do it manually.
- I have renamed manifest file to different name ( i done this as safety so any manual deployment without manifest file wont work and force you to specify file.
ofcourse, later to handle this better via travis.
thanks
Nasir
=> remove auto deployment from master branch to UAT

src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.html, src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.ts, src/app/features/workers/worker-summary/worker-summary.component.scss
This also ups the max length of the user input for Other Reason to 500
=> Delete Worker Popup IE Layout issue

src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.html
Updating Adult Social Care Question back links
Fixing issue with max length on provide more details on Delete Worker
=> Adult Social Care Link and Max Length Other Reasons

server/models/classes/worker.js
A quick turnaround a we can get this into dev and deploy to test ready for UAT.
=> Adding Validation on "reason.other" length

src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.ts
Also fixing a bug where `workers` wasn't set so erroring when trying to access the `.length`
=> Display Total Staff helper copy

src/app/app.module.ts, src/app/core/services/auth-service.ts, src/app/core/services/country.service.ts, src/app/core/services/establishment.service.ts, src/app/core/services/ethnicity.service.ts, src/app/core/services/feedback.service.ts, src/app/core/services/http-interceptor.ts, src/app/core/services/job.service.ts, src/app/core/services/localAuthority.service.ts, src/app/core/services/location.service.ts, src/app/core/services/nationality.service.ts, src/app/core/services/password-reset.service.ts, src/app/core/services/qualification.service.ts, src/app/core/services/recruitment.service.ts, src/app/core/services/registration.service.ts, src/app/core/services/worker.service.ts
This PR is being created to make the work on https://trello.com/c/THXBYGRj easier to complete
Cleaning up the services to
* remove unneeded comments
* remove http error handling to single interceptor
* remove debounceTime to single interceptor
* remove setting application/json header to single interceptor
=> Moving HTTP Error Handling to a single interceptor

src/app/core/services/password-reset.service.ts, src/app/core/services/user.service.ts
Removing HttpErrorHandler from Services
Removing debouceTime from Services
These are now handled in the HttpInterceptor
=> Fixing Merge Issues

server.js, server/models/serviceUsers.js, server/routes/establishments/index.js, server/routes/establishments/serviceUsers.js, server/routes/serviceUsers.js
Hi Denny
https://trello.com/c/6j4x0gui
To allow you to start on the service users component, I have created the serviceUser reference API endpoint and stubbed the two Establishment GET/POST endpoints.
This builds on the establishment audit changes which I hope we get to deploy in to dev today (all depending on the UAT deployment this morning).
Thanks
=> Adding ServiceUsers reference API and stubs for the Establishment "serviceUsers" GET/POST endpoints.

src/app/features/change-user-details/change-user-details.component.html, src/app/features/change-user-security/change-user-security.component.html, src/app/features/change-user-summary/change-user-summary.component.html
Just updated text on summary screen and the buttons.
=> Update the content

src/app/app.module.ts, src/app/core/header/header.component.html, src/app/core/header/header.component.ts, src/app/core/services/auth-service.ts, src/app/features/contactUs/contactUs.component.html, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.scss, src/app/features/dashboard/home-tab/home-tab.component.spec.ts, src/app/features/dashboard/home-tab/home-tab.component.ts, src/assets/scss/main.scss, src/assets/scss/partials/header.scss, src/assets/scss/type.scss, src/assets/scss/variables.scss
Changed contact phone number on Contact Page
Changed email on Dashboard
Made the Service name a link to the Dashboard
Updated the Home Tab to include links and notifications
Next Step alerts now display on a conditional
Added NMDS ID and Last Signed In Date to Dashboard
Truncating fullname to first name
=> Dashboard Home Tab

src/app/core/services/registration.service.ts, src/app/features/cqc-registered-question/cqc-registered-question-edit/cqc-registered-question-edit.component.ts, src/app/features/create-username/create-username.component.ts, src/app/features/select-workplace-address/select-workplace-address.component.ts, src/app/features/select-workplace/select-workplace.component.ts
Fixing issues with error handling on registration.
=> Update to fix issues with registration error handling

src/app/core/header/header.component.html, src/app/core/header/header.component.ts
Fixing display of users first name in the header
Fixing typo on the log out link
Removing title attributes from links
=> Header bugs

src/app/core/services/auth-service.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/dashboard/home-tab/home-tab.component.ts
Fixing display of last logged in time
Fixing alert for staff records
=> Dashboard bugs

angular.json, package.json, src/app/features/reset-password/edit/edit.component.html
bring edit component to GDS standards and remove unused popper.js package
=> gds assessment | 411 | reset account page

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/header/header.component.ts, src/app/core/services/auth-service.ts, src/app/core/services/http-error-handler.service.ts, src/app/core/services/idle.service.ts, src/app/features/login/login.component.ts, src/app/features/logout/logout.component.html, src/app/features/logout/logout.component.ts
Adding an Idle Service that will log the user out after `x` amount of seconds in inactivity
The service also ping's every `x` amount of seconds which can be used to refresh tokens.
=> Session Timeout

server/config/config.js, server/routes/login.js, server/utils/security/generateJWT.js, server/utils/security/isAuthenticated.js, src/app/app-routing.module.ts, src/app/core/header/header.component.ts, src/app/core/services/auth-service.ts, src/app/core/services/http-error-handler.service.ts, src/app/core/services/idle.service.ts, src/app/features/login/login.component.ts, src/app/features/logout/logout.component.html, src/app/features/logout/logout.component.ts
Note - this is just the API hotfix. You'll need a hotfix from Charlie too.
=> Hotfix for API token expiry - for UAT direct deployment

server/routes/login.js
=> Hotfix toekn expiry - hard coding jwt.ttl.login to 5 minutes

server/utils/security/generateJWT.js, server/utils/security/isAuthenticated.js
`generateJWT` and `isAuthenticated` were the other two files that I had copied in entirety.
Cherry picked out the non-hotfix code.
=> Cherry picking out the changes taken from develop branch, not relevant to this hotfix.

server/routes/login.js, server/routes/postcodes.js, server/routes/services.js
Hi Nasir
https://trello.com/c/PLIP2Ddv
Following on from the hotfix deployment yesterday whereby it was witness sequelize errors being returned from backend on login owing to schema mismatch between code and DB, Charlie raised the defect and I've fixed it here.
I've taken the opportunity to review all existing endpoints for good error handling from sequelize (meaning I've had to add exception handling blocks) and to return basic 503 responses without disclosure of the error.
=> Login sequelize error - and other endpoints

server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/reports/wdf/index.js
And per property values are now string (were boolean) with one of:
* Yes
* No
* Not relevant
The "Not relevant" state is owing to some of the properties (only one in Establishment but many in Worker) have predicate values.
=> Wdf reports - calculated values rather than mocked values for the WDF reports

package.json, src/app/app.module.ts, src/app/core/components/header/header.component.html, src/app/core/model/errorSummary.model.ts, src/app/core/services/error-summary.service.ts, src/app/features/forgot-your-password/confirmation/confirmation.component.html, src/app/features/forgot-your-password/edit/edit.component.html, src/app/features/forgot-your-password/edit/edit.component.ts, src/app/features/forgot-your-password/forgot-your-password.component.html, src/app/features/login/login.component.html, src/app/features/login/login.component.ts, src/app/features/logout/logout.component.html, src/app/features/reset-password/confirmation/confirmation.component.html, src/app/features/reset-password/edit/edit.component.html, src/app/features/reset-password/edit/edit.component.ts, src/app/features/reset-password/reset-password.component.html, src/app/shared/components/error-summary/error-summary.component.html, src/app/shared/components/error-summary/error-summary.component.ts, src/app/shared/validators/custom-form-validators.ts
- bring error-summary component in sync with GDS framework
- ensure reset-password screen is in sync with GDS framework
=> Feature | gds assessment | 416 | update app-error-summary component

server/routes/reports/dailySnapshot/index.js, server/routes/reports/index.js
https://trello.com/c/G0VFyXYn
The is a dedicated endpoint to simply call upon a new View and return all data. This endpoint is protected by specific JWT `aud`.
I've introduced this endpoint in a way that makes it easy to create a hotfix for UAT.
=> Daily snapshot report api

src/app/core/model/userDetails.model.ts, src/app/core/services/error-summary.service.ts, src/app/core/services/user.service.ts, src/app/features/change-password/change-password.component.html, src/app/features/change-password/change-password.component.spec.ts, src/app/features/change-password/change-password.component.ts, src/app/features/change-password/confirmation/confirmation.component.html, src/app/features/change-password/confirmation/confirmation.component.spec.ts, src/app/features/change-password/confirmation/confirmation.component.ts, src/app/features/change-password/edit/edit.component.html, src/app/features/change-password/edit/edit.component.spec.ts, src/app/features/change-password/edit/edit.component.ts, src/app/features/reset-password/confirmation/confirmation.component.html, src/app/features/reset-password/edit/edit.component.html, src/app/features/reset-password/edit/edit.component.ts, src/app/features/your-account/your-account.component.ts, src/app/shared/components/error-summary/error-summary.component.html, src/app/shared/components/error-summary/error-summary.component.ts
make change password screen GDS compliant
=> Feature | gds assessment | 445 | change password screen

src/app/core/model/qualification.model.ts, src/app/core/services/http-error-handler.service.ts, src/app/core/services/worker.service.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.spec.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.html, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.html, src/app/features/workers/add-edit-training/add-edit-training.component.ts, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.html, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.spec.ts, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.ts, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.ts, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.ts, src/app/features/workers/staff-record/qualifications/qualifications.component.html, src/app/features/workers/staff-record/qualifications/qualifications.component.spec.ts, src/app/features/workers/staff-record/qualifications/qualifications.component.ts, src/app/features/workers/staff-record/staff-record.component.html, src/app/features/workers/staff-record/staff-record.component.ts, src/app/features/workers/staff-record/training/training.component.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workers/workers.module.ts, src/assets/img/icon-information.svg, src/assets/scss/forms.scss
Add / View / Edit / Delete Qualifications
I also updated the HTTP Error Handler to throw an error on Unauthorised as it was chucking out a load of console logs.
=> Qualifications

src/app/features/change-user-details/change-user-details.component.html, src/app/features/change-user-details/change-user-details.component.ts, src/app/features/forgot-your-password/edit/edit.component.html, src/app/features/forgot-your-password/edit/edit.component.ts, src/app/features/login/login.component.html, src/app/features/login/login.component.ts
make change user details page GDS compliant
=> Feature | gds assessment | 451 | change user details page

src/app/features/change-user-security/change-user-security.component.html, src/app/features/change-user-security/change-user-security.component.ts
make change user security page gds compliant
=> feature | gds assessment | 466 | change user security

src/app/app.component.html, src/app/app.module.ts, src/app/core/model/url.model.ts, src/app/core/services/back.service.ts, src/app/features/workers/main-job-start-date/main-job-start-date.component.ts, src/app/features/workers/question/question.component.ts, src/app/shared/components/back-link/back-link.component.html, src/app/shared/components/back-link/back-link.component.ts
Adding a Back Link Service. You can set the back link by calling
```this.backService.back = { url: ['/path'] }```
It can also take `fragments` and `queryParams` as optional properties
=> Back Link Service

server/models/classes/wdfCalculator.js
hotfix for getTime error, also available for normal develop/staging deployment.
=> Correcting logic condition when testing against thisEstablishment.lastWdfEligibility

server/models/classes/wdfCalculator.js, src/app/features/dashboard/home-tab/home-tab.component.html
=> Merge from Develop to Test 

src/app/features/workers/mental-health-professional/mental-health-professional.component.html, src/app/features/workers/mental-health-professional/mental-health-professional.component.ts, src/app/features/workers/staff-details/staff-details.component.ts
Also fixed an issue around removing a pre-selected job role from Other Jobs. This should be handled on the Server but currently isn't
=> GOV.UK Framework | Staff Record | Mental Health Professional

server/config/localhost.yaml, server/models/classes/establishment.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/user.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/models/user.js, server/routes/accounts/user.js, server/routes/login.js, server/routes/registration.js, server/utils/security/generateJWT.js
Forced lowercase on username and email. Affects a lot of the API endpoints, specifically around username/email lookup, login, registration and create/update User.
Introduction of User.isPrimary (model); set to true on registration.
=> Preparing the backend to support migration

src/app/features/workers/other-qualifications-level/other-qualifications-level.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.ts
This is dependant on #536 for the details component
=> GOV.UK Framework | Staff Record | Other Qualification Level

src/app/core/services/worker.service.ts, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/dashboard/workplace-tab/workplace-tab.component.ts, src/app/features/workers/create-basic-records-start-screen/create-basic-records-start-screen.component.html, src/app/features/workers/create-basic-records-start-screen/create-basic-records-start-screen.component.spec.ts, src/app/features/workers/create-basic-records-start-screen/create-basic-records-start-screen.component.ts, src/app/features/workers/total-staff/total-staff.component.html, src/app/features/workers/total-staff/total-staff.component.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workers/workers.module.ts, src/app/shared/components/total-staff-panel/total-staff-panel.component.html, src/app/shared/components/total-staff-panel/total-staff-panel.component.ts
Adding Start Screen for Basic Records
Save and Return for Total Staff
=> Skeleton Records Bugs

server/models/classes/establishment.js, server/models/classes/worker.js
Hi Denny
This is a quick and easy PR for your review and approval.
This will fix the issues Ann is seeing in dev where none of the establishments/workers are updating their WDF eligibility.
If you could do the honours to review and approve(?) for me.
Thanks
=> Restoring currentEligibility when calculating local WDF

src/app/features/login/login.component.html, src/app/features/login/login.component.ts
- highlight form fields on unauthorized user login
- corrected error classes
=> bugfix | highlight form fields on unauthorized user login

src/app/app.component.html, src/assets/scss/main.scss, src/assets/scss/modules/_sticky-footer.scss
Adding in a flex based sticky footer.
=> Sticky Footer

src/app/core/constants/constants.ts, src/app/core/validators/date.validator.ts, src/app/features/dashboard/dashboard.component.ts, src/app/features/reports/reports.component.ts, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.html, src/app/features/workers/adult-social-care-started/adult-social-care-started.component.ts, src/app/features/workers/average-weekly-hours/average-weekly-hours.component.html, src/app/features/workers/average-weekly-hours/average-weekly-hours.component.ts, src/app/features/workers/country-of-birth/country-of-birth.component.ts, src/app/features/workers/date-of-birth/date-of-birth.component.ts, src/app/features/workers/days-of-sickness/days-of-sickness.component.ts, src/app/features/workers/main-job-start-date/main-job-start-date.component.html, src/app/features/workers/main-job-start-date/main-job-start-date.component.ts, src/app/features/workers/nationality/nationality.component.ts, src/app/features/workers/question/question.component.ts, src/app/features/workers/recruited-from/recruited-from.component.ts, src/app/features/workers/salary/salary.component.html, src/app/features/workers/salary/salary.component.ts, src/app/features/workers/staff-record-summary/employment/employment.component.ts, src/app/features/workers/staff-record-summary/personal-details/personal-details.component.ts, src/app/features/workers/weekly-contracted-hours/weekly-contracted-hours.component.html, src/app/features/workers/weekly-contracted-hours/weekly-contracted-hours.component.ts, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.html, src/app/features/workers/year-arrived-uk/year-arrived-uk.component.ts, src/assets/scss/components/_input.scss, src/assets/scss/main.scss
Fixing submission issues, error messages and retaining answers on conditional radios
=> Fixing issues with Staff Record Questions

src/app/features/workers/check-staff-record/check-staff-record.component.ts
Adding missing goBack function
=> Summary Back logs user out

src/app/features/change-your-details/change-your-details.component.ts, src/app/features/registration/confirm-workplace-details/confirm-workplace-details.component.html, src/app/features/registration/confirm-workplace-details/confirm-workplace-details.component.ts, src/app/features/registration/enter-workplace-address/enter-workplace-address.component.ts, src/app/features/registration/regulated-by-cqc/regulated-by-cqc.component.ts, src/app/features/registration/select-main-service/select-main-service.component.ts, src/app/features/registration/select-workplace/select-workplace.component.ts, src/app/features/registration/your-details/your-details.component.ts
- added missing back links to registration flow pages
- hide location Id if non cqc regulated and add in missing change links on confirm workplace details page
=> Bugfix | issues with registration back navigation

src/app/features/change-password/change-password.component.ts, src/app/features/change-password/edit/edit.component.html, src/app/features/change-password/edit/edit.component.ts
- fix console errors on change password screen
- remove unused authService and establishment id code
=> unable to change password

src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/workers/staff-record-summary/employment/employment.component.html, src/app/features/workers/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html, src/app/shared/components/workplace-summary/workplace-summary.component.html
Updating mandatory fields for WDF
=> bugfix-595/update-wdf

src/app/core/services/dialog.service.ts, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.html, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.html, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.spec.ts, src/assets/scss/modules/_overlay.scss
Updated Delete Training & Qualifications Dialogs.
Updated Dialog component to trap focus using Angular A11y
=> GOV.UK Framework | Staff Record | Delete Training & Qualifications

manifest.bluegreen.yml, manifest.test.yml
Dev is ok so need to put the config changes for Test and Bluegreen. Besides having this in bluegreen is ok as there is no auto deployment for blue/green
=> changes to config files for Test and BlueGreen env.

src/app/features/registration/create-username/create-username.component.html, src/app/features/registration/create-username/create-username.component.ts, src/app/features/registration/security-question/security-question.component.ts
- Ensure create username page is prepopulated if user has already entered these details and navigates back from confirm account details screen
- Also cater for backlink route destination, form submit route destination
- Also cater for call to action label
=> Bugfix | prepopulate edit username

server/models/classes/establishment.js
Removed some old code left behind which was overriding the preferred behaviour for when main service had capacities.
Also, correcting the response when there are no resulting main service capacities.
Thanks
=> WDF Capacities reporting

src/app/core/validators/date.validator.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.html, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.html, src/app/features/workers/add-edit-training/add-edit-training.component.ts, src/app/features/workers/date-of-birth/date-of-birth.component.html, src/app/features/workers/main-job-start-date/main-job-start-date.component.html, src/app/features/workers/staff-record/qualifications/qualifications.component.html, src/app/features/workers/staff-record/staff-record.component.html, src/app/features/workers/staff-record/training/training.component.html, src/app/shared/components/character-count/character-count.component.ts, src/app/shared/components/date-picker/date-picker.component.html, src/app/shared/components/date-picker/date-picker.component.ts, src/app/shared/components/error-summary/error-summary.component.ts
* Updated Date Picker to only show errors when submitted is true
* Fixed an error with character count where max length value was set to null
* Updated Staff Record page to fit GDS standards
* Add and View Qualifications
* Add and View Training
I'm not 100% happy with this, there is still a lot left around error messages that needs to be fixed. These pages should definitely be revisited
=> GOV.UK Framework | Staff Record | Training and Qulifications

src/app/core/model/establishment.model.ts, src/app/core/services/establishment.service.ts, src/app/features/workplace/edit-workplace/edit-workplace.component.html, src/app/features/workplace/edit-workplace/edit-workplace.component.spec.ts, src/app/features/workplace/edit-workplace/edit-workplace.component.ts, src/app/features/workplace/question/question.component.spec.ts, src/app/features/workplace/question/question.component.ts, src/app/features/workplace/type-of-employer/type-of-employer.component.html, src/app/features/workplace/type-of-employer/type-of-employer.component.scss, src/app/features/workplace/type-of-employer/type-of-employer.component.ts, src/app/features/workplace/workplace-routing.module.ts, src/app/features/workplace/workplace.module.ts, src/app/features/workplace/workplace.resolver.ts, src/app/shared/components/workplace-summary/workplace-summary.component.html
Updating Workplace Questions to use a base class
Updating Type of Employer Question
=> GOV.UK Framework | Staff Record | Workplace

src/app/features/registration/regulated-by-cqc/regulated-by-cqc.component.ts
=> bugfix | hide server error if cqc regulated radio is toggled

package-lock.json, package.json, src/app/core/services/back.service.ts
Added url-parse package
Back Link now checks to see if the URL portion of the Location URL has changed before removing the Back Link
=> Defect | Back Link now persists when navigating fragments

src/app/core/model/userDetails.model.ts, src/app/features/account-management/change-user-security/change-user-security.component.ts, src/app/features/account-management/change-your-details/change-your-details.component.ts, src/app/features/account-management/your-account/your-account.component.html, src/app/features/registration/change-your-details/change-your-details.component.ts, src/app/features/registration/confirm-account-details/confirm-account-details.component.html, src/app/features/registration/confirm-account-details/confirm-account-details.component.ts, src/app/features/registration/your-details/your-details.component.ts
- corrected payload for user registration
- added missing properties and some properties needed to be renamed
=> Bugfix | unable to register

src/app/features/workplace/services-capacity/services-capacity.component.ts
- parse string to number
- order imports
=> bugfix | unable to change service capacities

src/app/app-routing.module.ts, src/app/core/constants/constants.ts, src/app/core/services/auth-interceptor.ts, src/app/core/services/bulk-upload.service.ts, src/app/core/services/error-summary.service.ts, src/app/core/services/http-interceptor.ts, src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.html, src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.ts, src/app/features/bulk-upload/bulk-upload.module.ts, src/app/features/bulk-upload/files-upload/files-upload.component.html, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/selected-files-list/selected-files-list.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.spec.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts, src/app/features/bulk-upload/validated-files-list/validated-files-list.component.html, src/app/shared/validators/custom-form-validators.ts, src/assets/scss/modules/_utils.scss
- client side validation on bulk upload, error messages
- show selected files to be uploaded
- perform upload of files
- show uploaded files 
- `note`: file upload progress descoped to future sprint
=> Feature | bulk upload perform upload

src/app/core/model/logged-in.model.ts, src/app/features/dashboard/dashboard.component.html
- conditionally display `Parent` if logged in user has the `isParent` flag
=> feature | parents and subs | display parent

src/app/core/model/logged-in.model.ts, src/app/features/dashboard/dashboard.component.html
- display parent name in dashboard if logged in user is a subsidiary
=> feature | parents and subs | display parent name

src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.html, src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.ts, src/app/features/workplace/my-workplace/my-workplace.component.html
- simplified checkbox default checked/not checked state 
- typed `authorities`
- copy change for view workplaces
=> bugfix | local authorities selection deselection issues

server/models/classes/establishment.js, server/models/serviceUsers.js
Included data from associations now moved to individual queries after the initial establishment query to improve performance
=> Associations moved from includes to individual queries

src/app/core/services/worker.service.ts, src/app/features/workers/check-staff-record/check-staff-record.component.ts, src/app/features/workers/contract-with-zero-hours/contract-with-zero-hours.component.ts, src/app/features/workers/country-of-birth/country-of-birth.component.ts, src/app/features/workers/mental-health-professional/mental-health-professional.component.ts, src/app/features/workers/nationality/nationality.component.ts, src/app/features/workers/other-job-roles/other-job-roles.component.ts, src/app/features/workers/other-qualifications/other-qualifications.component.ts, src/app/features/workers/question/question.component.ts, src/app/features/workers/social-care-qualification/social-care-qualification.component.ts, src/app/features/workers/staff-details/staff-details.component.ts
Updating Staff Details Component to work with an unset Worker
Updating Question Component to properly keep the Worker state up to date
Updating surrounding Worker Questions to use the updated Worker state rather than the form values
Fixed an issue with navigation between Mental Health Professional and Main Job Start Dtate Questions
=> Bug Fix | Worker State and Staff Details Question

src/app/core/model/location.model.ts, src/app/core/model/workplace-service.model.ts, src/app/features/registration/confirm-account-details/confirm-account-details.component.ts, src/app/features/registration/confirm-workplace-details/confirm-workplace-details.component.html, src/app/features/registration/registration-routing.module.ts, src/app/features/registration/select-main-service/select-main-service.component.html, src/app/features/registration/select-main-service/select-main-service.component.ts
- Add the GDS conditionally revealing content for the `Other` text input on each `Other` radio element
- Ensure `maxlength` validator is set on the other input text field only if something is entered as its an optional field.
- Update the registration `POST` model request, associated interfaces etc
- Display new entered `Other` field on the confirm your workplace details summary page
=> Feature | change request | main service other input field

src/app/features/registration/regulated-by-cqc/regulated-by-cqc.component.html, src/app/features/registration/regulated-by-cqc/regulated-by-cqc.component.ts, src/app/features/registration/select-main-service/select-main-service.component.html
There was only one place I could actually find this at the moment.
=> Accessibility | Correct hidden class on conditional fields

server/routes/registration.js
=> registration debug code removed

src/app/core/model/services.model.ts, src/app/features/workplace/other-services/other-services.component.ts
- added missing property to interface
- if `user has previously entered data in to the other text field then display it
=> bugfix | previous data entered into the other text fields isnt redisplayed

.gitignore, package-lock.json, server/models/BulkImport/BUDI/index.js, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/worker.js, server/models/serviceCapacity.js, server/routes/establishments/bulkUpload.js
This follows approval on https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/pull/661, but github online is not letting me resolve conflicts online. So i created this branch from `develop` and did a manual merge.
Thanks
=> Bulk upload entity load for merge

.gitignore, package-lock.json, server/models/BulkImport/BUDI/index.js, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/worker.js, server/models/serviceCapacity.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/Aykp0AHW
Lots in this PR:
1. BUDI mappings - new country, requires new country/nationality code mapping.
2. BUDI mappings - Establishment service capacities (utilisations and capacities) needs to be translation from assumed capacity/utilisation in Bulk Import to a specific ServiceCapacity question. To make this easier I changed the original `cqc.ServicesCapacity` table to to add "Type"; required update to Sequelize model too.
More work on this to follow in later sprints.
3. Establishments CSV - the `toAPI` method, but also transposition of capacities/utilisations (positional values to indexed) and transposition of vacancies, starters an dleavers (positional values to indexed)
4. Establishments CSV  - now parsing `REGTYPE` and using that to test for `PROVID` and …
=> Bulk upload entity load

server/models/classes/worker/properties/mainJobProperty.js, server/models/classes/worker/properties/otherJobsProperty.js, server/models/job.js, server/models/worker.js, server/models/workerJobs.js, server/routes/jobs.js
- https://trello.com/c/hiy5ZcqL/77-7-change-request-job-roles-other-input-field
Still todo:
- Update Worker automated integration tests - main job and 'other jobs'. Double check on change audit.
=> Add other to main-job and other-job

server/models/classes/worker/properties/otherJobsProperty.js
Contains a fix, to check length validation
=> Fix - length validation for otherJobsProperty

server/models/BulkImport/csv/metaData.js, server/routes/establishments/bulkUpload.js
Outstanding issues: integrate in the metadata class once its prior changes are merged.
expiry of signed URL - currently set to same as the upload url, should this be different?
=> bulkupload get files and get by id

src/app/core/model/bulk-upload.model.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/file-validate-status/file-validate-status.component.html, src/app/features/bulk-upload/file-validate-status/file-validate-status.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
- FE work encapsulate happy path of bulk upload validate process with no errors
=> Feature | bulk upload | validate, pass no warnings

src/app/core/model/establishment.model.ts, src/app/core/model/services.model.ts, src/app/features/workplace/service-users/service-users.component.html, src/app/features/workplace/service-users/service-users.component.ts, src/app/shared/components/workplace-summary/workplace-summary.component.html
Updating Service Users to use the GOV.UK Design Framework
Adding Other fields to Service Users
The names of the interfaces are very confusing and I'm not 100% sure what to call them.
=> GOV.UK Framework | Workplace | Service Users

src/app/features/bulk-upload/files-upload/files-upload.component.html, src/app/features/bulk-upload/selected-files-list/selected-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html
- added missing contextual success message
- tweaks to html css class's to get spacing perfect
- ensure Upload files and remove files cta's don't display if files are uploading or files have already been uploaded
=> bugfix | missing contextual message

package-lock.json, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/establishment/properties/mainServiceProperty.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/validations/entityValidator.js, server/models/classes/validations/validationMessage.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
This is a complement PR for https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/pull/699, having resolved conflicts with `develop` branch - but `github resovle conflicts` online is failing.
=> Bulk upload validations merge with api merge conflicts

src/app/features/workplace/service-users/service-users.component.ts
Adding check to see if Establishment has ServiceUsers before trying to prefill form
=> Bug | Service Users error for new users

server/models/classes/establishment.js, server/routes/establishments/bulkUpload.js
A fix to training cross-reference lookup (no whitespace in keys), and downgrading of a validation message.
=> Bulk upload validations 2

src/app/shared/components/total-staff-panel/total-staff-panel.component.html, src/assets/scss/partials/_lists.scss
Updated the Total Staff Panel on the Staff Records Tab to use the definition list rather than divs for accessibility.
Tested and works on IE10/11, Edge and all modern browsers
=> Accessibility | Total Staff Panel now using Definition List

server/routes/establishments/bulkUpload.js
(14) Bulk Upload - Validation Report
The report is currently generating the following, still needs a bit of work for warnings, but basically done.
**********************************************
* Errors (will cause file(s) to be rejected) *
**********************************************
Invalid: A0000000000 on line 3
Establishment headers (HEADERS) can contain, LOCALESTID,STATUS,ESTNAME,ADDRESS1,ADDRESS2,ADDRESS3,POSTTOWN,POSTCODE,ESTTYPE,OTHERTYPE,IIPSTATUS,PERMCQC,PERMNHSC,PERMLA,SHARELA,REGTYPE,PROVNUM,LOCATIONID,MAINSERVICE,ALLSERVICES,CAPACITY,UTILISATION,SERVICEDESC,SERVICEUSERS,OTHERUSERDESC,TOTALPERMTEMP,ALLJOBROLES,STUDENTCOUNT,STARTERS,LEAVERS,VACANCIES,REASONS,REASONNOS,DESTNOS on line 1
Missing on line 3
Capacities (CAPACITY): position 1 is unexpected capacity (no expected …
=> add endpoint for bulk upload report

src/app/core/constants/constants.ts, src/app/features/registration/create-username/create-username.component.html, src/app/features/registration/create-username/create-username.component.ts
- added new `ALPHA_NUMERIC_WITH_HYPHENS_UNDERSCORES` constant
- updated validation rules on username with new `ALPHA_NUMERIC_WITH_HYPHENS_UNDERSCORES` rule and minlength rule
- markup and ts cleanup
=> bugfix | username form field | update validation rules

server/routes/establishments/bulkUpload.js
New report:
**********************************************
* Errors (will cause file(s) to be rejected) *
**********************************************
Training - Unknown establishment/workplace cross reference, 997 on line 3
Training - Unknown establishment/workplace cross reference, 997 on line 4
Training - Unknown establishment/workplace cross reference, 997 on line 5
Training - Unknown establishment/workplace cross reference, 997 on line 2
Workers - Worker headers (HEADERS) can contain, LOCALESTID,UNIQUEWORKERID,CHGUNIQUEWRKID,STATUS,DISPLAYID,NINUMBER,POSTCODE,DOB,GENDER,ETHNICITY,NATIONALITY,BRITISHCITIZENSHIP,COUNTRYOFBIRTH,YEAROFENTRY,DISABLED,CARECERT,RECSOURCE,STARTDATE,STARTINSECT,APPRENTICE,EMPLSTATUS,ZEROHRCONT,DAYSSICK,SALARYINT,SALARY,HOURLYRATE,MAINJOBROLE,MAINJRDESC,CONTH …
=> Update bulk upload report

src/app/features/registration/create-username/create-username.component.ts
=> feature | change request | username exists copy change

server/config/config.js, server/utils/email/notify-email.js, server/utils/slack/slack-logger.js
Hi Nasir
https://trello.com/c/OxdRoU55
As worked through appear.in, PR to fix the initialisation of Slack URl and Notify Key from AWS Secrets Manager.
=> Hotfix aws secrets slack notify

index_staging.html, index_uat.html
Updating Index file to include `js-enabled` class
=> Bugfix | `js-enabled` not being appended to body

src/app/core/guards/auth/auth.guard.ts, src/app/core/services/establishment.service.ts, src/app/features/login/login.component.ts
- check if logged in user is the same as previously stored establishmentId
- then conditionally set redirect if logged in user hasn't changed
=> bugfix | signout signin redirect issue

server/config/localhost.yaml, server/models/BulkImport/csv/establishments.js, server/models/classes/establishment.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/worker.js, server/models/establishment.js, server/models/worker.js, server/models/workerQualifications.js, server/models/workerTraining.js, server/routes/establishments/bulkUpload.js
This is the first of my Bulk Upload Complete PRs. It's a large change so I'd sooner drop code to you in sizeable chunks.
There is lots going on here:
1. `server/models/BulkImport/csv/establishments.js` -  Fixing the creation of Establishment entity for vacancies, starters and leavers following a recent correction to make the updates and fetches look the same.
2. `localhost.yaml` is a correction to the bucket name for bulk upload that I had managed to commit whilst testing dev deployment on Monday.
3. Allowing the restoring from both JSON and database not just the establishment, but the associative set of Workers too, and the Worker's associative set of Training and Qualifications - but only when told to do so (because it's an expensive operation otherwise). A large establishment can have …
=> Bulk upload - Complete Upload - setting the scene

src/app/core/model/reports.model.ts, src/app/core/services/reports.service.ts, src/app/features/account-management/change-your-details/change-your-details.component.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/selected-files-list/selected-files-list.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts, src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/features/public/feedback/feedback.component.ts, src/app/features/registration/change-your-details/change-your-details.component.ts, src/app/features/registration/confirm-account-details/confirm-account-details.component.ts, src/app/features/registration/confirm-workplace-details/confirm-workplace-details.component.ts, src/app/features/registration/create-username/create-username.component.ts, src/app/features/registration/enter-workplace-address/enter-workplace-address.component.ts, src/app/features/registration/find-workplace-address/find-workplace-address.component.ts, src/app/features/registration/security-question/security-question.component.ts, src/app/features/registration/select-workplace-address/select-workplace-address.component.ts, src/app/features/registration/select-workplace/select-workplace.component.ts, src/app/features/registration/your-details/your-details.component.ts, src/app/features/reports/eligibility-display-overview/eligibility-display-overview.component.ts, src/app/features/reports/reports.component.ts, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.html, src/app/features/workers/add-edit-training/add-edit-training.component.ts, src/app/features/workers/check-staff-record/check-staff-record.component.ts, src/app/features/workers/create-basic-records/create-basic-records.component.html, src/app/features/workers/other-job-roles/other-job-roles.component.html, src/app/features/workers/other-job-roles/other-job-roles.component.ts, src/app/features/workers/staff-record/staff-record.component.ts, src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.html
Fixing 184 errors blocking the production build of the application
=> Bugfix | Fixing issues reported during `ng build --prod`

src/app/features/workers/create-basic-records/create-basic-records.component.html, src/app/features/workers/create-basic-records/create-basic-records.component.ts
- Re-organise markup to solve specificity
=> - Add fix to correctly display staff record across browsers

server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
Tidying up error handling on training and qualification entity, which was resulting in empty entities added in association sets.
=> Belt and braces

src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/workplace-tab/workplace-tab.component.html, src/app/features/workplace/start/start.component.html, src/app/features/workplace/start/start.component.spec.ts, src/app/features/workplace/start/start.component.ts, src/app/features/workplace/type-of-employer/type-of-employer.component.ts, src/app/features/workplace/workplace-routing.module.ts, src/app/features/workplace/workplace.module.ts
Adding Workplace Start Screen and updating navigation to and from it.
=> Feature | Workplace | Start Screen

src/app/features/workplace/start/start.component.html, src/app/features/workplace/start/start.component.ts, src/app/features/workplace/type-of-employer/type-of-employer.component.ts
=> Bugfix | Fixing Navigation for Workplace Start Screen

src/app/core/constants/constants.ts, src/app/features/registration/create-username/create-username.component.html, src/app/features/registration/create-username/create-username.component.ts, src/app/features/registration/registration-routing.module.ts
- only trigger username existance check on CTA form submit, which also fixes any password errors appearing too quickly
- fix regex pattern
=> bugfix | username fixes

src/app/features/workers/create-basic-records/create-basic-records.component.html, src/app/features/workers/other-job-roles/other-job-roles.component.ts, src/app/features/workers/staff-details/staff-details.component.ts
Most of the changes seem to be formatting because of webstorm.
=> Updated error message for job role

src/app/core/model/bulk-upload.model.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
- consume preValidate api
- removed `UploadedFile` interface
- updated `ValidatedFile` interface with new BE properties
- updates to markup due to interface changes
=> feature | bulk upload consume pre validate api

src/app/core/model/bulk-upload.model.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
- handle pre validate missing mandatory file
- created BulkUploadFileType enum, utilize enum in template
- on files selection set filesUploaded to false so that user can re choose files
- cleanup `onValidateComplete()` method
=> Feature | bulk upload handle pre validate missing mandatory file

src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
this pr ensures file selection works from any point in the bulk upload process
=> feature | bulk upload | ensure file selection works from any point

src/app/features/bulk-upload/files-upload/files-upload.component.ts
currently if you select some files and click the remove btn the files are not removed from the dom node. this pr is to address that
=> bugfix | remove files still shows files count next to upload btn

src/app/core/model/alerts.model.ts, src/app/core/services/alerts.service.spec.ts, src/app/core/services/alerts.service.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts, src/app/shared/components/alerts/alerts.component.html, src/app/shared/components/alerts/alerts.component.ts
* This is a global alert - updated to make completely generic. 
* Added a service where an alert can be added from anywhere
* Only one alert will be present at any one time (currently)
=> Implemented alerts and updated bulk upload alert

server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
Hi Andrew
A quicky PR for review which goes against https://trello.com/c/LRlnSlDr.
=> Controlling how deep to restore associated entities.

src/app/core/model/worker.model.ts, src/app/core/services/worker.service.ts, src/app/features/workers/main-job-start-date/main-job-start-date.component.ts, src/app/features/workers/mental-health-professional/mental-health-professional.component.ts, src/app/features/workers/national-insurance-number/national-insurance-number.component.ts, src/app/features/workers/nursing-category/nursing-category.component.html, src/app/features/workers/nursing-category/nursing-category.component.spec.ts, src/app/features/workers/nursing-category/nursing-category.component.ts, src/app/features/workers/nursing-specialism/nursing-specialism.component.html, src/app/features/workers/nursing-specialism/nursing-specialism.component.spec.ts, src/app/features/workers/nursing-specialism/nursing-specialism.component.ts, src/app/features/workers/other-job-roles/other-job-roles.component.ts, src/app/features/workers/staff-details/staff-details.component.ts, src/app/features/workers/staff-record-summary/employment/employment.component.html, src/app/features/workers/staff-record-summary/employment/employment.component.ts, src/app/features/workers/staff-record-summary/staff-record-summary.component.ts, src/app/features/workers/staff-record/staff-record.component.html, src/app/features/workers/workers-routing.module.ts, src/app/features/workers/workers.module.ts
There's a few updates rolled into this PR which is why the files changed is a bit large
- Added Nursing Category Question
- Added Nursing Specialism Question
- Added Nursing Question to Staff Record Employment Summary List
- Added a helper in the Worker Service to check if a Staff Record has a Job Role
- Updated Navigation for first 7 Questions in the Staff Record flow
- Fixed an issue where navigating to a Question from the Staff Record page would not return back on submitting the Question
- Reordered some imports
=> Feature | Staff Record | Nursing Questions

server/models/BulkImport/BUDI/index.js
=> Changes to service users budi mapping

server/models/BulkImport/csv/workers.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/XHpJc6bC/125-2-validation-staff-records-bulk-upload-column-headings-mandatory
=> validating staff records

src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.html, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts
- added error summary to bulk upload reference page/s
- cater for unique form values
- made form errors generic
=> feature | bulk upload | reference validation

src/app/app.component.html, src/app/features/bulk-upload/download-data-files/download-data-files.component.html, src/app/features/logout/logout.component.html, src/app/features/registration/confirm-account-details/confirm-account-details.component.html, src/app/features/registration/registration-complete/registration-complete.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.html, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.html, src/assets/images/window.svg, src/assets/scss/main.scss, src/assets/scss/partials/_typography.scss
Added a CSS class for all anchors with the attribute `target="_blank"`
Also added a visually hidden context to each anchor that opens in a new window so screen readers will be warned.
=> Accessibility | Warning for anchors opening in new window

src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts, src/app/features/bulk-upload/workplace-references-page/workplace-references-page.component.ts, src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.html, src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.ts, src/app/shared/components/error-summary/error-summary.component.html
- add missing server error handling on `view-my-workplaces` screen
- add server error handling on `bulk upload references` screen
- add ngIf around errors list in error summary component
=> feature | bulk upload | references server validation

src/app/app.component.html, src/app/app.component.ts
Fixing tab positioning on main body
Removing console log
=> Accessibility | Quick fixes

src/app/features/workers/create-basic-records/create-basic-records.component.html
Adding context to Basic Record Change and Delete links
=> Accessibility | Basic Record Link Context

src/app/shared/components/error-summary/error-summary.component.ts
Correctly reset focus to Error Summary Component after form submission
=> Accessibility | Error Summary Focus

src/app/features/registration/select-workplace-address/select-workplace-address.component.html
Postcode is now displayed in Summary List
=> Accessibility | Postcode Semantic Markup

src/app/features/workplace/other-services/other-services.component.ts, src/app/shared/components/tabs/tabs.component.ts
Fixing an error where Other Services would not populate due to missing `other` property from the BE
=> Bug Fix | Other Services Erroring

src/app/shared/components/tabs/tabs.component.ts
Conditionally setting focus with Tabs so they don't steal it on load
=> Bug Fix | Tab taking focus from Skip Link

src/app/shared/components/tabs/tabs.component.ts
Adding missing IE event key names
=> Accessibility | Tab Controls IE

src/app/features/registration/select-main-service/select-main-service.component.ts, src/app/features/workers/create-basic-records-start-screen/create-basic-records-start-screen.component.ts, src/app/features/workers/create-basic-records/create-basic-records.component.ts, src/app/features/workers/create-staff-record-start-screen/create-staff-record-start-screen.component.ts
https://trello.com/c/qq502rNS/177-accessibility-back-link-sequence
Sanity checked form sequences.
Addition of 2 back links on add worker pages.
=> Accessibility | Back Link Sequence

src/app/features/registration/regulated-by-cqc/regulated-by-cqc.component.html, src/app/features/workers/ethnicity/ethnicity.component.html, src/app/features/workers/home-postcode/home-postcode.component.html, src/app/features/workers/national-insurance-number/national-insurance-number.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.html, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.html, src/assets/scss/partials/_typography.scss
Updated Questions to correctly use the **Label as Heading** pattern
Also fixed the external link icon being incorrectly placed when links wrap across two lines.
=> Accessibility | Missing Form Labels

src/app/features/workers/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html, src/app/features/workers/staff-record-summary/qualifications-and-training/qualifications-and-training.component.ts, src/app/features/workers/staff-record/staff-record.component.html
Add Qualifications and Training buttons only to be displayed on Staff Record page
=> Bug Fix | Remove Add Quals/Training buttons from Check Answers

server/routes/establishments/localIdentifier.js
=> A workaround to update local identifier in bulk with audit history

server/models/BulkImport/BUDI/index.js, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/cache/singletons/services.js, server/models/classes/establishment.js, server/models/classes/worker.js
https://trello.com/c/e1WYLQDb - Bulk Upload Download CSV
* Completion of Establishment properties - exception being "Reasons for Leaving columns * 2" as these can't be mapped yet.
* Completion of Worker properties"
Extra: https://trello.com/c/pdmnQFDT - "other services/other" context - `server/models/cache/singletons/services.js`
=> Bulk upload download csv extra

server/routes/establishments/localIdentifier.js, server/routes/establishments/worker.js
Hi Warren
These will probably need altering but thought I would put up for your review. I have made the error return the property 'duplicateValue'. Currently the worker mass update returns a similar response to the establishment mass update, but may need something different
=> Localident ext

src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.html, src/app/features/workplace/data-sharing/data-sharing.component.html, src/app/features/workplace/leavers/leavers.component.html, src/app/features/workplace/other-services/other-services.component.html, src/app/features/workplace/service-users/service-users.component.html, src/app/features/workplace/services-capacity/services-capacity.component.html, src/app/features/workplace/starters/starters.component.html, src/app/features/workplace/type-of-employer/type-of-employer.component.html, src/app/features/workplace/vacancies/vacancies.component.html
Adding Fieldset and Legend to Workplace forms
=> Accessibility | Fieldset and Legend | Workplace

server/models/classes/establishment.js, server/models/establishment.js, server/routes/establishments/bulkUpload.js, server/routes/login.js
https://trello.com/c/vjluKtX3
Allow for tracking of successful bulk upload completions, and "tracking of first bulkupload" returned in login response.
=> Bulk Upload "Local Identifiers" navigation conrtol

server.js, server/aws/kinesis.js, server/aws/sns.js, server/config/config.js, server/config/development.yaml, server/config/localhost.yaml, server/config/production.yaml, server/config/test.yaml, server/models/classes/establishment.js, server/models/classes/user.js, server/models/classes/worker.js, server/routes/feedback.js, server/routes/registration.js
=> Backend api kinesis and sns

README.md, src/app/app.component.html, src/app/features/bulk-upload/download-data-files/download-data-files.component.html, src/app/features/registration/confirm-account-details/confirm-account-details.component.html, src/app/features/registration/registration-complete/registration-complete.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.html, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.html, src/assets/images/window.svg, src/assets/scss/partials/_typography.scss
Also added to the README with some accessibility guidelines to follow.
=> Bug Fix | External Links

server.js, server/config/config.js, server/models/workerAvailableQualifications.js, server/routes/admin/index.js, server/routes/admin/search/establishments/index.js, server/routes/admin/search/index.js, server/routes/admin/search/users/index.js, server/routes/availableQualifications.js, server/routes/establishments/approve.js, server/routes/establishments/index.js, server/routes/establishments/reject.js, server/utils/security/isAuthenticated.js
https://trello.com/c/sEjGGebv - two new admin endpoints that allow for "wildcard" searching on users and establishments.
https://trello.com/c/bGZowHfz - two endpoints off .../establishment with different authentication to other endpoints - they're just stubs returning 200
https://trello.com/c/2TUiBVCq - two endpoints for updating the qualifications reference data - one PUT to update an existing qualifications record and one post to create a new one (with validation to check it is unique - by ID only).
=> Internal admin apis

server/aws/sns.js, server/models/workerAvailableQualifications.js, server/routes/availableQualifications.js, server/routes/registration.js
https://trello.com/c/bGZowHfz
As part of integrating registration approvals/rejection via Slack, had noticed we're missing establishment ID and NDMS for the registration message.
=> Registration posts to slack/SNS corrections

src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
Merging UploadedFile and ValidatedFile object correctly
=> Bug Fix | Uploaded files object destroyed on validate

src/app/app-routing.module.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts, src/app/features/bulk-upload/bulk-upload-routing.module.ts, src/app/features/bulk-upload/bulk-upload.module.ts, src/app/features/bulk-upload/staff-references-page/staff-references-page.component.ts, src/app/features/bulk-upload/staff-references.resolver.ts, src/app/features/bulk-upload/workplace-references-page/workplace-references-page.component.ts, src/app/features/bulk-upload/workplace-references.resolver.ts
This also fixes the back button flow through local identifiers
=> Bug Fix | Local Identifiers Resolver

server/models/classes/user.js, server/routes/accounts/user.js
Mid way point PR as Omar needs to test this on the FE
=> type guards

server/models/BulkImport/csv/establishments.js, server/models/classes/establishment.js, server/models/establishment.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/vNHbfdms - Adding an interim solution for reasons for leaving for bulk upload - what goes in, comes out
=> Bulk upload reasons for leaving

server/models/BulkImport/csv/establishments.js, server/models/classes/establishment.js, server/models/establishment.js, server/routes/establishments/bulkUpload.js, server/routes/registration.js
https://trello.com/c/W7AVdqP7 - introducing ProvID to establishment as a simple property (not change managed). Allowing ProvID to be updated (Establishment::load) from bulk upload.
https://trello.com/c/2A3BF3Yj - Splitting single address into multiple components to allow the preservation on "bulk upload" download. Allowing the individual address components to be updated (Establishment::load) from Bulk Upload.
=> Adding ProvID and splitting Address into individual Address1, Address2, Address3, Town and County components

src/app/core/guards/edit-user-permissions/edit-user-permissions.guard.spec.ts, src/app/core/guards/edit-user-permissions/edit-user-permissions.guard.ts, src/app/features/workplace/user-account-view/user-account-view.component.ts, src/app/features/workplace/workplace-routing.module.ts
Adding Guard to stop users editing Permissions if they are the only user left.
=> Feature | Guard to stop last user editing permissions

src/app/core/guards/bulk-upload/bulk-upload.guard.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.ts, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.html, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts, src/app/features/bulk-upload/staff-references-page/staff-references-page.component.ts, src/app/features/bulk-upload/workplace-references-page/workplace-references-page.component.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.ts
This is getting close to spaghetti code. Lots of random ways to enter and exit certain parts of the App. Personally I think we should be trying to create an easier navigation structure rather than forcing the user into certain pathways.
=> Bug Fix | Updating Local Identifiers navigation so it returns correctly

server/models/classes/establishment.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/CrAkpaAu
As the original author of the validation reports, here's a quick PR for your review, that uses the validation difference report to write out any establishments or workers that have been deleted.
=> Bulk upload validation report deleted workplace and staff records

server/routes/accounts/user.js, server/routes/establishments/localIdentifier.js, server/routes/establishments/worker.js
PR for
https://trello.com/c/HlxXnamI/141-6-user-accounts-pending-user-resend-activation-link
Also altered the activation email timeout for registration to 2 days
=> Resend activationlink

server/routes/accounts/user.js
This is a stub endpoint requested during User Account meeting so that Tom is able to continue working on the FE over the weekend
=> stub endpoint

server/config/config.js, server/utils/security/generateJWT.js, server/utils/security/isAuthenticated.js, server/utils/security/passport.js
Hey Nasir
Would appreciate getting this reviewed and approved and in dev before the next deploy to staging. This must go to production.
=> Updating JWT signing secret

src/app/core/services/auth.service.ts, src/app/features/dashboard/dashboard.component.ts
This places a check on the session and the establishment before returning a possible null value.
=> Double check on firstBulkUpload

src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/workplace/view-workplace/view-workplace.component.html, src/app/shared/components/staff-summary/staff-summary.component.html
=> Tech Debt | Design Review

src/app/app.component.html, src/app/core/components/error/page-not-found/page-not-found.component.html, src/app/core/components/error/problem-with-the-service/problem-with-the-service.component.html, src/app/core/components/footer/footer.component.html, src/app/core/components/header/header.component.html, src/app/features/bulk-upload/selected-files-list/selected-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html, src/app/features/search/search.component.html, src/app/shared/components/staff-summary/staff-summary.component.html, src/app/shared/components/user-accounts-summary/user-accounts-summary.component.html
Fixing routerLink to be HTML Valid
=> Accessibility | Invalid HTML | Router Links

server/models/classes/user.js, server/routes/accounts/user.js
https://trello.com/c/74MWmm6O/155-user-accounts-resend-activation-link-isnt-responding-with-the-trackinguuid-back-end
resend activation email now altered so that it returns back the trackingUUID as per the card above
=> resend tracking return

server/routes/accounts/user.js
Read/Edit permissions which exists on add, now also implemented on Update user
As per card
https://trello.com/c/AVl2iOR4/139-view-edit-accounts-issues
=> update permissions check

server/config/config.js, server/config/development.yaml, server/config/localhost.yaml, server/config/preproduction.yaml, server/config/production.yaml, server/config/test.yaml, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/Pae7NyN8
A collection of changes, each noted as a task on the associated trello card above for visibility.
Note - this PR is an open PR - it is not yet ready for code review.
=> 20190722 bulk upload - collection of onsite changes working side by side with Jackie on real bulk upload data

server/routes/accounts/user.js
https://trello.com/c/TmHH4qoN/209-expiry-of-activation-links-differs-between-original-and-resent
3 days changed to 2 in the code
=> 3 days changed to 2

src/app/features/search/search.component.html
Simple fix to update response flag to reflect json response data.
=> Updating answer flag to reflect response

server/models/classes/qualification.js, src/app/core/services/auth-interceptor.ts, src/app/core/services/auth.service.ts, src/app/features/account-management/your-account/your-account.component.ts, src/app/features/bulk-upload/files-upload-progress/files-upload-progress.component.ts, src/app/features/dashboard/workplace-tab/workplace-tab.component.ts, src/app/features/login/login.component.ts
A small update to remedy previously introduced spacing issues now I properly have Prettier working.
=> Fix for spacing issues previously introduced

src/app/features/search/search.component.html
Placeholder UI to accompany @wozzer72 new changes.
=> Addition of flags for establishments and user search

.vscode/launch.json, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js, server/routes/establishments/localIdentifier.js, server/routes/reports/dailySnapshot/index.js, server/sendEmail.js
https://trello.com/c/1pTd8zzJ
And the last PR in the trilogy.
Having validated (the first PR), then generated the differences (second PR), this last PR is all about processing the  differences.
I have also taken the time to rview all my console log ("WA DEBUG") and deleted lots that are now unnecessary.
Thanks
=> Bulk upload statuses 3

src/app/features/search/search.component.html
Silly mispelling of the code needed to display.
=> Update to fix mispell of nmsdId code

src/app/app-routing.module.ts, src/app/core/guards/add-workplace-in-progress/add-workplace-in-progress.guard.ts, src/app/core/model/workplace.model.ts, src/app/core/services/workplace.service.ts, src/app/features/add-workplace/add-workplace-routing.module.ts, src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.html, src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.ts, src/app/features/add-workplace/start/start.component.ts, src/app/features/registration/confirm-workplace-details/confirm-workplace-details.component.html
- Make api call to BE in order to complete adding a workplace [currently its always throwing a 400 so waiting on warren to help me troubleshoot]
- Handle BE api errors
=> feature | make api call to add workplace

server/routes/establishments/index.js
=> Correcting spelling mistake

server/models/classes/user.js, server/routes/accounts/user.js, server/routes/establishments/worker.js, server/utils/security/isAuthenticated.js
https://trello.com/c/4NczPkjf/136-13-site-wide-read-only-user-permissions
Here are the modifications to the permissions.
Altered workers so that it READ role is denied
Altered the isAuthenticated middleware so that there are now two possible options, one implementing role check, one not.
User accounts router altered so that the correct middleware is applied to each route
=> permissions

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js
https://trello.com/c/FwVIWjg5
Correcting validation on main job role of 0.
https://trello.com/c/JQJPPNPi
Social Worker/Nurse Main/Other Jobs cross-validation with AMHP, NMCREG and NURSESPEC
https://trello.com/c/QyEi3oTS
NOCHANGE to short circuit on validation
https://trello.com/c/J4e5vlyD
Downgrade status of DELETE from error to warning, and revised text
https://trello.com/c/Iafcmjbu
Missing DISPLAYID - upgrade from warning to error
https://trello.com/c/MThB51ro
Failing to map NONSCQUAL 2 and 999
=> Multiple defects carried over from sprint 18 and new defects in sprint 19

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js
https://trello.com/c/dHOHwC4G
Storing PROVID on successful validation for REFTYPE of 2 (cqc regulated)
https://trello.com/c/y2JIxYFa
Better year is integer validation and adding a warning if the qualification year is missing
=> 20190731 - general quick fix bulk upload defects

.vscode/settings.json, src/app/core/services/worker.service.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/workplace/view-workplace/view-workplace.component.html, src/app/features/workplace/view-workplace/view-workplace.component.ts, src/app/shared/components/tabs/tab.component.ts, src/app/shared/components/tabs/tabs.component.html, src/assets/images/flag-orange.svg, src/assets/scss/components/_tabs.scss
Also added the alert when no staff records are found.
=> Feature | Tab Alert

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js
https://trello.com/c/dHOHwC4G
Spelling mistake on creation with `provId`.
https://trello.com/c/yCaUUsa8
Reverting DELETE not exists as a warning, back to error
=> Refixing BU defects

src/app/features/workplace/confirm-leavers/confirm-leavers.component.html, src/app/features/workplace/confirm-leavers/confirm-leavers.component.ts, src/app/features/workplace/confirm-starters/confirm-starters.component.html, src/app/features/workplace/confirm-starters/confirm-starters.component.ts, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.html, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.ts, src/app/features/workplace/leavers/leavers.component.ts, src/app/features/workplace/question/question.component.ts, src/app/features/workplace/starters/starters.component.ts, src/app/features/workplace/vacancies/vacancies.component.ts, src/app/shared/components/workplace-summary/workplace-summary.component.html
Also cleaned up some stuff around lists and uids, which I'll continue in another PR
=> Bug Fix | All Workplace Questions available from Summary

src/app/app-routing.module.ts, src/app/core/guards/bulk-upload/bulk-upload.guard.ts, src/app/core/guards/parent/parent.guard.ts, src/app/core/resolvers/primary-workplace.resolver.ts, src/app/core/services/bulk-upload.service.ts, src/app/core/services/establishment.service.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/report-download-link/report-download-link.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workplace/workplace-routing.module.ts
Adding new Local Identifiers endpoint
Updating Bulk Upload Guard to check for null references
Updating API's to use Establishment UID rather than ID which is now stored in local storage
=> Bug Fix | Bulk Upload Guard & Tech Debt

src/app/features/workplace/confirm-leavers/confirm-leavers.component.html, src/app/features/workplace/confirm-leavers/confirm-leavers.component.ts, src/app/features/workplace/confirm-starters/confirm-starters.component.html, src/app/features/workplace/confirm-starters/confirm-starters.component.ts, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.html, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.ts
Now checks if return is set to switch CTA
=> Bug Fix | Starters, Leavers, Vacancies Confirm CTA

src/app/features/bulk-upload/download-data-files/download-data-files.component.html, src/app/features/bulk-upload/upload-data-files/upload-data-files.component.html
=> Update to heading structure

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/e8cmh8Gm
Validation alignments, mainly the wording of messages for establishments, but some worker anomalies corrected:
* Adding CHGUNIQUEWRKID duplciate validation.
* Changing worker DISPLAYID validation length to just 50.
* UNCHECKED status error
=> 20190802 bu validations

server/models/classes/establishment.js
https://trello.com/c/h2dX27BB
Removing hard coded EstablishmentID and correcting the query to allow for `cqc.Establishment` with no workers.
=> Missing establishment/worker local identifiers defect

server/config/localhost.yaml, server/routes/establishments/bulkUpload.js, server/utils/timerLog.js
https://trello.com/c/Eih5Vl6T
To better understand the performance of bulk upload to then better know where and how to focus attention, and to then better monitor how changes are benefitting bulk upload performance.
=> Bulk Upload validation and completion instrumentation

server/models/classes/establishment.js, server/models/classes/worker.js
=> Overall WDF on entity save - disable because it's broken develop" deployment.

server/models/classes/establishment.js, server/models/classes/establishment/properties/capacityProperties.js, server/models/classes/establishment/properties/employerTypeProperty.js, server/models/classes/establishment/properties/leaversProperty.js, server/models/classes/establishment/properties/mainServiceProperty.js, server/models/classes/establishment/properties/serviceUsersProperty.js, server/models/classes/establishment/properties/servicesProperty.js, server/models/classes/establishment/properties/staffProperty.js, server/models/classes/establishment/properties/startersProperty.js, server/models/classes/establishment/properties/vacanciesProperty.js, server/models/classes/worker.js, server/models/classes/worker/properties/annualHourlyPayProperty.js, server/models/classes/worker/properties/careCertificateProperty.js, server/models/classes/worker/properties/contractProperty.js, server/models/classes/worker/properties/dateOfBirthProperty.js, server/models/classes/worker/properties/daysSickProperty.js, server/models/classes/worker/properties/genderProperty.js, server/models/classes/worker/properties/highestQualificationProperty.js, server/models/classes/worker/properties/mainJobProperty.js, server/models/classes/worker/properties/mainJobStartDateProperty.js, server/models/classes/worker/properties/nationalityProperty.js, server/models/classes/worker/properties/otherJobsProperty.js, server/models/classes/worker/properties/otherQualificationProperty.js, server/models/classes/worker/properties/qualificationInSocialCareProperty.js, server/models/classes/worker/properties/recruitedFromProperty.js, server/models/classes/worker/properties/socialCareQualificationProperty.js, server/models/classes/worker/properties/weeklyHoursAverageProperty.js, server/models/classes/worker/properties/weeklyHoursContractedProperty.js, server/models/classes/worker/properties/zeroContractProperty.js, server/routes/establishments/worker.js
WDF effective date code now moved into the wdf section
=> corrections

src/app/app-routing.module.ts, src/app/app.component.html, src/app/core/components/error/problem-with-the-service/problem-with-the-service.component.html, src/app/core/components/footer/footer.component.html, src/app/core/guards/create-user/create-user.guard.ts, src/app/core/guards/logged-out/logged-out.guard.spec.ts, src/app/core/guards/logged-out/logged-out.guard.ts, src/app/features/activate-user-account/confirm-account-details/confirm-account-details.component.html, src/app/features/activate-user-account/expired-activation-link/expired-activation-link.component.spec.ts, src/app/features/add-workplace/add-workplace-complete/add-workplace-complete.component.html, src/app/features/registration/confirm-account-details/confirm-account-details.component.html, src/app/features/registration/registration-complete/registration-complete.component.html, src/app/features/reports/pages/reports/reports.component.html
Also updated routes to remove the `/public` URL prefix, and fixed where there was no context for links opening in new windows
=> Feature | Logged Out Guard

server/models/classes/establishment.js, server/models/classes/worker.js
https://trello.com/c/W7ZHJv93/62-5-wdf-update-worker-record
IsElligible check fix
=> isEligibleFix

src/app/features/public/terms-conditions/terms-conditions.component.html, src/assets/scss/partials/_lists.scss
- fixed indentation ui issues and cleaned up scss
- also appended `.` after first li as per designs
=> bugfix | nested counter lists indentation

server/models/classes/establishment.js, server/models/classes/establishment/properties/servicesProperty.js, server/models/classes/worker.js, server/models/classes/worker/properties/otherJobsProperty.js
https://trello.com/c/W7ZHJv93
* Worker/Establishment save - lastEligibleDate - if "WDF::isEligible" is true and if lastEligibleDate is null or is less than the effective date
* Worker/Establishment "WDF::isEligible" is calculated based on all properties being eligible (yes/not relevant) and if yes, their _updatedSince_ being true. This compares to "WDF::currentEligibility" which considers only all property's eligible value regardless of when last updated.
* Worker "other jobs" removed from WDF.
* Establishment "other services" removed from WDF.
=> WDF - workers and establishment changes

server/models/classes/establishment.js, server/models/classes/worker.js
https://trello.com/c/W7ZHJv93
Re-enabling the trigger for overall WDF eligibility calculation whensaving Establishment and Worker
=> Overall WDF re-calc

server/models/classes/user.js, server/routes/accounts/user.js, server/routes/login.js
https://trello.com/c/9hASXpDf
.../api/user/me API response updated to correct the returning of the lastLogin property and to add two new properties:
* "migratedUserFirstLogon"
* "migratedUser"
This impacts `server/models/classes/user.js`.
But also impacted is `server/routes/login.js`, as I was testing the login of a migrated user; some refactoring I did a long while back on login, and I hadn't fully tested on migrated user logins.
And following discussion with Charlie, have also added the `establishmentUid` property to the response.
=> Migrated user first logon api flag

server/routes/login.js, server/utils/login/response.js
=> Awkwardly adding migration user properties to login response

server/models/classes/wdfCalculator.js, server/models/classes/worker.js
https://trello.com/c/mnIaq8GR
Social and Non Social Care - "No"/"Don't know" -> "Not relevant"
https://trello.com/c/urKfkJwV
`overall.workplace`, not `overall.staff`, to include `establishment::staff` cross check against `#workers`
=> Known WDF defects

server/models/classes/training.js
https://trello.com/c/grDJCvfe
Revised property format for completed and expires to be a string in the format "YYYY-MM-DD".
Additionally, updated the "completed" validation to allow entering today's date for `completed`.
=> Training  revised "completed" and "expires" date format

server/models/classes/establishment.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/models/establishment.js, server/models/establishmentAudit.js, server/routes/establishments/index.js
https://trello.com/c/ouUV10ZZ
Introducing additional staff and establishment WDF properties, and refactoring the WdfCalculator to separately calculate overall, staff and establishment eligibility including audiseparate audit records.
Adding triggers from `Establishment`/`Worker` entities save/delete(archive) actions, which are ignored on bulk upload.
Bulk Upload trigger yet to do. Want to get this PR reviewed and deployed to dev for the frontend guys to validate and work on the navigation.
=> Overall WDF refactoring

server/models/classes/establishment.js, server/models/establishment.js, server/routes/establishments/worker.js, server/utils/security/isAuthenticated.js
https://trello.com/c/po4YrDE7/92-parent-subs-permissions-refactor
Initial PR for the above trello card
=> localidentifiers fix

src/app/features/workers/add-edit-training/add-edit-training.component.ts
Updating Completed and Expired Dates to use Default Date Format instead of ISO String
=> Bug Fix | Training using date format instead of ISO

server/models/classes/training.js, src/app/features/workers/add-edit-training/add-edit-training.component.ts
=> Bug Fix | Training Dates use date format from ISO

src/app/core/model/my-workplaces.model.ts, src/app/features/workplace/view-workplace/view-workplace.component.ts, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.html, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.ts, src/app/shared/pipes/data-view-permissions.pipe.spec.ts, src/app/shared/pipes/data-view-permissions.pipe.ts, src/app/shared/pipes/workplace-permissions-bearer.pipe.spec.ts, src/app/shared/pipes/workplace-permissions-bearer.pipe.ts, src/app/shared/shared.module.ts
There's one piece left on this that requires BE work, so going to merge this now and wait for the extra piece.
=> Feature | View Workplaces Permission UI

server/models/classes/establishment.js, server/models/classes/wdfCalculator.js
https://trello.com/c/owi0abmt
The staff and establishment eligibility and both true or false all the time the overall eligibility is false - they're always calculated not tracked.
https://trello.com/c/xZK7xOhR
Correction to logic for "one or more" worker.
=> 20190814 wdf be

src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.html
Fixing an issue where property was not available, causing UI issue
=> Bug Fix | Bulk Upload References UI issue

server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/admin/index.js, server/routes/admin/recalcWdf/index.js
https://trello.com/c/kU0xOGCX
Demo'd to Ann.
=> Wdf admin recalc

server/config/config.js, server/models/classes/wdfCalculator.js, server/utils/security/isLocalTest.js
=> Wdf override effective date

server/models/BulkImport/csv/training.js
=> Bulk upload download training dates

server/models/BulkImport/csv/training.js
Handling complete/expires as pure date strings now, not full dates/times.
https://trello.com/c/IwtqPbuf
=> hotfix (bulk upload download) - training completed/expires - duplicate fix into develop

server/routes/establishments/index.js
=> Delete associated workers when deleting an establishment.

server/models/classes/establishment.js, server/models/establishment.js
https://trello.com/c/EnNrPZAG/9-3-parents-and-subs-update-view-workplaces-view
Field added to Sequelize model and added to output of my establishments
=> DataPermissions timestamp

server/models/cache/singletons/permissions.js, server/routes/establishments/permissions.js, server/utils/security/isAuthenticated.js
https://trello.com/c/AWmbz8Vu/4-19-parent-and-subsidiaries-permissions
=> permission changes

src/app/app-routing.module.ts, src/app/core/guards/permissions/check-permissions/check-permissions.guard.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workplace/view-workplace/view-workplace.component.html, src/app/features/workplace/view-workplace/view-workplace.component.ts, src/app/features/workplace/workplace-routing.module.ts, src/app/shared/components/staff-records-tab/staff-records-tab.component.html, src/app/shared/components/staff-records-tab/staff-records-tab.component.ts, src/app/shared/components/staff-summary/staff-summary.component.html, src/app/shared/components/staff-summary/staff-summary.component.ts
permission checks and route guards for 
```
canViewListofWorkers
canViewWorker
canAddWorker
canAddUser
canBulkUpload
```
=> Feature | permissions

server/utils/security/isAuthenticated.js
https://trello.com/c/AWmbz8Vu
Adding a missing `req` attribute set during `hasAuthorisedEstablishment` middleware.
=> Add parentIsOwner to the else route in isAuthenticatedEstablishment

server/models/cache/singletons/permissions.js
https://trello.com/c/AWmbz8Vu/4-19-parent-and-subsidiaries-permissions
Admin role integrated
=> admin role

src/app/features/workers/salary/salary.component.html, src/app/features/workers/salary/salary.component.ts
* Makes all the validators trigger in the same way
=> Move pattern validator inline

server/models/cache/singletons/permissions.js
https://trello.com/c/AWmbz8Vu
Adding three new permission abilities from V5 spreadsheet:
* canEditEstablishment
* canViewUser
* canViewListOfUsers
=> V5 three additional permission abilities

.travis.yml
Hello, it appears one of the travis build flag Edge set to true from initial days. I exactly dont remember why i set it to true initially but i find my note as it something to do some experimental deployment tool.
I set it to false for deployment to work.
=> Issue with travis deployment

src/app/shared/components/workplace-tab/workplace-tab.component.html, src/app/shared/components/workplace-tab/workplace-tab.component.ts
Introduced a regression with previous commit
=> Only display workplace update alert when required

server/models/BulkImport/csv/workers.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/6yZLnek8/31-staff-records-errors-and-warnings-national-insurance-number
This is an initial PR to ensure it is as intended.
=> national insurance error

server/routes/reports/localAuthorityReport/user.js
https://trello.com/c/UsiGWFJU
The tinniest of changes - just to demonstrate I am getting some data out of the worker report table; it's a case sensitivity correctoin.
=> Correcting the localId property being returned in staffTab

server/models/cache/singletons/permissions.js
https://trello.com/c/bT6uTvTX
* Adding `Permission::filterForAdminRole`
* Adding new login scenario (as priority order) `requestData.role === 'Admin'`  to `Permission::myPermission`.
=> Returning all "establishment specific" permissions for all admin users

server/routes/establishments/worker.js
https://trello.com/c/bT6uTvTX
In this new brave world, a user with "Admin" role can run any Worker endpoint. Override worker  authentication middleware to ignore any restructions if role is Admin.
=> Admin override on Worker authentication middleware for "Admin" role

src/app/features/add-workplace/find-workplace-address/find-workplace-address.component.html, src/app/features/registration/find-workplace-address/find-workplace-address.component.html
=> Develop to Staging

src/app/features/workplace/services-capacity/services-capacity.component.html, src/app/features/workplace/services-capacity/services-capacity.component.ts
cleanup markup, fix console errors
=> bugfix | capacities validation

server/models/BulkImport/csv/training.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/UXt2gz82
Fixed three issues with training, following live defect (some additional observations whilst reproducing the original live fault:
1. BU prevalidate - not returning #records after upload
2. BU Training cross-validation - worker DOB when worker doesn't have DoB
3. (the live fault) BU Training validation expiry must be after completion date if given (matching the Training entity validation).
=> Live bu training defect

server/routes/reports/localAuthorityReport/template/xl/sharedStrings.xml, server/routes/reports/localAuthorityReport/user.js
https://trello.com/c/OdDLpQ7r
https://trello.com/c/nE7O8N8i
This work also includes feedback from https://trello.com/c/UsiGWFJU:
Column P - the total should be "No" unless all workplaces are "Yes", in which case the total is "Yes".
And column "N" - relevant to relevantSocialCareQualification when "no" is displayed in red
=> change validations slightly

server/models/BulkImport/csv/establishments.js
https://trello.com/c/Sag2FGQj
Handling special case on Workplace bul upload download for when all of starters, leavers and vacancies are "None".
=> LA Admin Report/BU Workplace Download - Starters, Leavers and Vacancies

server/routes/reports/localAuthorityReport/user.js
https://trello.com/c/vXgYgBdm
https://trello.com/c/nlzcLXNj
This PR also includes a bugfix on the postcode lookup for the local authority as an undeclared variable was being used
=> use the mapping provided from the SP

manifest.bluegreen.yml, server/config/config.js
As per card (https://trello.com/c/QgCEoU60/342-scaling-for-bulk-upload) 
I have made changes for Live branch
- Made the db pool size environment driven
- container size 10 and 8 GB memory
I have yet to define the env variable in Gov Paas (not AWS) so everytime we change we restart the app 
Thanks
=> Config changes for pre production so we can test Bulk upload

server/routes/reports/localAuthorityReport/user.js
https://trello.com/c/dtKHg6ZT
Optimised out calls to querySelector where nextSibling can be used instead and cached sst element for shared strings
=> optimised out unnecessary and slow dom querySelector calls

server/routes/reports/localAuthorityReport/user.js, src/app/features/workplace/services-capacity/services-capacity.component.ts
This has LA reporting changes and 1 db patch to apply
=> Develop to Staging 

server/models/BulkImport/BUDI/index.js
https://trello.com/c/hIzrJomp
Mapping of missing BUDI codes; simply extracted from the `cqc.Qualifications` table and compared against the Bulk Upload Staff Guidance.
=> Missing qualification BUDI codes

src/app/features/workplace/services-capacity/services-capacity.component.html, src/app/features/workplace/services-capacity/services-capacity.component.ts
cater for decimal numbers and also fix accessiblility anchor scroll
=> bugfix | capacities dont allow decimal numbers

src/app/features/workplace/user-account-change-primary-dialog/user-account-change-primary-dialog.component.html, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.html, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.ts, src/app/shared/components/change-data-owner-dialog/change-data-owner-dialog.component.html, src/app/shared/components/change-data-owner-dialog/change-data-owner-dialog.component.spec.ts, src/app/shared/components/change-data-owner-dialog/change-data-owner-dialog.component.ts, src/app/shared/components/error-summary/error-summary.component.html, src/app/shared/components/error-summary/error-summary.component.ts, src/app/shared/shared.module.ts
wip for change data owner dialog component as awaiting BE api
=> add change data owner dialog component

server/models/classes/establishment.js, server/models/classes/user.js, server/routes/accounts/user.js
https://trello.com/c/51gAeqPx
Return WDF facts for primary, and if relevant, for a parent's subs, but only if WDF parameter is passed to my/establishments API endpoint
=> Parents and Sub WDF Report - Backend API Update

server/models/BulkImport/csv/workers.js
https://trello.com/c/VrJBRSvf
Handling ".0" half days, in addition to the existing ".5" validation for DAYSSICK
=> Bulk Upload DAYSSICK P1

package-lock.json, package.json, server.js, server/data/notifications.js, server/routes/accounts/user.js, server/routes/login.js, server/utils/datastore/index.js, server/utils/security/generateJWT.js, server/utils/security/isAuthenticated.js
https://trello.com/c/gq5jNg9d
creating an enpoint to list notifications. As disussed, there will be separate restful api endpoints to create and update ownershipChangeRequest records. These endpoint will also create potentially multiple notification records, and more notifications may be created afterwards if the state of users or establishments change.
Rich also has specified pagination will be needed later, so I've added the backend facilities for it now. 
Here's a link the parent ticket that contains the wireframes for the piece of work as a whole. https://trello.com/c/22fJuVNO
=> New endpoint to list notifications for a user

server/data/notifications.js, server/routes/accounts/user.js
=> added a new endpoint to mark a notification a having been read

src/app/core/services/user.service.ts, src/app/features/reports/pages/workplaces/workplaces.component.ts
only apply filtering on wdf workplaces list page
=> bugfix | correct workplaces filtering

server/models/BulkImport/csv/workers.js
https://trello.com/c/VrJBRSvf
Handling ".0" half days, in addition to the existing ".5" validation for DAYSSICK
=> Hotfix V13.1 - merged down to develop

server/models/BulkImport/csv/workers.js
https://trello.com/c/NAMdCWwR
Aligning BU Worker and entity Qualification validation rules on qualification year.
=> HOTFIX Bulk Upload Qualification Year Validation

server/routes/establishments/bulkUpload.js
https://trello.com/c/nrKJgJ90
Training cross-validation on Worker DOB needs to handle the cases when worker association is not found and also when the worker doesn't have a DOB property.
Also fixed special case when training record has no `localeStId` and no `uniqueWorkerId` when trying to construct primary key.
=> Hotfix bu training x val dob

server/models/classes/establishment/properties/staffProperty.js
=> Ensure numberOfStaff is numeric before doing validation

server/models/classes/establishment/properties/staffProperty.js
Another few P1 defects to go live
=> Rel v1.13 hotfix to Live branch for pre prod

server/models/classes/establishment/properties/staffProperty.js
https://trello.com/c/K07LEvfo
https://trello.com/c/nrKJgJ90
Deployed to preprod.
Accepted in preprod.
Scheduled for live deployment.
=> Rel v1.13 hotfix merge to develop

server/models/classes/establishment/properties/staffProperty.js
https://trello.com/c/S1ppD7YK
Dave Dawson said he wants this in dev, so it can then be taken to live today.
So PR to merge the hotfix to dev.
=> Rel v1.13 hotfix merge to develop - BU Delete Primary

server/models/BulkImport/BUDI/index.js, server/models/BulkImport/csv/establishments.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/routes/accounts/user.js, server/routes/registration.js, server/routes/testOnly/location.js, server/sendEmail.js
=> Remove unneccessary debug logging

server/models/classes/establishment.js, server/models/classes/wdfCalculator.js, server/models/establishment.js
=> calculate wdf establishments status dynamically

server/models/classes/wdfCalculator.js
=> get a plain object from sequelize

server/models/classes/establishment.js, server/models/classes/wdfCalculator.js
https://trello.com/c/A5oyFId9
The wdf calculations were previously looking at archived workers. This change filters them out
=> only include non archived worker in the wdf calculations

package.json, server/models/BulkImport/csv/establishments.js, server/models/classes/establishment/properties/staffProperty.js, server/routes/establishments/bulkUpload.js
Merging two P1 fixes from 1.13  hotfix to Live branch
=> Rel v1.13 hotfix

server/data/ownership.js, server/models/classes/establishment.js, server/routes/establishments/ownershipChange.js
=> New endpoint to approve/deny an ownership change request with reason text

server/models/classes/wdfCalculator.js
https://trello.com/c/fJnzeNcL
The transaction that updates the overallWdfEligibility field on the establishment was auto committing after the first database query. I've now changed this to enable the transaction to be committed/rolled back at the proper time
=> Don't use sequelize transaction callback function

server/models/classes/establishment.js, server/models/classes/wdfCalculator.js, server/routes/establishments/index.js
https://trello.com/c/73vAATTU
The overall wdf eligibility check was testing whether the establishment fields have ever been valid in the current financial year, not whether they were together with all valid staff.
I'm using a previously unused establishment column "EstablishmentWdfEligibility" to store a copy of last wdf eligibility date which is not audited so can be blanked out if the est fields aren't valid.
As part of this ticket I've also run the establishment business object through a linter and static analysis tool called "semistandard" to clean up the code a bit and to find the usage of undeclared variables
=> Correct the eligibility check for workplace fields

server/models/cache/singletons/permissions.js, server/models/classes/establishment.js, server/routes/establishments/permissions.js
…ssionsForSubsidiary and canChangeDataOwner
=> Create canChangePermissionsForSubsidiary and canChangeDataOwner permissions property.

src/app/core/model/establishment.model.ts, src/app/core/services/establishment.service.ts, src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.html, src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.ts, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.ts, src/app/shared/components/change-data-owner-dialog/change-data-owner-dialog.component.html, src/app/shared/components/change-data-owner-dialog/change-data-owner-dialog.component.ts
=> FE-New endpoint to request data ownership with permissions

src/app/shared/components/workplace-summary/workplace-summary.component.html
Make the frontend pick up and display employer type
=> Make the frontend display not meeting requirements for employerType

index_staging.html, index_uat.html, src/app/app.component.ts
I swapped out the GTM script on all the versions of the HTML because this can be sorted in GTM itself.
=> Swapped GA to GTM

server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/k3Mzk94m
999 and 0 should be allowed for contract hours.
I've also run some of the bulk upload related code through the semistandard linter to make the code easier to read.
=> Amend bulk upload contract hours validation business logic

server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/routes/establishments/bulkUpload.js
=> rollback contract hours previous files

server/models/classes/establishment.js
This is to make bulk upload work correctly again
=> re-added missing field

src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.ts
Promoting to staging. Pull Request #1520 to fix bulk upload issue
=> Develop. Promoting to staging. Pull Request #1520 to fix bulk upload issue

server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/k3Mzk94m
The code had a mixture of logic and and or (&& and ||), and the order of the tests was incorrect. I've re written these functions and applied linting to the relevant files.
the two functions I've re-written are _validateContHours  and _validateAvgHours
=> fix conthours/avghours logic for bulk upload

server/models/BulkImport/csv/workers.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/JnTcZOra
The logic was looking for 'yes', but 'Yes' should have been there (note the capital Y). I've also linted some of the bulk upload files
=> Bulk upload not downloading the correct data for AMHP question

server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
About to promote changes made to Dev to Staging. This is to fix Bulk Upload Contracted hours not allowing 0
Bulk Upload Contracted hours not allowing 999 (not known)
Bulk Upload AMHP not populating download file and when file is updated not uploading AMHP back into the database
=> Develop to Stage 

server/data/ownership.js, server/routes/establishments/ownershipChange.js, server/utils/security/isAuthenticated.js
=> POST API for Cancel Ownership request.

server/data/notifications.js, server/data/ownership.js, server/routes/accounts/user.js, server/routes/establishments/ownershipChange.js
=> new endpoint to get individual notification details

server/data/ownership.js, server/routes/establishments/ownershipChange.js, src/app/core/model/establishment.model.ts, src/app/core/model/my-workplaces.model.ts, src/app/core/services/establishment.service.ts, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.html, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.ts, src/app/shared/components/cancel-data-owner-dialog/cancel-data-owner-dialog.component.html, src/app/shared/components/cancel-data-owner-dialog/cancel-data-owner-dialog.component.spec.ts, src/app/shared/components/cancel-data-owner-dialog/cancel-data-owner-dialog.component.ts, src/app/shared/components/change-data-owner-dialog/change-data-owner-dialog.component.ts, src/app/shared/shared.module.ts
https://trello.com/c/6wKqRuCs/
=> Cancel swap data owner request.

server/routes/establishments/ownershipChange.js, src/app/features/workplace/workplace-info-panel/workplace-info-panel.component.ts
https://trello.com/c/22fJuVNO/
=> Error handling for cancel swap ownership request.

server/config/accessibility.yaml, server/config/config.js, server/config/development.yaml, server/config/localhost.yaml, server/config/preproduction.yaml, server/config/production.yaml, server/config/test.yaml, server/models/classes/establishment.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/models/index.js, server/routes/establishments/bulkUpload.js
This is to help reconcile the deviations between branches we have currently to help prevent conflicts or 'missing' code later.
=> Live fixes to test

server/routes/reports/localAuthorityReport/user.js
=> Fixed: LA Report - Missing Sickness for Pool/Bank/Agency

server/models/BulkImport/csv/workers.js
=> Make average hours valid if worker is on a zero hours contract

server/routes/establishments/bulkUpload.js
https://trello.com/c/QgCEoU60
I've amended the bulk upload validation to use a chunked transfer response and periodically output a space character to keep the http socket alive. This won't make the response any quicker, but should prevent it from being closed due to a timeout
=> Trickle feed validation

server/models/BulkImport/csv/workers.js
=> Store ahmp correctly from bulk upload

server/utils/security/isAuthenticated.js
https://trello.com/c/pBiexzUa/51-subsidiary-link-to-change-data-ownership
=> Corrected the typo now changeownership API will work

server/models/classes/establishment.js
https://trello.com/c/pBiexzUa/51-subsidiary-link-to-change-data-ownership
=> Added OwmershipRequested field to JSON response.

server/models/classes/worker.js, server/routes/establishments/bulkUpload.js, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
=> Bulk upload trickle feed completion

src/app/core/model/establishment.model.ts, src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/features/login/login.component.ts
Fix for WDF report and bulk upload issues
=> Fix for WDF report and bulk upload issues

server/routes/establishments/bulkUpload.js
https://trello.com/c/QgCEoU60
Now that we've already applied "trickle feed" processing to the bulk upload validation and completion steps, it seems that we need to additionally apply it to the csv export step.
That is what this change is for
=> trickle feed for csv export in bulk upload

server/routes/establishments/bulkUpload.js
switched the bulkUpload csv export to stream the data
=> trickle feed for csv export in bulk upload (#1581)

server/routes/establishments/bulkUpload.js
I've also re-added the set timeout lines to control how long express js waits, and now frequently flush the response data sent out as well.
I don't think these will affect anything as I believe the limiting timeout is now the one on cloudfoundry, but these changes rule them out from being involved.
=> added more logging to bulk upload

server/routes/establishments/bulkUpload.js
Added more logging to bulk upload (#1589)
=> added more logging to bulk upload (#1589)

server/routes/admin/approval/index.js
(cherry picked from commit 1654baf3f8967bc21ca33be1961ab0078dfa7acd)
=> Fixed typo where establishments weren't getting updated when approved

server/data/ownership.js, server/routes/establishments/ownershipChange.js
https://trello.com/c/EjUrYnoc/53-swap-ownership-approve-request
=> Bug ej ur ynoc/53 swap ownership approve request

server/data/ownership.js, server/routes/accounts/user.js
this will fetch notification receiver name
=> this will fetch notification receiver name

server/data/notifications.js, server/data/ownership.js, server/routes/accounts/user.js, server/routes/establishments/ownershipChange.js, server/routes/ownershipRequest/index.js
=> Fixed requesterUserUID by adding a new column in Notifications table.

src/app/features/notifications/notification/notification.component.ts
https://trello.com/c/HPxMyT3B/29-error-when-trying-to-approve-swap-ownership-request
=> Fixed-error-when-trying-to-approve-swap-ownership-request

server/data/ownership.js, server/models/classes/establishment.js, server/routes/establishments/dataPermissions.js, server/routes/establishments/index.js, server/routes/ownershipRequest/index.js, src/app/core/services/establishment.service.ts
=> Completed with Transfer ownership and Data Permissions

server/routes/ownershipRequest/index.js
=> Updated notification api

server/models/classes/establishment.js, server/routes/ownershipRequest/index.js
https://trello.com/c/F1VXqNLm/25-16-parent-and-subsidiaries-swap-ownership-of-data-between-workplaces-workplace-b-receives-request
=> Added checks for correct swap ownership

src/app/features/forgot-your-password/confirmation/confirmation.component.spec.ts, src/app/features/notifications/notification/notification.component.spec.ts, src/app/features/reports/components/wdf-eligibility/wdf-eligibility.component.spec.ts, src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.spec.ts, src/app/features/workers/mental-health-professional/mental-health-professional.component.spec.ts, src/app/features/workers/weekly-contracted-hours/weekly-contracted-hours.component.spec.ts, src/app/features/workplace-find-and-select/select-workplace/select-workplace.spec.ts, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.spec.ts, src/app/features/workplace/question/question.component.spec.ts, src/app/features/workplace/vacancies/vacancies.component.spec.ts, src/app/shared/components/messages/messages.component.spec.ts
Enabled unit test cases for FE
=> Fe fixed unit test cases

server/models/BulkImport/csv/establishments.js, server/routes/establishments/bulkUpload.js
=> adding locking around the bulk upload endpoints

src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/features/notifications/notification/notification.component.ts, src/app/shared/components/staff-records-tab/staff-records-tab.component.ts, src/app/shared/components/user-accounts-summary/user-accounts-summary.component.ts, src/app/shared/components/workplace-summary/workplace-summary.component.ts
Fixed swap ownership refresh issue and optimized code
=> Fe fixed swap ownership issues

server/models/BulkImport/csv/establishments.js
=> Apply budi mapping to error message

server/models/BulkImport/csv/establishments.js, src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/features/forgot-your-password/confirmation/confirmation.component.spec.ts, src/app/features/notifications/notification-cancelled/notification-cancelled.component.html, src/app/features/notifications/notification/notification.component.spec.ts, src/app/features/notifications/notification/notification.component.ts, src/app/features/reports/components/wdf-eligibility/wdf-eligibility.component.spec.ts, src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.spec.ts, src/app/features/workers/mental-health-professional/mental-health-professional.component.spec.ts, src/app/features/workers/weekly-contracted-hours/weekly-contracted-hours.component.spec.ts, src/app/features/workplace-find-and-select/select-workplace/select-workplace.spec.ts, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.spec.ts, src/app/features/workplace/question/question.component.spec.ts, src/app/features/workplace/vacancies/vacancies.component.spec.ts, src/app/shared/components/messages/messages.component.spec.ts, src/app/shared/components/staff-records-tab/staff-records-tab.component.ts, src/app/shared/components/user-accounts-summary/user-accounts-summary.component.ts, src/app/shared/components/workplace-summary/workplace-summary.component.ts, src/assets/images/tick-icon.svg
Bring changes from bevelop to test. To address:
-changes in the heading
-Swap ownership
-budi mapping to error message
=> Develop to Test:Swap ownership

server/routes/ownershipRequest/index.js
=> CORRECTED Data PERMISSION

server/data/ownership.js, server/routes/establishments/ownershipChange.js, server/routes/ownershipRequest/index.js, src/app/features/notifications/notification-cancelled/notification-cancelled.component.html, src/app/features/notifications/notification/notification.component.html, src/app/features/notifications/notification/notification.component.ts, src/app/shared/components/staff-summary/staff-summary.component.html, src/app/shared/components/staff-summary/staff-summary.component.ts
Test from Develop: Swap Owensership Fix
=> Test from Develop: Swap Owensership Fix

server/models/BulkImport/csv/workers.js
=> fixed issue in bulk upload that was introduced by cross validations

src/app/shared/components/staff-summary/staff-summary.component.ts
(cherry picked from commit 580825e8cdb0e3921bfd6774ab71e9d3f9eaffb5)
=> Fixed case insensitive_issue

src/app/features/dashboard/dashboard.component.ts, src/app/features/notifications/notification/notification.component.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.ts
Added error handling to few files.
=> Added error handling to few files

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
https://trello.com/c/n8oB9pyL
Bulk upload validation for REGTYPE
=> Bulk upload validation for REGTYPE

src/app/core/services/worker.service.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.ts, src/app/features/workers/select-record-type/select-record-type.component.ts, src/app/features/workers/training-qualifications-record/qualifications/qualifications.component.html, src/app/features/workers/training-qualifications-record/qualifications/qualifications.component.ts, src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.html, src/app/features/workers/training-qualifications-record/training/training.component.html, src/app/features/workers/training-qualifications-record/training/training.component.ts
https://trello.com/c/ijeUjZZ6/6-3-training-and-qualifications-staff-record-summary
=> Training and Qualifications - Staff Record Summary

src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.html, src/app/features/workers/add-edit-training/add-edit-training.component.ts
=> ADDED ROUTES FOR CANCEL

src/app/features/workers/select-record-type/select-record-type.component.ts
=> FE-ADDED-CHECKS-FOR-RPUTES

server/models/BulkImport/csv/establishments.js
[Validations for testing (1).xlsx](https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/files/3902122/Validations.for.testing.1.xlsx)
=> Amendments based upon Roy's feedback

server.js, server/models/classes/establishment.js, server/routes/parentSubLinking/index.js, server/test/unit/models/establishment.spec.js, server/utils/datastore/index.js
Added logic to fetch all parent name and postcode.
https://trello.com/c/8RIBCbtd/8-10-parent-and-subsidiaries-subsidiary-linking-to-parent-request-modal
=> Added logic to fetch parent name and postcode.

server/data/parentWDFReport.js, server/routes/reports/wdf/parent.js
https://trello.com/c/VlPBCEkP/31-parent-wdf-not-seeing-all-staff-records
=> Changed functionality : In case of parent establishment, removed filter. Now all parent's workplace and worker will be there inside report.

server/models/cache/singletons/permissions.js, server/routes/establishments/permissions.js
=> Added new permission type

server/models/cache/singletons/permissions.js, server/routes/establishments/permissions.js
=> Be added new permission type

server/data/parentWDFReport.js, server/routes/reports/wdf/parent.js
https://trello.com/c/iB53hDxE/32-parent-wdf-inconsistent-answers-for-hours
=> Changed sicknessdays, nationality value, hours and recruitment source values functionality

server/data/parentWDFReport.js, server/routes/reports/wdf/parent.js, src/app/core/guards/auth/auth.guard.ts, src/app/core/guards/migrated-user/migrated-user.guard.ts, src/app/core/services/auth.service.ts, src/app/core/services/user.service.ts, src/app/features/login/login.component.ts, src/app/features/migrated-user-terms-conditions/migrated-user-terms-conditions.component.ts
=> Test from Develop: Parent WDF

server/data/linkToParent.js, server/models/classes/establishment.js, server/models/establishment.js, server/routes/establishments/index.js, server/routes/establishments/linkToParent.js, server/test/unit/models/establishment.spec.js
https://trello.com/c/8RIBCbtd/8-10-parent-and-subsidiaries-subsidiary-linking-to-parent-request-modal
=> LINK TO PARENT CHANGES

server/data/linkToParent.js, server/models/classes/establishment.js, server/routes/establishments/linkToParent.js, server/utils/datastore/index.js
https://trello.com/c/dyCn6eEH/10-10-parents-and-subsidiaries-cancelling-a-request-to-link-to-a-parent
=> CANCEL LINK TO PARENT

src/app/features/workers/add-edit-training/add-edit-training.component.ts
(cherry picked from commit 05d8c5784db652854ac30c44cf219119ed272a83)
=> Changes validation message

server/routes/reports/wdf/parent.js, server/routes/reports/wdf/template/xl/sharedStrings.xml
Remove -sc word from asc-wds-sc and fixed an iisue related to utilisation and capacity calculations.
=> Remove -sc word from asc-wds-sc and fixed an iisue related to utilisation and capacity calculations.

server/routes/reports/wdf/parent.js
Fixed capacity and utilisation issue.
=> Fixed capacity and utilisation issue.

server/routes/reports/wdf/parent.js
(cherry picked from commit 489d574c692c8164a7153f4a8667c5b9c0317ac1)
=> Fixed capacity and utilisation issue. (#1772)

src/app/features/workers/training-qualifications-record/training/training.component.ts
(cherry picked from commit 92795063d8eca14f22c63427035026ebf52b5c03)
=> training record order by

server/routes/accounts/user.js, server/routes/admin/search/establishments/index.js, src/app/features/search/search.component.html, src/app/features/search/search.component.ts
This reverts commit 0eacddfb8c077d47c85e0ad67904a3c1410340a5.
=> Revert "admin notification view"

package.json, server/config/config.js, server/data/parentWDFReportLock.js, server/routes/reports/wdf/parent.js, server/test/unit/routes/reports/wdf/parent.spec.js, src/app/core/model/wdf.model.ts, src/app/core/services/report.service.ts
=> Polling on wdf report

src/app/shared/components/staff-records-tab/staff-records-tab.component.html, src/app/shared/components/staff-records-tab/staff-records-tab.component.ts, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.ts
(cherry picked from commit 018a110474b0f9b56346da1ac81d27e821fec2ca)
=> Fix  for parent workers appearing in subsidiaries worker summary (#1802)

server/data/linkToParent.js, server/models/cache/singletons/permissions.js, server/routes/establishments/linkToParent.js, server/routes/establishments/permissions.js
de link parent association flag
=> DELINK PARRENT ASSOICATION FLAG

server/config/config.js, src/app/shared/components/staff-records-tab/staff-records-tab.component.html, src/app/shared/components/staff-records-tab/staff-records-tab.component.ts, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.ts
Bugfix/caching issue stage move to Test
=> Bugfix/caching issue stage move to Live

server/models/cache/singletons/permissions.js
=> BE NEW PERMISSION CHECK

src/app/shared/components/link-to-parent-remove/link-to-parent-remove-dialog.component.html
(cherry picked from commit a0e452d9f46b11d1d404c4f116439cfecbf5e899)
=> Corrected Typo

src/app/core/services/auth-interceptor.ts
https://trello.com/c/Mzl5ADRc/29-5-9407-signing-out-when-clicking-on-a-worker-record
=> Commented 403 to check if it works.

server/routes/reports/trainingReport/training.js
https://trello.com/c/2BYdghPF/30-training-report-defects
=> https://trello.com/c/2BYdghPF/30-training-report-defects

server/routes/reports/trainingReport/training.js, src/app/core/services/report.service.ts
Training Report from Develop to Test for 3.1
=> Training Report from Develop to Test for 3.1

server/routes/reports/trainingReport/training.js
Fix for training report for 3.1
=> Fix for training report for 3.1

server/routes/reports/trainingReport/training.js, src/app/core/services/report.service.ts
Fix for Training Report for 3.1 (to live)
=> Fix for Training Report for 3.1 (to live)

src/app/features/workers/move-worker-dialog/move-worker-dialog.component.html, src/app/features/workers/staff-record/staff-record.component.html, src/app/features/workers/training-qualifications-record/training-and-qualifications-record.component.html, src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html, src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html
=> UI CHANGES (#1901)

server/models/classes/training.js
https://trello.com/c/iBRwV2k5/17-4-14822-no-error-message-when-entering-a-training-name-of-less-than-3-characters
=> Changed BU validation

server/routes/reports/trainingReport/training.js, src/app/features/add-workplace/regulated-by-cqc/regulated-by-cqc.component.ts
Merge Develop into Test for 3.2 with fixes (Training Report, Workplace Navigation, Consequential Update)
=> Merge Develop into Test for 3.2 with fixes (Training Report, Workplace Navigation, Consequential Update)

src/app/features/workers/move-worker-dialog/move-worker-dialog.component.ts
https://trello.com/c/1fYdfd21/46-transfer-worker-unable-to-move-worker-to-a-parent
=> transfer-worker-unable-to-move-worker-to-a-parent

server/models/cache/singletons/permissions.js, server/routes/establishments/permissions.js
Added canDownloadWdfReport flag in permission.
=> BE added canDownloadWdfReport flag in permission

server/routes/reports/wdf/parent.js
This reverts commit 637c0f1b08efdd5dcaea67791868917dc4ff0136.
=> Revert "Enabled WDF logging"

package.json
This reverts commit 775ee9bc73ab357dc3a02ddce7012fa1db6586ad.
=> Revert "Upgraded old space to 8gb"

server/data/parentWDFReport.js, server/models/classes/establishment.js, server/models/classes/training.js, server/models/classes/user.js, server/models/worker.js, server/routes/accounts/user.js, server/routes/admin/registrations/index.js, server/routes/admin/unlock-account/index.js, server/routes/establishments/bulkUpload.js, server/routes/login.js, server/routes/reports/localAuthorityReport/user.js, server/routes/reports/trainingReport/training.js, server/routes/reports/wdf/parent.js, src/app/core/guards/bulk-upload/bulk-upload.guard.ts, src/app/core/model/worker.model.ts, src/app/core/services/bulk-upload.service.ts, src/app/core/services/user.service.ts, src/app/features/add-workplace/regulated-by-cqc/regulated-by-cqc.component.ts, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts, src/app/features/login/login.component.ts, src/app/features/reports/pages/workplaces/workplaces.component.ts, src/app/features/search/search.component.html, src/app/features/workers/add-edit-training/add-edit-training.component.ts, src/app/features/workers/move-worker-dialog/move-worker-dialog.component.ts, src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.ts
Merge Develop into Test for Release 3.4
=> Merge Develop into Test for Release 3.4

server/data/parentWDFReport.js, server/routes/reports/wdf/parent.js
This reverts commit 1152a9dbc745dc6f3cc2b57e9ac79b3d9439e061.
=> Revert "Added some code optimizations for parent wdf report. (#1963)"

src/app/core/model/worker.model.ts, src/app/features/dashboard/dashboard.component.ts, src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.ts, src/app/shared/components/training-info-panel/training-info-panel.component.html, src/app/shared/components/training-info-panel/training-info-panel.component.ts
https://trello.com/c/CFagAJGk/4-10-mandatory-training-missing-status
=> Mandatory Training - Missing Status

server/models/BulkImport/csv/establishments.js, server/routes/establishments/bulkUpload.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js, src/app/features/bulk-upload/files-upload/files-upload.component.ts
Validations for the following:
Fixed: If REGTYPE is 2 (CQC) but main service is not a CQC regulated service (Excludes Head office service (72)
New: If LOCATIONID is already in use in the database by a different workplace
New: If workplace changes from CQC to non CQC and has an RM (04) vacancy
=> Bulk upload validations

server/data/parentWDFReport.js, server/routes/reports/wdf/parent.js
https://trello.com/c/LJRNYGGQ/40-16488-download-wdf-report-not-showing-correct-data
=> Fixed :: Download WDF report not showing correct data

server/models/classes/establishment.js, server/models/worker.js
(cherry picked from commit 5ef946f445c71656efbdda4ab58e69f33516951c)
=> Fixed :: Duplicate Local Identifiers are not downloading in BU (#1966)

server/models/classes/mandatoryTraining.js, server/routes/establishments/mandatoryTraining/index.js
https://trello.com/c/cSlN8NaV/6-8-training-and-quals-view-all-mandatory-training
=> Added POST :: /mandatoryTraining/all API for View all mandatory training

server/models/classes/establishment.js
https://trello.com/c/VYstw5Qr/32-duplicate-local-identifiers-are-not-downloading-in-bu
=> Fixed an issue on this ticket.

server/routes/registration.js, src/app/core/services/registration.service.ts, src/app/features/account/confirm-account-details/confirm-account-details.ts, src/app/features/registration/confirm-account-details/confirm-account-details.component.ts, src/app/features/registration/regulated-by-cqc/regulated-by-cqc.component.ts
https://trello.com/c/VDdEVe8j/42-registrations-failing-for-head-offices
=> Dnlv v in6

server/data/parentWDFReport.js, server/routes/reports/wdf/parent.js, server/utils/datastore/index.js
https://trello.com/c/LJRNYGGQ/57-16488-download-wdf-report-not-showing-correct-data
=> Fixed CompletedWorkerRecords issue.

src/app/features/dashboard/home-tab/home-tab.component.html
(cherry picked from commit bed1042657bc3e080b344c6e4db017f1de722037)
=> Changed view report content

server/routes/reports/wdf/parent.js
https://trello.com/c/B2nfzhP8/77-17979-download-wdf-including-sickness-for-agency-and-pool-bank-staff
=> Fixed :: https://trello.com/c/B2nfzhP8/77-17979-download-wdf-including-sickness-for-agency-and-pool-bank-staff

server/models/classes/establishment.js, src/app/core/model/establishment.model.ts, src/app/features/reports/pages/wdf/wdf.component.ts
checks if all wdf essential data-fields are complete & last eligibility date is before the effective date
=> Updating rules for when Confirm button should be shown

server/models/classes/mandatoryTraining.js, src/app/features/add-mandatory-training/add-mandatory-training.component.html, src/app/features/add-mandatory-training/add-mandatory-training.component.ts, src/app/features/add-mandatory-training/add-mandatory-training.module.ts, src/app/features/add-mandatory-training/remove-all-selections-dialog.component.html, src/app/features/add-mandatory-training/remove-all-selections-dialog.component.ts
Upon clicking on this button:
- A modal will appear to confirm action.
- Upon confirmation, the modal will close with no navigation.
- The form will be reset to the original state. (I.e. no mandatory trainings)
- All mandatory trainings for the workplace will have been removed from the database.
=> Adds Remove all selections button to add mandatory changes screen

src/app/features/add-mandatory-training/add-mandatory-training.component.html, src/app/features/add-mandatory-training/add-mandatory-training.component.ts, src/app/features/add-mandatory-training/remove-all-selections-dialog.component.html
Changes design of add mandatory training screen to conform with new acceptence criteria and comments on https://trello.com/c/M0tTmv53/53-mandatory-training-remove-mandatory-training-selections.
=> Add Mandatory Training Redesign

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
* Updated the error to a warning
* Updated the unit test to match the change to an error
=> Changed validation for postcode not found from warning to error

src/app/features/add-mandatory-training/add-mandatory-training.component.ts
Following a conversation with Jackie, she asked that the errors were updated.
* Updated error messages for mandatory training
=> Mandatory training errors updated

src/app/core/services/trainingStatus.service.ts
After testing on Dev noticed an error
=> fixing broken logic

server/routes/establishments/bulkUpload.js, server/test/unit/routes/establishments/bulkUpload.spec.js
Edited the error message and added unit tests
=> Updated the training error message to remove the Subsidiary 3 text

src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html, src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html, src/app/shared/components/trianing-link-panel/trianing-link-panel.component.html
=> View training layout fixes

server/models/BulkImport/BUDI/index.js, server/test/unit/mockdata/workers.js, server/test/unit/models/Bulkimport/csv/workers.spec.js
=> Fix codes for Djibouti, Kosovo and Laos.

src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html, src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.ts
=> Updated link text from More to Open and Less to Close

.sequelizerc, migrations/20200519170545-create_approvals_table.js, package-lock.json, package.json, server/config/sequelize.js
**Work done**
- Added `Sequelize-cli` for generating and running migrations
- Added migration for `Approvals`
=> Feat: Add schema for Become a Parent Request

migrations/20200519170545-create_approvals_table.js
**Work done:**
- Added ID and UUID to Approvals table
=> Fix: Add ID and UUID columns to approvals table

server/models/BulkImport/csv/workers.js, server/models/classes/worker/properties/apprenticeshipTrainingProperty.js, server/test/unit/mockdata/workers.js, server/test/unit/models/Bulkimport/csv/workers.spec.js, server/test/unit/models/classes/worker/properties/apprenticeshipTrainingProperty.spec.js
=> Fixed a bug where downloading your Bulk Upload files the apprenticeship value was 999 if null

server/models/approvals.js
**Work done**
- Added the model for the Approvals table
=> Feat: Approvals Model

src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html
**Work done**
- Updated the copy when there are no training records.
=> Fix: Updated copy when there's no Staff training records

server.js, server/models/approvals.js, server/models/user.js, server/routes/approvals/becomeAParent.js, server/routes/approvals/index.js, server/test/unit/routes/approvals/becomeAParent.spec.js
**Work done**
- Added endpoint to create a BecomeAParent Approval request
- Added functions to Approvals model for abstracting queries
- Added tests
=> Feat: Add become a parent endpoint

server/models/cache/singletons/permissions.js, server/routes/establishments/permissions.js, server/test/factories/models.js, server/test/factories/user.js, server/test/unit/models/cache/singletons/permissions.spec.js, server/test/unit/routes/establishments/permissions.spec.js, src/app/core/model/permissions.model.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.ts
Added a can become a parent permission and show the link on the home page based on that permission. 
=> Become a parent permissions and link on home page

server/models/approvals.js, server/routes/admin/parent-approval/index.js, server/routes/approvals/becomeAParent.js, src/app/core/services/parent-requests.service.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.ts
Had problems with the server/test/integration/routes/admin/parent-approval/index.spec.js intergation tests. @chadtomkiss-madetech  and I had a look at them but had various issues with them.   Will look looked at in a subsequent PR
=> Fixing bugs on the Become a Parent branch

src/app/features/workers/add-edit-training/add-edit-training.component.ts
=> Fixed bug where the add training page might not load correctly

src/app/features/dashboard/home-tab/home-tab.component.ts
**Issue**
The API to check the become a parent request requires the workplace id. 
However, when logged in as an admin, they may not be assigned to a workplace.
**Work done**
- Fixed the home tab component to check the workplace exists before working out workplace specific details
=> Fix: Admin home tab

src/app/shared/components/become-a-parent/become-a-parent-dialog.component.html
=> Updated modal message with typo

src/app/features/workers/add-edit-training/add-edit-training.component.ts
=> Changed the URL depending on your previous location on Training save

src/app/features/notifications/notification-become-a-parent/notification-become-a-parent.component.html, src/app/features/notifications/notification-become-a-parent/notification-become-parent.component.spec.ts
=> Updated copy on the become a parent notification

src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.html, src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.ts
=> Fixed bug where pending workplaces weren't been shown without at least 1 workplace

migrations/20200528153134-IsRegulated.js, package.json, server/models/classes/establishment/establishmentProperties.js, server/models/classes/establishment/properties/isRegulatedProperty.js, server/models/establishment.js, server/test/unit/models/classes/establishment/establishmentProperties.spec.js, server/test/unit/models/classes/establishment/properties/isRegulatedProperty.spec.js
=> Added auditing to the isRegulated field

migrations/20200603104056-update_approvals_enum.js, package-lock.json, package.json, server/models/approvals.js
added migration file
added enum to backend model
added sequelize-replace-enum-postgres
- [ x ] No, they are not required for this change. ( we dont need tests for this right?)
=> Adding Enum CqcStatusChange

src/app/features/reports/pages/reports/reports.component.html
**Work done**
- Added copy to explain the changes to the WDF fund being re-directed to support rapid staff training as a response to COVID-19.
- Commented out details section for explaining the WDF fund (to be added back in later)
=> Hotfix: WDF copy for COVID-19

src/app/features/reports/pages/reports/reports.component.html
**Work done**
- Brought in the hot fix commit from #2193 into develop
=> Add PR #2193 hotfix to Develop

server/routes/establishments/mainService.js, server/routes/establishments/services.js, server/test/factories/models.js, server/test/unit/utils/correctCapacities.spec.js, server/utils/correctCapacities.js
- Added a new util for generating the correct capacities
- Added the util to the endpoints for changing a main service and other services
=> Remove unused capacity values

migrations/20200528153134-IsRegulated.js, package.json, server/models/classes/establishment/establishmentProperties.js, server/models/classes/establishment/properties/isRegulatedProperty.js, server/models/establishment.js, server/routes/establishments/mainService.js, server/routes/establishments/services.js, server/routes/locations.js, server/routes/workerTrainingCategories.js, server/test/factories/models.js, server/test/unit/models/classes/establishment/establishmentProperties.spec.js, server/test/unit/models/classes/establishment/properties/isRegulatedProperty.spec.js, server/test/unit/routes/locations.spec.js, server/test/unit/routes/trainingCategories/index.spec.js, server/test/unit/utils/correctCapacities.spec.js, server/transformers/trainingCategoryTransformer.js, server/utils/correctCapacities.js, src/app/features/reports/pages/reports/reports.component.html
=> Deploy Staging to Preprod 

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
=> Fixing error when mainservice isnt given

server/test/unit/routes/establishments/mainService.spec.js
=> Updated test for CQC to Non CQC

src/app/features/workplace/select-main-service/select-main-service-cqc.component.ts
Probably best to not think too hard about the fix.
=> Fixes tests for CQC Question component

server/models/cache/singletons/services.js, server/routes/establishments/mainService.js, server/test/unit/routes/establishments/mainService.spec.js, server/utils/correctServices.js, src/app/shared/components/workplace-summary/workplace-summary.component.html
**Work done**
- Fixed issue where the Change link for Main Service wasn't going to the correct URL
- Made sure `allMyServices` always returns an array
- Fixed `.send()` to `.json()` to use correct response headers
- Fixed tests for `setMainService`
=> Fix: Issues with non CQC to CQC flow

src/app/features/workplace/select-main-service/select-main-service-cqc.component.html
=> Added error message for radio on select if cqc reg for main service

src/app/features/workplace/view-my-workplaces/view-my-workplaces.component.html, src/app/shared/components/user-accounts-summary/user-accounts-summary.component.html, src/app/shared/components/workplace-summary/workplace-summary.component.html, src/assets/scss/components/_panel.scss, src/assets/scss/components/_tables.scss
- [x ] No, I found it difficult to test
=> Cqc padding

src/app/features/workplace-find-and-select/select-main-service/select-main-service.ts, src/app/features/workplace/select-main-service/select-main-service-cqc.component.html, src/app/shared/components/submit-exit-buttons/submit-exit-buttons.component.html
**Work done**
- Changed "Cancel" to "Exit" for consistency
- Fixed baseline alignment of Exit link
- Fixed error message to not say Please
=> Fix: Main Service UI updates

server/models/BulkImport/csv/training.js, server/test/unit/models/Bulkimport/csv/training.spec.js
=> Fix bug where training fails validation if ACCREDITED is blank.

src/app/features/add-workplace/select-workplace-address/select-workplace-address.component.html, src/app/features/registration/select-workplace-address/select-workplace-address.component.html, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.html, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.html, src/app/features/workers/wdf-worker-confirmation-dialog/wdf-worker-confirmation-dialog.component.html, src/app/features/workplace/wdf-workplace-confirmation-dialog/wdf-workplace-confirmation-dialog.component.html, src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html, src/app/shared/components/staff-record-summary/basic-record/basic-record.component.ts, src/app/shared/components/staff-record-summary/employment/employment.component.html, src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html, src/app/shared/components/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html, src/assets/scss/components/_summary-list.scss
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2222
=> Revert "Feat/staff summary redesign"

server/routes/establishments/bulkUpload.js, server/test/unit/routes/establishments/bulkUpload.spec.js
=> Added slack alert if there's a large bulk upload

src/app/features/add-workplace/select-workplace-address/select-workplace-address.component.html, src/app/features/registration/select-workplace-address/select-workplace-address.component.html, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.html, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.html, src/app/features/workers/wdf-worker-confirmation-dialog/wdf-worker-confirmation-dialog.component.html, src/app/features/workplace/wdf-workplace-confirmation-dialog/wdf-workplace-confirmation-dialog.component.html, src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html, src/app/shared/components/staff-record-summary/basic-record/basic-record.component.ts, src/app/shared/components/staff-record-summary/employment/employment.component.html, src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html, src/app/shared/components/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html, src/assets/scss/components/_summary-list.scss
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2229
=> Revert "Revert "Feat/staff summary redesign""

package.json, proxy.conf.json
=> Added Live Reload to `npm run server` command

src/app/shared/components/staff-records-tab/staff-records-tab.component.html
=> adding new line

src/app/core/guards/auth/auth.guard.ts, src/app/core/services/auth-interceptor.ts, src/app/features/login/login.component.ts, src/app/features/workers/add-edit-training/add-edit-training.component.ts
I also removed the annoyingauth console logs as they are not needed anymore
- Removed auth console logs
- Fixed training cat bug
=> Fix for training categories on edge

server/test/unit/models/classes/establishment.spec.js
=> Skipped failing test

server.js, server/utils/logger.js
=> Fixes a bug for environment logging and config initialisation

server.js
=> Ignore IdSources, since we don't care about Amazon's trace ID.

server/aws/secrets.js
=> Do not crash if secrets don't exist.

server.js
=> '' is actually falsey, put something there.

lighthouserc.json
**Context**
There are presets that can assert a lot more things about our code, for example, do we have a meta description.
However they currently give 21 errors to address.
I have instead added the top level category assertions so that we can tell if our overall performance/accessibility etc has dropped.
**Work done**
- Set a min score for the categories we care about
=> Add performance checks to Lighthouse

.cfignore, package-lock.json, package.json
**Work done**
- Added express and Winston as production level deps
- Added cfignore to ignore node_modules/.git/.circleci directories
- Downgraded tslib for Angular 9
=> Fix: Deployment

server/routes/reports/localAuthorityReport/user.js, server/test/unit/routes/reports/localAuthorityReport/user.spec.js
- Removed limit of 1 from the select for first half of postcode
- Only returned la if only 1 in array
=> Updated the postcode lookup to only sho LA if only 1 returned

server/models/BulkImport/csv/establishments.js, src/app/core/services/bulk-upload.service.ts
**Work done**
- Updated validation messages for the Workplace CSV
- Updated validation message when the user has not uploaded both a Workplace and Staff CSV
- Updated validation message when the user uploads a file that is not a CSV or ZIP
=> Fix: BU validation messages for Workplaces

server/models/BulkImport/csv/workers.js
=> Fix: Error messages for Staff BU file

server/models/BulkImport/csv/training.js
=> Fix: Error messages for Training BU file

server/config/config.js
**Work done**
- Updated Share LA window to 2020 dates.
=> Fix: Share LA dates

src/app/features/login/login.component.html
**Work done**
- Fixed casing for Sign In link/button
=> Fix: Sign in casing

package-lock.json
=> package-lock change after running npm install during deployment

src/app/core/guards/bulk-upload/bulk-upload.guard.ts
- [x ] No, I found it difficult to test
=> fix for bug where refreshing the bulk upload page breaks

.circleci/config.yml, manifest.preprod.yml
**Work done**
- Removed unused `RFR_ROOT` environment variable
- Added `performance` as a required job to pass before deploying
- Added `manifest.preprod.yml` for pre prod deployments
- Added `sfcuatblue` deployment to CircleCI
- Includes manual hold approval step
=> Feat: Preprod deployment

.circleci/config.yml, manifest.prod.yml
**Work done**
- Add production deployment step
- Add `manifest.prod.yml`
- Update `npm run build:prod` to only run on tagged builds.
=> Feat: Add prod deploy config and manifest

src/app/features/reports/components/reports-header/reports-header.component.html, src/app/features/reports/pages/reports/reports.component.html
Redesign of the reports page
- [ x ] No, they are not required for this change
=> Adding styling

src/app/features/reports/components/reports-header/reports-header.component.html, src/app/features/reports/pages/reports/reports.component.html
Reverting PR as base branch is wrong.  should be test.  (anyway we can default it to test?)
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2329
=> Revert "Adding styling"

.circleci/config.yml, manifest.preprod.yml, manifest.prod.yml
**Work done**
- Added just the CircleCI config to the live branch
=> Feat: Add config for pre-prod/prod deployment to LIVE

.circleci/config.yml
**Issue**
We decided to deploy to pre-prod from the live branch, so that any fixes needed for pre-prod don't result in numerous releases.
=> Fix: Deploy to pre-prod from live branch

.circleci/config.yml
- [ x ] No, they are not required for this change
=> correcting path to dist

.circleci/config.yml
=> adding attach workplace

server/config/test.yaml
=> removing dsn from test env

server.js
- [ x ] No, they are not required for this change
=> explictly only allowing id as user info

server/config/sequelize.js
**Issue**
Although we were using the environment variable for database connection, we still need to specify that we want to use SSL.
I have also set which schema to create the migration table for pre-prod/prod
=> Hotfix: SSL / schema storage config for migrations

src/app/features/dashboard/dashboard.component.html, src/app/shared/components/benchmark-tile/benchmark-tile.component.html, src/app/shared/components/benchmark-tile/benchmark-tile.component.scss, src/app/shared/components/benchmark-tile/benchmark-tile.component.spec.ts, src/app/shared/components/benchmark-tile/benchmark-tile.component.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts, src/app/shared/shared.module.ts
=> Benchmarks Tile Component

.circleci/config.yml
=> Updated CircleCI config - removed dev and added benchmarks

manifest.benchmarks.yml
=> Created new manifest for benchmarks

server/config/benchmarks.yaml, server/config/config.js, server/config/sequelize.js
=> Added benchmarks database config 

src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.spec.ts
=> Changed tab order and only show Benchmarks Tab when CQC Registered

server/routes/establishments/bulkUpload.js
=> Feat/pte fte cbulkupload - adding missing param

server.js
=> adding sample rate for Honeycomb

.circleci/config.yml
=> Fix: Try halting the deployment if the workflow is for a PR

migrations/20200727140242-benchmarks.js, package.json
=> Created migration for new table for Benchmark data

migrations/20200810100725-updateBenchmark.js, server/models/benchmarks.js, server/models/establishment.js, server/models/services.js, server/routes/establishments/benchmarks/index.js, server/routes/establishments/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/core/model/benchmarks.model.ts, src/app/core/services/benchmarks.service.ts, src/app/core/test-utils/MockBenchmarkService.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
Getting actual data for Pay tile
=> Benchmarking - Getting actual data for Pay tile

server.js
=> removing performance tracing in sentry

server/models/services.js, server/models/worker.js, server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/core/model/benchmarks.model.ts, src/app/core/services/benchmarks.service.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
=> Benchmarking Qualifications tile: getting actual values into the tile

server/models/establishment.js, server/models/worker.js
making calls async
- [ x] No, they are not required for this change
=> Benchmarks Qualifications : bug fix

server/models/worker.js, server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js
=> Benchmarks Pay : Adding in missing params

server/models/establishment.js, server/models/establishmentJobs.js, server/models/worker.js, server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/core/model/benchmarks.model.ts, src/app/core/services/benchmarks.service.ts, src/app/core/test-utils/MockBenchmarkService.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
=> Benchmarks turnover: adding in actual values

server/models/worker.js, server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js
=> Benchmarks Qualifications Calculation fix

src/app/core/test-utils/MockBreadcrumbService.ts, src/app/features/workplace/view-workplace/view-workplace.component.html, src/app/features/workplace/view-workplace/view-workplace.component.spec.ts
=> Benchmarks: Allowing subsidiaries  to view Benchmarks

server/models/worker.js, server/test/unit/routes/establishments/benchmarks.spec.js
=> Benchmarks Qualifications : fixing merge conflict

server/models/establishment.js
=> Benchmarks: Bug fix - when there is no cssr data for a postcode

server/models/establishment.js, server/routes/admin/search/establishments/index.js, server/test/unit/routes/admin/search/establishments/index.spec.js, src/app/features/search/search.component.html, src/app/features/search/search.component.ts
**Work done**
- Refactored search establishment endpoint to use Sequelize for loading users etc
- Updated search component to show/hide more workplace information and list the Edit users for individual workplaces
=> Feat: Admin search workplaces

src/app/core/model/benchmarks.model.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
=> Benchmarks: fixing models to be more flexible. 

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/core/model/benchmarks.model.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.html, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.spec.ts, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.ts, src/app/shared/shared.module.ts, src/assets/scss/modules/_utils.scss
=> Benchmarks: Show the comparison group header text

src/app/core/services/auth.service.ts
- [ x ] No, they are not required for this change
=> Getting Uid in sentry for angular errors

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js
=> Benchmarks: adding checks for no new leavers and null value

src/app/features/public/contact-us/contact-us.component.html
=> Message for phones been unavailable

server/models/cache/singletons/permissions.js, server/routes/establishments/permissions.js, server/test/unit/routes/establishments/permissions.spec.js, src/app/core/model/permissions.model.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.spec.ts, src/app/features/dashboard/dashboard.component.ts
=> Benchmarks: only common main services can view benchmarks

server/routes/admin/search/groups/index.js, server/test/unit/routes/admin/search/groups/index.spec.js, src/app/features/search/search.component.html, src/app/features/search/search.component.ts
=> Added a parent parameter to the admin groups search

src/app/features/public/privacy-notice/privacy-notice.component.html
=> Updated privacy notice

src/app/features/public/contact-us/contact-us.component.html
This reverts commit 049d37ce063ac227d46be2dda744b27155ac8c33.
=> Revert "Message for phones been unavailable"

.github/release-drafter.yml, .github/workflows/release-drafter.yml
=> Added release drafter

src/app/features/search/search.component.html
**Work done**
- Added copy to show the # of results returned by Admin search
=> Feat: num of search results for Admin

.github/workflows/release-drafter.yml
=> Added on release drafter

src/app/features/public/privacy-notice/privacy-notice.component.html, src/app/features/search/search.component.html
=> Deploy Pre prod: # of results returned by Admin search

.github/workflows/release-drafter.yml
=> Updated Release Drafter Config

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/app-routing.module.ts, src/app/core/services/benchmarks.service.ts, src/app/core/services/permissions/permissions.service.ts, src/app/core/test-utils/MockBenchmarkService.ts, src/app/features/dashboard/dashboard.component.ts, src/app/features/workplace/view-workplace/view-workplace.component.html, src/app/features/workplace/view-workplace/view-workplace.component.spec.ts, src/app/features/workplace/view-workplace/view-workplace.component.ts, src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.html, src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.spec.ts, src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts, src/app/shared/components/benchmarks-tab/benchmarks-routing.module.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts, src/app/shared/components/benchmarks-tab/benchmarks.module.ts, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.html, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.spec.ts, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.ts
=> Benchmarks: about the data Page

migrations/20200821105748-revertBenchmarks.js, server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
=> changing pay to be in pennies on the backend then converted in the frontend

migrations/20200821074704-updateBenchmarks.js, server/models/benchmarks.js
=> Updated turnover to accept a higher precision

src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts
=> fixing test

server/models/user.js, server/routes/admin/search/users/index.js, server/test/unit/routes/admin/search/users/index.spec.js, server/transformers/adminSearchTransformer.js, server/utils/db/index.js, src/app/core/services/switch-workplace.service.ts, src/app/core/test-utils/MockSwitchWorkplaceService.ts, src/app/features/search/cqc-status-change/cqc-status-change.component.ts, src/app/features/search/parent-request/parent-request.component.ts, src/app/features/search/search.component.html, src/app/features/search/search.component.spec.ts, src/app/features/search/search.component.ts
Introduced gray table for additional user details on search users tab
Added tests for `SearchComponent` relating to search users tab
=> Administrators can expand user search results

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments-old.spec.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
Added additional validation rules for bulk upload _starters, leavers and vacancies fields_
Added relevant unit tests
=> Bulk upload validations STARTERS LEAVER VACANCIES

server/config/preproduction.yaml
=> Upped db connections to 100

server/config/config.js, server/config/preproduction.yaml, server/models/index.js
=> Upped max db connections and timeout

server/config/preproduction.yaml
=> Changed max db connections to 500

server/config/preproduction.yaml
=> Downgraded it to a max of 4k connections

server/routes/establishments/bulkUpload.js
=> Added try catch round lockstatus

server/routes/establishments/bulkUpload.js
=> Reply with 200 after 1 second on lock status

.circleci/config.yml
=> Updated config for front end tests

server/config/preproduction.yaml, server/config/production.yaml
=> Upped production numbers to 300 and downgraded to 300 on preprod

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js
=> Benchmarks: fixing error when comparison group data is 0

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js
- [] No, they are not required for this change
=> Benchmarks: fixing order of checks

.vscode/launch.json, server/models/BulkImport/csv/workers.js, server/test/unit/models/Bulkimport/csv/workers.spec.js
Added validation warning for when worker days sick has not changed today
=> Bulk upload validation - SICKNESS not changing

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments-old.spec.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
=> Bulk Upload  S/L/V not changing

server/models/BulkImport/csv/workers.js, server/test/unit/models/Bulkimport/csv/workers.spec.js
=> Bulk upload validation - SICKNESS not changing - use savedAt

server/models/BulkImport/csv/establishments.js
=> Fixed issue if no SLV in db

server/models/BulkImport/csv/establishments.js
=> Added fix for if it's an array

server/models/BulkImport/csv/establishments.js
=> Removed spaces from localEstID in database

src/app/core/test-utils/MockWorkerService.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.spec.ts, src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/shared/components/inset-text/inset-text.component.html, src/app/shared/components/inset-text/inset-text.component.spec.ts, src/app/shared/components/inset-text/inset-text.component.ts, src/app/shared/components/staff-records-tab/staff-records-tab.component.html, src/app/shared/components/staff-records-tab/staff-records-tab.component.spec.ts, src/app/shared/components/workplace-tab/workplace-tab.component.html
=> Orange flu banner 

src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.ts, src/app/shared/components/staff-records-tab/staff-records-tab.component.html, src/app/shared/components/staff-records-tab/staff-records-tab.component.ts
=> Added returnTo for flu Jab questions

package.json, server/models/BulkImport/csv/workers.js, server/models/classes/worker.js, server/test/factories/worker/csv.js, server/test/unit/mockdata/workers.js, server/test/unit/models/Bulkimport/csv/workers.spec.js
=> Flu jab on Bulk Upload

src/app/features/workers/flu-jab/flu-jab.component.spec.ts
=> Tech debt: Remove todo

server/models/BulkImport/csv/establishments.js
=> Changed it so it looks for buValues before checkign the value

server/models/BulkImport/csv/establishments.js
=> Made sure buValues is always defined before getting values

server/models/BulkImport/csv/establishments.js
=> Updating error message for ALLJOBROLES

src/app/core/services/flu-jab.service.ts, src/app/features/workers/flu-jab/flu-jab.component.html, src/app/features/workers/flu-jab/flu-jab.component.spec.ts, src/app/features/workers/flu-jab/flu-jab.component.ts, src/app/features/workplace/flu-jab/flu-jab.component.html, src/app/features/workplace/flu-jab/flu-jab.component.spec.ts, src/app/features/workplace/flu-jab/flu-jab.component.ts
=> Always save flu jab data for all workers

server/models/BulkImport/csv/establishments.js
=> Updated error messages so they don't group together

server/models/BulkImport/csv/establishments.js
=> Bug fix if allJobs not an array

src/app/features/public/terms-conditions/terms-conditions.component.html
=> Removed reference to overseas

server/utils/fileLock.js
=> Added fix for timeout lock status calls

server/models/BulkImport/csv/establishments.js
=> Stopped SLV validation on BU

server/models/classes/worker.js, server/models/classes/worker/properties/daysSickProperty.js, server/test/unit/models/classes/worker.spec.js
=> Set days sick null when worker agency or pool

migrations/20200917104136-lnglat.js
=> Added migration for longitude and latitude

server/models/cache/singletons/permissions.js
=> adding in parent-sub view rights

server/models/establishment.js
=> Added more to if so we don't look for an object that doesn't exist

server/models/cssr.js
=> Fix for cssr bug

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
=> fixing type comparison error

src/app/app-routing.module.ts, src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts, src/app/shared/components/benchmarks-tab/benchmarks-routing.module.ts, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.html
=> Changing where the guard is for benchmarks

src/app/features/workplace/flu-jab/flu-jab.component.html, src/app/features/workplace/flu-jab/flu-jab.component.ts, src/app/features/workplace/question/question.component.ts
=> Flu jab form text link bug

server/test/unit/routes/establishments/bulkUpload.spec.js
=>  removing unused imports 

server/config/accessibility.yaml, server/config/benchmarks.yaml, server/config/config.js, server/config/development.yaml, server/config/preproduction.yaml, server/config/production.yaml, server/config/test.yaml, server/routes/reports/trainingReport/training.js, server/utils/fileLockS3.js
=> Created s3 file locking

server/models/BulkImport/csv/establishments.js, server/models/cssr.js, server/models/establishment.js
moving hot fix changes made on live to test
=> live to test: adding hotfix changes to test

CQCLocationAPICall/aws/secrets.js, CQCLocationAPICall/cqc-location-call-_star_-eu-west-1-policy.json
=> Fixes to CQC function to remove logging out the db details

src/app/core/components/footer/footer.component.html, src/app/core/components/footer/footer.component.ts, src/app/core/components/header/header.component.html, src/app/core/components/header/header.component.ts, src/app/core/services/benchmarks.service.ts, src/app/core/services/pdf.service.ts, src/app/core/test-utils/MockBenchmarkService.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/pdf/footer/pdf-footer.component.html, src/app/features/pdf/footer/pdf-footer.component.ts, src/app/features/pdf/header/pdf-header.component.html, src/app/features/pdf/header/pdf-header.component.ts, src/app/features/pdf/workplace-title/pdf-workplace-title.component.html, src/app/features/pdf/workplace-title/pdf-workplace-title.component.ts, src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.ts
=> Fixed benchmarks pdf to display correct workplace
