NMDSdevopsServiceAdm/SopraSteria-SFC

README.md, resources/db/cqc_ddl.sql, resources/establishment_api.schema.json, resources/establishment_types.schema.json, server.js, server/models/establishment.js, server/models/login.js, server/models/user.js, server/routes/tmpLogin.js
Morning Nasir
Firstly, please *do NOT delete* the branch.
I've not worked with `sequelize` before (first time with SQL databases and node.js - I've always used noSQL with node.js). So I got a head start on the faux login API, not least because the registration did not define the Establishment, Login and User types and their corresponding relationships, but had defined Services.
This pull request is my implementation for the faux login.  It does minimum validation on username, which it uses to resolve user, establishment and establishment's main service (if it is defined).
I've updated the JSON schema definition as I've gone along; not enforcing schema validation just yet though. Really need to separate the backend into its own repo first (not wanting to pollute the UI `package.json` with …
=> Establishment api

.gitignore
We want to git-ignore ./dist folder. If we do not, sooner or later somebody can push some generated stuff to origin.
=> Ignore ./dist folder.

src/app/features/select-workplace-address/select-workplace-address.component.html
Now includes the postcode location name, but only if the location name is defined from the resulting data, making it easier to select from multiple addresses at a specific postcode (typical of business addresses). See the attached screenshot as used by the team in Leeds to test.
=> Develop address lookup

server/routes/establishments/la.js, src/app/app.module.ts, src/app/features/shareLocalAuthorities/shareLocalAuthority.component.html, src/app/features/shareLocalAuthorities/shareLocalAuthority.component.ts
More than just a probability, we now have a specific example in test "BB10 1XX" where this can be demonstrated.
This PR impacts on:
1. UI - to handle an empty `primaryAuthority` by not showing the checkbox.
2. API - to return a 200 and empty `primaryAuthority` if not found (previously, returned 404).
=> Properly handling missing primary authority data

server/models/index.js, server/routes/registration.js
HI Nasir
This is to backfill the SSL option for database config - to be controlled as env variable.
Note, the Trello card is: https://trello.com/c/OoE63MqJ. There is a task on there for you to update the Travis deployment to pass `DB_SSL=1` to UAT. You can (and should) do that in advance of a deploy to UAT. Adding it now has no adverse consequence.
=> Handling DB SSL as a environment variable override

src/app/features/confirm-workplace-details/confirm-workplace-details.component.ts, src/app/features/cqc-registered-question/cqc-registered-question-edit/cqc-registered-question-edit.component.ts, src/app/features/select-workplace-address/select-workplace-address.component.ts
This is a fix for:
https://trello.com/c/TqbQarpT/116-confirm-your-workplace-details-spurious-location-id-given?menu=filter&filter=label:Cohort%201
I have cleared the default 'locationdata' data and set 'isRegistered: false;'. This will make confirm details display correctly as the default data will not exist, and the correct main services should also display for non-cqc registered users.
=> Fix is not registered issue on select address

resources/establishment_types.schema.json, server/models/classes/worker/properties/britishCitizenshipProperty.js, server/models/classes/worker/properties/countryProperty.js, server/models/classes/worker/properties/dateOfBirthProperty.js, server/models/classes/worker/properties/mainJobStartDateProperty.js, server/models/classes/worker/properties/recruitedFromProperty.js, server/models/classes/worker/properties/socialCareStartDateProperty.js, server/models/classes/worker/properties/yearArrivedProperty.js, server/models/classes/worker/workerProperties.js, server/models/worker.js, server/routes/country.js, server/routes/ethnicity.js, server/routes/nationalities.js, server/routes/qualifications.js, server/routes/recruitedFrom.js
NOTE - THIS PR IS NOT YET READY FOR REVIEW
Extending the Worker properties to include:
* British Citizenship - simple value based property
* Year Arrived - value based property, but if value is "Yes", has additional "Year" attribute with validation
* Social Cae Start Date
This PR includes a correction to the `recruitedFrom` JSON response, picked up by @adamfaryna while integrating with UI.
=> Adding British Citizenship, Year Arrived and Social Care Start Date Extended Properties, and correction to RecruitedFrom JSON output

resources/establishment_types.schema.json, server/models/classes/properties/changePrototype.js, server/models/classes/properties/manager.js, server/models/classes/worker.js, server/models/classes/worker/properties/annualHourlyPayProperty.js, server/models/classes/worker/properties/daysSickProperty.js, server/models/classes/worker/properties/otherJobsProperty.js, server/models/classes/worker/properties/weeklyHoursAverageProperty.js, server/models/classes/worker/properties/weeklyHoursContractedProperty.js, server/models/classes/worker/properties/yearArrivedProperty.js, server/models/classes/worker/properties/zeroContractProperty.js, server/models/classes/worker/workerProperties.js, server/models/worker.js, server/models/workerJobs.js
Having to extend the property framework to allow for any number of additional sequelize models to be defined when processing a property, so that records, outside the scope of the initial Worker table, can be created within the same lifetime as the Worker record.
Also, introducing this "other job" property, so it looks likes and behaves like any other property as though the value were a simple value stored as a column on the Worker table.
So I have implemented the "Other Job" property as a Virtual Property; it has the typical database columns but it populates the value on the `Worke`r table record as a made up value of 'Yes' or 'No'; 'with given other job' records and 'with no other job' records. This allows the existing framework implementation of `savedBy`, `savedAt`, `changedBy` and …
=> Worker "Other Jobs" property

package.json, server.js
- This PR implement Helmet package which prevent reflective xss warning. 
- The is part of v1.3 release with 2 trello work item
- Due to issues with develop 1.3v-beta branch; this branched off from Test.
=> Adding Helmet package to stop reflected xss warning

resources/establishment_types.schema.json, server/models/classes/properties/changePrototype.js, server/models/classes/worker.js, server/models/classes/worker/properties/annualHourlyPayProperty.js, server/models/classes/worker/properties/apprenticeshipTrainingProperty.js, server/models/classes/worker/properties/careCertificateProperty.js, server/models/classes/worker/properties/daysSickProperty.js, server/models/classes/worker/properties/highestQualificationProperty.js, server/models/classes/worker/properties/otherQualificationProperty.js, server/models/classes/worker/properties/qualificationInSocialCareProperty.js, server/models/classes/worker/properties/socialCareQualificationProperty.js, server/models/classes/worker/properties/weeklyHoursAverageProperty.js, server/models/classes/worker/properties/weeklyHoursContractedProperty.js, server/models/classes/worker/workerProperties.js, server/models/worker.js
This PR includes the last of the five Worker properties (all using the standard Worker change property framework):
* Care Certificate
* Apprenticeship Training
* Qualification in Social Care
* Other Qualification
* Highest (Other) Qualification
It also includes renaming a previously deliver property called "Qualification"; turns out there are two different Qualifications. Highest (added as new above) and "Social Care Qualification".
All new and renamed properties have been included successfully with modified automated integration tests. Test Evidence report has been updated. API Usage report has been updated.
It includes a correction to "Days Sick" property (JSON presentation), following completion of automated integration tests.
It includes a correction to "Annually Hourly Pay" (JSON …
=> Final Worker Backend PR

server/routes/establishments/worker.js, server/routes/testOnly/cleanStart.js, server/routes/testOnly/index.js, server/routes/testOnly/timestamp.js, server/utils/security/isLocalTest.js
Firstly, the PR resets the error reported by `Worker.get(/)` to be the safe message, following latest deployment to dev now working.
Secondly, this PR includes a correction to the test API endpoint `clean` to remove the additional `WorkerJobs` and `WorkerAudit` records.
And finally, this PR extends access to the test API endpoints to include `sfcdev.cloudapps.digital`, which allows the backend integration API to executed remotely against the deployed dev application.
=> Restoring Worker.get to use safe error and corrections to test/clean and allowing remote access to test endpoint in dev

manifest.dev.yml, manifest.test.yml, manifest.yml
Hi, 
Due to absense of any nodejs build pack; it always pick the latest and prone to error with our application and dependencies. hence i  have explicitly defined the version in all manifest files.
Thanks
NAsir
=> specify nodejs buildpack in manifest file

server/models/classes/worker/properties/socialCareStartDateProperty.js, server/models/classes/worker/properties/yearArrivedProperty.js
Revising the year of entry lower bound to be inclusive, this matching the UI.
The same logic is used for start date in social care; for consistency, updated that too.
=> Social Care Start Date & Year of entry - lower boundary (100 years) now inclusive

src/app/features/leavers/leavers.component.ts, src/app/features/starters/starters.component.ts, src/app/features/vacancies/vacancies.component.ts
This follows feedback from Ann on testing https://trello.com/c/d4uwAajW yesterday.
Even when the user had previously selected "none" or "don't know" options, we still need to display a single job role with "Select job title" option shown.
This also fixed a bug I had introduced on starters and leavers default view (the else clause using the wrong control to set).
I've taken the opporutnity to remove unused variable in vacancies and starters (`noVacanciesReasonControl`).
=> Revised default uninitialised job role for None and Don't know options.

package.json, server.js, server/routes/testOnly/location.js, server/routes/testOnly/postcode.js
Hi Nasir
To complete on the outstanding helmet Trello card code review (https://trello.com/c/0395dNwz), I've created a new branch from the stabalised `develop` branch, and I've manually brought in the explicit configuration of helmet which includes CSP, brought in `xss-clean`, and `express-sanitizer`, both used in my last demonstration to remove all but two warnings from contrast.
I've added that last contrast log that demonstrated this to the trello card.
I've tidied up the middleware paths, including allowing for exclusion of `xss-clean` on the test only route, allowing the demonstration of sanitizer on test only routes.
Ready for your review and approval, then we can close out the work done during evaluation of contrast.
=> Refactoring helmet and introducing xss-clean and express-santizer

server/models/classes/worker/properties/annualHourlyPayProperty.js, src/app/features/workers/salary/salary.component.ts
Following test review, the upper boundary for hourly pay should be £200 not £100. Frontend and backend updates here.
Trello card (https://trello.com/c/el8TER0J) has evidence screenshots for frontend and backend showing 200 now successful.
Thanks
=> Correcting the hourly pay upper boundary limit both frontend and backend

src/app/features/workers/salary/salary.component.ts
A duplication of hard coded values in the same component for upper boundaries. Rather than refactoring now, I've highlighted with a TODO that we should be using constants, and should refactor when we come to implement cross-validations - because the upper/lower boundaries here will change because we need to vary  them based on job type.
A quick review and approval.
=> Updating the upper boundary on the associated error message

resources/establishment_types.schema.json, server/models/classes/properties/manager.js, server/models/classes/user.js, server/models/classes/user/properties/emailProperty.js, server/models/classes/user/properties/fullnameProperty.js, server/models/classes/user/properties/jobTitleProperty.js, server/models/classes/user/properties/phoneProperty.js, server/models/classes/user/properties/securityQuestionAnswerProperty.js, server/models/classes/user/properties/securityQuestionProperty.js, server/models/classes/user/userExceptions.js, server/models/classes/user/userProperties.js, server/models/classes/worker.js, server/models/user.js, server/routes/accounts/user.js, server/routes/establishments/worker.js, server/routes/registration.js, server/utils/security/isAuthenticated.js
This PR is not as big as it first looks.
Trello card: https://trello.com/c/pByUKSW3 - Change User Details.
You've already reviewed and approved much of the Change User Details, with the introduction of the Change Property columns for `User`.
This PRs build on that by introducing the `User` Extended Change class, along with it's six properties:
1. Fullname
2. Job title
3. Email
4. Phone
5. Security Question
6. Security Question Answer
In addition, I've taken the opportunity to payback some debt, by updating the extended change model to return JSON based only on fhe set of properties, and have taken the opportunity to update Workers too (the original debt): https://trello.com/c/0FslUApY.
And because it has been agreed that we're including Worker UID in the URL in the frontend (now deployed …
=> Change user details

server/models/classes/worker/properties/annualHourlyPayProperty.js, server/models/classes/worker/properties/daysSickProperty.js, server/models/classes/worker/properties/nationalInsuranceProperty.js, server/models/classes/worker/properties/socialCareStartDateProperty.js, server/models/classes/worker/properties/yearArrivedProperty.js
Hi Nasir
Ann raised observation against the Worker change history, where some properties were showing as changed, when their data had not.
I've taken the opportunity to improve upon my Worker integration to assert on "no change", using a method I prove while delivering upon the User Change Details you've just reviewed.
It highlighted there five properties where change was being incorrectly cited. I've fixed the properties and once again I have a full successful regression run against all Worker properties.
Complementary PR for the automated integration tests: https://github.com/wozzer72/restful-api-qa/pull/9
=> Worker "no change" assertions

server/config/config.js, server/config/localhost.yaml, server/config/production.yaml, server/config/test.yaml, server/models/addUserTracking.js, server/models/classes/user.js, server/models/classes/user/properties/roleProperty.js, server/models/classes/user/userExceptions.js, server/models/classes/user/userProperties.js, server/models/login.js, server/models/user.js, server/routes/accounts/user.js, server/routes/login.js, server/routes/registration.js, server/routes/testOnly/cleanStart.js, server/utils/email/notify-email.js, server/utils/security/generateJWT.js, server/utils/security/isAuthenticated.js
Hi Nasir
https://trello.com/c/HzYGVltp
With so many changes here, you could ask "What isn't included in this change?".
Essentially, it is to allow adding and edit of new users (explicitly no delete). A user is added in two stages:
* First registered by a logged in user (having Edit role); sends an email with a link
* Second, on receipt of email, the target user completes registration including the more sensitive aspects of their username (can be duplicate) and their security question/answer
There are changes to the GDS (gov.uk) notify to allow sending an email on registration; consequently, there are changes to the config and test/production for the new email template ID.
There is an AddUserTracking database table (similar to the password reset tracking) with the sequelize model.
Of …
=> Add/Edit User

src/app/features/workers/recruited-from/recruited-from.component.html, src/app/features/workers/recruited-from/recruited-from.component.ts
Using form.controls in custom validator over form.value as it is not updated on validation request.
Fix was provided by @wozzer72, but I also changed the validation error to `required` over `recruitedFromIdValid` and added an ID to the select element for future use.
=> Recruited From Validation error

server/models/classes/worker.js, src/app/core/services/worker.service.ts, src/app/features/workers/create-staff-record/create-staff-record.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.ts
This PR includes changes to how the Skeleton Records work. When a record is updated and then the Save button is pressed, the record is saved in the DB. The Delete button now either removes the row (if the record has not been saved yet) or sends a request to the DB to delete the record, and then removes the row.
Total Staff is only ever changed if the amount becomes greater than what they entered. There was no specific logic around this described in the AC's.
```
staffRecordsRequiredValidator(control: FormArray) {
if (!control.controls.some(c => !isNull(c.get('uid').value))) {
return { required: true };
}
return null;
}
```
This is a weird bit of logic, the double negative is there because sometimes there might not be any items in the FormArray, so it's checking for that in the same …
=> Save / Delete Skeleton Records

src/app/core/services/worker.service.ts, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.ts, src/app/features/workers/create-staff-record/create-staff-record.component.html, src/app/features/workers/create-staff-record/create-staff-record.component.ts
Updating Skeleton Records to be less complex when validating against total staff number
* Remove Total Staff validation
* Fix success message on Staff Records tab
* Add prompt to Staff Records tab when Total Staff and Staff Records amount doesn't match
* Change Staff records displayed index to reflect total staff records
* Hide "Provide more information" link when entered Total Staff does not equal Staff Records.
* Added scrolling to the open record
=> Removing Validation around Total Staff

server/config/config.js, server/config/localhost.yaml, server/models/classes/establishment.js, server/models/classes/establishment/establishmentExceptions.js, server/models/classes/establishment/establishmentProperties.js, server/models/classes/establishment/properties/employerTypeProperty.js, server/models/classes/user.js, server/models/establishment.js, server/models/establishmentAudit.js, server/models/index.js, server/routes/establishments/index.js, server/routes/login.js, server/routes/registration.js, server/utils/security/generateJWT.js, server/utils/security/isAuthenticated.js
Nasir
The PR covers the work so far on https://trello.com/c/jaqBQdQg. This card will have a lot of changes, so I thought I'd get this one in first.
This covers a lot of ground by introducing the Establishment Extended Property class, along with the exceptions/property manager. I've updated the existing GET endpoint with a new presentation using this Establishment Extended Property class (renaming the old presentation endpoint to end in `alt`).
I've proven the restore from DB and the presentation to JSON, including updating my integration tests for the timeline and full history.
But significantly in this PR, I've introduce Establishment UID (complementing Worker UID and User UID); the framework makes good on UUIDs.
This impacts:
1. Registration - to create the UUID
2. Login - to return the …
=> Establishment full audit

src/app/app-routing.module.ts, src/app/core/services/auth-guard.service.ts, src/app/core/services/auth-service.ts, src/app/features/login/login.component.ts
Redirect after Login now uses an object to pass fragments and query parameters to `router.navigate()`
=> Redirect with params and fragments

server/models/classes/establishment.js, server/models/classes/establishment/establishmentProperties.js, server/models/classes/establishment/properties/mainServiceProperty.js, server/models/classes/establishment/properties/nameProperty.js, server/models/classes/establishment/properties/serviceUsersProperty.js, server/models/establishment.js, server/models/establishmentServiceUsers.js, server/routes/establishments/capacity.js, server/routes/establishments/employerType.js, server/routes/establishments/index.js, server/routes/establishments/jobs.js, server/routes/establishments/la.js, server/routes/establishments/mainService.js, server/routes/establishments/name.js, server/routes/establishments/serviceUsers.js, server/routes/establishments/services.js, server/routes/establishments/shareData.js, server/routes/establishments/staff.js, server/routes/login.js, server/routes/registration.js
Two trello cards in one branch/PR:
* https://trello.com/c/6y2OTQmB
* https://trello.com/c/6j4x0gui
This is because both introduce one or more change properties to Establishment, so it is more efficient to do both changes in one go.
It's pretty much everything you've seen before.
The "Service Users" can be zero or more reflexion records; hence the new `EstablishmentServiceUsers` sequelize model (for the table) and new association from `Establishment` sequelize model.
A little wierdness on the name property, in that because it (the name) is returned on every establishment endpoint (GET and POST), because it's now a managed property, every endpoint needs both it's target endpint and the "Name" endpoint.
Any question, just ask of course.
=> Establishment additional properties

server.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/index.js, server/routes/establishments/worker.js, server/routes/reports/index.js, server/routes/reports/wdf/index.js, server/utils/wdfEligibilityDate.js
Hey Denny
I've worked through the API changes for WDF Eligibility reporting.
I've implemented all API endpoints, including the passing of optional "effective from" date.
All the endpoints return WDF eligibility data in a format that I believe will be useful for you.
The dashboard WDF results are pure mock data (random).
The Establishment WDF results are mainly factual (just have some voodoo stuff to do in regards to the set of Workers); but you have the WDF eligibility by property.
The Worker WDF results are factual; I've raised an issue with Maria about needing better acceptance critiera to handle the inter-property calculations.
The Workers (staff list summary) is factual.
I've not written any automated tests yet, cause wanting to get this to you early so we have plenty of time to play …
=> Wdf report api stub

server/routes/serviceUsers.js
The reference output looks equivalent to that already consumed by frontend for `.../api/services/byCategory`.
=> Restructuring the output on service users reference endpoint.

server/models/classes/qualification.js, server/models/classes/training.js, server/models/workerAvailableQualifications.js, server/models/workerQualifications.js, server/routes/establishments/qualification/index.js, server/routes/establishments/worker.js
Trello card: https://trello.com/c/zkIxMNm0
Introducing Qualifications endpoints:
* GET all records for the given Worker
* GET individual record for the given Worker
* POST (create) record for the given Worker
* PUT (update) record for the given Worker
* DELETE record for the given Worker
Based on the same implementation for Worker Training records; in fact, this implementation was branched off `training-api`; hence the target merge branch is `training-api`. This extends to the routing from `Worker` and reusing the Worker/Estabishment authorisation middleware introduced with the Training API.
Currently missing one API endpoint listed on backend tasks: `[GET] .../api/establishment/:eid/worker/:wid/allQualifications`. I may yet find time to complete this before the review and approval of …
=> Qualifications API and Training optional properties reset

server/models/classes/qualification.js, server/models/classes/training.js, server/models/workerQualifications.js, server/models/workerTraining.js, server/routes/establishments/qualification/index.js
This one PR relates to both Training (https://trello.com/c/t2xFhyaa) and Qualifications (https://trello.com/c/zkIxMNm0) and includes changes based on feedback on the cards by Maria and feedback during yesterday's demo.
I've also included a little tidying up exceptions for duplicate, extending the catch for duplication on the update of Qualification too.
Plus I tided up the Qualification responses to include the qualification id in all responses.
1. Type and Other not necessary.
2. Year is optional.
3. Removing the validation/resolve of Qualification by "title/level" - because level can be null. But also, the available qualifications have to be fetched based on type/group, the qualification id is always known.
1. All fields except the training category are optional.
=> Training and Qualificatoin refinements following demo feedback 

server/models/classes/establishment/properties/leaversProperty.js, server/models/classes/establishment/properties/startersProperty.js, server/models/classes/establishment/properties/vacanciesProperty.js
The Change Property `isEqual` method is what controls change audit history. The fact it (`isEqual`) was only checking for arrays not values, meant the changes to values were being tracked as change everytime.
=> Correcting the isEqual logic to properly handle change on value based Vacancies, Starters and Leavers

server/models/classes/training.js, server/models/workerTraining.js
Just a DB schema change (to enum) and validation changes.
Have assumed "accredited" remains optional until told otherwise.
=> Training accredited dont know

src/app/core/model/qualification.model.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.ts, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.html, src/app/features/workers/add-edit-qualification/qualification-form/qualification-form.component.ts, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.html, src/app/features/workers/staff-record-summary/qualifications-and-training/qualifications-and-training.component.html
Validation rules were missed where a Qualification had imposed a from and/or until date in which it could be achieved. This has now been applied and overwrites the -100 years and future date rules where applicable.
=> Validation rules now apply to from/until returned from Qualification API

server/models/classes/establishment.js, server/models/classes/user.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/models/establishment.js, server/models/establishmentAudit.js, server/models/worker.js, server/models/workerAudit.js, server/routes/accounts/user.js, server/routes/establishments/index.js, server/routes/establishments/worker.js, server/routes/registration.js, server/routes/reports/wdf/index.js
https://trello.com/c/yBCo8FV7
Following a review with Will Fenton, it was highlighted that a workplace attains Overal WDF Eligibility at any time throughout the year, and once attained, keeps it until the effective period restarts.
Will also wanted the calculation to be based on when the user Completes their Establishment or Worker; because Establishment Complete is not yet available, this implementation is based on Establishment update.
This now means having to store the Overall WDF Eligibility. It also means we have to recalculate the Overall WDF Eligibility (which is against an Establishment and all it's Workers) whenever the Establishment or Worker is updated. To keep the code simpler, I've introduced a singleton as the `WdfCalculator` which also encapsulates the "effective from" …
=> WDF Reports Rework

index.html, index_staging.html, index_uat.html, src/app/app-routing.module.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/core/services/title.service.ts, src/app/features/registration/registration-routing.module.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workplace/workplace-routing.module.ts
This grabs the Page Title from the data property on the route. It pulls through all of the Parent routes titles to build a page title separated by a hyphen. eg `Skills for Care - Registration - CQC Regulated`
=> Page Title Service

src/app/features/registration/create-username/create-username.component.html, src/app/features/registration/create-username/create-username.component.ts, src/app/features/registration/security-question/security-question.component.html, src/app/features/registration/security-question/security-question.component.ts
when accessing errors in the template `maxLength` is exposed in lowercase so this fix is to ensure the error is accessible and to prevent any console errors
=> bugfix | fix validation type name casing

resources/establishment_types.schema.json, server/models/classes/establishment.js, server/models/establishment.js, server/routes/login.js, server/utils/security/generateJWT.js
This first parent & subs PR inrtoduces the "is parent" and "parent ID/UID" attributes for Establishment - including the DB schema changes.
All current registrations are standalone; so is parent defaults to false and parent ID/UID is always NULL.
Login API response has been updated to return the "is parent" status; for now, it will be necessary to manually update the Establishment record in the database to change to true. Actions to make parent/make a sub are not yet in sprint scope.
Login JWT also updated to include "is parent" status. I need this for a new API I will next develop to return the set of associated subs for a parent establishment.
_Apologies for the extensive updates on Establishment JSON Schema type. Whilst I was updating it for parent/subs I realised it was out of date. …
=> Parents and subs - login API

server/models/login.js, server/models/user.js, server/routes/accounts/user.js, server/routes/login.js
https://trello.com/c/cfj4ZW7y
It's not my best code ever in respect to the login callback, but the twists and turns in the successful/unsuccessful logins with audit events and updating failed attempt counters, meant I wanted to reuse as much of that as possible.
I've tested this code on local database with existing non-migrated users. I've tested this code on Tribal migrated database, on migrated users by forcing a reset "Tribal Hash" on one user.
I've also re-run successfully all my regression tests, which highlighted the "changePassword" impact too.
All is good. But I need to get this in to dev to be sure from a new build perspective.
=> Adding support for tribal hashing of migrated tribal user accounts

resources/establishment_types.schema.json, server/models/classes/establishment.js, server/models/classes/user.js, server/models/establishment.js, server/routes/accounts/user.js, server/routes/establishments/worker.js, server/utils/security/isAuthenticated.js
Hi Nasir
https://trello.com/c/ikScd2O3
Well, this is the last of the big changes for this "parent and subs - view subsidiaries".
This one changes the very rigid authorisation that restricts establishments to users of the establishments only.
The main crux of the changes are in: `server/utils/security/isAuthenticated.js`. It might serve best for me to walk you through over appear.in.
I'm not overly happy with the code; because its middleware, I'm having to use promise callbacks which makes conditional paths hard! Whilst there is some duplication, there is a much bigger piece of work pending around permissions in general, where I expect such authentication logic to be completed encapsulated.
Thanks
=> Parents and subs access establishments and workers

src/app/features/bulk-upload/bulk-upload-page/bulk-upload-page.component.html, src/app/features/bulk-upload/check-workplace-references/check-workplace-references.component.html, src/app/features/bulk-upload/download-data-files/download-data-files.component.html, src/app/features/bulk-upload/upload-data-files/upload-data-files.component.html
- second attempt at fixing this but this time a cross browser solution that works in IE, firefox and chrome and no more alignment issues.
- gds classes such as `govuk-grid-row` and column width classes was the root cause for the `<ol>` list to not line up its inner content properly. so have simplified the markup
=> bugfix | bulk upload | alignment issues

src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/shared/validators/custom-form-validators.ts
- clear sync validators for fileUpload when files are cleared
- use a timeout when setting sync validators for file upload to fix validation for IE11
=> make IE11 show validation errors

src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.ts
- fix to correct `POST` payload effectively ensuring local authorities can be deleted
=> bugfix | local authorities not deleting properly

src/app/app.component.ts, src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.ts
- removed `this.addLocalAuthority();` which was ultimately trying to create an authority without a custodianCode and therefore displaying a select dropdown with no authority selected
- remove empty sass file and its reference
- alphabetised imports
=> bugfix | remove local authorities extra row

src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.html, src/app/features/workplace/data-sharing-with-local-authorities/data-sharing-with-local-authorities.component.ts
- set default checkbox value
- ensure checkbox is checked on page load only if `primaryAuthority` is shared
- only send `primaryAuthority` in payload if its checkbox is checked
=> bugfix | local authorities fix primary authority selection

package.json, src/polyfills.ts
this polyfill is required as IE11 doesn't support the collapse/expand behavior thats comes out of the box with modern browsers.
=> bugfix | ie11 details tag polyfill

src/app/features/bulk-upload/files-upload/files-upload.component.ts
- ensure required validator is set whilst clearing other validators when files are removed
- ensure error summary form errors event is only dispatched if submitted flag is true when files are removed
=> bugfix | bulk upload files still upload after removal

server/routes/login.js
https://trello.com/c/uboErFyw
After I had developed the login response, the UI designs had updated to require the "parent's name" when logged in as a subsidiary.
This quick change on to the login API returns such detail.
It was brought up in stand up this morning, and it's required for Ann to close out one of the sprint cards under test.
=> Subs parent name on login

server/models/classes/establishment/properties/shareWithLAProperty.js
https://trello.com/c/XKIVxy98 - whilst delivering on the GDS changes, testing identified an update fault on Local Authorities, whereby it was actually updating the data store.
Many weeks ago, we refactored Local Authorities within the backend and database, but we agreed to keep the API exposed interface the same (Local Authorities and custodian codes).
Unfortunately, the `isEqual` didn't keep up and still referenced the old `custodianCode` assumed from the database.
=> LA is equal use "CssrId" in comparison

server/models/BulkImport/csv/metaData.js, server/routes/establishments/bulkUpload.js
Hello, this is modified validate end point which now returns following to FE upon validation.
1) The method is Put now rather get and there is no need to pass filenames as input
2) The method will retrieve the three files only, first determine its type and then upload it as key latest i.e. 144/latest/test.csv 
3 The method will now calculate type, recrods, error and wrning and  will upload all meta data as object in s3 latest by name of filename.metadata.json.
2) Return response 200 and 400 formatted by establishment,, worker and training.
Here is the tickete with some screenshots
https://trello.com/c/6QIQX5SL
=> update validate endpoint

server/models/BulkImport/BUDI/index.js, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js
https://trello.com/c/nAtfBMoi
On re-test, Ann found an error I had introduced for utilisation validation; fixed as a result of some poor copying of revised capacity validation.
* ALLSERVICES trap for mandatory was not previously tested, and consequently there were are few code failures expecting `this._allServices` to be not null failing (HTTP 503).
* LOCATIONID; validating against PROVID (twice); dam copy 'n' paste.
https://trello.com/c/pquWOjG2 - Worker validation errors resulting from initial test
* CARECERT & APPRENTICE - 0 is not a valid option (careless predicate on integer value rather than original string value)
https://trello.com/c/BQDpmGEl - Worker validation errors resulting from Jackie's test
* GENDER - is optional
* EMPLSTATUS - 5 and 6 should error
* SALARYRATE - 4 should …
=> Bulk upload validation corrections

src/app/shared/form-controls/file-control-value-accessor.ts, src/app/shared/shared.module.ts
Adding ControlValueAccessor to ensure that onchange events are fired for File Inputs in Safari
=> Bug | Safari File Upload

src/app/features/workplace/other-services/other-services.component.ts
bugfix | only prefill form if user has previously checked other services as BE omits the otherServices property from get establishment call altogether rather than sending back an empty array
=> bugfix | only prefill form if user has previously checked other services

package-lock.json, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/establishment/properties/mainServiceProperty.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/validations/entityValidator.js, server/models/classes/validations/validationMessage.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
This is a fairly large PR for review against https://trello.com/c/FUtQEhVR.
It covers extending the bulk upload specific validation to incorporate the entity property framework validation.
To do this I have introduced the `EntityValidator` base class to all four entities: Establishment, Worker, Qualification and Training, which intercepts the existing `hasMandatoryProperties` and `isValid` entity validators.
Establishments/Workers are based on Change Properties. Training/Qualifications are based on internal properties. Consequently, the way they valid is slightly different.
I've had to reduce the severity in response for both Training and Qualification when there is a validation error;l before it raised an exception, now it returns false (aligned with Workers/Establishment).
I also had to …
=> Bulk upload validations merge with api

src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.html, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.ts, src/assets/scss/components/_panel.scss, src/assets/scss/main.scss, src/assets/scss/partials/_lists.scss
Extended the Panel SCSS to include an interruption card https://github.com/alphagov/govuk-design-system-backlog/issues/27
Added Definition List SCSS to display block of 3 list items, using CSS Grids, making sure it's prefixed for IE.
Updating Confirm Vacancies to use the GOV.UK Design Framework
=> GOV.UK Framework | Workplace | Confirm Vacancies

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment/properties/servicesProperty.js, server/routes/establishments/bulkUpload.js
As agreed during refinement yesterday, https://trello.com/c/FUtQEhVR card needs to include the additionally identified uniqueness validation on establishments and workers, in addition to the cross-check of workers against establishments, and training against both establishments and workers.
The codes changes are here. The trello card comments includes confirmation of the validation output.
This PR also includes a subtle rename to one of the Establishment properties (`ServicesPropertyProperty`). The double "Property" is not necessary.
Also includes a minor update to the establishment header V1 - removing IIPSTATUS, PERMNHSC, STUDENTCOUNT and DESTNOS columns.
=> Bulk upload validations 2 - unique workers/establishments and cross-check on workers/training records

server/models/classes/establishment/properties/leaversProperty.js, server/models/classes/establishment/properties/startersProperty.js, server/models/classes/establishment/properties/vacanciesProperty.js, server/routes/establishments/bulkUpload.js, server/routes/establishments/jobs.js, server/routes/registration.js, src/app/core/model/establishment.model.ts, src/app/core/services/establishment.service.ts, src/app/features/workplace/confirm-leavers/confirm-leavers.component.html, src/app/features/workplace/confirm-starters/confirm-starters.component.html, src/app/features/workplace/confirm-vacancies/confirm-vacancies.component.html, src/app/shared/components/workplace-summary/workplace-summary.component.html
on endpoint `[POST] http://localhost:3000/api/establishment/479/jobs`, removed the prefix with "jobs":
```
{
"leavers" : [
{
"title" : "Activities worker or co-ordinator",
"total" : 999
},
{
"jobId" : 10,
"total" : 333
}
],
"vacancies": "None",
"starters": "Don't know"
}
```
and response is:
```
{
"id": 479,
"uid": "98a83eef-e1e1-49f3-89c5-b1287a3cc8dd",
"name": "WOZiTech Cares Updated",
"created": "2019-03-15T09:54:10.562Z",
"updated": "2019-06-15T09:46:14.884Z",
"updatedBy": "aylingw",
"vacancies": "None",
"totalVacancies": 0,
"starters": "Don't know",
"totalStarters": 0,
"leavers": [
{
"jobId": 1,
"title": "Activities worker or co-ordinator",
"total": 999
},
{
"jobId": 10,
"title": "Care Worker",
"total": 333
}
],
"totalLeavers": 1332
}
```
Note all properties are lowercase prefixed …
=> Reformatting the input and reponse for starters, leavers and vacancies

server/models/BulkImport/BUDI/index.js, server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/training.js, server/models/BulkImport/csv/workers.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/FUtQEhVR
Remapping each errors/validations raised within the entities Establishment, Worker, Qualification and Training to the original bulk upload validation error/warning.
With Qualifications this included having to maintain provenance of the column against which the entity was constructed from.
Re-sequenced all CSV errors/warning numbers now, given there is no dependency on them. Consistent numbers used across CSV types for duplicates, unchecked and headers. And all warnings have the same _final octet_ number as errors.
Fixed a BUDI code mapping - 101, resulting always in an entity error.
=> Bulk upload normalise api validations

.gitignore, .vscode/launch.json, server.js, server/aws/secrets.js, server/config/appConfig.js, server/config/config.js, server/config/development.yaml, server/config/localhost.yaml, server/config/production.yaml, server/config/test.yaml, server/models/BulkImport/BUDI/index.js, server/models/index.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/OxdRoU55
Incorporates AWS Secret Manager with convict configuration, to allow overriding of sensitive information.
Introduces AppConfig emitter, to broadcast when the convict configuration had been updated following successful initialisation from AWS Secret Manager.
The express server now waits for the config ready event.
The sequelize configuration also now rebind on the config ready event, thus restoring connection pool once sensitive properties are made available, namely, database host, password and client SSL certs.
Sequelize model now broadcasts when it is ready, which is then consumed by BUDI singleton, to ensure it does try to initialise with "not yet ready" sequelize parameters.
And finally, had to refactor the way client SSL certs/keys are presented to …
=> Aws secrets manager

server/config/test.yaml, server/routes/establishments/bulkUpload.js
Hi Nasir
With the introduction of AWS Secrets Manager, I rejigged the config.js schema which include renaming the `bulkupload` root name.
At the time, I didn't have your validation report endpoint.
This PR fixes the report endpoint to use the new config name.
Also included in this PR are changes to `test.yaml` we had to do to get the deployment to staging working.
Thanks
=> Bulk upload validation report config hotfix

src/app/core/components/header/header.component.html, src/app/core/guards/auth/auth.guard.ts, src/app/core/services/auth.service.ts, src/app/features/login/login.component.ts
- simplify and fix redirect to previous page if user logs in again
**Note:** This was the best solution I could come up without exposing the previous route in the browser address bar and also without touching the `window.location` object itself.
I also tried to use angular's `ActivatedRouteSnapshot` in the `AuthService` but angular throws injector errors, I then tried to use `ActivatedRoute` within `AuthService` but not all url segments were not exposed
=> bugfix | redirect issue

src/app/app-routing.module.ts, src/app/core/model/bulk-upload.model.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/shared/validators/custom-form-validators.ts
- change `/api/establishment/:$establishmentId/bulkupload/signedUrl` to `/api/establishment/:$establishmentId/bulkupload/uploaded` in order to consume new api 
- create new interfaces
- allow 2 - 3 files selection
=> Feature - bulk upload consume uploaded api for getting signed urls

src/app/core/model/bulk-upload.model.ts, src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/selected-files-list/selected-files-list.component.html, src/app/features/bulk-upload/selected-files-list/selected-files-list.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.html, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts, src/app/shared/validators/custom-form-validators.ts
- renamed `UploadFile` interface to `UploadedFile` and ensure its not extending `File`
- made `selectedFiles$` observable to type `File[]` and removed unnecessary `uploadedFiles$` observable
=> feature | bulk upload | cleanup interfaces

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/metaData.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
Hi Darren
This is the validation difference report, which needs to load all current known establishments and their workers, and compare against the constructed set of establishments and workers identifying new, updated and deleted.
The difference report is uploaded to S3; I will consume it on the "complete" (the last I have to do to create, update and delete establishments and workers).
The difference report is then used to count the number of deleted establishments and deleted workers, which will be used by the frontend to display a popup modal as a warning.
Note - we cannot delete the primary establishment (the establishment of the logged in user). I do need to raise an error validation message. I'll have a look at doing that whilst you review this puppy.
Additionally, thus PR includes …
=> Bulk upload complete validate difference report

server/models/BulkImport/csv/establishments.js, server/models/classes/establishment.js, server/routes/establishments/bulkUpload.js, server/utils/security/isAuthenticated.js
Hey Darren
We're on the road to creation.
This PR includes bulk upload processing of new, updated and deleted establishments.
New establishments are consuming now the `initialiseSub` method on `Establishment`, which I've extended to default on data owner and parent permissions. This is working a treat.
I've also updated `Establishment:;save` to handle the owner/parent permissions, including removing the default 'Workplace` data ownership. But also to add properties additional models on creation (not necessary for registration). I've ran the establishment and registration restful integration tests - all successful.
Updated `Establishment::delete` to take an external transaction.
Before I whack on with the creation, update and delete of Workers following associated entities in …
=> Bulk upload complete create and update entities

.gitignore, package-lock.json, package.json, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js, server/routes/establishments/qualification/index.js
Hi Darren
This PR extends from the previous one which implemented basic create, update and delete on Establishments.
The PR builds on that, by making an Establishment create, update and delete associated Workers.
For new Establishments, it is simply a case of passing down the new establishment ID in the associate set of Workers to be able to create the foreign key between Worker/Establishment records.
For existing Establishments, it gets a little hard, in that when loading the Establishment, new Workers result in new associations, existing Workers are passed new content to load (update) and  existing associated Workers not in the new set, are marked ready for deletion upon save.
When deleting an Establishment, it is only good practice to delete all associated Workers too.
I've done a …
=> Bulk upload complete create, update and delete establishments and workers

server/config/development.yaml, server/config/localhost.yaml, server/config/production.yaml, server/config/test.yaml, server/models/classes/establishment.js, server/models/classes/qualification.js, server/models/classes/training.js, server/models/classes/worker.js
Hey Darren
https://trello.com/c/QAzbzesV
Well this should have been easier than I had expected, but it pretty much done.
This PR includes updating associated qualifications and training records when a Worker entity is saved. As there is no change audit on training or qualifications, its a simple case of delete all such records, then create new records with the data as given on bulk upload last Worker records.
To allow for that, I had to introduce setters on the Training/Qualification entities to set the associated establishment and worker id, necessary to create the foreign keys in database. I also took the opportunity for a quick optimisation in each of `Qualification::save` and `Training::save` so if the `WorkerID` is known (it would be on bulk upload through the associations) then no …
=> Bulk upload complete training and qualifications

.vscode/extensions.json, .vscode/settings.json
This is an update to make sure that Prettier is being forced for certain file types.
It will only effect developers using VSCode, other editors should push their settings too.
=> Updating VSCode Settings

server/models/BulkImport/csv/establishments.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
* Includes https://trello.com/c/fqa2hTrd - "other" main job description. Reusing bulk upload branch because it's a quick fix.
* For the purpose of the demo, suppressing the services/capacities warning in the validation report.
* An observation made during demo was that on successful completion, the uploaded files should have been  deleted.
* https://trello.com/c/CcwKfzlP - defect raised by Ann on standalone bulk uploads which may have been contributing to the contradictory validation errors for a parent upload too.
=> Bulk Upload and Main Job "Other" Fixes

src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
- no need to invoke the prevalidate files again as this step is immediately done once files are uploaded to s3
=> bugfix | dont call prevalidate api on fetched uploaded-files

src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts, src/app/features/bulk-upload/uploaded-files-list/uploaded-files-list.component.ts
- on successful file upload to s3, fire prevalidate observable event in order for the uploaded files component to go ahead and prevalidate the files. This fixes the bug where on files selection the prevalidate api was being called and cancelled immediately
=> bugfix | bulk upload | api call cancelled on files selection

src/app/core/services/bulk-upload.service.ts, src/app/features/bulk-upload/files-upload/files-upload.component.ts
- ensure that upon successful files upload to s3 the file input dom element is cleared. Otherwise once files are validated, and in the scenario where the exact same files with the same files names are chosen the observable doesnt fire as technically the data stream hasn't changed
=> bugfix | unable to choose files after validate step

server/models/BulkImport/csv/establishments.js
Hey Andrew
https://trello.com/c/u4uhUDRK
This is a simple fix to account for recent introductions to the CSV upload files that allow a single value of `999` to be used to identify "Don't know" on vacancies, leavers and starters.
The sum of leavers is a predicate in validating "REASONS". That predicate needs to exclude single value of 999.
But the main reason this was caught is because I had an validation copy and paste error in that I was trying to report on MIN_COUNT  when parsing `REASONS`.
=> Fixing the predicate on sum of leavers to ignore when a single value of 999 (Don't know) is given.

server.js, server/config/config.js, server/config/development.yaml, server/config/production.yaml, server/config/test.yaml
https://trello.com/c/LyVCfwYI
Hi Nasir
Requesting your review of this backend change, because the change is more about the application hosting environment than it is about code.
As per discussion yesterday, I'm introducing "npm proxy" to the `server.js` allowing me to proxy all requests to `public/download` to an S3 bucket. Using a new config property `public.download.baseurl` I am able to redirect to URL, but most significantly, control which of three S3 buckets to redirect to - config by environment specific URL.
I've introduced three new buckets allowing public access; one for each of dev, staging and production.
I've uploaded the current set of guidance doc PDFs and I've made them public.
Note, every time the PDFs are uploaded, they have to be make public again.
=> Introducing "public/download" proxy to S3 buckets.

src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.html, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.scss, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts, src/app/features/bulk-upload/check-workplace-references/check-workplace-references.component.html, src/app/features/bulk-upload/workplace-references-page/workplace-references-page.component.ts, src/assets/scss/components/_form-group.scss, src/assets/scss/components/_grid.scss, src/assets/scss/main.scss, src/assets/scss/modules/_utils.scss
- made bulk upload references page ui conform to design using css grids whilst retaining accessible markup using the preferred GDS form-group's for holding form elements
- renamed `workplaces` > `references`, `getEstablishments()` > `getReferences()`
- added link to `workplace-references` route form bulk upload
- added new css grid helper classes to `utils.scss`
=> feature | bulk upload | references display grid

src/app/features/bulk-upload/download-data-files/download-data-files.component.html, src/app/features/dashboard/staff-records-tab/staff-records-tab.component.html, src/app/features/reports/reports.component.html, src/app/features/workers/basic-records-save-success/basic-records-save-success.component.html, src/app/features/workers/other-qualifications-level/other-qualifications-level.component.html, src/app/features/workers/social-care-qualification-level/social-care-qualification-level.component.html, src/app/features/workers/staff-record/staff-record.component.html, src/app/features/workers/worker-save-success/worker-save-success.component.html, src/app/features/workplace/data-sharing/data-sharing.component.html, src/app/features/workplace/success/success.component.html
Binding custom directive `title` so HTML doesn't pick it up
=> Accessibility | Removing incorrect use of title attribute

src/app/core/components/dialog.component.ts, src/app/core/services/dialog.service.ts, src/app/features/bulk-upload/upload-warning-dialog/upload-warning-dialog.component.html, src/app/features/bulk-upload/upload-warning-dialog/upload-warning-dialog.component.ts, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.html, src/app/features/workers/delete-qualification-dialog/delete-qualification-dialog.component.ts, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.html, src/app/features/workers/delete-training-dialog/delete-training-dialog.component.ts, src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.html, src/app/features/workers/delete-worker-dialog/delete-worker-dialog.component.ts
Dialogs can now be closed by pressing the Escape key, or clicking outside of the Dialog area.
Updated Dialog with ARIA labels
Dialog `h1`'s must contain the `dialogHeading` id
=> Accessibility | Close Dialog Improvements

src/app/core/model/worker.model.ts, src/app/core/services/worker.service.ts, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.html, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.scss, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts, src/app/features/bulk-upload/staff-references-page/staff-references-page.component.ts, src/app/features/bulk-upload/workplace-references-page/workplace-references-page.component.ts, src/assets/scss/components/_grid.scss
- invoke `getAllWorkers` api call and update ui
- display subsidiary name and enter temporary workplaces remaining count copy
- conditionally display name or nameOrId property on label
- relocated `WorkersResponse` and `WorkerEditResponse` to model file so they can be reused
- moved common 503 error code to base class
- removed/relocated userService from base class as only one child class needed it
- adjust cols width as per design
=> feature | bulk upload | references | get workers

server/models/classes/user.js, server/models/user.js, server/routes/login.js
Adding support for an Admin user role, allowing for both known primary establishment, but also a given establishment to then assume as primary establishment.
Effectively, once logged in (authenticated) the JWT should support all user, establishment and worker/training/qualifications endpoint activity.
Removing the defunct "AdminUser" property on "User".
=> new "admin" user role on login

server/models/BulkImport/csv/training.js
This is a couple of fixes Ann picked up during testing.
The apiValidations are causing some issues, e.g. we have validations for category are already in place, but api validation validates again, and we have two errors for the same issue.
In the case of training, there are no warnings, and all error validation are already in place, so the call to apiValidations is a bit pointless.
I have commented the category section out for now.   Happy to change at your request.
=> fix training validation errors

.travis.yml, server/config/accessibility.yaml
Hello, 
As part of client specfic environment, i have reuse the existing accessibility config file and copied all test config in it except the database name and user which points to accessibility related database. The AWS secret has also changed and point to demo/api.
In summary
- URL is sfcaccessbility
- DB is NEW and separate from dev/staging
- Application config file is accessibility.config
- AWS Secret (user, policy etc) new and separate  dev/staging
Thanks
=> Merge Accessibility config changese into Develop

src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.html, src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts
this bug ensures html id's are not beginning with a number which was causing a console error. now the error summary links correctly navigate to there destination
=> bugfix | error summary links dont navigate local identifiers

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
Predominantly, this is all about effecting use upon local identifiers replacing previous dependency on Establishment::name and Worker::nameOrId for uniqueness.
I didn't realise how many occurrences would be impacted.
But I have done full testing here on upload and downloads, on new, updated and deleted establishments, or new, updated and deleted workers.
I've changed Local Identifiers and checked download and impact on upload. I've changed Local Idenitifier in the bulk upload CSV for worker and establishment, and confirmed the results of the upload.
All is looking good and repeatable.
Note - although I tried to include CHANGEWORKID in the scope of these changes, alas, rather than updating the worker, the worker is deleted. I've moved the associated card back to backend development.
Other …
=> Bulk upload use local identifiers

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/cache/singletons/capacities.js, server/models/classes/establishment.js, server/routes/establishments/bulkUpload.js
Includes:
https://trello.com/c/VsaLkn07 - fixes for ALLJOBROLES output on dedup'd job ids, which also impacts the formating of STARTERS, LEAVERS, and VACANCIES, and allowing for the fact that ALLJOBROLES could be empty.
https://trello.com/c/kfsOldCN - relaxing validation on import for empty ALLJOBROLES.
No trello card, bu t I fixed an issue with empty main job role (null). It was bombing on 503.
https://trello.com/c/sI1R6XCy - correctlng mapping CQC other services on bulk upload completion - onload entities restored from `all.entities.json`.
https://trello.com/c/8PqGW9jf - and this a proper headcase of first Capacity caching returning bizarre results owing to returning object references. And then, mismapped "otherServices" on entity load from JSON to get list of services to get associated …
=> Bulk upload defects 20170717

server/routes/login.js
https://trello.com/c/sEjGGebv
In preparation for work on the Quick 'n' Dirty Search with Bryce tomorrow, the backend needs to allow for successful login on admin roles only where there is no primary (home) establishment.
Whilst implementing this change to login, I have been able to update the login response to include UID and username.
=> Admin role with no primary establishment

server/config/config.js, server/config/preproduction.yaml
Hi Warren,
Here is trello card for this request https://trello.com/c/EJxfSl0p
I have introduced preproduction.yml and have following changes
- point to preprod wallet (has its own api users and other policy) - Screen shot is in Trello ticket
- point to preprod bucket (only this has auto-delete policy)
- i have turn status = false for client_ssl (there are no ssl cert for preprod need)
- I have also remove the database name and user because it comes from gov paas 
Only i dont know sns and kenisis values postfix with .prod? do you have prepro for those?
Thanks
Nasir
=> Introducting AWS secret configs for preprod.

server/models/BulkImport/csv/establishments.js, server/routes/establishments/bulkUpload.js, server/routes/establishments/worker.js, server/utils/security/isAuthenticated.js
https://trello.com/c/LtgGtQho
Introduces authorisation to bulk upload (BU), as defined by the parent/sub owner/parent permissions.
BU can only work on subs it owns.
On BU Download, simply filters out those establishments it is does not owner.
But on BU upload, a validation error is required if trying to upload against a sub not owned.
Whilst implementing this I noticed some dodgy handling of null data on establishments - atypical of a newly created establishment with no properties - `entity.employerType` and `entity.serviceUsers` - fixed.
Also, whilst adding this new error, I've used "unshift" to put it to the top of all errors, and have updated accordingly missing primary and expect just one establishment validation errors too.
And whilst updating the Worker authentication, I noticed …
=> Bulk upload parent subs permissions

server/routes/accounts/user.js
Check implemented to prevent a user from deleting their own account 
As per:
https://trello.com/c/bMEfsdSV/202-user-accounts-block-delete-own-account
=> prevent self delete

src/app/features/workplace/user-account-edit-permissions/user-account-edit-permissions.component.html, src/app/features/workplace/user-account-edit-permissions/user-account-edit-permissions.component.ts, src/app/features/workplace/user-account-view/user-account-view.component.ts
Users can now delete primary users
When a primary user is deleted the logged in user then becomes primary
Users get an error when they try to change a users permissions to a role that is already maxed out
=> Bug Fix | User Accounts Issues

src/app/core/services/bulk-upload.service.ts
remove caching block as if user logs out and a different user signs in > the previous data is cached and returned
=> bugfix | workplace references caching

server/routes/accounts/user.js
Added in a check to prevent the deletion of the primary as requested in:
https://trello.com/c/bkIXF7MI/214-delete-user-accounts-primary-should-not-be-allowed-to-be-deleted
=> Prevent deletion of primary on BE

server/routes/reports/dailySnapshot/index.js
No trello card for this one, but I tried to run the daily snapshot against the tribalDB remotely, and it timed out after 2 mins (express default).
This was a remote database connection, although I did expect the query/simple JSON presentation to return within that period - it's 640k records.
In preparation for the deployment to green, I want to be sure the daily snapshot completes, so adding this quick change to cover my bases.
=> Increase the request timeout for daily snasphot report to ten minutes

server/models/classes/user.js
https://trello.com/c/9XNubIaU/227-new-user-account-is-activated-with-archived-set-to-true
Removed the code which sets the registration user account to archived, now that it updates the existing instead of creating a new one
=> archived no longer set to true

server/models/BulkImport/csv/establishments.js, server/models/BulkImport/csv/workers.js, server/models/classes/establishment.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/1pTd8zzJ
This first cut of code covers just the validation of the statuses for both establishments and workers, cross checking for existing or missing establishments/workers of the current state.
It also includes the creation of skeletal establishment and worker entities by updating the entities' `hasMandatoryProperties` and `isValid` to short cicuit if status is "UNCHECKED".
I've doubled checked the intermediatry `all.entities.json`, all establishments and their associated workers are accurately represented including holding the original "status", which will be required for subsequent processing.
I've also double checked the validation `difference.report.json`, and this is still showing the correct set of new, updated and deleted establishments and workers.
=> Bulk upload statuses - validations

src/app/core/guards/bulk-upload/bulk-upload.guard.ts
This has been updated to allow admin users to bypass the wizard for adding local identifiers.
=> 211 internal admin bulk upload local identifiers

server/routes/establishments/index.js
https://trello.com/c/xTafQNkP
Corrections to Establishment POST endpoint:
* to remove the array as input
* to correct the returning of the NMDS ID; and
* to handle the recent change of splitting the Address when calling upon `Establishment::initialise`.
=> Add Workplace

server/models/classes/establishment.js, server/models/classes/user.js, server/models/classes/worker.js, server/routes/establishments/localIdentifier.js, server/routes/establishments/worker.js
Hi Darren
https://trello.com/c/Z93EZqyB
This PR covers some refactoring of local identifier code, moving model specific sequelize code under the `Establishment` and `Worker` entities.
This is done ahead of two optimisations:
1. Only update those local identifiers that have been changed - when faced with 1100 workers, needlessly updating each and every Worker consumes precious resources and time
2. Not to reflect any change on the Worker or Establishment when the local identifier is updated
Thanks
=> BU local identifiers - optimisations

src/app/features/workplace/services-capacity/services-capacity.component.html, src/app/features/workplace/services-capacity/services-capacity.component.ts
This may look slightly odd but this is the rationale.
* Service capacity validation is broken in some instances (in this case Shared lives)  because the validator method relies on the order of the controls.
* The questions are sorted by question.seq, but when added to form control this makes no difference because a FormGroup is an object map and is always ordered by its key (question.id)
* My preference here was to use a FormArray instead but this caused other issues with the error validation service.
* Fix was to prepend question.seq to form control name so validator will pick up controls in correct order.
* Filtered out this prepend when sending back to server.
=> Fix service capacity validation

src/app/features/workplace/other-services/other-services.component.ts, src/app/shared/components/workplace-summary/workplace-summary.component.html, src/app/shared/components/workplace-summary/workplace-summary.component.ts
It can be argued that the BE should also remove from other services list when a main service is selected (and will mention that in the ticket). However this PR guards against ui errors in this scenario and does fix the bug.
=> Cater for instances where main service exists in other services list

server/models/classes/establishment.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/ouUV10ZZ
Now incorporating the bulk upload integration for WdfCalculator. And a couple of subtle changes for deleting workers and establishments (`savedBy` is `deletedBy`).
https://trello.com/c/oK09M0XL
Correcting service users WDF eligible to include a minimum of one service users.
=> Wdf backend refactoring - delete worker/establishment and bulk upload and service users

src/app/shared/components/tabs/tab.component.ts
Removing the hidden attribute which effects Angular's rendering
=> Bug Fix | Tabs not displaying in MS Edge

server/models/BulkImport/csv/workers.js
https://trello.com/c/5s1BaWgz
Note - establishment CSV download also has a cqv quote function, and that already does what this PR is doing, checking for `toCSV`. Doh. Damn duplication of code. We simply don't get enough time to refactor.
=> Allow handling of nulls passed into _csvQuote in BU Worker download

server/config/config.js, server/routes/admin/search/users/index.js, server/routes/reports/localAuthorityReport/admin.js
https://trello.com/c/6DpN53GL
Removed the returning of stub CSV data, with the actual call upon admin report pgsql function, and iterating through the return data formatting CSV data column by column.
Checked the data returned in Insomonia; column by column.
This PR includes a fix update to return "InvalidAttempts" on the search user records; I've squeezed the change in this PR because it's effectively a one liner, and because whilst sat in Leeds I observed the number of requests from the Admin team asking Sopra to check if a user was locked out. The SFC admin team should be able to see this info themselves.
=> Local authority report admin

server/config/config.js, server/models/localAuthorityReportsWorkers.js, server/routes/admin/search/users/index.js, server/routes/reports/localAuthorityReport/admin.js, server/routes/reports/localAuthorityReport/user.js
https://trello.com/c/UsiGWFJU
Removing the wrong dependency on worker report records to establishment records, because worker records must be created before establishment, and the establishment needs to aggregate against the Worker records.
In fact, this simplifies the local authority establishment/worker model, because now they both use the primary establishment id as pass when generating the report.
Also adding ordering to the establishment and worker data, in preparation for writing out to Excel (the latter still yet not supported).
=> Local authority report user - revisions following review with Jackie

server/models/BulkImport/csv/workers.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/ahBZTUMC
Initial bulk upload implementation restricted number of qualifications to just three on:
1. Validation of the headers
2. Download of existing qualifications
This PR removes those restrictions, whilst still applying header validation if more than three qualifications.
Also, the existing Bulk Upload import of upto 20 qualifications has been extended to 99 qualifications - a limit imposed by the header format of `QUALACHxx` and `QUALACHxxNOTES`.
=> Bulk upload max quals

server/models/BulkImport/csv/workers.js, server/routes/reports/localAuthorityReport/admin.js
https://trello.com/c/lhVVjVVb
Although this defect was raised against the LA Admin report, the actual defect was in the bulk upload Staff (Worker) downloaded CSV. Two of the records were effectively "Don't know" on the LA reports, but in Bulk Upload were output as empty; should output 999. Impacts both the "CONTHOURS" and "AVGHOURS" CSV column output data.
**During observations/reproducing the defect with Jackie, it is observed a spelling mistake one of the LA Admin columns. Corrected that as part of this PR.**
=> 20190909 bu la defects backend

server/config/config.js, server/routes/establishments/bulkUpload.js, server/routes/reports/localAuthorityReport/admin.js, server/routes/reports/localAuthorityReport/user.js
https://trello.com/c/H1CVyIKZ
Increasing the endpoint timeout for LA Admin report - the DB call takes a little over two minutes, the default Express timeout.
Note - whilst in there implementing endpoint timeout, have also added one to the Bulk Upload downloads - a focus of other performance discussions today - to complement the existing config property based timeouts on Bulk Upload `validation` and `completion`.
=> La admin report endpoint timeout

server/models/BulkImport/csv/establishments.js
https://trello.com/c/m8XEJyhS
Handling better when entity.[starters|leavers|vacancies] being null when downloading the Establishment CSV content.
=> HOTFIX - Bulk Upload F134107 failing on Download Workplaces

server/models/BulkImport/csv/establishments.js, server/models/classes/establishment/properties/staffProperty.js
Allowing "0" as valid numberOfStaff value when restoring StaffProperty from JSON. BU Establishment  validation to only allow 0 if main service head office.
=> HOTFIX Bulk Upload Head Office and Zero Staff

server/models/BulkImport/csv/establishments.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/S1ppD7YK
Adding a trap to prevent setting a status of delete on the primary establishment CSV record
Note - when testing the new validation message, I noticed that the validation message had `undefined` for the establishment name. It was missing the validation message `name` attribute.
As I copied the existing CSV `Establishment::missingPrimaryEstablishmentError` method, then I updated that method too to add the `name` attribute.
=> HOTFIX Preventing deleting primary establishment on BU upload

server/models/classes/establishment.js
https://trello.com/c/A5oyFId9
Missed a order by clause on the "fetch establishements" query that prevented the primary being at the top of the list so results.shift() returned a sub rather than the parent
=> added missing order by clause

package.json
This is related to the javascript heap error we have seen before during report testing. For some reason it is not in Live branch so i have intoduced this in Live and Develop branch
The trello card for this is here
https://trello.com/c/paUIdY08/392-user-unable-to-download-la-progress-for-large-establishments
The actualy issues details is here 
https://trello.com/c/wx98vIy4/896-daily-snapshot-report
As per container size of 4, i have set the nodejs value to 4096
=> this is to fix the memory heap issue with js

src/app/app-routing.module.ts, src/app/core/breadcrumb/journey.report.ts, src/app/core/guards/reports.guard.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/reports/pages/reports/reports.component.html, src/app/features/reports/pages/reports/reports.component.ts, src/app/features/reports/pages/wdf/wdf.component.ts, src/app/features/reports/pages/workplaces/workplaces.component.html, src/app/features/reports/reports-routing.module.ts, src/app/features/reports/reports.module.ts, src/app/features/workers/wdf-staff-summary/wdf-staff-summary.component.ts, src/app/features/workplace/workplace-routing.module.ts
WIP pr for ensuring that the reports landing page always displays primary workplace info. This meant relocating the reports routes outside of the workplace module and lots of subsquent refactoring afterwords.
the original issue is resolved, and I believe this is the most elegant fix. however as its my last day this branch should be picked up by another dev in order to iron out any routing issues [if they exist].
=> Bugfix | wdf report <-> parent sub routing

server/config/accessibility.yaml, server/config/config.js, server/config/development.yaml, server/config/localhost.yaml, server/config/preproduction.yaml, server/config/production.yaml, server/config/test.yaml, server/models/classes/establishment.js, server/models/classes/wdfCalculator.js, server/models/classes/worker.js, server/models/index.js, server/routes/establishments/bulkUpload.js
https://trello.com/c/ZXO2w83F
I've added a database connection pool acquire timeout of 60 seconds, changed the way transactions are managed when deleting an establishment and have added a new constructor parameter to the Establishment and Worker business objects so as to prevent the wdf calculation from being run when it shouldn't be in bulk upload to reduce the number of queries that get run
=> Bulk Upload Delete Error

src/app/features/reports/pages/wdf/wdf.component.ts
**Issue**
When confirming the Workplace details for WDF funds, the logic was checking against the current eligibility which included the eligibility of each Worker.
This meant that the confirming Workplace information would not be possible if you had Workers who were not eligible.
**Changes**
I have updated `displayConfirmationPanel` to check that the date the Workplace was last eligible is before the current effective from date.
=> Fix: WDF confirmation

src/app/features/workplace/view-all-mandatory-trainings/view-all-mandatory-training.component.html
**Issue**
When expanding mandatory training for a training category, the up to date status was not being shown.
**Work Done**
- Updated `view-all-mandatory-training.component.html` template to have the same logic as `training-and-qualifications-summary.component.html` for determining whether a worker has up to date training records.
=> Fix: Add up to date status to mandatory training table

src/app/features/reports/reports.module.ts, src/app/features/workplace/workplace.module.ts
**Issue**
It seems the `WdfWorkplaceConfirmationDialogComponent` was used on the WDF report page but was imported in the `workplace.module.ts` NgModule and not the `reports.module.ts`
I have checked the usage of this component and it looks like we can remove it from `workplace.module.ts`
The WDF dialog used in the components that are under `workplace.module.ts` is `WdfWorkerConfirmationDialogComponent` which is a different dialog.
**Work done**
- Moved `WdfWorkplaceConfirmationDialogComponent` to `reports.module.ts`
=> Fix: Confirm WDF dialog

src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.ts
**Issue**
The total # of records was subtracting the # of missing mandatory training records.
This meant that, if a worker had 1 training record and 1 missing training record, it'd calculate as 0.
**Work done**
- Removed missing training record number being included in the number of total records calculation.
=> Fix: Incorrect total count for Training & Qualifications

server/models/classes/training.js
**Issue**
The calculation of training records was incorrect - it was making it either the number of up-to-date records or the sum of expired/expiring/missing.
**Work done**
Updated the calculation to be a simple length of training records
=> Fix: Count of training and quals records for a worker

src/app/core/services/auth.service.ts, src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.ts, src/app/features/search/search.component.ts, src/app/features/workplace/workplace.module.ts, src/app/shared/shared.module.ts
This adds the capability for administrators to delete Workplaces.
The flow to do so is as follows:
- Click Search Establishments
- Search for Establishment, by postcode, ID, etc
- Click Establishment, this switches context to the Establishment
- Click Delete Workplace and Confirm
- This will _archive_ the Workplace and return the user to the Search Establishment screen with their original login context.
=> Allow Administrators to delete Workplaces

server/test/integration/routes/admin/approval/index.spec.js, server/test/unit/routes/admin/unlock-account/index.spec.js, server/test/unit/routes/establishments/worker.spec.js
**Issue:**
When running `npm run server:test` - if a method has already been stubbed in another file then sinon throws an error that it has already been wrapped.
**Work done:**
I have moved the stubs into a `before` and restored `sinon` after each test.
=> Fix: Test stubs

src/app/features/dashboard/home-tab/home-tab.component.html
Adding the link to mandatory training.    Follows the same viewing rules as canAddWorker.   Does that make sense or should I rename the canAddWorker Boolean?
=> Adding Mandatory training link to relevant links

package-lock.json, package.json, server.js, server/models/establishment.js, server/models/worker.js, server/models/workerTrainingCategories.js, server/routes/workerTrainingCategories.js, server/test/factories/models.js, server/test/integration/routes/trainingCategories/index.spec.js, server/test/unit/routes/trainingCategories/index.spec.js, server/transformers/trainingCategoryTransformer.js, src/app/core/services/training-category.service.ts, src/app/core/services/trainingStatus.service.ts, src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html, src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.spec.ts, src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.ts, src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.html, src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.ts, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.ts, src/app/shared/shared.module.ts
**Work done:**
- Added endpoint for getting a list of training categories with training & workers
- Updated `worker` model to associate training 
- Updated `workerTrainingCategories` model to associate mandatory training
- Updated `workerTrainingCategories` model to have a `findAllWithMandatoryTraining` method
- Updated `establishment` model to have a `findWithWorkersAndTraining` method
- Added a `trainingCategoryService` to talk to the new endpoint
- Added components to view training by category
- Added `trainingCategoryTransformer` to convert Sequelize data into a object for JSON
- Introduced `node-mocks-http` to easily mock Express requests
=> View training by categories

.cfignore
**Work done**
- Added a `.cfignore` to prevent `node_modules` being uploaded during `cf push`
**Why?**
To see if it improves time to deploy ;D
=> Add .cfignore

package.json
**Issue:**
GovPaaS runs `ng build` when deploying but we don't need to because Travis has already run it
=> We don't need to build to run the server

.cfignore, package.json
GovPaaS cannot find Express - even though it runs `npm install`.
Super confusing.
Reverting so as to not block the pipeline
=> Remove .cfignore and revert npm start

package.json
Investigating the logs for deployment, it actually tries to do a health check while running `ng build`
The startup script should only run the server
=> Remove npm run build from startup script

src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html, src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.ts, src/app/shared/components/training-and-qualifications-summary/training-and-qualifications-summary.component.html, src/app/shared/components/training-and-qualifications-tab/training-and-qualifications-tab.component.html
**Work done:**
- Fixed sizing of View by staff name / View by category links
- Removed `showViewByToggle` when viewing training by category - this is not needed as the *ngIf in the parent component means it'd always be set to true so we can just show them.
=> Fix: Training by category links

src/app/shared/components/training-and-qualifications-categories/training-and-qualifications-categories.component.html
**Work done**
Fix issue where table cells were aligned in the middle, but needed to be aligned at the top - this was an issue when a training category had multiple training statuses (expired, expiring soon etc)
=> Fix: Alignment on training by category table

server/routes/workerTrainingCategories.js, server/test/integration/routes/trainingCategories/index.spec.js
**Issue**
When trying to get the training by category and there's no results returned from the database, it sends a 404, but it was sending back HTML instead of JSON.
=> Fix: Worker training categories 404

server/routes/workerTrainingCategories.js, server/test/unit/routes/trainingCategories/index.spec.js, server/transformers/trainingCategoryTransformer.js
**Issue**
When getting training by category, if a Workplace has no staff members, the endpoint was returning a 404 which was causing display issues.
**Work done**
- Amended `/api/trainingCategories/${establishmentId}/with-training` endpoint to return an empty array if the Workplace has no staff.
- Fixed 503 errors to return JSON headers
- Fixed issue checking `.length` on `trainingCategory.MandatoryTraining` if it didn't exist.
=> Fix: Issue where training by category endpoint returns a 404

server/routes/admin/cqc-status-change/index.js, server/routes/establishments/mainService.js, src/app/core/services/cqc-status-change.service.ts, src/app/features/workplace-find-and-select/select-main-service/select-main-service.ts
- Updated `setMainService` to create an Approval request when a Workplace changes their Main Service from a non CQC regulated service to a CQC regulated service.
- Fixed issue where approving a request wasn't working because the `updateMainService` function had been renamed
- Fixed issue where if you had set your Main Service to "Other" and filled out the text input and then tried to change from non CQC to CQC - it would try and pre-fill the form with the custom name but wouldn't find the input because the list of CQC services don't have the option of "Other"
=> Feat: Approval request to change Main Service to be CQC regulated

server/routes/establishments/mainService.js
**Issue**
When the main service is updated for a Workplace, there are properties which do not change but are needed in the response.
These include:
- OtherServices
- ShareData
- IsRegulated
- LocationId
**Work done**
- Updated `filteredProperties` to include the missing properties.
- Changed `toJSON` parameter to set `modifiedOnlyProperties` to false so that we can include properties that haven't been changed.
=> Fix: Missing data for consequential updates to a workplace when updating main service

src/app/features/workplace-find-and-select/select-main-service/select-main-service.component.html, src/app/features/workplace-find-and-select/select-main-service/select-main-service.ts, src/app/features/workplace/select-main-service/select-main-service-cqc-confirm.component.html, src/app/features/workplace/select-main-service/select-main-service-cqc.component.html, src/app/features/workplace/select-main-service/select-main-service-cqc.component.ts, src/app/features/workplace/select-main-service/select-main-service.component.ts, src/app/shared/components/submit-exit-buttons/submit-exit-buttons.component.html, src/app/shared/components/workplace-summary/workplace-summary.component.html, src/assets/scss/components/_buttons.scss
**Work done**
**Selecting a main service screen**
- Fixed issue where clicking an error message wasn't focusing on the related form element
- Added input error class to radio buttons
- Fixed `preFillForm` when selectedMainService wasn't available in the list of options (only happens when going from non CQC to CQC)
**Confirmation screen**
- Update `src/app/features/workplace/select-main-service/select-main-service-cqc-confirm.component.html` to use the grid system
**Yes/No screen**
- Updated `src/app/shared/components/submit-exit-buttons/submit-exit-buttons.component.html` to use the grid system
- Updated hint text to be a paragraph
=> Fix: Non CQC to CQC flow

server/routes/establishments/bulkUpload.js, server/test/unit/routes/establishments/bulkUpload.spec.js
Uses Worker.localIdentifier instead of Worker.key.
=> [## 16372 ##] Bulk upload pre populating the UNIQUEWORKERID on the training file

.circleci/config.yml
**Issue**
Looks like rfr is failing - it's treating the root as `/home/vcap/deps/0/` when the root should actually be `/home/vcap/app`
Trying to set the root as an environment variable to fix the issue
=> Fix: Deployment RFR

package-lock.json, package.json, server.js
**Work done**
- Added `compression` middleware in order to return gzip encoded responses.
=> Fix: Add gzip compression

index.html
**Work done**
- Remove meta tag that we used to get ownership of our GA account.
=> Fix: Remove GA meta for account ownership

.circleci/config.yml
**Context**
Currently, the dark/live deployments are based on the same domain.
However, in order to deploy to production, we need to be able to differentiate between `cloudapps.digital` and `skillsforcare.org.uk` for the dark/live config.
This PR introduces the ability to set different dark/live domains to use in anticipation of production config
=> Fix: Split dark live domains

.circleci/config.yml
**Work done**
Tags by default are not built by Circle - however, if we have a job that requires other jobs, the required jobs also need to have the tag filter on them
=> Fix: Add tag filters to all jobs

.circleci/config.yml
**Issue**
If you stop an app that does not exist, the cf CLI tool will exit with an error code - by using `|| echo` we can make sure the exit code is 0.
If the app already exists, and it fails to stop - then `cf delete -f` will force delete the app anyway.
=> Fix: Check app exists before stopping it

.circleci/config.yml
**Work done**
- Fixed issue where unmapping the previous app domain returned an exit code of 1 if it did not exist
=> Fix: unmap route for previous version exit code

.circleci/config.yml
**Issue**
We changed the pre prod deployment to be based off the live branch rather than a tag but forgot to update the require block of the `hold_prod` step
=> Fix: Require step for prod deployment

src/app/features/bulk-upload/bulk-upload-references/bulk-upload-references.ts
**Work done**
- Changed the max length for workplace and staff references to be 50 characters.
This is inline with the bulk upload validation.
**Note**
I have checked with Jackie and the maximum reference in the current database is 50 characters for Workplaces and 49 characters for Staff
=> Fix: Update reference length for workplace/staff to be same as bulk upload

package-lock.json, package.json, server/routes/reports/wdf/parent.js
JSDom is no longer used in the project so removing as a dependency.
There was a require statement in `server/routes/reports/wdf/parent.js` but the variables weren't used
=> Fix: Remove JSDom

package-lock.json, package.json
We used to use `cross-env` in our `npm run start` command but this is no longer the case.
=> Fix: Remove cross-env dependency

package-lock.json, package.json
**Issue**
We removed `jsdom` which required in `request` as a dependency. However, in-between `jsdom` being installed and it being removed, `request` has been deprecated (Feb 2020).
As a result, `require` no longer installs automatically, but is required by `request-promise` which some of our deps use.
**Work done**
- Installed `request` manually
=> Fix: Request dependency

.circleci/config.yml
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2389
`circleci step halt` will stop the job from running, but not the entire workflow which is what we wanted to achieve.
=> Revert "Fix: Try halting the deployment if the workflow is for a PR"

.circleci/config.yml
The `CIRCLE_PULL_REQUEST` isn't set to the current PR for the workflow, it's set for an "associated PR for a branch"
If we merge a PR into `test` but there is an PR open for `test` (i.e `test > `live`) then the `CIRCLE_PULL_REQUEST` will still be set and therefore not deploy to staging.
What I was hoping for, was that `CIRCLE_PULL_REQUEST` wouldn't be set when merging into a branch but would be set when opening a PR.
Reverts NMDSdevopsServiceAdm/SopraSteria-SFC#2394
=> Revert "Fix: Skip Deploy/Release for PRs"

server/models/BulkImport/csv/establishments.js, server/test/unit/models/Bulkimport/csv/establishments-old.spec.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js
**Issue**
When doing a bulk upload, if `ALLJOBROLES` was an empty string, it was validating Starters, Leavers and Vacancies.
The reason it was still validating is because an empty string that is `.split` returns an array element of an empty string:
```
[""]
```
As a result, when doing a `.length` check to determine whether to run the validation rule, it was returning a length of 1 element.
**Work done**
In order to skip validation, I have wrapped the split in a ternary so that it will default to an empty array if ALLJOBROLES returns a falsey value.
```
console.log(allJobs);
// before: [""] 
// after: []
```
=> Fix: ALLJOBROLES Bulk Upload validation

src/app/features/search/search.component.html, src/app/features/search/search.component.ts
**Issue**
When an address had missing fields, it was being displayed on the search results as:
```
Address1, , ,
```
**Work done**
- Added function to build up address and filter falsey values.
- Updated template to use new address function
=> Fix: commas when address fields are empty when searching Workplaces

server/routes/admin/search/establishments/index.js
**Issue**
When expanding a Workplace on the search results page, the list of users also included those who are archived.
**Work done**
- Updated query to filter out archived users
=> Fix: Filter Archived users from Workplace search results

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks.spec.js, src/app/shared/components/benchmarks-tab/benchmarks-tab.component.html
=> Benchmarks Turnover: adding new type of stateMessage then turnover cant be calculated

src/app/features/search/search.component.html, src/app/features/search/search.component.spec.ts
**Work done**
- Added tests for the groups tab in the `SearchComponent`
- Used null propagation to guard against empty properties in the results object.
=> Feat: Add tests for SearchComponent Groups tab

karma.conf.js, package-lock.json, package.json
**Issue**
When writing tests locally, making changes involves waiting for a whole rebuild only to be told you've made a mistake in your set up / expectations etc.
As a result, writing new tests can be quite arduous.
After some investigating, if you have `autoWatch` set to `true` and `singleRun` set to true, then no tests will run.
However, you cannot override `singleRun` from the `ng test` command.
Given that `singleRun` is a config setting for when running tests in CI (to make it exit) - I have included the `is-ci` package so that we can set the values as required by CI.
The end result is:
Locally:
```
autoWatch: true,
singleRun: false,
```
in CI:
```
autoWatch: false
singleRun: true
```
Running `ng test` will now run the tests, wait for any changes then re-build / re-run the suite - the …
=> Fix Allow ng test to run in watch mode locally to speed up feedback loop

README.md, package.json
**Issue**
I noticed we had a `dev` command in package.json that wouldn't even work.
**Work done**
- Removed unused `dev` command from `package.json`
- Updated the README to reflect the changes we have made for local dev.
=> Fix: Tidy package json and update README

.eslintrc.js, angular.json, package-lock.json, package.json
**Work done**
- Running `ng lint` will now lint Angular using ESLint
=> Fix: Update ng lint to use eslint

.circleci/config.yml, package.json
**Issue**
v14 of Node was made LTS 2 days ago and that seems to coincide with when the issue with `ng build` started happening.
`ng build` also uses ~2GB of memory but the default is 1.5GB.
**Work done**
- Fixed `lts-browsers` image to use `12.19.0-browsers`
- Fixed `.circleci/config.yml` environment variable for `NODE_OPTIONS` to set the `--max-old-space`
- Added `--no-progress` to `ng build`
=> Fix: ng build

src/app/shared/components/tabs/tabs.component.html
**Issue**
When the tab is focused and has an alert flag, the highlight was also highlighting the icon.
If there was an icon that was the same colour it would not be visible.
**Work done**
- Moved the icon outside of the focus state.
=> Fix: Tab alert

src/app/core/services/pdf.service.ts
**Issue**
The `y` position for the PDF was starting at 20 in order to add spacing to the header, however this was creating an extra page (I think because this was pushing it past the A4 size)
**Work done**
- Changed the `y` position to be 0 and instead added a spacer above the header component
=> Fix: PDF spacing

src/app/core/test-utils/MockPermissionsService.ts, src/app/core/test-utils/MockUserService.ts, src/app/shared/components/user-accounts-summary/user-accounts-summary.component.spec.ts, src/app/shared/components/user-accounts-summary/user-accounts-summary.component.ts
If a workplace user doesn't have a name (this can only happen if the user was migrated) then the Add a user Button disappears.  Added a check to avoid this in the future.
- [x ] Yes
=> Bug/cant see add user: Fixing bug where User can't see Add a user button

server/utils/security/hasPermission.js
**Issue**
There is an issue on staging with the permissions not quite right that have not been tested.
However we also want to deploy a bunch of changes that are on staging.
Rather than undoing every change to the endpoints that have permission checks applied to them, I am making the request passthrough by calling `next()` and returning early.
Once `test` has been merged into `live` this PR will be reverted.
=> Fix: Skip permission check until bugs have been tested

package-lock.json, package.json
**Issue**
The AWS SDK was upgraded and for some reason it introduced a breaking change that prevented reports being uploaded to S3.
Unsure of the fix, so downgrading for now
**Work done**
- Downgrade `aws-sdk` from `v2.824.0` to `v2.712.0`
=> Fix: Downgrade aws-sdk to fix reports not downloading

package-lock.json, package.json
**Issue**
For some reason, the latest release of cheerio was giving us:
```
TypeError: data.replace is not a function
```
when compiling the XML
Would need to investigate further to determine what `data` is meant to be and why it's no longer working (it could be invalid XML etc)
**Work done**
- Downgraded `cheerio` from `v1.0.0-rc.5` to `v1.0.0-rc.3`
=> Fix: Downgrade cheerio

server/config/test.yaml
**Issue**
Moving the staging DB to GovPaaS means we no longer need SSL certificates to connect.
**Work done**
- Update `server/config/test.yaml`
- remove db name/user as these come from ENV
- set `client_ssl` status to `false` 
=> Fix: Remove db name/user from test config and set client_ssl to false

server/config/accessibility.yaml, server/config/config.js, server/config/development.yaml, server/config/localhost.yaml, server/config/preproduction.yaml, server/config/production.yaml, server/config/sequelize.js, server/config/test.yaml, server/models/index.js
**Issue**
Now that all DBs for the environments are in GovPaaS we no longer need to configure whether to use client certificates to connect to a DB instance.
**Work done**
- Removed `client_ssl` config
**Notes**
- The `client_ssl` config is still present in the CQCLocationAPI - we need to keep this until we refactor how location data is synced between environments
=> Feat: Remove client ssl config

.gitallowed, server.js
**Issue**
There was an update to the `Tracing` integration for Sentry which failed `ng build` - this was fixed in #2909
However, we also use Sentry on the Express app and the `Tracing` integration wasn't updated.
**Work done**
- Update `Tracing` integration for Sentry in `server.js`
=> fix(sentry): Fix tracing for Express app

src/app/features/bulk-upload-v2/bulk-upload-sidebar/bulk-upload-sidebar.component.html
**Issue**
About the bulk upload link in the sidebar of BU v2 had `dev` hardcoded.
**Work done**
- Updated BU v2 sidebar links to use relative URLs
=> Fix: BU v2 sidebar links

karma.conf.js
**Issue**
When running the tests, Chrome will start and then compile the assets before running the tests. However, the default timeout is 60s and the time to compile is ~90s.
There doesn't seem to be an elegant wait to wait for `ng build` before trying to run the tests.
**Work done**
- Have upped the `captureTimeout` to 120s
=> Fix: capture timeout for Karma

server/routes/establishments/index.js, src/app/core/resolvers/primary-workplace.resolver.ts
No data users can login and see workplace name
It shouldn't be like this, instead there should be a check to make sure
they have access to the correct permissions only, I have left a comment
on this for now
=> Removed canViewEstablishment permission from establishment endpoint

.nycrc, package-lock.json, package.json
**Issue**
Running `npm run server:test:coverage` was broken due to an issue with `nyc` and `typescript`
**Work done**
- Added `@istanbuljs/nyc-config-typescript` dependency
- Added `.nycrc` to extend the typescript config
=> Fix: Server coverage

src/app/app-routing.module.ts, src/app/core/services/dialog.service.ts, src/app/features/search/emails/dialogs/send-emails-confirmation-dialog/send-emails-confirmation-dialog.component.html, src/app/features/search/emails/dialogs/send-emails-confirmation-dialog/send-emails-confirmation-dialog.component.spec.ts, src/app/features/search/emails/dialogs/send-emails-confirmation-dialog/send-emails-confirmation-dialog.component.ts, src/app/features/search/emails/emails.component.html, src/app/features/search/emails/emails.component.spec.ts, src/app/features/search/emails/emails.component.ts, src/app/features/search/search.component.html, src/app/features/search/search.component.spec.ts, src/app/features/search/search.component.ts, src/app/features/search/search.module.ts
**Work done**
- Added `Emails` tab to admin navigation
- Initial template for sending emails to inactive workplaces
- Added dialog to confirm whether emails would be sent
**Note**
This is a static design of the Keep Workplaces Active screen and has no working functionality - merging into a feature branch rather than `test`
=> Feat: Keep Workplaces Active screen

.gitignore
**Issue**
Running `ng test --code-coverage` creates a folder `fecoverage` which was not git ignored
**Work done**
- Added `fecoverage` folder to `.gitignore`
=> Fix: Update .gitignore to include Angular code coverage

src/app/features/search/emails/emails.component.html, src/app/features/search/emails/emails.component.spec.ts
- Disable button if there are no inactive workplaces
- Add tests 
=> Feat: disable 'Send emails' button when there are no inactive workplaces

src/app/features/dashboard/home-tab/home-tab.component.spec.ts, src/app/features/dashboard/home-tab/home-tab.component.ts
**Issue**
In most components, we have a `.subscribe()` Observable that makes an API request and then updates the UI with data from the response.
However, some of the variables that are updated by the response have a default value, and this means we end up with a scenario of:
```
updateStaffRecords = true
.subscribe(() => {
updateStaffRecords = false
}
```
When this is the case, the initial rendering of the UI displays a banner that tells the user they need to add staff records even though the API request to get the staff records hasn't finished. Once it has finished, the banner disappears.
By removing the default value we then end up with:
```
updateStaffRecords = undefined
.subscribe(() => {
updateStaffRecords = false
}
```
When a variable is undefined, the UI will wait until it has been …
=> Fix: Loading states for home tab

package-lock.json, package.json, server/config/config.js, server/routes/admin/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js, server/routes/admin/email-campaigns/inactive-workplaces/index.js, server/routes/admin/email-campaigns/inactive-workplaces/report.js, server/routes/admin/email-campaigns/inactive-workplaces/sendEmail.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/sendEmail.spec.js, server/test/unit/utils/email/sendInBlueEmail.spec.js, server/utils/email/sendInBlueEmail.js
- Add Send In Blue SDK
- Update `createCampaign` endpoint to send emails
- Changed named imports in order to stub using `sinon`
=> Feat: keep workplaces active Send In Blue

migrations/20210302141451-create_last_updated_establishments_view.js, server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js, server/routes/admin/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js, server/routes/admin/email-campaigns/inactive-workplaces/index.js, server/routes/admin/email-campaigns/inactive-workplaces/report.js, server/routes/admin/email-campaigns/inactive-workplaces/sendEmail.js, server/test/unit/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/report.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/sendEmail.spec.js, src/app/features/search/emails/emails.component.ts
**Work done**
- Added `LastUpdatedEstablishments ` view to store Workplace information and when they were last updated
- Implemented `findInactiveWorkplaces`
- Updated `sendEmails` function to use `switchMap` in order to get latest # of inactive workplaces after creating the campaign
- Fixed issue where API would respond before finishing inserting campaign history (this was a bug that meant the UI would not update when re-sending a request)
=> Feat: Keep workplaces active - Calculate inactive workplaces

server/config/config.js, server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js, server/test/unit/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.spec.js
**Work done**
- Added function to calculate next email template
- Filter workplaces who have already been sent an email
- Removed  `LastEmailedDate` and `EmailCount` as these are no longer needed
=> Feat: Calculate which email template to send

src/app/app.module.ts, src/app/core/guards/bulk-upload/bulk-upload-missing.guard.ts, src/app/core/guards/bulk-upload/bulk-upload-start.guard.ts, src/app/features/bulk-upload-v2/admin-skip.service.ts, src/app/features/bulk-upload-v2/bulk-upload-missing/bulk-upload-missing-page.component.spec.ts, src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.spec.ts, src/app/features/bulk-upload-v2/bulk-upload-page/bulk-upload-page.component.ts, src/app/features/bulk-upload-v2/bulk-upload-references/missing-staff-references/missing-staff-references-page.component.spec.ts, src/app/features/bulk-upload-v2/bulk-upload-references/missing-staff-references/missing-staff-references-page.component.ts, src/app/features/bulk-upload-v2/bulk-upload-references/missing-workplace-references/missing-workplace-references-page.component.spec.ts, src/app/features/bulk-upload-v2/bulk-upload-references/missing-workplace-references/missing-workplace-references-page.component.ts, src/app/features/bulk-upload-v2/bulk-upload-references/staff-references/staff-references-page.component.spec.ts, src/app/features/bulk-upload-v2/bulk-upload-references/workplace-references/workplace-references-page.component.spec.ts, src/app/features/bulk-upload-v2/bulk-upload-start-page/bulk-upload-start-page.component.spec.ts
…… (#3092)
* Fix(buAdminSkipToBulkUploadPage): Add adminSkipService to skip through to bulk upload page after skipping through missing references
* Fix(buAdminSkipToBulkUploadPage): Add adminSkipService to dependencies in bulk upload tests
* Fix(buAdminSkipToBulkUploadPage): Add ngOnDestroy to bulk upload page so after leaving page, going on bulk upload again would return you to the missing refs page
=> Live: Admin Skip button on bulk upload

server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js, server/test/unit/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.spec.js
**Issue**
The logic to determine whether an inactive workplace should be emailed also included those in-between 6/12/18/24 months
**Work done**
- Fixed logic to only include workplaces if they have been inactive in the same month & year as 6/12/18/24 months ago
=> Fix: Date range for inactive workplaces

server/config/config.js, server/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.js, server/routes/admin/email-campaigns/inactive-workplaces/index.js, server/routes/admin/email-campaigns/inactive-workplaces/report.js, server/routes/admin/email-campaigns/inactive-workplaces/sendEmail.js, server/test/unit/models/email-campaigns/inactive-workplaces/findInactiveWorkplaces.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/report.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/sendEmail.spec.js
**Issue**
The template column in the Inactive Workplaces report was the ID for Send in Blue which wasn't helpful.
**Work done**
- Replaced the ID of the template with the name of the template
=> Feat: Replace template id with name in the inactive workplace report

server/utils/email/sendInBlueEmail.js
**Issue**
The way in which JS requires code means that the API key for Send in Blue was being set before AWS Secrets Manager had responded with the config value.
We need to listen for `AppConfig's` `READY_EVENT` in order to set it after AWS has returned.
**Work done**
- Used `AppConfig` to update the API key once AWS has responded with the secrets
=> Fix: AWS Secrets for Send in Blue

server/aws/secrets.js, server/config/config.js, server/services/email-campaigns/inactive-workplaces/nextEmail.js, server/test/unit/services/email-campaigns/inactive-workplaces/nextEmail.spec.js
**Issue**
In order to test Keep Workplaces Active, we don't want to send emails unless they have been whitelisted.
**Work done**
- Add send in blue whitelist config
- Only include emails in the whitelist if it has been set
=> Fix: Only email workplaces in the whitelist

migrations/20210316155005-update_last_updated_establishments_view.js
**Issue**
We use a Materialized View to store the list of workplaces and their last updated date / who to email etc.
However they were also including workplaces that have been archived
Given Sequelize adds `"Archived" = false` as a default scope for all of the queries so we don't have to think about that, it didn't register!
**Work done**
- Re-created `LastUpdatedEstablishments` view to only include Workplaces who are not archived.
=> Fix: Remove Archived workplaces from the KWA view 

server/aws/secrets.js
**Issue**
`SEND_IN_BLUE_WHITELIST` was missing from `myLocalSecrets` object.
Not sure why `myLocalSecrets` can't be set to `mySecrets` - it's a 1-1 mapping, but it may be intentional.
**Work done**
- Added `mySecrets.SEND_IN_BLUE_WHITELIST` to `myLocalSecrets`
=> Fix: Send in Blue whitelist not being set from AWS secrets

server/services/email-campaigns/inactive-workplaces/nextEmail.js, server/services/email-campaigns/inactive-workplaces/sendEmail.js, server/test/unit/services/email-campaigns/inactive-workplaces/nextEmail.spec.js, server/test/unit/services/email-campaigns/inactive-workplaces/sendEmail.spec.js
**Issue**
We added the whitelisting logic to the place where we decide whether a workplace should be sent an email, but this meant that workplaces would be filtered out in the report etc.
**Work done**
- Moved the whitelisting logic to when the emails are actually sent
=> Fix: Only whitelist when sending email

migrations/20210316155005-update_last_updated_establishments_view.js, server/aws/secrets.js, server/config/config.js, server/services/email-campaigns/inactive-workplaces/nextEmail.js, server/services/email-campaigns/inactive-workplaces/sendEmail.js, server/test/unit/services/email-campaigns/inactive-workplaces/nextEmail.spec.js, server/test/unit/services/email-campaigns/inactive-workplaces/sendEmail.spec.js
**Changes introduced**
- Add a Send in Blue whitelist for staging and pre-prod
- Filter out archived workplaces in the `LastUpdatedEstablishments` view
=> Live: Exclude Archived workplaces & add Send in Blue whitelist

server/config/config.js, server/models/email-campaigns/inactive-workplaces/getParentWorkplaces.js, server/models/emailcampaign.js, server/routes/admin/email-campaigns/inactive-workplaces/index.js, server/services/email-campaigns/inactive-workplaces/findParentWorkplaces.js, server/services/email-campaigns/inactive-workplaces/sendEmail.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js, server/test/unit/services/email-campaigns/inactive-workplaces/findParentWorkplaces.spec.js, server/test/unit/services/email-campaigns/inactive-workplaces/sendEmail.spec.js, src/app/features/search/emails/emails.component.html
- Add parent template to config
- Update endpoints and `sendEmail` function to send email to both inactive and parent workplaces
- Filter out parent workplaces/subsidiaries that have updated in the last 6 months
- Add tests
- Reverse history table so that the newest campaign is shown first
=> Feat: Keep Workplaces Active - Update endpoints for parents

server/models/email-campaigns/inactive-workplaces/getInactiveWorkplaces.js
**Issue**
The Workplace ID in the Inactive Workplace report has spaces in it, which makes it hard to cross reference with other reports (like the deletion report etc)
**Work done**
- Removed spaces from either side of the Workplace ID by using `TRIM`
=> Fix: use TRIM to remove whitespace from either side of Workplace ID

server/reports/inactive-workplaces/index.js, server/reports/inactive-workplaces/parents.js, server/reports/inactive-workplaces/subsidiaries.js, server/reports/inactive-workplaces/workplaces.js, server/routes/admin/email-campaigns/inactive-workplaces/report.js, server/test/unit/reports/inactive-workplaces/parents.spec.js, server/test/unit/reports/inactive-workplaces/subsidiaries.spec.js, server/test/unit/reports/inactive-workplaces/workplaces.spec.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/report.spec.js
**Work done**
- Added parents and subsidiaries worksheets to the Inactive Workplaces report
- Moved the code needed to build the report to `server/reports/inactive-workplaces`
=> Keep Workplaces Active - Parent Report

server/services/email-campaigns/inactive-workplaces/nextEmail.js, server/test/unit/services/email-campaigns/inactive-workplaces/nextEmail.spec.js
**Issue**
- If a workplace had been more than 24 months inactive, they were not being included in the report.
**Work done**
- Added a `matches` function to each of the templates
- Refactored `getTemplate` to use `matches` function
- 
=> Fix: 24 months plus inactive

server/routes/admin/email-campaigns/inactive-workplaces/index.js, server/services/email-campaigns/inactive-workplaces/findParentWorkplaces.js, server/test/unit/routes/admin/email-campaigns/inactive-workplaces/index.spec.js, server/test/unit/services/email-campaigns/inactive-workplaces/findParentWorkplaces.spec.js
**Issue**
When the query from the database returns a subsidiary and then a parent, the server returns `Cannot read property 'subsidiaries' of undefined` because we are trying to add it to the parent object in the array which doesn't exist yet.
The reason Back to admin didn't work is because the endpoint wasn't using `try/catch` and so it just hung around waiting for a response.
**Work done**
- Updated `buildWorkplaces ` to use `||` in order to set the object before accessing it.
- Updated `api/admin/email-campaigns/inactive-workplaces` endpoint to use `try/catch` so that the request returns a 503 when a promise is rejected
=> Fix: Subsidiaries undefined error

server/reports/inactive-workplaces/subsidiaries.js
**Issue**
We don't need the email template column for the subsidiaries worksheet as they'll be included in the parent email
**Work done**
- Removed email template column from subsidiaries worksheet
=> Fix: Remove email template column from subsidiaries

src/assets/scss/components/_summary-list.scss
Fix the shade of a couple of the orange warning banners that were missed
=> Accessibility audit: Fix shade of orange banners

migrations/20210422101858-update_last_updated_establishments_view.js, server/models/email-campaigns/inactive-workplaces/getInactiveWorkplaces.js, server/models/email-campaigns/inactive-workplaces/getParentWorkplaces.js
**Issue**
The query to calculate the primary user was looking to the parent workplace if the subsidiary did not have a primary user.
This meant that we had a situation where parents would be emailed when a subsidiary owns their data but do not have a primary user
**Work done**
- Fixed `LastUpdatedEstablishments` view to not use the parent workplace primary user when there is no primary user for a subsidiary
- Updated queries to filter out workplaces where the primary user is empty 
**Note**
The reason we are filtering out empty primary users in our `SELECT` query is because the deletion report also uses the  `LastUpdatedEstablishments` view.
=> Fix: KWA Subsidiaries primary user being set to parent who may not own the data

src/app/core/model/wdf.model.ts, src/app/features/wdf/wdf-data/wdf-data.component.html, src/app/features/wdf/wdf-data/wdf-data.component.spec.ts, src/app/features/wdf/wdf-data/wdf-data.component.ts, src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.html, src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.ts, src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.html, src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.spec.ts, src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.ts, src/app/features/wdf/wdf-status-message/wdf-status-message.component.html, src/app/features/wdf/wdf-status-message/wdf-status-message.component.ts, src/app/features/wdf/wdf.module.ts
- Create new `wdfStaffSummaryComponent`
- Add conditional rendering of WDF eligibility status message
- Add conditional rendering of green ticks and orange flags on tabs and staff summary table
- Create `wdfEligibilityStatus` interface
=> Feat: WDF Staff Summary - meeting with changes

src/app/core/breadcrumb/journey.wdf.ts, src/app/core/model/establishment.model.ts, src/app/features/wdf/wdf-overview/wdf-overview.component.html, src/app/features/wdf/wdf-overview/wdf-overview.component.spec.ts, src/app/features/wdf/wdf-overview/wdf-overview.component.ts, src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.html, src/app/features/wdf/wdf-requirements-state/wdf-requirements-state.component.ts, src/app/features/wdf/wdf-routing.module.ts, src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.html, src/app/features/wdf/wdf-status-message/wdf-status-message.component.html, src/app/features/wdf/wdf-status-message/wdf-status-message.component.ts, src/app/features/wdf/wdf-workplaces-summary-table/wdf-workplaces-summary-table.component.html, src/app/features/wdf/wdf-workplaces-summary-table/wdf-workplaces-summary-table.component.spec.ts, src/app/features/wdf/wdf-workplaces-summary-table/wdf-workplaces-summary-table.component.ts, src/app/features/wdf/wdf-workplaces-summary/wdf-workplaces-summary.component.html, src/app/features/wdf/wdf-workplaces-summary/wdf-workplaces-summary.component.spec.ts, src/app/features/wdf/wdf-workplaces-summary/wdf-workplaces-summary.component.ts, src/app/features/wdf/wdf.module.ts
- Add sort by options for workplaces
- Refactor WDF requirements state component so it can be used for workplaces
- Add new message for parents in WDF status message component
- New workplaces summary page and workplaces summary table component
=> Feat: WDF Parent - Workplaces summary page

src/app/core/breadcrumb/journey.wdf.ts, src/app/features/wdf/wdf-data/wdf-data.component.ts, src/app/features/wdf/wdf-overview/wdf-overview.component.html, src/app/features/wdf/wdf-routing.module.ts, src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.ts, src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.spec.ts, src/app/features/wdf/wdf-staff-summary/wdf-staff-summary.component.ts, src/app/shared/components/staff-record-summary/staff-record-summary.component.ts
- Added staff records to parent breadcrumb journey
- Fix breadcrumbs for parents on WDF data page (parents were seeing breadcrumbs for standalone workplaces when viewing their own workplace)
- Set `exitUrl` and breadcrumbs on staff record page depending on if parent or standalone workplace
=> Feat: WDF parent staff records - happy path

src/app/features/wdf/wdf-data-status-message/wdf-data-status-message.component.html, src/app/features/wdf/wdf-data-status-message/wdf-data-status-message.component.ts, src/app/features/wdf/wdf-data/wdf-data.component.html, src/app/features/wdf/wdf-data/wdf-data.component.spec.ts, src/app/features/wdf/wdf-staff-record-status-message/wdf-staff-record-status-message.component.html, src/app/features/wdf/wdf-staff-record/wdf-staff-record.component.spec.ts, src/app/shared/components/staff-record-summary/personal-details/personal-details.component.html, src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.html, src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.spec.ts, src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.ts
- Add WDF data status messages for parents
- Update staff record status message
- Add logic to show the 'Add information' button when DOB and gender fields are empty
- Update 'view staff records' URL in staff mismatch message component depending on whether user is a parent or sub
=> Feat: WDF Parent - meeting with changes/not meeting

migrations/20210607093353-WdfEligibilityColumn.js, server/models/classes/worker.js, server/models/worker.js, server/routes/establishments/worker.js, server/test/unit/models/classes/worker.spec.js, server/test/unit/routes/establishments/worker.spec.js
- Add new `wdfEligible` column to the database and remove `currentWdfEligibiity` column
- Refactor save and load functions in `worker.js` to use `setWdfProperties`
- Use `wdfEligible` from database to determine if a worker is eligible for WDF for `viewAllWorkers` endpoint
- Delete unused function `recalcWdf` from `worker.js`
=> Bug: WDF Eligibility

src/app/features/wdf/wdf-data/wdf-data.component.spec.ts, src/app/features/wdf/wdf-data/wdf-data.component.ts
- Fixed an issue where staff tab had a tick when there were no workers
- Set `staffWdfEligibility` to false when there are no workers
=> Fix: WDF tab icon

src/app/features/dashboard/home-tab/home-tab.component.html
- Add check for workplace for related content and news in the home tab to keep admin home tab empty on login
=> fix(removeContentFromAdminHome)

src/app/shared/components/staff-record-summary/staff-record-summary.component.spec.ts, src/app/shared/components/staff-record-summary/staff-record-summary.component.ts
Fixing a bug where anytime you go onto a wdf staff page it would auto update the fields that dont need confirmation ( e.g date of birth), which in turn would change the Last Updated date for the staff without any user input.
Its now been checked so that this only happens once all other fields are up-to-date. 
There was also one field missing which has been added in.
Adding missing auto confirm field,
Moving auto confirm to only happen once every other field is confirmed.
adding tests
=> Auto confirm fix

server/models/emailcampaign.js, server/models/user.js, server/routes/admin/email-campaigns/inactive-workplaces/index.js, server/routes/admin/email-campaigns/index.js, server/routes/admin/email-campaigns/targeted-emails/index.js, server/services/email-campaigns/inactive-workplaces/sendEmail.js, server/services/email-campaigns/isWhitelisted.js, server/services/email-campaigns/limit.js, server/services/email-campaigns/targeted-emails/sendEmail.js, server/test/unit/routes/admin/email-campaigns/targeted-emails/index.spec.js, server/test/unit/services/email-campaigns/inactive-workplaces/sendEmail.spec.js, server/test/unit/services/email-campaigns/isWhitelisted.spec.js, server/test/unit/services/email-campaigns/targeted-emails/sendEmail.spec.js, server/test/unit/utils/email/sendInBlueEmail.spec.js, server/utils/email/sendInBlueEmail.js, src/app/core/model/emails.model.ts, src/app/core/resolvers/admin/email-campaign-history.resolver.spec.ts, src/app/core/resolvers/admin/email-campaign-history.resolver.ts, src/app/core/resolvers/admin/email-template.resolver.spec.ts, src/app/core/resolvers/admin/email-template.resolver.ts, src/app/core/services/admin/email-campaign.service.spec.ts, src/app/core/services/admin/email-campaign.service.ts, src/app/features/search/emails/dialogs/send-emails-confirmation-dialog/send-emails-confirmation-dialog.component.html, src/app/features/search/emails/dialogs/send-emails-confirmation-dialog/send-emails-confirmation-dialog.component.spec.ts, src/app/features/search/emails/dialogs/send-emails-confirmation-dialog/send-emails-confirmation-dialog.component.ts, src/app/features/search/emails/emails.component.html, src/app/features/search/emails/emails.component.spec.ts, src/app/features/search/emails/emails.component.ts, src/app/features/search/search-routing.module.ts, src/app/features/search/search.module.ts
- Add functionality for admins to send emails to targeted users by selecting a user group and template
- Create `allPrimaryUsers` function in user model to get all primary users
- Add `getTemplates` function to get templates using Send In Blue API
=> Feat: Targeted emails

src/app/features/articles/article/article.component.html, src/app/shared/components/page/page.component.html, src/assets/scss/partials/_lists.scss
- Added class around CMS content
- Added SCSS to copy the govuk styles for `ul` and `ol` bulleted and numbers lists.
=> Added formatting for `UL` and `OL` in CMS content

migrations/20210621154154-eightWeeksFromFirstLogin.js, server/models/classes/establishment.js, server/models/establishment.js, server/routes/login.js, src/app/core/model/establishment.model.ts, src/app/features/dashboard/home-tab/home-tab.component.html, src/app/features/dashboard/home-tab/home-tab.component.spec.ts, src/app/features/dashboard/home-tab/home-tab.component.ts
- Added new column called `eightWeeksFromFirstLogin`
- Only show banner if it's after the `eightWeeksFromFirstLogin` date
- Added `eightWeeksFromFirstLogin` on first login
- Some of this I couldn't test due to the large nature of the whole function and how small my function was
=> New User not shown staff mismatch banner until 8w after first login

src/app/shared/components/eligibility-icon/eligibility-icon.component.html, src/app/shared/components/wdf-field-confirmation/wdf-field-confirmation.component.scss, src/app/shared/components/wdf-field-confirmation/wdf-field-confirmation.component.ts, src/assets/scss/modules/_utils.scss
Work done
- Moved asc-icon-align class into utils scss file
- Added asc-icon-align class to img in eligibility-icon and removed govuk__flex class
=> fix(wdfMeetingRequirementsAlignment): Fix icon alignment for add information message

src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.html, src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.spec.ts, src/app/shared/components/wdf-staff-mismatch-message/wdf-staff-mismatch-message.component.ts
- Changed the staff mismatch message to say 'delete more records' or 'add more records' depending on how many staff and records you have
- Removed the 'Either change the total or...' message when the total number of staff is set to zero
=> Fix: WDF staff mismatch message

src/app/shared/directives/user/security-question.directive.ts
- Removed the erroneous full stops at the end of 1 of the error messages due to a complaint by the content designer of the service.
- Removed the erroneous full stops at the end of another of the error messages due to a complaint by the content designer of the service.
=> Removed full stops from error messages

src/app/features/admin/admin-menu/admin-menu.component.html, src/app/features/admin/admin-menu/admin-menu.component.spec.ts
- Fixed admin links from `/admin` to `/sfcadmin`
=> Fixed links in admin menu

src/app/features/add-workplace/select-workplace/select-workplace.component.spec.ts, src/app/features/add-workplace/select-workplace/select-workplace.component.ts, src/app/features/registration/select-workplace/select-workplace.component.spec.ts, src/app/features/registration/select-workplace/select-workplace.component.ts, src/app/features/workplace-find-and-select/select-workplace/select-workplace.directive.ts
- Fix url on continue button for `select-workplace` page on registration and parent flow to be `new-select-main-service` if feature flag is on
=> Fix: Select workplace navigation

src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.spec.ts, src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts, src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.spec.ts, src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts, src/app/features/registration/select-workplace/select-workplace.component.html, src/app/features/workplace-find-and-select/select-workplace/select-workplace.component.html, src/app/features/workplace-find-and-select/select-workplace/select-workplace.directive.ts
- Add feature flag to navigation in `workplace-name-address` component to go to `new-select-main-service` page
- Fix links to workplace not found page
=> Fix: Workplace name address navigation

src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- Fixed an issue where the workplace name and address form wasn't prefilling workplace information on workplace tab
- Swapped `setupForm()` function with `init()` so that the form is set up before `prefillForm()` is run in `init`
=> Fix: Workplace name address form

src/app/core/model/admin/local-authorities-return.model.ts, src/app/features/admin/local-authorities-return/monitor/monitor.component.html, src/app/features/admin/local-authorities-return/monitor/monitor.component.spec.ts, src/app/features/admin/local-authorities-return/monitor/monitor.component.ts
- created a `toggleAll` function
- Added open to all areas to know whether it's dropped or not
- Added default data to the table
- Added drops to each heading
=> Added open/close functionality to monitor page

src/app/shared/components/staff-record-summary/staff-record-summary.component.ts
- For parents who only have read access looking at staff records of child workplaces in WDF, the `updateFieldsWhichDontRequireConfirmation` would still run if conditions met and the PUT would be unsuccessful and log out user 
- Add canEditUser check before automatically updating fields in staff record summary
=> hotfix(onlyAutomaticallyUpdateFieldsInStaffRecordSummaryWhenCanEdit)

src/app/shared/components/workplace-summary/workplace-summary.component.ts
- For parents who only have read access looking at child workplaces in WDF, the `updateEmployerTypeIfNotUpdatedSinceEffectiveDate` would still run if conditions met and the PUT would be unsuccessful and log out user 
- Add canEditEstablishment check before automatically updating fields in workplace summary
=> hotfix: Add canEditEstablishment check before automatically updating workplace fields in WDF

src/app/features/add-workplace/confirm-workplace-details/confirm-workplace-details.component.spec.ts, src/app/features/create-account/workplace/confirm-workplace-details/confirm-workplace-details.component.spec.ts, src/app/shared/directives/create-workplace/confirm-workplace-details/confirm-workplace-details.directive.ts
- Fix change link for non CQC regulated flow to go to `find-workplace-address` instead of `find-workplace`
=> Fix: Create account change links - non CQC regulated

src/app/features/add-workplace/find-workplace-address/find-workplace-address.component.spec.ts, src/app/features/add-workplace/find-workplace-address/find-workplace-address.component.ts, src/app/features/create-account/workplace/find-workplace-address/find-workplace-address.component.spec.ts, src/app/features/create-account/workplace/find-workplace-address/find-workplace-address.component.ts, src/app/shared/directives/create-workplace/find-workplace-address/find-workplace-address.ts
- Set back link on `find-workplace-address` component to confirm details url if you come from that page 
=> Fix: Find workplace address back link

src/app/core/test-utils/MockConfigCatClient.ts, src/app/core/test-utils/MockFeatureFlagService.ts, src/app/shared/services/feature-flags.service.ts
- Moved mockConfigCatClient from mockFeatureFlagsService into separate file
- Changed getValueAsync in mockConfigCatClient to return based on flag name
- Added environment check in featureFlagsService to pass in mockConfigCatClient when in other(localhost) environment
- Override getValueAsync in mockFeatureFlagsService to set flags to true for tests  
=> Tech debt/mock feature flag endpoint

src/app/core/test-utils/MockRegistrationService.ts, src/app/core/test-utils/MockWorkplaceService.ts, src/app/features/create-account/workplace/new-select-main-service/new-select-main-service.component.spec.ts, src/app/shared/directives/create-workplace/select-main-service/select-main-service.component.html, src/app/shared/directives/create-workplace/select-main-service/select-main-service.directive.ts
- Due to us using `updateOn: 'submit'` the value is not updated until submitted, to combat this we have to get the JS value of the option to know if it's checked or not
=> Fixed other services input not showing when selecting an other option

src/app/features/add-workplace/select-workplace/select-workplace.component.spec.ts, src/app/features/add-workplace/select-workplace/select-workplace.component.ts, src/app/features/create-account/workplace/select-workplace/select-workplace.component.ts, src/app/shared/directives/create-workplace/select-workplace/select-workplace.directive.ts
- Fix the url for the continue button on `select-workplace` page in `add-workplace` flow
=> Fix: select workplace continue button

src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.spec.ts, src/app/shared/directives/create-workplace/find-your-workplace/find-your-workplace.directive.ts
- Added a pattern validation to now allow special characters other than hyphens
=> Pattern Validation to only allow postcode and location ID's

src/app/features/add-workplace/select-workplace-address/select-workplace-address.component.ts, src/app/features/create-account/workplace/select-workplace-address/select-workplace-address.component.ts
- Set `workplaceNotFound$` to false on `select-workplace-address` page so that the back button on `workplace-name-address` takes you back to `select-workplace-address`
=> Fix: workplace name address back buttons

src/app/core/services/workplace-interface.service.ts, src/app/features/add-workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.spec.ts, src/app/features/add-workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.ts, src/app/features/add-workplace/find-workplace-address/find-workplace-address.component.spec.ts, src/app/features/add-workplace/new-workplace-not-found/new-workplace-not-found.component.spec.ts, src/app/features/add-workplace/workplace-added-thank-you/workplace-added-thank-you.component.spec.ts, src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts, src/app/features/create-account/workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.spec.ts, src/app/features/create-account/workplace/could-not-find-workplace-address/could-not-find-workplace-address.component.ts, src/app/features/create-account/workplace/find-workplace-address/find-workplace-address.component.spec.ts, src/app/features/create-account/workplace/new-workplace-not-found/new-workplace-not-found.component.spec.ts, src/app/features/create-account/workplace/thank-you/thank-you.component.spec.ts, src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts, src/app/shared/directives/create-workplace/could-not-find-workplace-address/could-not-find-workplace-address.directive.ts, src/app/shared/directives/create-workplace/find-workplace-address/find-workplace-address.ts, src/app/shared/directives/create-workplace/new-workplace-not-found/new-workplace-not-found.directive.ts
- Added a new behaviour subject in `workplaceInterfaceService` which is used to decide which radio buttons to pre fill on the `workplace-not-found` pages
- Added `prefillForm()` functions to `workplace-not-found` and `workplace-address-not-found`
- Update back link on `find-workplace-address` page so that it takes you back to the `workplace-address-not-found` page if that's where you came from
- Set `workplaceNotFound$` to false after setting back button in `workplace-name-address` to prevent back button loop
=> Fix: Prefill workplace not found

src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.spec.ts, src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.ts, src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.spec.ts, src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.ts, src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- Fixed an issue with `workplace-name-address` not pre filling the form at all for old flow
- Fixed an issue where the back button for the `workplace-name-address` page was disappearing because address line 2 and 3 didn't exist, so `prefillForm()` was erroring
=> Fix: pre filling workplace name address

migrations/20210819131429-addDeleteToUserAuditChangeType.js
- Fixed an issue where migrations were failing on staging because the enum label `delete` already exists
- Added a check to the migration to only add `delete` to the enum if it doesn't already exist 
=> Fix: Delete user migration

src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- After entering workplace details manually and continuing to the select main service page, if you pressed the back button twice it would take you to the `select-workplace` / `select-workplace-address` page where the information was empty, instead of to the `workplace-not-found` page
- Removed lines where `workplaceNotFound` was being set to false in the service as it gets set to false already when navigating to the `select-workplace` or `select-workplace-address` page
=> Fix: Workplace name address - back button

src/app/core/services/training.service.ts, src/app/features/add-multiple-training/select-staff/select-staff.component.html, src/app/features/add-multiple-training/select-staff/select-staff.component.spec.ts, src/app/features/add-multiple-training/select-staff/select-staff.component.ts, src/app/features/add-multiple-training/training-details/training-details.component.spec.ts, src/app/features/add-multiple-training/training-details/training-details.component.ts, src/app/shared/directives/add-edit-training/add-edit-training.component.html
- Reset `selectedStaff` in training service when pressing cancel on `Select staff` page
- Fix spacing between buttons on `Add training details` page
- Set back button to `Select staff` page from `Add training details` page
- Change `ngAfterContentInit()` to `ngAfterViewInit()` to fix validation highlighting not working
=> Fix: Multi Update - Snagging list

src/app/features/add-multiple-training/add-multiple-training.module.ts, src/app/features/add-multiple-training/select-staff/select-staff.component.html, src/app/features/add-multiple-training/select-staff/select-staff.component.spec.ts, src/app/features/add-multiple-training/select-staff/select-staff.component.ts, src/app/features/add-multiple-training/training-details/training-details.component.spec.ts, src/app/features/add-multiple-training/training-details/training-details.component.ts, src/app/shared/directives/add-edit-training/add-edit-training.component.html, src/app/shared/directives/add-edit-training/add-edit-training.directive.ts
- Use `[(ngModel)]` in form for select all checkbox instead of reactive form so that validation is updated on submit
- Reset selected staff in training service when pressing cancel on `add-training-details` page
=> Fix: Multi update

server/routes/reports/localAuthorityReport/admin.js, server/test/unit/routes/reports/localAuthorityReport/admin.spec.js
- Added `order by` to the admin LA report `SELECT` statement
=> Added order by to query for admin LA report

src/app/features/admin/registration-requests/registration-request/registration-request.component.spec.ts, src/app/features/admin/registration-requests/registration-request/registration-request.component.ts
- Add success alerts when registration is approved or rejected
=> feat: addSuccessAlertsForRegistrationApprovalAndRejection

src/app/features/add-workplace/add-workplace-routing.module.ts, src/app/features/add-workplace/add-workplace.module.ts, src/app/features/add-workplace/find-your-workplace/find-your-workplace.component.spec.ts, src/app/features/add-workplace/workplace-name-address/workplace-name-address.component.spec.ts, src/app/features/add-workplace/workplace-not-found/workplace-not-found.component.spec.ts, src/app/features/add-workplace/workplace-not-found/workplace-not-found.component.ts, src/app/features/create-account/workplace/find-your-workplace/find-your-workplace.component.spec.ts, src/app/features/create-account/workplace/workplace-name-address/workplace-name-address.component.spec.ts, src/app/features/create-account/workplace/workplace-not-found/workplace-not-found.component.spec.ts, src/app/features/create-account/workplace/workplace-not-found/workplace-not-found.component.ts, src/app/features/registration/registration-routing.module.ts, src/app/features/registration/registration.module.ts, src/app/shared/directives/create-workplace/find-your-workplace/find-your-workplace.directive.ts, src/app/shared/directives/create-workplace/workplace-name-address/workplace-name-address.ts
- Remove new from new-workplace-not-found component names and routing
- There's a workplace-not-found directive which is extended by components in different areas and new-workplace-not-found directive, out of scope of this ticket to refactor components to use same directive, will be raised as tech debt.
=> techDebt(removeNewFromWorkplaceNotFoundComponents)

server/routes/reports/trainingAndQualifications/parentReport/parentSummaryTab.js
- Error messages were appearing in Excel when downloading the report as there were duplicate column names (`Total`, `Mandatory` and `Non-mandatory`)
- Changed `parentSummaryTab` to add rows directly instead of using a table
=> Fix: Parent report - Summary tab

server/routes/establishments/trainingAndQualifications/getAllTrainingAndQualifications.js, src/app/core/breadcrumb/journey.workplaces.ts, src/app/features/workers/new-training-qualifications-record/new-qualifications/new-qualifications.component.html, src/app/features/workers/new-training-qualifications-record/new-qualifications/new-qualifications.component.ts, src/app/features/workers/new-training-qualifications-record/new-qualifications/new-qualifications.spec.ts, src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.html, src/app/features/workers/new-training-qualifications-record/new-training/new-training.component.html, src/app/features/workers/new-training-qualifications-record/new-training/new-training.component.spec.ts, src/app/features/workers/new-training-qualifications-record/new-training/new-training.component.ts
- Parents viewing a sub's training and quals information when they don't have edit worker permissions meant they couldn't access the new training and quals page
- Once accessing the page, they could still click on the training title to go to the edit page
- Changed `getAllTrainingAndQualifications` endpoint to check `canViewWorker` instead of `canEditWorker`
- Add new training page to `allWorkplacesJourney` breadcrumbs
- Changed the title in `new-training` and `new-qualifications` components to only be a link if you are an edit user
=> Bug - Parent training and quals page

src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.html
- Added `canEditWorker` input to `app-new-training` component where it had been missed
=> Fix: Mandatory training links

src/app/core/resolvers/training-record.resolver.ts, src/app/core/test-utils/MockWorkerService.ts, src/app/features/workers/add-edit-training/add-edit-training.component.spec.ts, src/app/features/workers/add-edit-training/add-edit-training.component.ts, src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.html, src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.spec.ts, src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.ts, src/app/features/workers/workers-routing.module.ts, src/app/features/workers/workers.module.ts, src/app/shared/directives/add-edit-training/add-edit-training.component.html, src/app/shared/directives/add-edit-training/add-edit-training.directive.ts
- Create `TrainingRecordResolver` for individual training record
- Rename titles in `add-edit-training` component to remove "Edit"
- Rename "Update training" button to "Save and return"
- Create `delete-record` component
=> Feat: Training delete button

src/app/core/resolvers/qualification.resolver.ts, src/app/core/test-utils/MockWorkerService.ts, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.html, src/app/features/workers/add-edit-qualification/add-edit-qualification.component.spec.ts, src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.html, src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.spec.ts, src/app/features/workers/new-training-qualifications-record/delete-record/delete-record.component.ts, src/app/features/workers/select-record-type/select-record-type.component.html, src/app/features/workers/workers-routing.module.ts, src/app/features/workers/workers.module.ts, src/app/shared/directives/add-edit-training/add-edit-training.component.html
- Create `QualificationResolver`
- Change heading titles and sizes for consistency on `add-edit-qualification` and `select-record-type` components
- Adapt `delete-record` component for deleting a qualification record
=> Feat: Qualifications delete button

migrations/20211115163843-allowNullInShareLaAndLocalAuthorities.js, server/models/classes/establishment/properties/shareWithProperty.js, server/models/establishment.js, server/test/unit/models/classes/establishment/properties/shareWithProperty.spec.js
- Added migration to allow null for ShareDataWithLA and ShareDataWithCQC
- Updated restoreFromJson in shareData property to return object with null values for cqc and localAuthorities
=> Fix: Allow null in ShareWithCqc and LA 

.vscode/settings.json
- Add formatOnSave to js and json files in vscode settings
=> Add formatOnSave to js and json files in vscode settings

server/test/factories/models.js, src/app/shared/components/workplace-summary/workplace-summary.component.html, src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts
- Added Not sharing to Data sharing section of workplace summary to display when user has selected No to sharing data with the CQC or local authorities 
=> Feat: Sharing permissions in workplace summary

server/models/BulkImport/csv/workers.js, server/test/unit/models/Bulkimport/csv/workers.spec.js
- If a user updates a worker to be a registered manager but uploads the workplace file with the establishment as `UNCHECKED` or `NOCHANGE`, we get the error `Workers MAINJOBROLE is Registered Manager but you are not providing a CQC regulated service` even if the establishment is CQC regulated
- Create `checkEstablishmentRegulated` function which checks if the workplace is regulated in the database
- Add `UNCHECKED` and `NOCHANGE` to switch statement so that in these cases, we can still verify that the establishment is regulated
- Remove duplicate test
=> Spike: Bulk Upload - Workplace status

server/models/classes/establishment.js
- When a user updated an establishment in bulk upload, they would still have the update your sharing permissions banner when they go onto the workplace tab
- Set showSharingPermissionsBanner to false when establishment updated in bulk upload
=> Fix: Set showSharingPermissionsBanner to false when establishment updated in bulk upload

server/models/BulkImport/csv/establishments.js, server/routes/establishments/bulkUpload/validate/validateEstablishmentCsv.js, server/test/unit/models/Bulkimport/csv/establishments.spec.js, server/test/unit/routes/establishments/bulkUpload.spec.js
- When doing a Bulk Upload, the address fields other than address1 were not getting updated. This was due to the establishment toAPI function creating fields which were uppercase, meaning the fields were not getting updated in the properties, as the properties restore from the document based on lowercase fields.
- Updated toAPI in bulk import establishments to have lower case fixed properties to match lower case fields in restoreFromJson functions in properties
=> Bug: Bulk Upload not uploading full addresses

migrations/20211208143300-expiresSoonAlertDates.js, server/models/establishment.js, server/routes/establishments/expiresSoonAlertDates.js, server/routes/establishments/index.js, server/routes/longTermAbsence.js, server/test/unit/routes/establishments/expiresSoonAlertDates.spec.js, src/app/core/resolvers/expiresSoonAlertDates.resolver.ts, src/app/core/services/establishment.service.ts, src/app/core/test-utils/MockEstablishmentService.ts, src/app/features/workplace/change-expires-soon-alerts/change-expires-soon-alerts.component.html, src/app/features/workplace/change-expires-soon-alerts/change-expires-soon-alerts.component.spec.ts, src/app/features/workplace/change-expires-soon-alerts/change-expires-soon-alerts.component.ts, src/app/features/workplace/workplace-routing.module.ts, src/app/features/workplace/workplace.module.ts
- New migration to add `ExpiresSoonAlertDate` column and set default to `'90'`
- Create db call to get the expires soon alert date
- Create `getExpiresSoonAlertDate` and `setExpiresSoonAlertDate` endpoints
- Create new component and resolver
=> Feat: Change expires soon alerts

migrations/20211214152944-archivingRejectedWorkplaces.js, server/routes/admin/approval/index.js, server/test/unit/routes/admin/approval/index.spec.js
- When rejecting a workplace, the status was being set to `REJECTED` but it wasn't being archived, so it still appeared in reports and the CQC location ID wasn't being archived
- Add `archived: true` when rejecting a workplace or user
=> Bug: archiving rejected workplaces

server/models/classes/establishment.js, server/routes/registration.js
- When creating a new workplace, the `ExpiresSoonAlertDate` column was being set to null instead of 90
- Set ExpiresSoonAlertDate to `'90'` when creating new account
=> Bug: Registrations expires soon date

src/app/features/workers/add-edit-training/add-edit-training.component.spec.ts, src/app/features/workers/new-training-qualifications-record/new-training-and-qualifications-record.component.ts, src/app/shared/directives/add-edit-training/add-edit-training.directive.ts
- When clicking the cancel button after being on the training categories page, `previousUrl` was being set correctly to the `/dashboard?view=categories#training-and-qualifications` url but Angular was converting special characters like `=` to `%3D` when navigating which meant the page didn't exist 
- Use `navigateByUrl` instead of `navigate` to prevent special characters from changing
- Add `setReturnRoute` to `OnInit` in new training component
=> Bug: Training cancel button

server/routes/accounts/user.js, server/test/unit/routes/accounts/user.spec.js
- Moved user limit check to another function
- Added no limit for admin users
- Added tests for max users function
=> Allowed admins to add unlimited users, other users should use preset limits

server/routes/accounts/user.js, server/routes/registration.js
- Added CanManageWdfClaims to user creation in user and registration files to default to false when not in req
- Issue - CanManageWdfClaims does not allow null in user table, so field must be set on creation of user
=> Fix: Handle CanManageWdfClaims in user creation

server/test/unit/routes/establishments/benchmarks/usage.spec.js
- Changed test to use getCall and deep equal comparison (it looks like it was failing because of the object comparison of the moment date)
=> fix: Flaky Benchmarks Viewed Test

src/app/core/breadcrumb/journey.workplaces.ts, src/app/features/add-mandatory-training/add-and-manage-mandatory-training/add-and-manage-mandatory-training.component.ts, src/app/features/add-mandatory-training/add-mandatory-training.component.html, src/app/features/add-mandatory-training/add-mandatory-training.component.spec.ts, src/app/features/add-mandatory-training/add-mandatory-training.component.ts
- Fixed navigation when a parent is accessing mandatory training on a child account
=> Fix/add mandatory training parent navigations Fix/stop new mandatory training prefill

src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.html, src/app/features/new-dashboard/benchmarks-tab/comparison-group-header/comparison-group-header.component.html, src/app/features/new-dashboard/benchmarks-tab/comparison-group-header/comparison-group-header.component.spec.ts, src/app/features/new-dashboard/benchmarks-tab/comparison-group-header/comparison-group-header.component.ts, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.html, src/app/shared/components/benchmarks-tab/comparison-group-header/comparison-group-header.component.spec.ts
- add conditional to text shown on the benchmarks header depending on the viewing permissions
=> add text to benchmarks comparison header

src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.spec.ts, src/app/features/new-dashboard/home-tab/summary-section/summary-section.component.ts
https://trello.com/c/qcFUOofY/1218-new-homepage-design-training-and-quals-message-1
-Updated message 1 to use staffMissingMandatoryTraining property rather than missingMandatoryTraining property
=> changed condition on message 1

src/app/features/dashboard/dashboard.component.html, src/app/features/dashboard/dashboard.component.spec.ts, src/app/features/dashboard/dashboard.component.ts, src/app/features/new-dashboard/dashboard/dashboard.component.html, src/app/features/new-dashboard/data-area-tab/data-area-tab.component.html, src/app/features/new-dashboard/data-area-tab/data-area-tab.component.ts, src/app/shared/components/benchmarks-select-view-panel/benchmarks-select-view-panel.component.html
- Allow establishments that are using the old dashboard to see the data area if they are in the [1,2,8] service club.
=> data area to also be viewed on the old dashboard

server/routes/establishments/benchmarks/index.js, server/test/unit/routes/establishments/benchmarks/index.spec.js
- Fix to get meta data to handle when no comparison groups instead of blowing up.
=> fix get meta data to handle when no comparison groups

src/app/shared/components/data-area-tab/data-area-tab.component.html, src/app/shared/components/data-area-tab/data-area-tab.component.ts
- As part of [1244-data-area-r-r-comparison-box](https://trello.com/c/Henb9YIy/1244-data-area-r-r-comparison-box)
- Add local authority and comparison group data to select box and dynamic text at the top of data area page
=> 1244 comparison box r and r

src/app/app-routing.module.ts, src/app/app.module.ts, src/app/core/model/benchmarks.model.ts, src/app/core/resolvers/rankings.resolver.spec.ts, src/app/core/resolvers/rankings.resolver.ts, src/app/core/services/benchmarks.service.ts, src/app/core/test-utils/MockBenchmarkService.ts, src/app/shared/components/benchmark-metric/ranking-content/ranking-content.component.ts, src/app/shared/components/benchmarks-tab/rankings/rankings.component.html, src/app/shared/components/benchmarks-tab/rankings/rankings.component.spec.ts, src/app/shared/components/benchmarks-tab/rankings/rankings.component.ts, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.spec.ts, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.ts, src/app/shared/components/data-area-tab/data-area-tab.component.html, src/app/shared/components/data-area-tab/data-area-tab.component.ts
- Work as part of [1251-data-area-pay-where-you-rank](https://trello.com/c/CpOIZOJT/1251-data-area-pay-where-you-rank)
- Adds the rankings resolver to get all rankings data. 
- Passes the rankings response to the pay data area
- Sets pay data in the pay data area component
- 
=> Add rankings resolver and set pay rankings data on data area pay

server/routes/establishments/benchmarks/rankings/index.js, src/app/core/model/benchmarks.model.ts, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart-options-builder.ts, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.html, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.spec.ts, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.ts, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.html
- As part of [1257-data-area-pay-where-you're-positioned](https://trello.com/c/VhCu7mXF/1257-data-area-pay-where-youre-positioned)
- Add all values of the current establishment to rankings response when there are no comparison group data.
- Update bar chart component to use the rankings data from the backend.
Bar chart when data is available
Bar chart when there is no comparison group data
Bar chart when there is no workplace data
=> Update bar chart component to use rankings data from backend

src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart-options-builder.ts, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.html, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.spec.ts, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.ts, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.html, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.spec.ts, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.ts, src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking.component.html, src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking.component.spec.ts, src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking.component.ts, src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruiment-and-retention.component.ts, src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruitment-and-retention.component.html, src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruitment-and-retention.component.spec.ts
- For ticket [1276-data-area-not-enough-data-added-for-workplace-and-comparator-group](https://trello.com/c/7IVEOb38/1276-data-area-not-enough-data-added-for-workplace-and-comparator-group)
- Add no comparison group and workplace message to rankings and bar chart components.
- Add handling in bar charts options to display an empty bar chart when no data is available.
=> 1276 data area not enough data added for workplace and comparator group

src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.html, src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.spec.ts, src/app/shared/components/data-area-tab/about-the-data-link/about-the-data-link.component.ts, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.html, src/app/shared/components/data-area-tab/data-area-barchart/data-area-barchart.component.spec.ts, src/app/shared/components/data-area-tab/data-area-pay/data-area-pay.component.html, src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking.component.html, src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking.component.spec.ts, src/app/shared/components/data-area-tab/data-area-ranking/data-area-ranking.component.ts, src/app/shared/components/data-area-tab/data-area-recruitment-and-retention/data-area-recruitment-and-retention.component.html, src/app/shared/components/data-area-tab/data-area-tab.component.html, src/app/shared/components/data-area-tab/data-area-tab.component.spec.ts, src/app/shared/components/data-area-tab/data-area-tab.component.ts, src/app/shared/shared.module.ts
- For the ticket [here](https://trello.com/c/PNKtjACC/1301-benchmarks-text-changes)
- Update text on ranking and bar chart when no workplace data is available for vacancy, turnover or time in role
- Create about the data link component
=> 1301 benchmarks r and r text changes

src/app/shared/components/new-dashboard-header/dashboard-header.component.html, src/app/shared/components/new-dashboard-header/dashboard-header.component.scss
- Issue showing longer workplace names as stated [here](https://trello.com/c/Nd44r5na/1302-51543-full-workplace-name-not-showing)
- Move delete workplace button on admin view
=> Adjust css for longer workplace names

src/app/app-routing.module.ts
- Bug fix. Sub establishments pages were not being displayed correctly when navigating from a parent.
This was due to the resolvers needed to get the data for the data area tab were not added to the workplace pages routes.
- This PR adds those resolvers onto the workplace routes.
=> Add data area resolvers to workplace routes

server/routes/establishments/benchmarks/index.js
- Bug fix where Recruitment and retention benchmark data was not being returned from backend route. 
- Issue was cssr param being passed as worker Id by mistake. 
- Reordered params to avoid this in future as only workId can be undefined which is handled within the function. 
###TODO
**Once this PR is merged this bug fix should also be merged back into the staging/test branch.** 
=> Move position of cssr and workerId params to avoid mistakes when calling

server/config/config.js
- Reverted the environment variables to Redis & Postgresql as it breaks the environment. Will change these back post migration.
=> Revert Redis and PG environment varibles

server/routes/establishments/benchmarks/benchmarksService.js, server/routes/establishments/benchmarks/rankings/index.js
- Reduce the number of calls to the cssr service by moving call up into the get rankings route function and out of the individual functions for Pay, Sickness etc.
=> Move cssr service call up into the get rankings function

server/models/establishment.js, server/routes/postcodes.js, server/test/unit/routes/establishments/updateSingleEstablishmentField.spec.js, server/test/unit/routes/postcodes.spec.js
- Add getAddressAPI all if postcode not found on create
- Add transformer for response
- Stub tests to not communicate with getAddress
- Handle no responses from getAddressAPI
=> Add get address to create account postcode lookup

buildspec/build.yml, buildspec/deploy-backend.yml, buildspec/deploy-frontend.yml, buildspec/test-frontend.yml, buildspec/test-performance.yml
- Changed the ecr uri from nonprod to build and deploy 
- Changed the s3 bucket name from nonprod to build and deploy 
- Removed npm ci from test pipelines in favour of using cache
- Removed base directory so we could include all build files from cache
=> Buildspec files are now compatible with running on build and deploy

buildspec/deploy-prod.yml
- Created buildspec file to deploy application code to production environment 
=> Create buillspec to deploy code to production

src/app/core/test-utils/MockReportService.ts, src/app/features/wdf/wdf-data-change/wdf-data/wdf-data.component.spec.ts, src/app/features/wdf/wdf-data-change/wdf-overview/wdf-overview.component.spec.ts, src/app/features/wdf/wdf-data-change/wdf-parent-status-message/wdf-parent-status-message.component.html, src/app/features/wdf/wdf-data-change/wdf-staff-record/wdf-staff-record.component.spec.ts, src/app/features/wdf/wdf-data-change/wdf-workplaces-summary/wdf-workplaces-summary.component.spec.ts, src/app/shared/components/wdf-tab/wdf-tab.component.spec.ts
- Made the parent status message component years dynamic as was hard-coded to 2021
-- wdf-parent-status-message.component.html
- Made all relevant tests have dynamic dates
=> Wdf parent status message dynamic year

server/models/benchmarks.js, server/models/cssr.js, server/models/pcodedata.js, server/models/postcodes.js, server/models/worker.js, server/routes/postcodes.js, server/routes/reports/localAuthorityReport/user.js, server/test/unit/routes/postcodes.spec.js
- Removed loose matching for postcodes lookup
- renamed function
- fixed issue with loose matching
- fixed tests to reflect no loose matching on getAddresesFromPostcode endpoint
=> Remove loose matching on customer postcode lookup

server/models/classes/establishment.js
=> remove logging

backend/Dockerfile
- Use AWS Public ECR Libary for backend image to avoid rate limiting
=> Use AWS Public ECR Libary for backend image to avoid rate limiting

frontend/src/app/shared/components/breadcrumbs/breadcrumbs.component.html, frontend/src/app/shared/components/breadcrumbs/breadcrumbs.component.ts
- Made beginning of breadcrumb show the establishment name if no override provided
- Removed one override that was establishment name
=> Make breadcrumb show workplace name 

frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmark.component.scss, frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.html, frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.spec.ts, frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.ts, frontend/src/app/features/subsidiary/subsidiary-routing.module.ts, frontend/src/app/features/subsidiary/subsidiary.module.ts, frontend/src/app/shared/components/summary-section/summary-section.component.spec.ts
- This PR allows the parent to view the subsidiary benchmark tab of pay and comparison group data
=> View sub benchmark as parent

frontend/src/app/shared/components/data-area-tab/data-area-useful-link/data-area-useful-link-pay/data-area-useful-link-pay.component.ts
As the `data-area-useful-link-pay` file had been updated in the test branch, the changes in main weren't pulled through in the previous merge (https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/pull/6144).
Adding this fixes the failing test which highlighted that the component hadn't been updated.
- Updated data-area-useful-link-pay ts file to have version merged in from main
=> Update data-area-useful-link-pay ts file to have version merged in from main

frontend/src/app/features/new-dashboard/home-tab/home-tab.component.html, frontend/src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.html, frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.html, frontend/src/app/shared/components/summary-section/summary-section.component.html
- Set margins to be same above and below across components which use summary-section component
=> Set margins to be same above and below across components which use summary-section component

frontend/src/app/features/new-dashboard/dashboard/dashboard.component.ts, frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.spec.ts, frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts
- Update variable to use benchmarks v2 for benchmark message card on home for parent and standalone 
- Add function to show home page benchmark message for parent in sub view
=> Show benchmark message on home page

frontend/src/app/core/breadcrumb/breadcrumb.model.ts, frontend/src/app/core/breadcrumb/journey.subsidiary.ts, frontend/src/app/core/breadcrumb/journey.workplaces.ts, frontend/src/app/core/services/breadcrumb.service.ts, frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.html, frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.spec.ts, frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.ts, frontend/src/app/features/subsidiary/benchmarks/view-subsidiary-benchmarks.component.html, frontend/src/app/features/subsidiary/subsidiary-routing.module.ts, frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.spec.ts, frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts, frontend/src/app/shared/components/benchmarks-tab/benchmarks-tab.component.spec.ts
- Added benchmark module to the subsidiary routing module
- Added breadcrumb journey for old benchmark about the data 
- Removed `about the data` journey from subsidiary journey
=> Show breadcrumb for about the data link 

frontend/src/app/core/breadcrumb/journey.public.ts, frontend/src/app/core/components/subsidiaryAccount/subsidiaryAccount.component.html, frontend/src/app/features/first-login-wizard/first-login-wizard.component.spec.ts, frontend/src/app/features/first-login-wizard/first-login-wizard.component.ts, frontend/src/app/features/subsidiary/subsidiary-routing.module.ts, frontend/src/app/shared/services/subsidiary-router-service.ts
- Removed first-login-wizard from exitSubsidiaryViewPages
- Fixed if statement check to return false when checking if first-login-wizard exists in the array
- Removed padding for pages with banner which adds padding spacing between breadcrumbs and content on other links pages
- Added breadcrumb for first login wizard - help you get started page
=> Remove first-login-wizard from exitSubsidiaryViewPages

backend/server/routes/notification/index.js
- notifications service was previously setting isViewed incorrectly on the returned notification data.
- I looked into adding some tests for the notification service, however this would likely also involve substantially rewriting the data access layer to use models rather than the raw sql that the notifications service currently uses. This would unfortunately go beyond the scope of a fix and introduce more risk into an already large feature.
=> notification service now returns correctly updated isViewed value

frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.html, frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.spec.ts
- uncommented a usage of the about the data component used on the old benchmarks tab, this was commented out during the initial benchmarks rollback and should've been reintroduced with the benchmarks 2.0 deployment.
=> resolved issue with downloading pdf on old benchmarks

frontend/src/app/features/new-dashboard/benchmarks-tab/benchmarks-tab.component.html, frontend/src/app/shared/components/benchmarks-tab/about-the-data/about-the-data.component.ts
- Added an if check only show old benchmark tab breadcrumbs in parent view only
- Subview breadcrumbs are all populated from `journey.subsidiary` 
=> Show the breadcrumb only in parent view

frontend/src/app/core/services/pdf.service.ts
The Benchmarks PDF wasn't downloading due to an error throwing when trying to remove a class from a child element which didn't exist. As you cannot download a PDF currently in the new version of benchmarks, we can remove it for now.  
- Removed unused logic which breaks benchmarks pdf download from sub view
=> Remove unused logic which breaks benchmarks pdf download from sub view

frontend/src/app/core/breadcrumb/journey.workplaces.spec.ts, frontend/src/app/core/breadcrumb/journey.workplaces.ts, frontend/src/app/core/services/breadcrumb.service.ts
- Included fragment to the get route instead of in the referrer object. This will apply the fragment to both home and benchmark routes. 
=> Add fragment to the route to navigate to the right flow in the benchmark breadcrumbs

frontend/src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.html, frontend/src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.scss
- Updated padding around cards in parent home tab to ensure spacing above and below same
=> Parent home page spacing fix

frontend/src/app/features/subsidiary/subsidiary-routing.module.ts
- Added change-expires-soon-alerts to the sub routing path 
=> Fix broken Manage expiry alerts link in sub routing

Makefile, backend/bin/run-db-migrations.js, backend/package.json, backend/server/config/sequelize.js
- Added changes to run migrations in all environments on completion of pipeline
We had intended to use the inactive workplaces ticket to move database migrations through to live, however that ticket needs more work as the changes cause a timeout in pre-prod where there is a lot of data. After consideration, this ticket has minimal risk as there are no code changes reliant on the database changes in the event that the migration does not run successfully in live. 
=> Add changes to run migrations in all environments

backend/migrations/20240501131241-fixTrainingCategoryName.js
- Added migration to fix name of 'Positive behaviour support and non-restrictive practice' category
Added as separate migration as the changes to training categories branch has already been deployed to staging
=> Add migration to fix name of positive behaviour training category

frontend/src/app/features/new-dashboard/workplace-tab/workplace-tab.component.html, frontend/src/app/features/new-dashboard/workplace-tab/workplace-tab.component.ts, frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.html, frontend/src/app/features/subsidiary/training-and-qualifications/view-subsidiary-training-and-qualifications.component.ts, frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.html, frontend/src/app/features/subsidiary/workplace/view-subsidiary-workplace.component.ts, frontend/src/app/features/workers/staff-record/staff-record.component.spec.ts, frontend/src/app/features/workers/staff-record/staff-record.component.ts, frontend/src/app/features/workplace/check-answers/check-answers.component.spec.ts, frontend/src/app/features/workplace/check-answers/check-answers.component.ts
- Allowed alert banner to show after the user has confirmed the workplace details
- Fixed alert confirm staff record detail banner in parent staff record tab
- Fixed alert confirm workplace details banner in sub workplace record tab
- Fixed alert banner to display after adding multiple training records 
- Fix alert confirm staff record detail banner in sub staff record tab
- Moving away from state alert messages from staff and training and qualification tabs. This makes the banner stay even after navigating from other page. 
- Fix delete staff record confirmation banner in the sub
=> Fix alert banners 

frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.ts, frontend/src/app/shared/components/summary-section/summary-section.component.spec.ts, frontend/src/app/shared/components/summary-section/summary-section.component.ts
- Added call to router navigate for links in summary section in the parent sub view
- This resolves an issue with navigating to tabs in the sub view from the summary section, which was caused by only navigating on change of tab when triggered by click event (changes introduced to stop switching tabs on reload)
=> Add navigation in sub view when link clicked from summary section

frontend/src/app/core/resolvers/primary-workplace.resolver.ts, frontend/src/app/features/benefits-bundle/benefit-tailored-seminars/benefit-tailored-seminars.component.ts, frontend/src/app/features/benefits-bundle/benefits-bundle.component.html, frontend/src/app/features/benefits-bundle/benefits-bundle.component.spec.ts, frontend/src/app/features/benefits-bundle/benefits-bundle.component.ts, frontend/src/app/features/benefits-bundle/benefits-elearning/benefits-elearning.component.ts, frontend/src/app/features/benefits-bundle/benefits-training-discounts/benefits-training-discounts.component.ts, frontend/src/app/features/workplace/user-account-saved/user-account-saved.component.ts, frontend/src/app/shared/components/breadcrumbs/breadcrumbs.component.ts, frontend/src/app/shared/services/parent-subsidiary-view.service.ts
The way have been setting state in the establishment class for subsidiary workplaces is different from the original way of having primary workplace which is the logged in workplace, and establishment, which is set either as the primary workplace or the subsidiary which is being viewed. This created problems with setting permissions and meant that original navigating logic in the question sections was being ignored and then handled by the subsidiary router service. 
- Removed setting primaryWorkplace from parent subsidiary service
- Changed primaryWorkplaceResolver to set establishment as well so that sections outside of question areas can access it from parent view
- Updated benefits bundle area to use establishment instead of primary workplace to display correct name in sub view
Does …
=> Removed setting primary workplace in sub view and update benefits bundle to use establishment

frontend/src/app/shared/services/subsidiary-router-service.spec.ts, frontend/src/app/shared/services/subsidiary-router-service.ts
- Added checks for format of url tree to prevent error being thrown on login after timeout in subsidiary view
=> Add check to subsidiary router service to prevent error being thrown on login

frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.spec.ts, frontend/src/app/features/subsidiary/staff-records/view-subsidiary-staff-records.component.ts
- Added check for worker length before setting staffLastUpdated to prevent error being thrown when no worker records for subsidiary workplace
=> Add check for worker length before setting staffLastUpdated to prevent error being thrown

frontend/src/app/core/test-utils/MockParentSubsidiaryViewService.ts, frontend/src/app/shared/components/new-dashboard-header/dashboard-header.component.spec.ts, frontend/src/app/shared/components/new-dashboard-header/dashboard-header.component.ts
Changing it so that the sub is not set as primaryWorkplace meant that the Delete workplace link was no longer displaying in the sub view.
- Updated dashboard header to set permissions based on workplace uid instead of primary
=> Updated dashboard header to set permissions based on workplace uid instead of primary

frontend/src/app/features/workplace/change-expires-soon-alerts/change-expires-soon-alerts.component.spec.ts, frontend/src/app/features/workplace/change-expires-soon-alerts/change-expires-soon-alerts.component.ts
In the sub view, after setting training expiry dates, it was navigating to the workplace tab instead of going back to the training and quals tab
- Set dashboard as return in change expires soon alert page and handle sub navigation through sub router service
=> Set dashboard as return in change expires soon alert page and handle sub navigation through sub router service

frontend/src/app/core/services/breadcrumb.service.ts, frontend/src/app/shared/components/new-tabs/new-tabs.component.spec.ts, frontend/src/app/shared/components/new-tabs/new-tabs.component.ts
- Added tracking of navigation events to tabs component to set tab after clicking browser back button
Once work is done to stop using fragments in parent/stand alone view, we should hopefully be able to use this way of setting tabs across the service and wouldn't need to set tabs as we navigate 
=> Add tracking of navigation events to tabs component to set tab after clicking browser back button

frontend/src/app/shared/components/new-tabs/new-tabs.component.spec.ts, frontend/src/app/shared/components/new-tabs/new-tabs.component.ts
Moving navigation out of the event listener for setting the tab allowed the setting of tab without navigating so that tabs can be set as you press the back button. However, this meant that navigation was running on page load in the sub view. This PR resolves that issue.
- Added check for setting tab on page load to stop navigation back to home tab on refresh
=> Don't navigate when tab is set on page load in sub view

frontend/src/app/features/workers/question/question.component.ts, frontend/src/app/features/workers/staff-details/staff-details.component.spec.ts
- Updated staff record pages to navigate to dashboard on back/cancel buttons and handle route in sub routing service
=> Update staff record pages to navigate to dashboard on back/cancel buttons and handle route in sub routing service

backend/server/test/unit/utils/security/permissions.spec.js, backend/server/utils/security/permissions.js
Subs which owned their own data could see the Delete workplace link, this was due to subsidiaries incorrectly being given the canDeleteEstablishment permission which was probably filtered out in the front end in the old version of the dashboard.
- Changed it so canDeleteEstablishment is only given for a subsidiary when request is made by parent which owns data
=> Only give canDeleteEstablishment permission when viewing sub as parent

frontend/src/app/features/pages/about-parents/about-parents.component.html
- Fixed spacing between content and return button on about parents page
=> Fix spacing between content and return button on about parents page

backend/server/data/linkToParent.js, frontend/src/app/features/notifications/notification-link-to-parent/notification-link-to-parent.component.html, frontend/src/app/features/notifications/notification-link-to-parent/notification-link-to-parent.component.spec.ts, frontend/src/app/features/notifications/notification-link-to-parent/notification-link-to-parent.component.ts
- Added retrieving sub postcode to the notification details database call
- Pass in parent or sub postcode to notification message depending on notification type
=> Add sub postcode to link to parent notification

backend/server/routes/nhsBsaApi/workplaceData.js, backend/server/test/unit/routes/nhsBsaApi/workplaceData.spec.js
- Changed isEligible to boolean
=> Return isEligible as boolean and not string in NHS BSA API

frontend/src/app/shared/services/subsidiary-router-service.spec.ts, frontend/src/app/shared/services/subsidiary-router-service.ts
Our fix for going back to the parent view when you click the home banner was to clear the sub view when an empty navigation is called. However, this introduced a flicker of the parent name in the navigate to workplace dropdown as it would momentarily clear the sub view. This is due to the dropdown component navigating to /subsidiary before its proper navigation, which allows a clean render of the sub view. 
- Added logic to stop clearing sub view for case when navigate to workplace dropdown navigates to /subsidiary
=> Fix: Flickering navigate to workplace dropdown

backend/server/routes/nhsBsaApi/workplaceData.js, backend/server/test/unit/routes/nhsBsaApi/workplaceData.spec.js
- Updated workplaceData to always return isEligible as boolean
- Updated WDF database call to only return required workplace
=> Fix: NHS API always return isEligible as boolean

backend/server/routes/establishments/bulkUpload/validate/workers/validateWorkerUnderNationalInsuranceMaximum.js, backend/server/test/unit/routes/establishments/bulkUpload/validate/workers/validateWorkerUnderNationalInsuranceMaximum.spec.js
One bulk upload validation function was returning a NI number for a validation error message instead of the workplace ID
- Updated NI maximum working hours validation in bulk upload to return local ID instead of NI number
=> Hotfix: NI number returned in BU worker validation 

backend/server/models/classes/worker.js, backend/server/models/classes/worker/properties/healthAndCareVisa.js, backend/server/test/unit/models/classes/worker.spec.js, frontend/src/app/features/workers/british-citizenship/british-citizenship.component.spec.ts, frontend/src/app/features/workers/british-citizenship/british-citizenship.component.ts, frontend/src/app/features/workers/nationality/nationality.component.spec.ts, frontend/src/app/features/workers/nationality/nationality.component.ts
- Add condition to reset healthAndVisaCare and employedFromOutsideUK when nationality and British citizenship are updated to values that shouldn't show the healthAndVisaCare and employedFromOutsideUK questions.
=> Fix/reset health and care when nationality and British citizenship values change

frontend/src/app/core/services/training.service.spec.ts, frontend/src/app/core/services/training.service.ts, frontend/src/app/core/test-utils/MockTrainingService.ts, frontend/src/app/features/training-and-qualifications/add-edit-training/add-edit-training.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-edit-training/add-edit-training.component.ts, frontend/src/app/shared/directives/add-edit-training/add-edit-training.component.html, frontend/src/app/shared/directives/add-edit-training/add-edit-training.directive.ts
- Show text of category chosen in previous page of add training record
- Add change link to go back to page to change the chosen category
- Redirects back to category page if there's no category id found in training service for add, or params for edit. This will prevent the page being incorrect, on page refresh
=> 1471-training-changes-to-the-main-add-a-training-record-page-after-selecting-category

backend/migrations/20240730084222-updateParentApprovalForWorkplacesWithCqcChangeRecord.js
[The previous fix PR](https://github.com/NMDSdevopsServiceAdm/SopraSteria-SFC/pull/6305) created a migration to add become a parent records to parent workplaces with no approval record. This worked on the assumption that these accounts would have no records in the Approvals table. However, workplaces with CQC status change records were not included in the update. This PR ensures those workplaces are also updated.
- Created new migration to ensure workplaces with CQC status change records have parent approval record, by adding check for parent approval type to the previous query.
=> Create migration to ensure workplaces with CQC status change records have parent approval record

frontend/src/app/features/registration-survey/why-create-account/why-create-account.component.spec.ts, frontend/src/app/features/registration-survey/why-create-account/why-create-account.component.ts
- Removed the TDF checkbox from the '_Why did you create an account?_' page due to unknowns on the state of the fund
=> Remove TDF checkbox from Why did you create an account page

frontend/src/app/core/model/training.model.ts, frontend/src/app/core/services/training.service.spec.ts, frontend/src/app/core/services/training.service.ts, frontend/src/app/core/test-utils/MockTrainingService.ts, frontend/src/app/features/training-and-qualifications/add-edit-training/add-edit-training.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-edit-training/add-edit-training.component.ts, frontend/src/app/features/training-and-qualifications/add-edit-training/select-training-category/select-training-category.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-edit-training/select-training-category/select-training-category.component.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/confirm-multiple-training/confirm-multiple-training.component.html, frontend/src/app/features/training-and-qualifications/add-multiple-training/confirm-multiple-training/confirm-multiple-training.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/confirm-multiple-training/confirm-multiple-training.component.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/select-training-category-multiple/select-training-category-multiple.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/select-training-category-multiple/select-training-category-multiple.component.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/training-details/training-details.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/training-details/training-details.component.ts, frontend/src/app/shared/directives/add-edit-training/add-edit-training.component.html, frontend/src/app/shared/directives/add-edit-training/add-edit-training.directive.ts, frontend/src/app/shared/directives/select-training-category/select-training-category.component.html, frontend/src/app/shared/directives/select-training-category/select-training-category.directive.ts
- Add a change link beside Training category, which returns to category selection page
- Hide Number of Staff/Training Category fields in training detail page if accessed from summary page
=> 1481 training add multiple records summary

frontend/src/app/features/wdf/wdf-data-change/wdf-routing.module.ts
- Added health and care visa and Employed inside or outside the UK pages to the WDF view
The health and care visa pages were not added to the WDF routing, so although you could see them on the staff summary page in WDF, clicking the Change link would take the user to the Page not found page.
=> Added Health and care visa and Inside or outside UK questions to WDF routing

frontend/src/app/features/training-and-qualifications/add-multiple-training/select-staff/select-staff.component.spec.ts, frontend/src/app/features/training-and-qualifications/add-multiple-training/select-staff/select-staff.component.ts, frontend/src/app/features/workers/select-record-type/select-record-type.component.spec.ts, frontend/src/app/features/workers/select-record-type/select-record-type.component.ts
- When in the middle of adding a training record and you click one of the tabs while in training details, when you go back to the beginning of the journey of adding a single or multiple training record the category is already selected in the select category page. Added a check that at the beginning of both journeys, to make sure the selectedTrainingCategory variable is clear in the training service
=> Add check to clear selected category at beginning of add training record

frontend/src/app/features/wdf/wdf-data-change/wdf-routing.module.ts, frontend/src/app/features/workers/mandatory-details/mandatory-details.component.spec.ts, frontend/src/app/shared/components/staff-record-summary/basic-record/basic-record.component.html, frontend/src/app/shared/components/staff-record-summary/basic-record/basic-record.component.spec.ts, frontend/src/app/shared/components/staff-record-summary/basic-record/basic-record.component.ts
- Move main job role in basic record and add a change link to navigate to the new main job role page
- Moved jobs resolver in wdf routing to stop causing issues viewing that route
=> 1466 job roles changes to the main record summay page

backend/server/routes/nhsBsaApi/apiDocs.js, backend/server/routes/nhsBsaApi/workplaceData.js
There were issues with throttling errors when making requests to the NHS BSA API. This PR sets the same rate limiting config for those endpoints as the rest of the service to stop the throttling and give us time to investigate whether rate limiting is still working correctly since the migration to AWS.
=> Update the NHS API endpoints to use existing rate limiting config

backend/migrations/20240909153100-fixQualificationStatsViewForAnalysisFiles.js, backend/migrations/20240909153600-fixWorkerTrainingStatsViewForAnalysisFiles.js
- Add migrations to correct the materialised view WorkerQualificationStats and WorkerTrainingStats, so that Archived worker will be included. This is to allow Analysis file to generate the leavers report correctly.
=> amend materialized view WorkerQualificationStats and WorkerTrainingStats to not filter out Archived workers

backend/server/routes/establishments/bulkUpload/download/workerCSV.js, backend/server/test/unit/routes/establishments/bulkUpload/download/workerCSV.spec.js
- Updated download of start in sector to set No to 999 and empty string when unanswered
The STARTINSECT column would be empty for users who had answered No previously, and they would then get a warning when trying to upload if they leave the column blank. This ensures users can differentiate between No and not answering the Start in sector question.
=> Updated download of start in sector to set No to 999 and empty string when unanswered

frontend/src/app/features/training-and-qualifications/add-edit-training/select-training-category/select-training-category.component.spec.ts, frontend/src/app/shared/directives/select-training-category/select-training-category.directive.ts
- Changed incorrect example for staff development training category
=> Change incorrect example for staff development training category

frontend/src/app/shared/directives/add-edit-training/add-edit-training.component.html
- Add a subheading to upload certificates section
=> add a h2 subheading for certificates

frontend/src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.html, frontend/src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.spec.ts
- Added check for article object before rendering ASC-WDS news card on parent home page to ensure failure of CMS doesn't break parent home page
=> Add check for article before rendering ASC-WDS news card on parent home page

frontend/src/app/features/training-and-qualifications/add-edit-training/add-edit-training.component.spec.ts, frontend/src/app/shared/components/select-upload-file/select-upload-file.component.ts
- Clear the value of the file input element to allow the same file to be selected again
=> Fix issue of the same file could not be added again after removal

frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-training-and-qualifications-record.component.html, frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-training-and-qualifications-record.component.spec.ts, frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-training-and-qualifications-record.component.ts
In testing of the training certificates feature, an issue was spotted where after you have uploaded a certificate on the training and qualifications summary page, everything in the actions list was duplicated. This was due to the actions list not being cleared and training data being pushed to it again when the data is refreshed after an upload.
- Clear the actions list before populating it when setting training, to ensure that there is no unintended duplication.
=> Reset actions list when training is refreshed to prevent duplication after upload of training certificate

frontend/src/app/features/training-and-qualifications/add-edit-training/add-edit-training.component.spec.ts, frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-training-and-qualifications-record.component.spec.ts, frontend/src/app/shared/directives/add-edit-training/add-edit-training.component.html, frontend/src/app/shared/validators/custom-form-validators.ts
- Increased the size of file limit for uploading training certificates - agreed that previous limit was too low
=> Increase size of file limit for uploading training certificates

frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-qualifications/new-qualifications.component.html, frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-qualifications/new-qualifications.spec.ts
- Added canEditWorker check for displaying qualification certificate links on training and quals summary page to ensure that parents viewing subs who own their data or subs viewing data owned by the parent cannot see these actions they don't have permission for 
=> Fix: Hide qualification certificate links for read only users

backend/server/models/establishment.js, backend/server/routes/establishments/hasTrainingCertificates.js, backend/server/test/unit/routes/establishments/hasTrainingCertificates.spec.js
With the introduction of training certificates, a check was added to the bulk upload page for training certificates for the workplace or any subs, in order to display a warning that the certificates will be deleted if they upload the training file. The functionality worked as expected, but for one particularly large parent workplace, the page was failing to load and the server continually returned a 503 response. This PR attempts to improve the efficiency of the endpoint.  
- Increased efficiency of hasTrainingCertificates endpoint by using raw sql and SELECT 1 instead of returning all data and looping through
=> Increase efficiency of check for training certificates on Bulk Upload page

backend/server/routes/establishments/workerCertificate/qualificationCertificate.js, backend/server/routes/establishments/workerCertificate/trainingCertificate.js, backend/server/routes/establishments/workerCertificate/workerCertificateService.js, backend/server/test/unit/routes/establishments/workerCertificate/workerCertificateService.spec.js
- Updated certificate endpoints to send default Internal server error message when unexpected errors occur in the WorkerCertificate service
- We should not send error messages which come directly from unexpected errors being thrown in our codebase, these can confuse the user or give insight into issues with our code. This change means that expected cases where the requests are incorrectly formatted return specific messages, otherwise a generic message is returned. 
=> Fix: Only return expected error messages from certificate endpoints

backend/server/models/BulkImport/csv/crossValidate.js, backend/server/models/BulkImport/csv/crossValidateErrors.js, backend/server/models/classes/establishment.js, backend/server/routes/establishments/bulkUpload/data/workerHeaders.js, backend/server/routes/establishments/bulkUpload/validate/headers/worker.js, backend/server/routes/establishments/bulkUpload/whichFile.js, backend/server/test/unit/models/Bulkimport/csv/crossValidate.spec.js, backend/server/test/unit/routes/establishments/bulkUpload/validate/headers/worker.spec.js, backend/server/test/unit/routes/establishments/bulkUpload/whichFile.spec.js
- Updated bulk upload validation to allow both the _CHGUNIQUEWRKID_ and _TRANSFERSTAFFRECORD_ columns in the same file
- This allows users to update the worker reference for a worker they are moving if the reference already exists in the workplace they are being moved to
=> Fix: Allow change id and staff transfer

backend/migrations/20241128152100-other-job-role-name-column.js, backend/server/models/classes/establishment.js, backend/server/models/classes/establishment/properties/jobHelper.js, backend/server/models/classes/establishment/properties/leaversProperty.js, backend/server/models/classes/establishment/properties/startersProperty.js, backend/server/models/classes/establishment/properties/vacanciesProperty.js, backend/server/models/establishment.js, backend/server/models/establishmentJobs.js, backend/server/models/establishmentLeavers.js, backend/server/models/establishmentStarters.js, backend/server/models/establishmentVacancies.js, backend/server/routes/establishments/jobs.js, backend/server/test/unit/routes/establishments/jobs.spec.js, frontend/src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.html, frontend/src/app/shared/components/new-wdf-workplace-summary/wdf-workplace-summary.component.spec.ts, frontend/src/app/shared/components/new-workplace-summary/workplace-summary.component.html, frontend/src/app/shared/components/new-workplace-summary/workplace-summary.component.spec.ts, frontend/src/app/shared/components/workplace-summary/workplace-summary.component.html, frontend/src/app/shared/components/workplace-summary/workplace-summary.component.spec.ts, frontend/src/app/shared/pipes/format-starters-leavers-vacancies.pipe.spec.ts, frontend/src/app/shared/pipes/format-starters-leavers-vacancies.pipe.ts, frontend/src/app/shared/shared.module.ts
- Add an "OtherJobRoleName" column to EstablishmentJobs table, update related view tables to include the new column
- Update `/establishment/:establishmentUid/jobs` endpoint to handle an optional "other" field for vacancies/starters/leavers
- Update establishment property and jobs endpoint to return vacancies/starters/leavers with "other" field if exist in database
- Update frontend workplace summary pages to show the optional job role name with a colon
=> Feat/1564 - add other job role column

frontend/src/app/features/wdf/wdf-data-change/wdf-staff-summary/wdf-staff-summary.component.spec.ts, frontend/src/app/features/wdf/wdf-data-change/wdf-staff-summary/wdf-staff-summary.component.ts
- Set links for staff records tab correctly for no staff records message
=> Fix: Set links for staff records tab correctly for no staff records message

frontend/src/app/features/login/login.component.html, frontend/src/app/features/login/login.component.spec.ts, frontend/src/app/shared/components/error-summary/error-summary.component.html, frontend/src/app/shared/components/error-summary/error-summary.component.spec.ts
- when error message of invalid username/password is clicked, set focus on the username input box
=> Fix/Login page - should set focus on username field when invalid username/password error message is clicked

backend/migrations/20250113140000-adminLAReportFunctionFix.js, backend/migrations/20250127120327-refactorLocalAuthorityReportEstablishmentFunction.js, backend/migrations/20250128162910-adminLAReportFunctionFix.js
- Added a migration which corrects the sql function `cqc.localauthorityreportadmin` stored in database.
(content of function is the same as in 2021 version)
- Added a migration to refactor the `cqc.localauthorityreportestablishment` function
Reintroduction of the data refresh in our pre-prod environment caused issues with memory in the database, after investigation we found that the `cqc.localauthorityreportestablishment` function was very slow and required a lot of memory due to the way it was looping over large amounts of data and inserting into the LA table one establishment at a time. To reduce the amount of memory used, we changed the query to use `INSERT INTO SELECT`, which means the query does not have to store everything in a refcursor and loop over it.  
Does this PR include …
=> fix/Investigate LA report not returning the latest data

frontend/src/app/features/dashboard/home-tab/home-tab.component.html, frontend/src/app/features/dashboard/home-tab/home-tab.component.spec.ts, frontend/src/app/features/new-dashboard/home-tab/home-tab.component.html, frontend/src/app/features/new-dashboard/home-tab/home-tab.component.spec.ts, frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.spec.ts, frontend/src/app/shared/components/other-links/other-links.component.html, frontend/src/app/shared/components/other-links/other-links.component.spec.ts
- Removed "Help to get you started" links from the various versions of the dashboard
=> removed get started link and tests from dashboard pages

frontend/src/app/core/breadcrumb/journey.help.ts, frontend/src/app/features/help/contact-us/contact-us.component.html, frontend/src/app/features/help/contact-us/contact-us.component.spec.ts, frontend/src/app/features/help/contact-us/contact-us.component.ts, frontend/src/app/features/help/help-routing.module.ts, frontend/src/app/features/help/help.module.ts
- Created contact us component in help section to use the same CMS content as the contact us in the footer
=> Add contact us in help section

frontend/src/app/features/bulk-upload/help-area/bulk-upload-flowchart/bulk-upload-flowchart.component.spec.ts, frontend/src/app/features/bulk-upload/help-area/bulk-upload-flowchart/bulk-upload-flowchart.component.ts
- Updated bulk upload flow chart page to use new back link service to navigate back to previous page correctly
This resolves issue with navigating to the bulk upload flow chart from new help Q&A page, as it was setting navigation back to bulk upload help and tips page. This is incorrect, but would also log out read only users who don't have permission to view the bulk upload pages. 
=> Fix: Update BU flow chart page to use new back link service

frontend/src/app/core/breadcrumb/journey.help.ts
- Added breadcrumb journey for individual Q&A page which matches main Questions and answers page
=> Fix: Breadcrumbs on individual Q&A pages

backend/server/models/classes/establishment.js
- Added check for bulk upload in establishment creation to set showAddWorkplaceDetailsBanner to false to stop add more details being displayed for new workplaces created in bulk upload instead of whole workplace page
=> Fix: Stop showing add workplace details after bulk upload

frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-training-and-qualifications-record.component.html, frontend/src/app/features/training-and-qualifications/new-training-qualifications-record/new-training-and-qualifications-record.component.ts
Users have called the support team to say that they can't click on the Add links on the action list on the individual staff training and quals page. However, the links are working correctly for other users and admins accessing the same page. Without being able to replicate the issue, I suspect that it could be linked to using `javascript:void(0)` for those links and potentially users' browsers/firewalls stopping it so this is an attempted fix.  
- Updated training-and-qualifications-record to use event prevent default instead of javascript:void(0)
=> Fix: Add link on training actions list not working

frontend/src/app/shared/components/submit-button/submit-button.component.html, frontend/src/app/shared/components/submit-button/submit-button.component.ts
- Added horizontal padding on staff record submit button when CTA is short (Save)
- Adjusted div to min-width so it doesn't cause long CTAs to wrap
- Removed unused showSaveAndCancel input and html section related to it
=> Fix: Staff record save button

frontend/src/app/core/services/alert.service.spec.ts, frontend/src/app/core/services/alert.service.ts
- undo the recent change to alert service
A previous PR changed removeAlert subscription to listen to NavigationEnd event to solve an issue of alert disappeared before page change.
However, we found that the change doesn't go well with some existing usage of AlertService.
This PR will undo the change from feature branch, so that we can work on AlertService in a separate branch.
=> undo change to alert service

frontend/src/app/features/workers/mandatory-details/mandatory-details.component.html
- Removed grid-column outside of grid-row to prevent help button rising and increase spacing above buttons
=> Fix: Layout on mandatory details page

backend/migrations/20250530144042-addCWPQuestionViewedColumn.js, backend/server/models/classes/establishment.js, backend/server/models/establishment.js, frontend/src/app/core/model/establishment.model.ts, frontend/src/app/core/services/tabs.service.ts, frontend/src/app/features/new-dashboard/home-tab/home-tab.component.html, frontend/src/app/features/new-dashboard/parent-home-tab/parent-home-tab.component.html, frontend/src/app/features/subsidiary/home/view-subsidiary-home.component.html, frontend/src/app/features/subsidiary/subsidiary-routing.module.ts, frontend/src/app/features/subsidiary/subsidiary.module.ts, frontend/src/app/features/workplace/care-workforce-pathway-use/care-workforce-pathway-use.component.spec.ts, frontend/src/app/features/workplace/care-workforce-pathway-use/care-workforce-pathway-use.component.ts, frontend/src/app/features/workplace/question/question.component.ts, frontend/src/app/shared/components/new-tabs/new-tabs.component.spec.ts, frontend/src/app/shared/components/summary-section/summary-section.component.spec.ts, frontend/src/app/shared/components/summary-section/summary-section.component.ts, frontend/src/mockdata/establishment.js
- Added question to workplace section of home summary panel when user has not answered awareness question
- Don't show link again on summary panel after user has clicked it, even if they don't answer the question
- Updated the back link on CWP use question to use smart back link service so back correctly navigates to previous page (awareness question or workplace summary)
=> Feat/1721 workplace summary flag for CWP awareness

backend/server/models/establishment.js
- Added CWP flags for workplace and staff records to query for flagging sub checks
=> Add CWP flags for workplace and staff records to flagging sub checks

frontend/src/app/features/workplace/care-workforce-pathway-awareness/care-workforce-pathway-awareness.component.spec.ts, frontend/src/app/features/workplace/care-workforce-pathway-awareness/care-workforce-pathway-awareness.component.ts, frontend/src/app/features/workplace/care-workforce-pathway-use/care-workforce-pathway-use.component.spec.ts, frontend/src/app/features/workplace/care-workforce-pathway-use/care-workforce-pathway-use.component.ts, frontend/src/app/features/workplace/question/question.component.ts, frontend/src/app/features/workplace/vacancies-and-turnover/how-many-starters-leavers-vacancies.directive.ts
- Use .then to ensure navigation is complete before banner is displayed for answering CWP questions, to prevent banner flashing before user is taken back to the home page
=> Fix: Saved banner flashing after answering CWP questions from summary panel link

backend/server/models/classes/establishment.js, backend/server/routes/establishments/careWorkforcePathway/careWorkforcePathwayAwareness.js, backend/server/test/unit/routes/establishments/careWorkforcePathway/careWorkforcePathwayAwareness.spec.js
- Change CWP awareness endpoint to set CWP use to null only when both of the following conditions are met:
1. CWP awareness is answered as "Not aware" or "Do not know"
2. CWP use already got an answer before
When CareWorkforcePathway use is null (not answered) and CareWorkforcePathway Awareness is answered as “Not aware“ or “I don’t know“, currently the backend will try to set CareWorkforcePathway use to null again and add a date to the columns of CareWorkforcePathwayUseSavedAt and CareWorkforcePathwayUseChangedAt.  
This change is to prevent the said unwanted behaviour.
=> fix/1745 CWP use savedAt / changedAt date unexpected update when awareness question is answered.
